/******************************************************************************
 * Net instancer.
 * This file instantiate all nets in the simulation.
 * This file was generated by a verilog parser.
 ******************************************************************************/

#ifndef NETINSTATIATION_H
#define NETINSTATIATION_H
 
#include <stdio.h>
#include "NetFlow.h"

#define NET_INDEX_out__6__OBUF__115_a0_b 0
#define NET_INDEX_out__5__OBUF__0_a0_b 1
#define NET_INDEX_out__1__OBUF__121_a0_b 2
#define NET_INDEX_out__0__OBUF__0_a0_b 3
#define NET_INDEX_out__3__OBUF__126_a0_b 4
#define NET_INDEX_out__2__OBUF__0_a0_b 5
#define NET_INDEX_enable__IBUF__0_a0_b 6
#define NET_INDEX_clk__BUFGP_a0_b 7
#define NET_INDEX__bcntr__inst_scntr__133_a0_b 8
#define NET_INDEX__bclk__BUFGP_sIBUFG__0_a0_b 9
#define NET_INDEX_out__4__OBUF__135_a0_b 10
#define NET_INDEX__bgray__inst_scount_l1_g__rt__17_a0_b 11
#define NET_INDEX__bgray__inst_scount_l2_g__rt__13_a0_b 12
#define NET_INDEX__bProtoComp1_dCYINITGND_d0_a0_b 13
#define NET_INDEX__bgray__inst_scount_l3_g__rt__1_a0_b 14
#define NET_INDEX__bgray__inst_scount_l4_g__rt__47_a0_b 15
#define NET_INDEX__bgray__inst_scount_l5_g__rt__43_a0_b 16
#define NET_INDEX__bgray__inst_scount_l6_g__rt__39_a0_b 17
#define NET_INDEX__bgray__inst_scount_l7_g__rt__29_a0_b 18
#define NET_INDEX__bclk__BUFGP_sIBUFG__56_a0_b 19
#define NET_INDEX_enable__IBUF__59_a0_b 20
#define NET_INDEX_out__2__OBUF__84_a0_b 21
#define NET_INDEX_out__5__OBUF__90_a0_b 22
#define NET_INDEX_out__0__OBUF__99_a0_b 23
#define NET_INDEX__bNlwBufferSignal__gray__inst_scount__3_sCLK_a0_b 24
#define NET_INDEX__bNlwBufferSignal__gray__inst_scount__2_sCLK_a0_b 25
#define NET_INDEX__bNlwBufferSignal__gray__inst_scount__1_sCLK_a0_b 26
#define NET_INDEX__bNlwBufferSignal__gray__inst_scount__0_sCLK_a0_b 27
#define NET_INDEX__bNlwBufferSignal__gray__inst_scount__7_sCLK_a0_b 28
#define NET_INDEX__bNlwBufferSignal__gray__inst_scount__6_sCLK_a0_b 29
#define NET_INDEX__bNlwBufferSignal__gray__inst_scount__5_sCLK_a0_b 30
#define NET_INDEX__bNlwBufferSignal__gray__inst_scount__4_sCLK_a0_b 31
#define NET_INDEX__bNlwBufferSignal__q__OBUF_sI_a0_b 32
#define NET_INDEX__bNlwBufferSignal__out__0__OBUF_sI_a0_b 33
#define NET_INDEX__bNlwBufferSignal__out__1__OBUF_sI_a0_b 34
#define NET_INDEX__bNlwBufferSignal__out__2__OBUF_sI_a0_b 35
#define NET_INDEX__bNlwBufferSignal__out__3__OBUF_sI_a0_b 36
#define NET_INDEX__bNlwBufferSignal__out__4__OBUF_sI_a0_b 37
#define NET_INDEX__bNlwBufferSignal__out__5__OBUF_sI_a0_b 38
#define NET_INDEX__bNlwBufferSignal__out__6__OBUF_sI_a0_b 39
#define NET_INDEX__bNlwBufferSignal__out__7__OBUF_sI_a0_b 40
#define NET_INDEX__bNlwBufferSignal__clk__BUFGP_sBUFG_sIN_a0_b 41
#define NET_INDEX__bNlwBufferSignal__cntr__inst_scntr_sCLK_a0_b 42
#define NET_INDEX_GND_a0_b 43
#define NET_INDEX__bNLW__reset__4_dD5LUT__O__UNCONNECTED_a0_b 44
#define NET_INDEX__bNLW__gray__inst_sMcount__count__cy_l3_g__CO_a0_b__UNCONNECTED_a0_b 45
#define NET_INDEX__bNLW__gray__inst_sMcount__count__cy_l3_g__CO_a1_b__UNCONNECTED_a0_b 46
#define NET_INDEX__bNLW__gray__inst_sMcount__count__cy_l3_g__CO_a2_b__UNCONNECTED_a0_b 47
#define NET_INDEX__bNLW__reset__5_dC5LUT__O__UNCONNECTED_a0_b 48
#define NET_INDEX__bNLW__reset__6_dB5LUT__O__UNCONNECTED_a0_b 49
#define NET_INDEX__bNLW__N0__2_dA5LUT__O__UNCONNECTED_a0_b 50
#define NET_INDEX__bNLW__gray__inst_sMcount__count__xor_l7_g__CO_a0_b__UNCONNECTED_a0_b 51
#define NET_INDEX__bNLW__gray__inst_sMcount__count__xor_l7_g__CO_a1_b__UNCONNECTED_a0_b 52
#define NET_INDEX__bNLW__gray__inst_sMcount__count__xor_l7_g__CO_a2_b__UNCONNECTED_a0_b 53
#define NET_INDEX__bNLW__gray__inst_sMcount__count__xor_l7_g__CO_a3_b__UNCONNECTED_a0_b 54
#define NET_INDEX__bNLW__gray__inst_sMcount__count__xor_l7_g__DI_a3_b__UNCONNECTED_a0_b 55
#define NET_INDEX__bNLW__reset_dC5LUT__O__UNCONNECTED_a0_b 56
#define NET_INDEX__bNLW__reset__2_dB5LUT__O__UNCONNECTED_a0_b 57
#define NET_INDEX__bNLW__reset__3_dA5LUT__O__UNCONNECTED_a0_b 58
#define NET_INDEX_VCC_a0_b 59
#define NET_INDEX__bgray__inst_scount_a0_b 60
#define NET_INDEX__bgray__inst_scount_a1_b 61
#define NET_INDEX__bgray__inst_scount_a2_b 62
#define NET_INDEX__bgray__inst_scount_a3_b 63
#define NET_INDEX__bgray__inst_scount_a4_b 64
#define NET_INDEX__bgray__inst_scount_a5_b 65
#define NET_INDEX__bgray__inst_scount_a6_b 66
#define NET_INDEX__bgray__inst_scount_a7_b 67
#define NET_INDEX__bgray__inst_sMcount__count__cy_a3_b 68
#define NET_INDEX__bgray__inst_sMcount__count__lut_a0_b 69
#define NET_INDEX__bgray__inst_sResult_a0_b 70
#define NET_INDEX__bgray__inst_sResult_a1_b 71
#define NET_INDEX__bgray__inst_sResult_a2_b 72
#define NET_INDEX__bgray__inst_sResult_a3_b 73
#define NET_INDEX__bgray__inst_sResult_a4_b 74
#define NET_INDEX__bgray__inst_sResult_a5_b 75
#define NET_INDEX__bgray__inst_sResult_a6_b 76
#define NET_INDEX__bgray__inst_sResult_a7_b 77



#endif // NETINSTATIATION_H
 

