/******************************************************************************
 * Net instancer.
 * This file instantiate all nets in the simulation.
 * This file was generated by a verilog parser.
 ******************************************************************************/

 
#include <stdio.h>
#include "NetFlow.h"
#include "netinstatiation.h"
#include "SimulatorEngine.h"

void instance_nets(SimulatorEngine engine){

	engine.register_net(new NetFlow("\NlwBufferSignal_gray_inst/count_0/CLK=net ID: \NlwBufferSignal_gray_inst/count_0/CLK lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("clk_BUFGP=net ID: clk_BUFGP lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\gray_inst/count<2>_rt_13=net ID: \gray_inst/count<2>_rt_13 lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\gray_inst/Mcount_count_lut=net ID: \gray_inst/Mcount_count_lut lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\gray_inst/count<1>_rt_17=net ID: \gray_inst/count<1>_rt_17 lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\NLW_reset_6.B5LUT_O_UNCONNECTED=net ID: \NLW_reset_6.B5LUT_O_UNCONNECTED lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\NlwBufferSignal_gray_inst/count_1/CLK=net ID: \NlwBufferSignal_gray_inst/count_1/CLK lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\NlwBufferSignal_out_1_OBUF/I=net ID: \NlwBufferSignal_out_1_OBUF/I lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\NlwBufferSignal_out_2_OBUF/I=net ID: \NlwBufferSignal_out_2_OBUF/I lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\ProtoComp1.CYINITGND.0=net ID: \ProtoComp1.CYINITGND.0 lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("enable_IBUF_59=net ID: enable_IBUF_59 lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\NLW_reset_2.B5LUT_O_UNCONNECTED=net ID: \NLW_reset_2.B5LUT_O_UNCONNECTED lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\NlwBufferSignal_out_5_OBUF/I=net ID: \NlwBufferSignal_out_5_OBUF/I lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("out_0_OBUF_99=net ID: out_0_OBUF_99 lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("enable_IBUF_0=net ID: enable_IBUF_0 lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\NlwBufferSignal_out_3_OBUF/I=net ID: \NlwBufferSignal_out_3_OBUF/I lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\NlwBufferSignal_out_7_OBUF/I=net ID: \NlwBufferSignal_out_7_OBUF/I lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\NlwBufferSignal_out_0_OBUF/I=net ID: \NlwBufferSignal_out_0_OBUF/I lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\NlwBufferSignal_out_4_OBUF/I=net ID: \NlwBufferSignal_out_4_OBUF/I lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\NlwBufferSignal_out_6_OBUF/I=net ID: \NlwBufferSignal_out_6_OBUF/I lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\NLW_gray_inst/Mcount_count_xor<7>_CO[1]_UNCONNECTED=net ID: \NLW_gray_inst/Mcount_count_xor<7>_CO[1]_UNCONNECTED lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\NlwBufferSignal_gray_inst/count_7/CLK=net ID: \NlwBufferSignal_gray_inst/count_7/CLK lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\NLW_gray_inst/Mcount_count_xor<7>_CO[0]_UNCONNECTED=net ID: \NLW_gray_inst/Mcount_count_xor<7>_CO[0]_UNCONNECTED lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("out_5_OBUF_0=net ID: out_5_OBUF_0 lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("CONST_ONE=net ID: CONST_ONE lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\NlwBufferSignal_gray_inst/count_6/CLK=net ID: \NlwBufferSignal_gray_inst/count_6/CLK lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("out_1_OBUF_121=net ID: out_1_OBUF_121 lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\NLW_gray_inst/Mcount_count_xor<7>_DI[3]_UNCONNECTED=net ID: \NLW_gray_inst/Mcount_count_xor<7>_DI[3]_UNCONNECTED lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\NLW_gray_inst/Mcount_count_cy<3>_CO[1]_UNCONNECTED=net ID: \NLW_gray_inst/Mcount_count_cy<3>_CO[1]_UNCONNECTED lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("VCC=net ID: VCC lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\NLW_gray_inst/Mcount_count_cy<3>_CO[0]_UNCONNECTED=net ID: \NLW_gray_inst/Mcount_count_cy<3>_CO[0]_UNCONNECTED lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("GND=net ID: GND lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\NLW_gray_inst/Mcount_count_xor<7>_CO[2]_UNCONNECTED=net ID: \NLW_gray_inst/Mcount_count_xor<7>_CO[2]_UNCONNECTED lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\NLW_gray_inst/Mcount_count_xor<7>_CO[3]_UNCONNECTED=net ID: \NLW_gray_inst/Mcount_count_xor<7>_CO[3]_UNCONNECTED lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\NLW_reset_3.A5LUT_O_UNCONNECTED=net ID: \NLW_reset_3.A5LUT_O_UNCONNECTED lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("out_6_OBUF_115=net ID: out_6_OBUF_115 lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\NlwBufferSignal_gray_inst/count_5/CLK=net ID: \NlwBufferSignal_gray_inst/count_5/CLK lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\gray_inst/count=net ID: \gray_inst/count lsb: 0  msb: 7"));
	engine.register_net(new NetFlow("\gray_inst/Result=net ID: \gray_inst/Result lsb: 0  msb: 7"));
	engine.register_net(new NetFlow("\NLW_gray_inst/Mcount_count_cy<3>_CO[2]_UNCONNECTED=net ID: \NLW_gray_inst/Mcount_count_cy<3>_CO[2]_UNCONNECTED lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\clk_BUFGP/IBUFG_56=net ID: \clk_BUFGP/IBUFG_56 lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("out_5_OBUF_90=net ID: out_5_OBUF_90 lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("out_4_OBUF_135=net ID: out_4_OBUF_135 lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\gray_inst/count<5>_rt_43=net ID: \gray_inst/count<5>_rt_43 lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\gray_inst/count<6>_rt_39=net ID: \gray_inst/count<6>_rt_39 lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\NlwBufferSignal_gray_inst/count_4/CLK=net ID: \NlwBufferSignal_gray_inst/count_4/CLK lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\NLW_reset.C5LUT_O_UNCONNECTED=net ID: \NLW_reset.C5LUT_O_UNCONNECTED lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\NLW_reset_5.C5LUT_O_UNCONNECTED=net ID: \NLW_reset_5.C5LUT_O_UNCONNECTED lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\cntr_inst/cntr_133=net ID: \cntr_inst/cntr_133 lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\NlwBufferSignal_gray_inst/count_2/CLK=net ID: \NlwBufferSignal_gray_inst/count_2/CLK lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\clk_BUFGP/IBUFG_0=net ID: \clk_BUFGP/IBUFG_0 lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\NlwBufferSignal_q_OBUF/I=net ID: \NlwBufferSignal_q_OBUF/I lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("out_0_OBUF_0=net ID: out_0_OBUF_0 lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\gray_inst/count<4>_rt_47=net ID: \gray_inst/count<4>_rt_47 lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("out_3_OBUF_126=net ID: out_3_OBUF_126 lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\NLW_reset_4.D5LUT_O_UNCONNECTED=net ID: \NLW_reset_4.D5LUT_O_UNCONNECTED lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("out_2_OBUF_0=net ID: out_2_OBUF_0 lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\gray_inst/count<7>_rt_29=net ID: \gray_inst/count<7>_rt_29 lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("out_2_OBUF_84=net ID: out_2_OBUF_84 lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\NlwBufferSignal_cntr_inst/cntr/CLK=net ID: \NlwBufferSignal_cntr_inst/cntr/CLK lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\gray_inst/count<3>_rt_1=net ID: \gray_inst/count<3>_rt_1 lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\NLW_N0_2.A5LUT_O_UNCONNECTED=net ID: \NLW_N0_2.A5LUT_O_UNCONNECTED lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("CONST_ZERO=net ID: CONST_ZERO lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\NlwBufferSignal_gray_inst/count_3/CLK=net ID: \NlwBufferSignal_gray_inst/count_3/CLK lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\NlwBufferSignal_clk_BUFGP/BUFG/IN=net ID: \NlwBufferSignal_clk_BUFGP/BUFG/IN lsb: 0  msb: 0"));
	engine.register_net(new NetFlow("\gray_inst/Mcount_count_cy=net ID: \gray_inst/Mcount_count_cy lsb: 3  msb: 3"));

}

