/******************************************************************************
 * Net instancer.
 * This file instantiate all nets in the simulation.
 * This file was generated by a verilog parser.
 ******************************************************************************/

 
#include <stdio.h>
#include "NetFlow.h"
#include "netinstatiation.h"
#include "SimulatorEngine.h"

void instance_nets(SimulatorEngine engine){

	engine.register_net(new NetFlow("out_6_OBUF_115[0]"));
	engine.register_net(new NetFlow("out_5_OBUF_0[0]"));
	engine.register_net(new NetFlow("out_1_OBUF_121[0]"));
	engine.register_net(new NetFlow("out_0_OBUF_0[0]"));
	engine.register_net(new NetFlow("out_3_OBUF_126[0]"));
	engine.register_net(new NetFlow("out_2_OBUF_0[0]"));
	engine.register_net(new NetFlow("enable_IBUF_0[0]"));
	engine.register_net(new NetFlow("clk_BUFGP[0]"));
	engine.register_net(new NetFlow("\cntr_inst/cntr_133[0]"));
	engine.register_net(new NetFlow("\clk_BUFGP/IBUFG_0[0]"));
	engine.register_net(new NetFlow("out_4_OBUF_135[0]"));
	engine.register_net(new NetFlow("\gray_inst/count<1>_rt_17[0]"));
	engine.register_net(new NetFlow("\gray_inst/count<2>_rt_13[0]"));
	engine.register_net(new NetFlow("\ProtoComp1.CYINITGND.0[0]"));
	engine.register_net(new NetFlow("\gray_inst/count<3>_rt_1[0]"));
	engine.register_net(new NetFlow("\gray_inst/count<4>_rt_47[0]"));
	engine.register_net(new NetFlow("\gray_inst/count<5>_rt_43[0]"));
	engine.register_net(new NetFlow("\gray_inst/count<6>_rt_39[0]"));
	engine.register_net(new NetFlow("\gray_inst/count<7>_rt_29[0]"));
	engine.register_net(new NetFlow("\clk_BUFGP/IBUFG_56[0]"));
	engine.register_net(new NetFlow("enable_IBUF_59[0]"));
	engine.register_net(new NetFlow("out_2_OBUF_84[0]"));
	engine.register_net(new NetFlow("out_5_OBUF_90[0]"));
	engine.register_net(new NetFlow("out_0_OBUF_99[0]"));
	engine.register_net(new NetFlow("\NlwBufferSignal_gray_inst/count_3/CLK[0]"));
	engine.register_net(new NetFlow("\NlwBufferSignal_gray_inst/count_2/CLK[0]"));
	engine.register_net(new NetFlow("\NlwBufferSignal_gray_inst/count_1/CLK[0]"));
	engine.register_net(new NetFlow("\NlwBufferSignal_gray_inst/count_0/CLK[0]"));
	engine.register_net(new NetFlow("\NlwBufferSignal_gray_inst/count_7/CLK[0]"));
	engine.register_net(new NetFlow("\NlwBufferSignal_gray_inst/count_6/CLK[0]"));
	engine.register_net(new NetFlow("\NlwBufferSignal_gray_inst/count_5/CLK[0]"));
	engine.register_net(new NetFlow("\NlwBufferSignal_gray_inst/count_4/CLK[0]"));
	engine.register_net(new NetFlow("\NlwBufferSignal_q_OBUF/I[0]"));
	engine.register_net(new NetFlow("\NlwBufferSignal_out_0_OBUF/I[0]"));
	engine.register_net(new NetFlow("\NlwBufferSignal_out_1_OBUF/I[0]"));
	engine.register_net(new NetFlow("\NlwBufferSignal_out_2_OBUF/I[0]"));
	engine.register_net(new NetFlow("\NlwBufferSignal_out_3_OBUF/I[0]"));
	engine.register_net(new NetFlow("\NlwBufferSignal_out_4_OBUF/I[0]"));
	engine.register_net(new NetFlow("\NlwBufferSignal_out_5_OBUF/I[0]"));
	engine.register_net(new NetFlow("\NlwBufferSignal_out_6_OBUF/I[0]"));
	engine.register_net(new NetFlow("\NlwBufferSignal_out_7_OBUF/I[0]"));
	engine.register_net(new NetFlow("\NlwBufferSignal_clk_BUFGP/BUFG/IN[0]"));
	engine.register_net(new NetFlow("\NlwBufferSignal_cntr_inst/cntr/CLK[0]"));
	engine.register_net(new NetFlow("GND[0]"));
	engine.register_net(new NetFlow("\NLW_reset_4.D5LUT_O_UNCONNECTED[0]"));
	engine.register_net(new NetFlow("\NLW_gray_inst/Mcount_count_cy<3>_CO[0]_UNCONNECTED[0]"));
	engine.register_net(new NetFlow("\NLW_gray_inst/Mcount_count_cy<3>_CO[1]_UNCONNECTED[0]"));
	engine.register_net(new NetFlow("\NLW_gray_inst/Mcount_count_cy<3>_CO[2]_UNCONNECTED[0]"));
	engine.register_net(new NetFlow("\NLW_reset_5.C5LUT_O_UNCONNECTED[0]"));
	engine.register_net(new NetFlow("\NLW_reset_6.B5LUT_O_UNCONNECTED[0]"));
	engine.register_net(new NetFlow("\NLW_N0_2.A5LUT_O_UNCONNECTED[0]"));
	engine.register_net(new NetFlow("\NLW_gray_inst/Mcount_count_xor<7>_CO[0]_UNCONNECTED[0]"));
	engine.register_net(new NetFlow("\NLW_gray_inst/Mcount_count_xor<7>_CO[1]_UNCONNECTED[0]"));
	engine.register_net(new NetFlow("\NLW_gray_inst/Mcount_count_xor<7>_CO[2]_UNCONNECTED[0]"));
	engine.register_net(new NetFlow("\NLW_gray_inst/Mcount_count_xor<7>_CO[3]_UNCONNECTED[0]"));
	engine.register_net(new NetFlow("\NLW_gray_inst/Mcount_count_xor<7>_DI[3]_UNCONNECTED[0]"));
	engine.register_net(new NetFlow("\NLW_reset.C5LUT_O_UNCONNECTED[0]"));
	engine.register_net(new NetFlow("\NLW_reset_2.B5LUT_O_UNCONNECTED[0]"));
	engine.register_net(new NetFlow("\NLW_reset_3.A5LUT_O_UNCONNECTED[0]"));
	engine.register_net(new NetFlow("VCC[0]"));
	engine.register_net(new NetFlow("\gray_inst/count[0]"));
	engine.register_net(new NetFlow("\gray_inst/count[1]"));
	engine.register_net(new NetFlow("\gray_inst/count[2]"));
	engine.register_net(new NetFlow("\gray_inst/count[3]"));
	engine.register_net(new NetFlow("\gray_inst/count[4]"));
	engine.register_net(new NetFlow("\gray_inst/count[5]"));
	engine.register_net(new NetFlow("\gray_inst/count[6]"));
	engine.register_net(new NetFlow("\gray_inst/count[7]"));
	engine.register_net(new NetFlow("\gray_inst/Mcount_count_cy[3]"));
	engine.register_net(new NetFlow("\gray_inst/Mcount_count_lut[0]"));
	engine.register_net(new NetFlow("\gray_inst/Result[0]"));
	engine.register_net(new NetFlow("\gray_inst/Result[1]"));
	engine.register_net(new NetFlow("\gray_inst/Result[2]"));
	engine.register_net(new NetFlow("\gray_inst/Result[3]"));
	engine.register_net(new NetFlow("\gray_inst/Result[4]"));
	engine.register_net(new NetFlow("\gray_inst/Result[5]"));
	engine.register_net(new NetFlow("\gray_inst/Result[6]"));
	engine.register_net(new NetFlow("\gray_inst/Result[7]"));

}

