/******************************************************************************
 * Net instancer.
 * This file instantiate all nets in the simulation.
 * This file was generated by a verilog parser.
 ******************************************************************************/

 
#include <stdio.h>
#include "NetFlow.h"
#include "netinstatiation.h"
#include "SimulatorEngine.h"

void instance_nets(SimulatorEngine engine){

engine.register_primitive(
	new X_FF("\gray_inst/count_3",
	//Module parameters:
	"1'b0", 
	""SLICE_X6Y2"", 
	"null", 
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bgray__inst_scount_a3_b), 
	engine.get_net(NET_INDEX_enable__IBUF__0), 
	engine.get_net(NET_INDEX__bNlwBufferSignal__gray__inst_scount__3_sCLK), 
	engine.get_net(NET_INDEX__bgray__inst_sResult_a3_b), 
	engine.get_net(NET_INDEX_GND), 
	engine.get_net(NET_INDEX_GND), 
)

engine.register_primitive(
	new X_LUT6("\gray_inst/count<3>_rt",
	//Module parameters:
	"64'hFFFF0000FFFF0000", 
	""SLICE_X6Y2"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bgray__inst_scount_l3_g__rt__1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX__bgray__inst_scount_a3_b), 
	engine.get_net(NET_INDEX_1'b1), 
)

engine.register_primitive(
	new X_LUT5("\reset_4.D5LUT",
	//Module parameters:
	"32'h00000000", 
	""SLICE_X6Y2"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bNLW__reset__4_dD5LUT__O__UNCONNECTED), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
)

engine.register_primitive(
	new X_ZERO("\ProtoComp1.CYINITGND",
	//Module parameters:
	""SLICE_X6Y2"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bProtoComp1_dCYINITGND_d0), 
)

engine.register_primitive(
	new X_FF("\gray_inst/count_2",
	//Module parameters:
	"1'b0", 
	""SLICE_X6Y2"", 
	"null", 
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bgray__inst_scount_a2_b), 
	engine.get_net(NET_INDEX_enable__IBUF__0), 
	engine.get_net(NET_INDEX__bNlwBufferSignal__gray__inst_scount__2_sCLK), 
	engine.get_net(NET_INDEX__bgray__inst_sResult_a2_b), 
	engine.get_net(NET_INDEX_GND), 
	engine.get_net(NET_INDEX_GND), 
)

engine.register_primitive(
	new X_CARRY4("\gray_inst/Mcount_count_cy<3>",
	//Module parameters:
	""SLICE_X6Y2"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX_{_bgray__inst_sMcount__count__cy_a3_b,_bNLW__gray__inst_sMcount__count__cy_l3_g__CO_a2_b__UNCONNECTED,_bNLW__gray__inst_sMcount__count__cy_l3_g__CO_a1_b__UNCONNECTED,_bNLW__gray__inst_sMcount__count__cy_l3_g__CO_a0_b__UNCONNECTED}), 
	engine.get_net(NET_INDEX_{_bgray__inst_sResult_a3_b,_bgray__inst_sResult_a2_b,_bgray__inst_sResult_a1_b,_bgray__inst_sResult_a0_b}), 
	engine.get_net(NET_INDEX_1'b0), 
	engine.get_net(NET_INDEX__bProtoComp1_dCYINITGND_d0), 
	engine.get_net(NET_INDEX_{1'b0,1'b0,1'b0,1'b1}), 
	engine.get_net(NET_INDEX_{_bgray__inst_scount_l3_g__rt__1,_bgray__inst_scount_l2_g__rt__13,_bgray__inst_scount_l1_g__rt__17,_bgray__inst_sMcount__count__lut_a0_b}), 
)

engine.register_primitive(
	new X_LUT6("\gray_inst/count<2>_rt",
	//Module parameters:
	"64'hFFFF0000FFFF0000", 
	""SLICE_X6Y2"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bgray__inst_scount_l2_g__rt__13), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX__bgray__inst_scount_a2_b), 
	engine.get_net(NET_INDEX_1'b1), 
)

engine.register_primitive(
	new X_LUT5("\reset_5.C5LUT",
	//Module parameters:
	"32'h00000000", 
	""SLICE_X6Y2"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bNLW__reset__5_dC5LUT__O__UNCONNECTED), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
)

engine.register_primitive(
	new X_FF("\gray_inst/count_1",
	//Module parameters:
	"1'b0", 
	""SLICE_X6Y2"", 
	"null", 
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bgray__inst_scount_a1_b), 
	engine.get_net(NET_INDEX_enable__IBUF__0), 
	engine.get_net(NET_INDEX__bNlwBufferSignal__gray__inst_scount__1_sCLK), 
	engine.get_net(NET_INDEX__bgray__inst_sResult_a1_b), 
	engine.get_net(NET_INDEX_GND), 
	engine.get_net(NET_INDEX_GND), 
)

engine.register_primitive(
	new X_LUT6("\gray_inst/count<1>_rt",
	//Module parameters:
	"64'hFFFF0000FFFF0000", 
	""SLICE_X6Y2"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bgray__inst_scount_l1_g__rt__17), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX__bgray__inst_scount_a1_b), 
	engine.get_net(NET_INDEX_1'b1), 
)

engine.register_primitive(
	new X_LUT5("\reset_6.B5LUT",
	//Module parameters:
	"32'h00000000", 
	""SLICE_X6Y2"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bNLW__reset__6_dB5LUT__O__UNCONNECTED), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
)

engine.register_primitive(
	new X_FF("\gray_inst/count_0",
	//Module parameters:
	"1'b0", 
	""SLICE_X6Y2"", 
	"null", 
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bgray__inst_scount_a0_b), 
	engine.get_net(NET_INDEX_enable__IBUF__0), 
	engine.get_net(NET_INDEX__bNlwBufferSignal__gray__inst_scount__0_sCLK), 
	engine.get_net(NET_INDEX__bgray__inst_sResult_a0_b), 
	engine.get_net(NET_INDEX_GND), 
	engine.get_net(NET_INDEX_GND), 
)

engine.register_primitive(
	new X_LUT6("\gray_inst/Mcount_count_lut<0>_INV_0",
	//Module parameters:
	"64'h0000FFFF0000FFFF", 
	""SLICE_X6Y2"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bgray__inst_sMcount__count__lut_a0_b), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX__bgray__inst_scount_a0_b), 
	engine.get_net(NET_INDEX_1'b1), 
)

engine.register_primitive(
	new X_LUT5("\N0_2.A5LUT",
	//Module parameters:
	"32'hFFFFFFFF", 
	""SLICE_X6Y2"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bNLW__N0__2_dA5LUT__O__UNCONNECTED), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
)

engine.register_primitive(
	new X_FF("\gray_inst/count_7",
	//Module parameters:
	"1'b0", 
	""SLICE_X6Y3"", 
	"null", 
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bgray__inst_scount_a7_b), 
	engine.get_net(NET_INDEX_enable__IBUF__0), 
	engine.get_net(NET_INDEX__bNlwBufferSignal__gray__inst_scount__7_sCLK), 
	engine.get_net(NET_INDEX__bgray__inst_sResult_a7_b), 
	engine.get_net(NET_INDEX_GND), 
	engine.get_net(NET_INDEX_GND), 
)

engine.register_primitive(
	new X_LUT6("\gray_inst/count<7>_rt",
	//Module parameters:
	"64'hFFFFFFFF00000000", 
	""SLICE_X6Y3"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bgray__inst_scount_l7_g__rt__29), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX__bgray__inst_scount_a7_b), 
)

engine.register_primitive(
	new X_FF("\gray_inst/count_6",
	//Module parameters:
	"1'b0", 
	""SLICE_X6Y3"", 
	"null", 
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bgray__inst_scount_a6_b), 
	engine.get_net(NET_INDEX_enable__IBUF__0), 
	engine.get_net(NET_INDEX__bNlwBufferSignal__gray__inst_scount__6_sCLK), 
	engine.get_net(NET_INDEX__bgray__inst_sResult_a6_b), 
	engine.get_net(NET_INDEX_GND), 
	engine.get_net(NET_INDEX_GND), 
)

engine.register_primitive(
	new X_CARRY4("\gray_inst/Mcount_count_xor<7>",
	//Module parameters:
	""SLICE_X6Y3"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX_{_bNLW__gray__inst_sMcount__count__xor_l7_g__CO_a3_b__UNCONNECTED,_bNLW__gray__inst_sMcount__count__xor_l7_g__CO_a2_b__UNCONNECTED,_bNLW__gray__inst_sMcount__count__xor_l7_g__CO_a1_b__UNCONNECTED,_bNLW__gray__inst_sMcount__count__xor_l7_g__CO_a0_b__UNCONNECTED}), 
	engine.get_net(NET_INDEX_{_bgray__inst_sResult_a7_b,_bgray__inst_sResult_a6_b,_bgray__inst_sResult_a5_b,_bgray__inst_sResult_a4_b}), 
	engine.get_net(NET_INDEX__bgray__inst_sMcount__count__cy_a3_b), 
	engine.get_net(NET_INDEX_1'b0), 
	engine.get_net(NET_INDEX_{_bNLW__gray__inst_sMcount__count__xor_l7_g__DI_a3_b__UNCONNECTED,1'b0,1'b0,1'b0}), 
	engine.get_net(NET_INDEX_{_bgray__inst_scount_l7_g__rt__29,_bgray__inst_scount_l6_g__rt__39,_bgray__inst_scount_l5_g__rt__43,_bgray__inst_scount_l4_g__rt__47}), 
)

engine.register_primitive(
	new X_LUT6("\gray_inst/count<6>_rt",
	//Module parameters:
	"64'hFFFF0000FFFF0000", 
	""SLICE_X6Y3"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bgray__inst_scount_l6_g__rt__39), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX__bgray__inst_scount_a6_b), 
	engine.get_net(NET_INDEX_1'b1), 
)

engine.register_primitive(
	new X_LUT5("\reset.C5LUT",
	//Module parameters:
	"32'h00000000", 
	""SLICE_X6Y3"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bNLW__reset_dC5LUT__O__UNCONNECTED), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
)

engine.register_primitive(
	new X_FF("\gray_inst/count_5",
	//Module parameters:
	"1'b0", 
	""SLICE_X6Y3"", 
	"null", 
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bgray__inst_scount_a5_b), 
	engine.get_net(NET_INDEX_enable__IBUF__0), 
	engine.get_net(NET_INDEX__bNlwBufferSignal__gray__inst_scount__5_sCLK), 
	engine.get_net(NET_INDEX__bgray__inst_sResult_a5_b), 
	engine.get_net(NET_INDEX_GND), 
	engine.get_net(NET_INDEX_GND), 
)

engine.register_primitive(
	new X_LUT6("\gray_inst/count<5>_rt",
	//Module parameters:
	"64'hFFFF0000FFFF0000", 
	""SLICE_X6Y3"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bgray__inst_scount_l5_g__rt__43), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX__bgray__inst_scount_a5_b), 
	engine.get_net(NET_INDEX_1'b1), 
)

engine.register_primitive(
	new X_LUT5("\reset_2.B5LUT",
	//Module parameters:
	"32'h00000000", 
	""SLICE_X6Y3"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bNLW__reset__2_dB5LUT__O__UNCONNECTED), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
)

engine.register_primitive(
	new X_FF("\gray_inst/count_4",
	//Module parameters:
	"1'b0", 
	""SLICE_X6Y3"", 
	"null", 
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bgray__inst_scount_a4_b), 
	engine.get_net(NET_INDEX_enable__IBUF__0), 
	engine.get_net(NET_INDEX__bNlwBufferSignal__gray__inst_scount__4_sCLK), 
	engine.get_net(NET_INDEX__bgray__inst_sResult_a4_b), 
	engine.get_net(NET_INDEX_GND), 
	engine.get_net(NET_INDEX_GND), 
)

engine.register_primitive(
	new X_LUT6("\gray_inst/count<4>_rt",
	//Module parameters:
	"64'hFFFF0000FFFF0000", 
	""SLICE_X6Y3"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bgray__inst_scount_l4_g__rt__47), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX__bgray__inst_scount_a4_b), 
	engine.get_net(NET_INDEX_1'b1), 
)

engine.register_primitive(
	new X_LUT5("\reset_3.A5LUT",
	//Module parameters:
	"32'h00000000", 
	""SLICE_X6Y3"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bNLW__reset__3_dA5LUT__O__UNCONNECTED), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
)

engine.register_primitive(
	new X_OPAD("q_31",
	//Module parameters:
	""PAD143"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX_q), 
)

engine.register_primitive(
	new X_OBUF("q_OBUF",
	//Module parameters:
	""PAD143"", 
	"null", 
	"null", 
	"null", 
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX_q), 
	engine.get_net(NET_INDEX__bNlwBufferSignal__q__OBUF_sI), 
)

engine.register_primitive(
	new X_IPAD("clk_35",
	//Module parameters:
	""PAD172"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX_clk), 
)

engine.register_primitive(
	new X_BUF("\clk_BUFGP/IBUFG",
	//Module parameters:
	""PAD172"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bclk__BUFGP_sIBUFG__56), 
	engine.get_net(NET_INDEX_clk), 
)

engine.register_primitive(
	new X_BUF("\ProtoComp4.IMUX",
	//Module parameters:
	""PAD172"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bclk__BUFGP_sIBUFG__0), 
	engine.get_net(NET_INDEX__bclk__BUFGP_sIBUFG__56), 
)

engine.register_primitive(
	new X_IPAD("enable_39",
	//Module parameters:
	""PAD144"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX_enable), 
)

engine.register_primitive(
	new X_BUF("enable_IBUF",
	//Module parameters:
	""PAD144"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX_enable__IBUF__59), 
	engine.get_net(NET_INDEX_enable), 
)

engine.register_primitive(
	new X_BUF("\ProtoComp4.IMUX.1",
	//Module parameters:
	""PAD144"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX_enable__IBUF__0), 
	engine.get_net(NET_INDEX_enable__IBUF__59), 
)

engine.register_primitive(
	new X_OPAD("\out<0>",
	//Module parameters:
	""PAD121"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX_out_a0_b), 
)

engine.register_primitive(
	new X_OBUF("out_0_OBUF",
	//Module parameters:
	""PAD121"", 
	"null", 
	"null", 
	"null", 
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX_out_a0_b), 
	engine.get_net(NET_INDEX__bNlwBufferSignal__out__0__OBUF_sI), 
)

engine.register_primitive(
	new X_OPAD("\out<1>",
	//Module parameters:
	""PAD122"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX_out_a1_b), 
)

engine.register_primitive(
	new X_OBUF("out_1_OBUF",
	//Module parameters:
	""PAD122"", 
	"null", 
	"null", 
	"null", 
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX_out_a1_b), 
	engine.get_net(NET_INDEX__bNlwBufferSignal__out__1__OBUF_sI), 
)

engine.register_primitive(
	new X_OPAD("\out<2>",
	//Module parameters:
	""PAD133"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX_out_a2_b), 
)

engine.register_primitive(
	new X_OBUF("out_2_OBUF",
	//Module parameters:
	""PAD133"", 
	"null", 
	"null", 
	"null", 
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX_out_a2_b), 
	engine.get_net(NET_INDEX__bNlwBufferSignal__out__2__OBUF_sI), 
)

engine.register_primitive(
	new X_OPAD("\out<3>",
	//Module parameters:
	""PAD134"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX_out_a3_b), 
)

engine.register_primitive(
	new X_OBUF("out_3_OBUF",
	//Module parameters:
	""PAD134"", 
	"null", 
	"null", 
	"null", 
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX_out_a3_b), 
	engine.get_net(NET_INDEX__bNlwBufferSignal__out__3__OBUF_sI), 
)

engine.register_primitive(
	new X_OPAD("\out<4>",
	//Module parameters:
	""PAD135"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX_out_a4_b), 
)

engine.register_primitive(
	new X_OBUF("out_4_OBUF",
	//Module parameters:
	""PAD135"", 
	"null", 
	"null", 
	"null", 
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX_out_a4_b), 
	engine.get_net(NET_INDEX__bNlwBufferSignal__out__4__OBUF_sI), 
)

engine.register_primitive(
	new X_OPAD("\out<5>",
	//Module parameters:
	""PAD136"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX_out_a5_b), 
)

engine.register_primitive(
	new X_OBUF("out_5_OBUF",
	//Module parameters:
	""PAD136"", 
	"null", 
	"null", 
	"null", 
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX_out_a5_b), 
	engine.get_net(NET_INDEX__bNlwBufferSignal__out__5__OBUF_sI), 
)

engine.register_primitive(
	new X_OPAD("\out<6>",
	//Module parameters:
	""PAD137"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX_out_a6_b), 
)

engine.register_primitive(
	new X_OBUF("out_6_OBUF",
	//Module parameters:
	""PAD137"", 
	"null", 
	"null", 
	"null", 
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX_out_a6_b), 
	engine.get_net(NET_INDEX__bNlwBufferSignal__out__6__OBUF_sI), 
)

engine.register_primitive(
	new X_OPAD("\out<7>",
	//Module parameters:
	""PAD138"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX_out_a7_b), 
)

engine.register_primitive(
	new X_OBUF("out_7_OBUF",
	//Module parameters:
	""PAD138"", 
	"null", 
	"null", 
	"null", 
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX_out_a7_b), 
	engine.get_net(NET_INDEX__bNlwBufferSignal__out__7__OBUF_sI), 
)

engine.register_primitive(
	new X_CKBUF("\clk_BUFGP/BUFG",
	//Module parameters:
	""BUFGMUX_X3Y13"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX_clk__BUFGP), 
	engine.get_net(NET_INDEX__bNlwBufferSignal__clk__BUFGP_sBUFG_sIN), 
)

engine.register_primitive(
	new X_SFF("\cntr_inst/cntr",
	//Module parameters:
	"1'b0", 
	""SLICE_X1Y2"", 
	"null", 
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bcntr__inst_scntr__133), 
	engine.get_net(NET_INDEX_VCC), 
	engine.get_net(NET_INDEX__bNlwBufferSignal__cntr__inst_scntr_sCLK), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_GND), 
	engine.get_net(NET_INDEX_GND), 
	engine.get_net(NET_INDEX__bcntr__inst_scntr__133), 
	engine.get_net(NET_INDEX_GND), 
)

engine.register_primitive(
	new X_BUF("\out_3_OBUF/out_3_OBUF_DMUX_Delay",
	//Module parameters:
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX_out__2__OBUF__0), 
	engine.get_net(NET_INDEX_out__2__OBUF__84), 
)

engine.register_primitive(
	new X_LUT6("\gray_inst/Mxor_out<3>_xo<0>1",
	//Module parameters:
	"64'h0FF00FF00FF00FF0", 
	""SLICE_X4Y2"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX_out__3__OBUF__126), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX__bgray__inst_scount_a3_b), 
	engine.get_net(NET_INDEX__bgray__inst_scount_a4_b), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
)

engine.register_primitive(
	new X_LUT5("\gray_inst/Mxor_out<2>_xo<0>1",
	//Module parameters:
	"32'h3C3C3C3C", 
	""SLICE_X4Y2"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX_out__2__OBUF__84), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX__bgray__inst_scount_a2_b), 
	engine.get_net(NET_INDEX__bgray__inst_scount_a3_b), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
)

engine.register_primitive(
	new X_BUF("\out_6_OBUF/out_6_OBUF_BMUX_Delay",
	//Module parameters:
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX_out__5__OBUF__0), 
	engine.get_net(NET_INDEX_out__5__OBUF__90), 
)

engine.register_primitive(
	new X_LUT6("\gray_inst/Mxor_out<6>_xo<0>1",
	//Module parameters:
	"64'h3C3C3C3C3C3C3C3C", 
	""SLICE_X4Y3"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX_out__6__OBUF__115), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX__bgray__inst_scount_a7_b), 
	engine.get_net(NET_INDEX__bgray__inst_scount_a6_b), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
)

engine.register_primitive(
	new X_LUT5("\gray_inst/Mxor_out<5>_xo<0>1",
	//Module parameters:
	"32'h0FF00FF0", 
	""SLICE_X4Y3"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX_out__5__OBUF__90), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX__bgray__inst_scount_a6_b), 
	engine.get_net(NET_INDEX__bgray__inst_scount_a5_b), 
	engine.get_net(NET_INDEX_1'b1), 
)

engine.register_primitive(
	new X_LUT6("\gray_inst/Mxor_out<4>_xo<0>1",
	//Module parameters:
	"64'h0000FFFFFFFF0000", 
	""SLICE_X4Y3"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX_out__4__OBUF__135), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX__bgray__inst_scount_a5_b), 
	engine.get_net(NET_INDEX__bgray__inst_scount_a4_b), 
)

engine.register_primitive(
	new X_BUF("\out_1_OBUF/out_1_OBUF_DMUX_Delay",
	//Module parameters:
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX_out__0__OBUF__0), 
	engine.get_net(NET_INDEX_out__0__OBUF__99), 
)

engine.register_primitive(
	new X_LUT6("\gray_inst/Mxor_out<1>_xo<0>1",
	//Module parameters:
	"64'h3333CCCC3333CCCC", 
	""SLICE_X7Y2"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX_out__1__OBUF__121), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX__bgray__inst_scount_a1_b), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX__bgray__inst_scount_a2_b), 
	engine.get_net(NET_INDEX_1'b1), 
)

engine.register_primitive(
	new X_LUT5("\gray_inst/Mxor_out<0>_xo<0>1",
	//Module parameters:
	"32'h3C3C3C3C", 
	""SLICE_X7Y2"", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX_out__0__OBUF__99), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX__bgray__inst_scount_a1_b), 
	engine.get_net(NET_INDEX__bgray__inst_scount_a0_b), 
	engine.get_net(NET_INDEX_1'b1), 
	engine.get_net(NET_INDEX_1'b1), 
)

engine.register_primitive(
	new X_BUF("\NlwBufferBlock_gray_inst/count_3/CLK",
	//Module parameters:
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bNlwBufferSignal__gray__inst_scount__3_sCLK), 
	engine.get_net(NET_INDEX_clk__BUFGP), 
)

engine.register_primitive(
	new X_BUF("\NlwBufferBlock_gray_inst/count_2/CLK",
	//Module parameters:
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bNlwBufferSignal__gray__inst_scount__2_sCLK), 
	engine.get_net(NET_INDEX_clk__BUFGP), 
)

engine.register_primitive(
	new X_BUF("\NlwBufferBlock_gray_inst/count_1/CLK",
	//Module parameters:
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bNlwBufferSignal__gray__inst_scount__1_sCLK), 
	engine.get_net(NET_INDEX_clk__BUFGP), 
)

engine.register_primitive(
	new X_BUF("\NlwBufferBlock_gray_inst/count_0/CLK",
	//Module parameters:
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bNlwBufferSignal__gray__inst_scount__0_sCLK), 
	engine.get_net(NET_INDEX_clk__BUFGP), 
)

engine.register_primitive(
	new X_BUF("\NlwBufferBlock_gray_inst/count_7/CLK",
	//Module parameters:
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bNlwBufferSignal__gray__inst_scount__7_sCLK), 
	engine.get_net(NET_INDEX_clk__BUFGP), 
)

engine.register_primitive(
	new X_BUF("\NlwBufferBlock_gray_inst/count_6/CLK",
	//Module parameters:
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bNlwBufferSignal__gray__inst_scount__6_sCLK), 
	engine.get_net(NET_INDEX_clk__BUFGP), 
)

engine.register_primitive(
	new X_BUF("\NlwBufferBlock_gray_inst/count_5/CLK",
	//Module parameters:
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bNlwBufferSignal__gray__inst_scount__5_sCLK), 
	engine.get_net(NET_INDEX_clk__BUFGP), 
)

engine.register_primitive(
	new X_BUF("\NlwBufferBlock_gray_inst/count_4/CLK",
	//Module parameters:
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bNlwBufferSignal__gray__inst_scount__4_sCLK), 
	engine.get_net(NET_INDEX_clk__BUFGP), 
)

engine.register_primitive(
	new X_BUF("\NlwBufferBlock_q_OBUF/I",
	//Module parameters:
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bNlwBufferSignal__q__OBUF_sI), 
	engine.get_net(NET_INDEX__bcntr__inst_scntr__133), 
)

engine.register_primitive(
	new X_BUF("\NlwBufferBlock_out_0_OBUF/I",
	//Module parameters:
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bNlwBufferSignal__out__0__OBUF_sI), 
	engine.get_net(NET_INDEX_out__0__OBUF__0), 
)

engine.register_primitive(
	new X_BUF("\NlwBufferBlock_out_1_OBUF/I",
	//Module parameters:
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bNlwBufferSignal__out__1__OBUF_sI), 
	engine.get_net(NET_INDEX_out__1__OBUF__121), 
)

engine.register_primitive(
	new X_BUF("\NlwBufferBlock_out_2_OBUF/I",
	//Module parameters:
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bNlwBufferSignal__out__2__OBUF_sI), 
	engine.get_net(NET_INDEX_out__2__OBUF__0), 
)

engine.register_primitive(
	new X_BUF("\NlwBufferBlock_out_3_OBUF/I",
	//Module parameters:
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bNlwBufferSignal__out__3__OBUF_sI), 
	engine.get_net(NET_INDEX_out__3__OBUF__126), 
)

engine.register_primitive(
	new X_BUF("\NlwBufferBlock_out_4_OBUF/I",
	//Module parameters:
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bNlwBufferSignal__out__4__OBUF_sI), 
	engine.get_net(NET_INDEX_out__4__OBUF__135), 
)

engine.register_primitive(
	new X_BUF("\NlwBufferBlock_out_5_OBUF/I",
	//Module parameters:
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bNlwBufferSignal__out__5__OBUF_sI), 
	engine.get_net(NET_INDEX_out__5__OBUF__0), 
)

engine.register_primitive(
	new X_BUF("\NlwBufferBlock_out_6_OBUF/I",
	//Module parameters:
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bNlwBufferSignal__out__6__OBUF_sI), 
	engine.get_net(NET_INDEX_out__6__OBUF__115), 
)

engine.register_primitive(
	new X_BUF("\NlwBufferBlock_out_7_OBUF/I",
	//Module parameters:
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bNlwBufferSignal__out__7__OBUF_sI), 
	engine.get_net(NET_INDEX__bgray__inst_scount_a7_b), 
)

engine.register_primitive(
	new X_BUF("\NlwBufferBlock_clk_BUFGP/BUFG/IN",
	//Module parameters:
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bNlwBufferSignal__clk__BUFGP_sBUFG_sIN), 
	engine.get_net(NET_INDEX__bclk__BUFGP_sIBUFG__0), 
)

engine.register_primitive(
	new X_BUF("\NlwBufferBlock_cntr_inst/cntr/CLK",
	//Module parameters:
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX__bNlwBufferSignal__cntr__inst_scntr_sCLK), 
	engine.get_net(NET_INDEX_clk__BUFGP), 
)

engine.register_primitive(
	new X_ZERO("NlwBlock_dut_top_GND",
	//Module parameters:
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX_GND), 
)

engine.register_primitive(
	new X_ONE("NlwBlock_dut_top_VCC",
	//Module parameters:
	"null", 
	
	//Module port assignments:
	engine.get_net(NET_INDEX_VCC), 
)


}
