/******************************************************************************
 * Generated Cpp template for simulation primitives.
 * Author: Benedek Racz
 ******************************************************************************/

#include "NetFlow.h"
#include "sim_types.h"
#include "Primitive.h"

namespace CPrimitives {
	
	class X_EMAC: public Primitive{

		//Verilog Parameters:
		parameter_string_t LOC;
		//Verilog Ports in definition order:
		NetFlow* DCRHOSTDONEIR; // net ID: DCRHOSTDONEIR lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC0CLIENTANINTERRUPT; // net ID: EMAC0CLIENTANINTERRUPT lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC0CLIENTRXBADFRAME; // net ID: EMAC0CLIENTRXBADFRAME lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC0CLIENTRXCLIENTCLKOUT; // net ID: EMAC0CLIENTRXCLIENTCLKOUT lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC0CLIENTRXD; // net ID: EMAC0CLIENTRXD lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC0CLIENTRXDVLD; // net ID: EMAC0CLIENTRXDVLD lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC0CLIENTRXDVLDMSW; // net ID: EMAC0CLIENTRXDVLDMSW lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC0CLIENTRXDVREG6; // net ID: EMAC0CLIENTRXDVREG6 lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC0CLIENTRXFRAMEDROP; // net ID: EMAC0CLIENTRXFRAMEDROP lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC0CLIENTRXGOODFRAME; // net ID: EMAC0CLIENTRXGOODFRAME lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC0CLIENTRXSTATS; // net ID: EMAC0CLIENTRXSTATS lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC0CLIENTRXSTATSBYTEVLD; // net ID: EMAC0CLIENTRXSTATSBYTEVLD lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC0CLIENTRXSTATSVLD; // net ID: EMAC0CLIENTRXSTATSVLD lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC0CLIENTTXACK; // net ID: EMAC0CLIENTTXACK lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC0CLIENTTXCLIENTCLKOUT; // net ID: EMAC0CLIENTTXCLIENTCLKOUT lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC0CLIENTTXCOLLISION; // net ID: EMAC0CLIENTTXCOLLISION lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC0CLIENTTXGMIIMIICLKOUT; // net ID: EMAC0CLIENTTXGMIIMIICLKOUT lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC0CLIENTTXRETRANSMIT; // net ID: EMAC0CLIENTTXRETRANSMIT lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC0CLIENTTXSTATS; // net ID: EMAC0CLIENTTXSTATS lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC0CLIENTTXSTATSBYTEVLD; // net ID: EMAC0CLIENTTXSTATSBYTEVLD lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC0CLIENTTXSTATSVLD; // net ID: EMAC0CLIENTTXSTATSVLD lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC0PHYENCOMMAALIGN; // net ID: EMAC0PHYENCOMMAALIGN lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC0PHYLOOPBACKMSB; // net ID: EMAC0PHYLOOPBACKMSB lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC0PHYMCLKOUT; // net ID: EMAC0PHYMCLKOUT lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC0PHYMDOUT; // net ID: EMAC0PHYMDOUT lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC0PHYMDTRI; // net ID: EMAC0PHYMDTRI lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC0PHYMGTRXRESET; // net ID: EMAC0PHYMGTRXRESET lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC0PHYMGTTXRESET; // net ID: EMAC0PHYMGTTXRESET lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC0PHYPOWERDOWN; // net ID: EMAC0PHYPOWERDOWN lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC0PHYSYNCACQSTATUS; // net ID: EMAC0PHYSYNCACQSTATUS lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC0PHYTXCHARDISPMODE; // net ID: EMAC0PHYTXCHARDISPMODE lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC0PHYTXCHARDISPVAL; // net ID: EMAC0PHYTXCHARDISPVAL lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC0PHYTXCHARISK; // net ID: EMAC0PHYTXCHARISK lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC0PHYTXCLK; // net ID: EMAC0PHYTXCLK lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC0PHYTXD; // net ID: EMAC0PHYTXD lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC0PHYTXEN; // net ID: EMAC0PHYTXEN lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC0PHYTXER; // net ID: EMAC0PHYTXER lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC1CLIENTANINTERRUPT; // net ID: EMAC1CLIENTANINTERRUPT lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC1CLIENTRXBADFRAME; // net ID: EMAC1CLIENTRXBADFRAME lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC1CLIENTRXCLIENTCLKOUT; // net ID: EMAC1CLIENTRXCLIENTCLKOUT lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC1CLIENTRXD; // net ID: EMAC1CLIENTRXD lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC1CLIENTRXDVLD; // net ID: EMAC1CLIENTRXDVLD lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC1CLIENTRXDVLDMSW; // net ID: EMAC1CLIENTRXDVLDMSW lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC1CLIENTRXDVREG6; // net ID: EMAC1CLIENTRXDVREG6 lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC1CLIENTRXFRAMEDROP; // net ID: EMAC1CLIENTRXFRAMEDROP lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC1CLIENTRXGOODFRAME; // net ID: EMAC1CLIENTRXGOODFRAME lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC1CLIENTRXSTATS; // net ID: EMAC1CLIENTRXSTATS lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC1CLIENTRXSTATSBYTEVLD; // net ID: EMAC1CLIENTRXSTATSBYTEVLD lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC1CLIENTRXSTATSVLD; // net ID: EMAC1CLIENTRXSTATSVLD lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC1CLIENTTXACK; // net ID: EMAC1CLIENTTXACK lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC1CLIENTTXCLIENTCLKOUT; // net ID: EMAC1CLIENTTXCLIENTCLKOUT lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC1CLIENTTXCOLLISION; // net ID: EMAC1CLIENTTXCOLLISION lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC1CLIENTTXGMIIMIICLKOUT; // net ID: EMAC1CLIENTTXGMIIMIICLKOUT lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC1CLIENTTXRETRANSMIT; // net ID: EMAC1CLIENTTXRETRANSMIT lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC1CLIENTTXSTATS; // net ID: EMAC1CLIENTTXSTATS lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC1CLIENTTXSTATSBYTEVLD; // net ID: EMAC1CLIENTTXSTATSBYTEVLD lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC1CLIENTTXSTATSVLD; // net ID: EMAC1CLIENTTXSTATSVLD lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC1PHYENCOMMAALIGN; // net ID: EMAC1PHYENCOMMAALIGN lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC1PHYLOOPBACKMSB; // net ID: EMAC1PHYLOOPBACKMSB lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC1PHYMCLKOUT; // net ID: EMAC1PHYMCLKOUT lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC1PHYMDOUT; // net ID: EMAC1PHYMDOUT lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC1PHYMDTRI; // net ID: EMAC1PHYMDTRI lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC1PHYMGTRXRESET; // net ID: EMAC1PHYMGTRXRESET lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC1PHYMGTTXRESET; // net ID: EMAC1PHYMGTTXRESET lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC1PHYPOWERDOWN; // net ID: EMAC1PHYPOWERDOWN lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC1PHYSYNCACQSTATUS; // net ID: EMAC1PHYSYNCACQSTATUS lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC1PHYTXCHARDISPMODE; // net ID: EMAC1PHYTXCHARDISPMODE lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC1PHYTXCHARDISPVAL; // net ID: EMAC1PHYTXCHARDISPVAL lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC1PHYTXCHARISK; // net ID: EMAC1PHYTXCHARISK lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC1PHYTXCLK; // net ID: EMAC1PHYTXCLK lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC1PHYTXD; // net ID: EMAC1PHYTXD lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC1PHYTXEN; // net ID: EMAC1PHYTXEN lsb: 0  msb: 0 OUTPUT
		NetFlow* EMAC1PHYTXER; // net ID: EMAC1PHYTXER lsb: 0  msb: 0 OUTPUT
		NetFlow* EMACDCRACK; // net ID: EMACDCRACK lsb: 0  msb: 0 OUTPUT
		NetFlow* EMACDCRDBUS; // net ID: EMACDCRDBUS lsb: 0  msb: 0 OUTPUT
		NetFlow* HOSTMIIMRDY; // net ID: HOSTMIIMRDY lsb: 0  msb: 0 OUTPUT
		NetFlow* HOSTRDDATA; // net ID: HOSTRDDATA lsb: 0  msb: 0 OUTPUT
		NetFlow* CLIENTEMAC0DCMLOCKED; // net ID: CLIENTEMAC0DCMLOCKED lsb: 0  msb: 0 INPUT
		NetFlow* CLIENTEMAC0PAUSEREQ; // net ID: CLIENTEMAC0PAUSEREQ lsb: 0  msb: 0 INPUT
		NetFlow* CLIENTEMAC0PAUSEVAL; // net ID: CLIENTEMAC0PAUSEVAL lsb: 0  msb: 15 INPUT
		NetFlow* CLIENTEMAC0RXCLIENTCLKIN; // net ID: CLIENTEMAC0RXCLIENTCLKIN lsb: 0  msb: 0 INPUT
		NetFlow* CLIENTEMAC0TXCLIENTCLKIN; // net ID: CLIENTEMAC0TXCLIENTCLKIN lsb: 0  msb: 0 INPUT
		NetFlow* CLIENTEMAC0TXD; // net ID: CLIENTEMAC0TXD lsb: 0  msb: 15 INPUT
		NetFlow* CLIENTEMAC0TXDVLD; // net ID: CLIENTEMAC0TXDVLD lsb: 0  msb: 0 INPUT
		NetFlow* CLIENTEMAC0TXDVLDMSW; // net ID: CLIENTEMAC0TXDVLDMSW lsb: 0  msb: 0 INPUT
		NetFlow* CLIENTEMAC0TXFIRSTBYTE; // net ID: CLIENTEMAC0TXFIRSTBYTE lsb: 0  msb: 0 INPUT
		NetFlow* CLIENTEMAC0TXGMIIMIICLKIN; // net ID: CLIENTEMAC0TXGMIIMIICLKIN lsb: 0  msb: 0 INPUT
		NetFlow* CLIENTEMAC0TXIFGDELAY; // net ID: CLIENTEMAC0TXIFGDELAY lsb: 0  msb: 7 INPUT
		NetFlow* CLIENTEMAC0TXUNDERRUN; // net ID: CLIENTEMAC0TXUNDERRUN lsb: 0  msb: 0 INPUT
		NetFlow* CLIENTEMAC1DCMLOCKED; // net ID: CLIENTEMAC1DCMLOCKED lsb: 0  msb: 0 INPUT
		NetFlow* CLIENTEMAC1PAUSEREQ; // net ID: CLIENTEMAC1PAUSEREQ lsb: 0  msb: 0 INPUT
		NetFlow* CLIENTEMAC1PAUSEVAL; // net ID: CLIENTEMAC1PAUSEVAL lsb: 0  msb: 15 INPUT
		NetFlow* CLIENTEMAC1RXCLIENTCLKIN; // net ID: CLIENTEMAC1RXCLIENTCLKIN lsb: 0  msb: 0 INPUT
		NetFlow* CLIENTEMAC1TXCLIENTCLKIN; // net ID: CLIENTEMAC1TXCLIENTCLKIN lsb: 0  msb: 0 INPUT
		NetFlow* CLIENTEMAC1TXD; // net ID: CLIENTEMAC1TXD lsb: 0  msb: 15 INPUT
		NetFlow* CLIENTEMAC1TXDVLD; // net ID: CLIENTEMAC1TXDVLD lsb: 0  msb: 0 INPUT
		NetFlow* CLIENTEMAC1TXDVLDMSW; // net ID: CLIENTEMAC1TXDVLDMSW lsb: 0  msb: 0 INPUT
		NetFlow* CLIENTEMAC1TXFIRSTBYTE; // net ID: CLIENTEMAC1TXFIRSTBYTE lsb: 0  msb: 0 INPUT
		NetFlow* CLIENTEMAC1TXGMIIMIICLKIN; // net ID: CLIENTEMAC1TXGMIIMIICLKIN lsb: 0  msb: 0 INPUT
		NetFlow* CLIENTEMAC1TXIFGDELAY; // net ID: CLIENTEMAC1TXIFGDELAY lsb: 0  msb: 7 INPUT
		NetFlow* CLIENTEMAC1TXUNDERRUN; // net ID: CLIENTEMAC1TXUNDERRUN lsb: 0  msb: 0 INPUT
		NetFlow* DCREMACABUS; // net ID: DCREMACABUS lsb: 9  msb: 8 INPUT
		NetFlow* DCREMACCLK; // net ID: DCREMACCLK lsb: 0  msb: 0 INPUT
		NetFlow* DCREMACDBUS; // net ID: DCREMACDBUS lsb: 31  msb: 0 INPUT
		NetFlow* DCREMACENABLE; // net ID: DCREMACENABLE lsb: 0  msb: 0 INPUT
		NetFlow* DCREMACREAD; // net ID: DCREMACREAD lsb: 0  msb: 0 INPUT
		NetFlow* DCREMACWRITE; // net ID: DCREMACWRITE lsb: 0  msb: 0 INPUT
		NetFlow* HOSTADDR; // net ID: HOSTADDR lsb: 0  msb: 9 INPUT
		NetFlow* HOSTCLK; // net ID: HOSTCLK lsb: 0  msb: 0 INPUT
		NetFlow* HOSTEMAC1SEL; // net ID: HOSTEMAC1SEL lsb: 0  msb: 0 INPUT
		NetFlow* HOSTMIIMSEL; // net ID: HOSTMIIMSEL lsb: 0  msb: 0 INPUT
		NetFlow* HOSTOPCODE; // net ID: HOSTOPCODE lsb: 0  msb: 1 INPUT
		NetFlow* HOSTREQ; // net ID: HOSTREQ lsb: 0  msb: 0 INPUT
		NetFlow* HOSTWRDATA; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
		NetFlow* PHYEMAC0COL; // net ID: PHYEMAC0COL lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMAC0CRS; // net ID: PHYEMAC0CRS lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMAC0GTXCLK; // net ID: PHYEMAC0GTXCLK lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMAC0MCLKIN; // net ID: PHYEMAC0MCLKIN lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMAC0MDIN; // net ID: PHYEMAC0MDIN lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMAC0MIITXCLK; // net ID: PHYEMAC0MIITXCLK lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMAC0PHYAD; // net ID: PHYEMAC0PHYAD lsb: 0  msb: 4 INPUT
		NetFlow* PHYEMAC0RXBUFERR; // net ID: PHYEMAC0RXBUFERR lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMAC0RXBUFSTATUS; // net ID: PHYEMAC0RXBUFSTATUS lsb: 0  msb: 1 INPUT
		NetFlow* PHYEMAC0RXCHARISCOMMA; // net ID: PHYEMAC0RXCHARISCOMMA lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMAC0RXCHARISK; // net ID: PHYEMAC0RXCHARISK lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMAC0RXCHECKINGCRC; // net ID: PHYEMAC0RXCHECKINGCRC lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMAC0RXCLK; // net ID: PHYEMAC0RXCLK lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMAC0RXCLKCORCNT; // net ID: PHYEMAC0RXCLKCORCNT lsb: 0  msb: 2 INPUT
		NetFlow* PHYEMAC0RXCOMMADET; // net ID: PHYEMAC0RXCOMMADET lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMAC0RXD; // net ID: PHYEMAC0RXD lsb: 0  msb: 7 INPUT
		NetFlow* PHYEMAC0RXDISPERR; // net ID: PHYEMAC0RXDISPERR lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMAC0RXDV; // net ID: PHYEMAC0RXDV lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMAC0RXER; // net ID: PHYEMAC0RXER lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMAC0RXLOSSOFSYNC; // net ID: PHYEMAC0RXLOSSOFSYNC lsb: 0  msb: 1 INPUT
		NetFlow* PHYEMAC0RXNOTINTABLE; // net ID: PHYEMAC0RXNOTINTABLE lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMAC0RXRUNDISP; // net ID: PHYEMAC0RXRUNDISP lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMAC0SIGNALDET; // net ID: PHYEMAC0SIGNALDET lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMAC0TXBUFERR; // net ID: PHYEMAC0TXBUFERR lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMAC1COL; // net ID: PHYEMAC1COL lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMAC1CRS; // net ID: PHYEMAC1CRS lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMAC1GTXCLK; // net ID: PHYEMAC1GTXCLK lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMAC1MCLKIN; // net ID: PHYEMAC1MCLKIN lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMAC1MDIN; // net ID: PHYEMAC1MDIN lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMAC1MIITXCLK; // net ID: PHYEMAC1MIITXCLK lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMAC1PHYAD; // net ID: PHYEMAC1PHYAD lsb: 0  msb: 4 INPUT
		NetFlow* PHYEMAC1RXBUFERR; // net ID: PHYEMAC1RXBUFERR lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMAC1RXBUFSTATUS; // net ID: PHYEMAC1RXBUFSTATUS lsb: 0  msb: 1 INPUT
		NetFlow* PHYEMAC1RXCHARISCOMMA; // net ID: PHYEMAC1RXCHARISCOMMA lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMAC1RXCHARISK; // net ID: PHYEMAC1RXCHARISK lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMAC1RXCHECKINGCRC; // net ID: PHYEMAC1RXCHECKINGCRC lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMAC1RXCLK; // net ID: PHYEMAC1RXCLK lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMAC1RXCLKCORCNT; // net ID: PHYEMAC1RXCLKCORCNT lsb: 0  msb: 2 INPUT
		NetFlow* PHYEMAC1RXCOMMADET; // net ID: PHYEMAC1RXCOMMADET lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMAC1RXD; // net ID: PHYEMAC1RXD lsb: 0  msb: 7 INPUT
		NetFlow* PHYEMAC1RXDISPERR; // net ID: PHYEMAC1RXDISPERR lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMAC1RXDV; // net ID: PHYEMAC1RXDV lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMAC1RXER; // net ID: PHYEMAC1RXER lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMAC1RXLOSSOFSYNC; // net ID: PHYEMAC1RXLOSSOFSYNC lsb: 0  msb: 1 INPUT
		NetFlow* PHYEMAC1RXNOTINTABLE; // net ID: PHYEMAC1RXNOTINTABLE lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMAC1RXRUNDISP; // net ID: PHYEMAC1RXRUNDISP lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMAC1SIGNALDET; // net ID: PHYEMAC1SIGNALDET lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMAC1TXBUFERR; // net ID: PHYEMAC1TXBUFERR lsb: 0  msb: 0 INPUT
		NetFlow* RESET; // net ID: RESET lsb: 0  msb: 0 INPUT
		NetFlow* TIEEMAC0CONFIGVEC; // net ID: TIEEMAC0CONFIGVEC lsb: 0  msb: 79 INPUT
		NetFlow* TIEEMAC0UNICASTADDR; // net ID: TIEEMAC0UNICASTADDR lsb: 0  msb: 47 INPUT
		NetFlow* TIEEMAC1CONFIGVEC; // net ID: TIEEMAC1CONFIGVEC lsb: 0  msb: 79 INPUT
		NetFlow* TIEEMAC1UNICASTADDR; // net ID: TIEEMAC1UNICASTADDR lsb: 0  msb: 47 INPUT
		
		X_EMAC(
			const char * name,
			//Verilog Parameters:
			parameter_string_t LOC, // Default: "UNPLACED"
			//Verilog Ports in definition order:
			NetFlow* DCRHOSTDONEIR, // net ID: DCRHOSTDONEIR lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC0CLIENTANINTERRUPT, // net ID: EMAC0CLIENTANINTERRUPT lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC0CLIENTRXBADFRAME, // net ID: EMAC0CLIENTRXBADFRAME lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC0CLIENTRXCLIENTCLKOUT, // net ID: EMAC0CLIENTRXCLIENTCLKOUT lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC0CLIENTRXD, // net ID: EMAC0CLIENTRXD lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC0CLIENTRXDVLD, // net ID: EMAC0CLIENTRXDVLD lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC0CLIENTRXDVLDMSW, // net ID: EMAC0CLIENTRXDVLDMSW lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC0CLIENTRXDVREG6, // net ID: EMAC0CLIENTRXDVREG6 lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC0CLIENTRXFRAMEDROP, // net ID: EMAC0CLIENTRXFRAMEDROP lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC0CLIENTRXGOODFRAME, // net ID: EMAC0CLIENTRXGOODFRAME lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC0CLIENTRXSTATS, // net ID: EMAC0CLIENTRXSTATS lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC0CLIENTRXSTATSBYTEVLD, // net ID: EMAC0CLIENTRXSTATSBYTEVLD lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC0CLIENTRXSTATSVLD, // net ID: EMAC0CLIENTRXSTATSVLD lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC0CLIENTTXACK, // net ID: EMAC0CLIENTTXACK lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC0CLIENTTXCLIENTCLKOUT, // net ID: EMAC0CLIENTTXCLIENTCLKOUT lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC0CLIENTTXCOLLISION, // net ID: EMAC0CLIENTTXCOLLISION lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC0CLIENTTXGMIIMIICLKOUT, // net ID: EMAC0CLIENTTXGMIIMIICLKOUT lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC0CLIENTTXRETRANSMIT, // net ID: EMAC0CLIENTTXRETRANSMIT lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC0CLIENTTXSTATS, // net ID: EMAC0CLIENTTXSTATS lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC0CLIENTTXSTATSBYTEVLD, // net ID: EMAC0CLIENTTXSTATSBYTEVLD lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC0CLIENTTXSTATSVLD, // net ID: EMAC0CLIENTTXSTATSVLD lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC0PHYENCOMMAALIGN, // net ID: EMAC0PHYENCOMMAALIGN lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC0PHYLOOPBACKMSB, // net ID: EMAC0PHYLOOPBACKMSB lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC0PHYMCLKOUT, // net ID: EMAC0PHYMCLKOUT lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC0PHYMDOUT, // net ID: EMAC0PHYMDOUT lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC0PHYMDTRI, // net ID: EMAC0PHYMDTRI lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC0PHYMGTRXRESET, // net ID: EMAC0PHYMGTRXRESET lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC0PHYMGTTXRESET, // net ID: EMAC0PHYMGTTXRESET lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC0PHYPOWERDOWN, // net ID: EMAC0PHYPOWERDOWN lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC0PHYSYNCACQSTATUS, // net ID: EMAC0PHYSYNCACQSTATUS lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC0PHYTXCHARDISPMODE, // net ID: EMAC0PHYTXCHARDISPMODE lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC0PHYTXCHARDISPVAL, // net ID: EMAC0PHYTXCHARDISPVAL lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC0PHYTXCHARISK, // net ID: EMAC0PHYTXCHARISK lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC0PHYTXCLK, // net ID: EMAC0PHYTXCLK lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC0PHYTXD, // net ID: EMAC0PHYTXD lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC0PHYTXEN, // net ID: EMAC0PHYTXEN lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC0PHYTXER, // net ID: EMAC0PHYTXER lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC1CLIENTANINTERRUPT, // net ID: EMAC1CLIENTANINTERRUPT lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC1CLIENTRXBADFRAME, // net ID: EMAC1CLIENTRXBADFRAME lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC1CLIENTRXCLIENTCLKOUT, // net ID: EMAC1CLIENTRXCLIENTCLKOUT lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC1CLIENTRXD, // net ID: EMAC1CLIENTRXD lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC1CLIENTRXDVLD, // net ID: EMAC1CLIENTRXDVLD lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC1CLIENTRXDVLDMSW, // net ID: EMAC1CLIENTRXDVLDMSW lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC1CLIENTRXDVREG6, // net ID: EMAC1CLIENTRXDVREG6 lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC1CLIENTRXFRAMEDROP, // net ID: EMAC1CLIENTRXFRAMEDROP lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC1CLIENTRXGOODFRAME, // net ID: EMAC1CLIENTRXGOODFRAME lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC1CLIENTRXSTATS, // net ID: EMAC1CLIENTRXSTATS lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC1CLIENTRXSTATSBYTEVLD, // net ID: EMAC1CLIENTRXSTATSBYTEVLD lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC1CLIENTRXSTATSVLD, // net ID: EMAC1CLIENTRXSTATSVLD lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC1CLIENTTXACK, // net ID: EMAC1CLIENTTXACK lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC1CLIENTTXCLIENTCLKOUT, // net ID: EMAC1CLIENTTXCLIENTCLKOUT lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC1CLIENTTXCOLLISION, // net ID: EMAC1CLIENTTXCOLLISION lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC1CLIENTTXGMIIMIICLKOUT, // net ID: EMAC1CLIENTTXGMIIMIICLKOUT lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC1CLIENTTXRETRANSMIT, // net ID: EMAC1CLIENTTXRETRANSMIT lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC1CLIENTTXSTATS, // net ID: EMAC1CLIENTTXSTATS lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC1CLIENTTXSTATSBYTEVLD, // net ID: EMAC1CLIENTTXSTATSBYTEVLD lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC1CLIENTTXSTATSVLD, // net ID: EMAC1CLIENTTXSTATSVLD lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC1PHYENCOMMAALIGN, // net ID: EMAC1PHYENCOMMAALIGN lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC1PHYLOOPBACKMSB, // net ID: EMAC1PHYLOOPBACKMSB lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC1PHYMCLKOUT, // net ID: EMAC1PHYMCLKOUT lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC1PHYMDOUT, // net ID: EMAC1PHYMDOUT lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC1PHYMDTRI, // net ID: EMAC1PHYMDTRI lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC1PHYMGTRXRESET, // net ID: EMAC1PHYMGTRXRESET lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC1PHYMGTTXRESET, // net ID: EMAC1PHYMGTTXRESET lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC1PHYPOWERDOWN, // net ID: EMAC1PHYPOWERDOWN lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC1PHYSYNCACQSTATUS, // net ID: EMAC1PHYSYNCACQSTATUS lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC1PHYTXCHARDISPMODE, // net ID: EMAC1PHYTXCHARDISPMODE lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC1PHYTXCHARDISPVAL, // net ID: EMAC1PHYTXCHARDISPVAL lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC1PHYTXCHARISK, // net ID: EMAC1PHYTXCHARISK lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC1PHYTXCLK, // net ID: EMAC1PHYTXCLK lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC1PHYTXD, // net ID: EMAC1PHYTXD lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC1PHYTXEN, // net ID: EMAC1PHYTXEN lsb: 0  msb: 0 OUTPUT
			NetFlow* EMAC1PHYTXER, // net ID: EMAC1PHYTXER lsb: 0  msb: 0 OUTPUT
			NetFlow* EMACDCRACK, // net ID: EMACDCRACK lsb: 0  msb: 0 OUTPUT
			NetFlow* EMACDCRDBUS, // net ID: EMACDCRDBUS lsb: 0  msb: 0 OUTPUT
			NetFlow* HOSTMIIMRDY, // net ID: HOSTMIIMRDY lsb: 0  msb: 0 OUTPUT
			NetFlow* HOSTRDDATA, // net ID: HOSTRDDATA lsb: 0  msb: 0 OUTPUT
			NetFlow* CLIENTEMAC0DCMLOCKED, // net ID: CLIENTEMAC0DCMLOCKED lsb: 0  msb: 0 INPUT
			NetFlow* CLIENTEMAC0PAUSEREQ, // net ID: CLIENTEMAC0PAUSEREQ lsb: 0  msb: 0 INPUT
			NetFlow* CLIENTEMAC0PAUSEVAL, // net ID: CLIENTEMAC0PAUSEVAL lsb: 0  msb: 15 INPUT
			NetFlow* CLIENTEMAC0RXCLIENTCLKIN, // net ID: CLIENTEMAC0RXCLIENTCLKIN lsb: 0  msb: 0 INPUT
			NetFlow* CLIENTEMAC0TXCLIENTCLKIN, // net ID: CLIENTEMAC0TXCLIENTCLKIN lsb: 0  msb: 0 INPUT
			NetFlow* CLIENTEMAC0TXD, // net ID: CLIENTEMAC0TXD lsb: 0  msb: 15 INPUT
			NetFlow* CLIENTEMAC0TXDVLD, // net ID: CLIENTEMAC0TXDVLD lsb: 0  msb: 0 INPUT
			NetFlow* CLIENTEMAC0TXDVLDMSW, // net ID: CLIENTEMAC0TXDVLDMSW lsb: 0  msb: 0 INPUT
			NetFlow* CLIENTEMAC0TXFIRSTBYTE, // net ID: CLIENTEMAC0TXFIRSTBYTE lsb: 0  msb: 0 INPUT
			NetFlow* CLIENTEMAC0TXGMIIMIICLKIN, // net ID: CLIENTEMAC0TXGMIIMIICLKIN lsb: 0  msb: 0 INPUT
			NetFlow* CLIENTEMAC0TXIFGDELAY, // net ID: CLIENTEMAC0TXIFGDELAY lsb: 0  msb: 7 INPUT
			NetFlow* CLIENTEMAC0TXUNDERRUN, // net ID: CLIENTEMAC0TXUNDERRUN lsb: 0  msb: 0 INPUT
			NetFlow* CLIENTEMAC1DCMLOCKED, // net ID: CLIENTEMAC1DCMLOCKED lsb: 0  msb: 0 INPUT
			NetFlow* CLIENTEMAC1PAUSEREQ, // net ID: CLIENTEMAC1PAUSEREQ lsb: 0  msb: 0 INPUT
			NetFlow* CLIENTEMAC1PAUSEVAL, // net ID: CLIENTEMAC1PAUSEVAL lsb: 0  msb: 15 INPUT
			NetFlow* CLIENTEMAC1RXCLIENTCLKIN, // net ID: CLIENTEMAC1RXCLIENTCLKIN lsb: 0  msb: 0 INPUT
			NetFlow* CLIENTEMAC1TXCLIENTCLKIN, // net ID: CLIENTEMAC1TXCLIENTCLKIN lsb: 0  msb: 0 INPUT
			NetFlow* CLIENTEMAC1TXD, // net ID: CLIENTEMAC1TXD lsb: 0  msb: 15 INPUT
			NetFlow* CLIENTEMAC1TXDVLD, // net ID: CLIENTEMAC1TXDVLD lsb: 0  msb: 0 INPUT
			NetFlow* CLIENTEMAC1TXDVLDMSW, // net ID: CLIENTEMAC1TXDVLDMSW lsb: 0  msb: 0 INPUT
			NetFlow* CLIENTEMAC1TXFIRSTBYTE, // net ID: CLIENTEMAC1TXFIRSTBYTE lsb: 0  msb: 0 INPUT
			NetFlow* CLIENTEMAC1TXGMIIMIICLKIN, // net ID: CLIENTEMAC1TXGMIIMIICLKIN lsb: 0  msb: 0 INPUT
			NetFlow* CLIENTEMAC1TXIFGDELAY, // net ID: CLIENTEMAC1TXIFGDELAY lsb: 0  msb: 7 INPUT
			NetFlow* CLIENTEMAC1TXUNDERRUN, // net ID: CLIENTEMAC1TXUNDERRUN lsb: 0  msb: 0 INPUT
			NetFlow* DCREMACABUS, // net ID: DCREMACABUS lsb: 9  msb: 8 INPUT
			NetFlow* DCREMACCLK, // net ID: DCREMACCLK lsb: 0  msb: 0 INPUT
			NetFlow* DCREMACDBUS, // net ID: DCREMACDBUS lsb: 31  msb: 0 INPUT
			NetFlow* DCREMACENABLE, // net ID: DCREMACENABLE lsb: 0  msb: 0 INPUT
			NetFlow* DCREMACREAD, // net ID: DCREMACREAD lsb: 0  msb: 0 INPUT
			NetFlow* DCREMACWRITE, // net ID: DCREMACWRITE lsb: 0  msb: 0 INPUT
			NetFlow* HOSTADDR, // net ID: HOSTADDR lsb: 0  msb: 9 INPUT
			NetFlow* HOSTCLK, // net ID: HOSTCLK lsb: 0  msb: 0 INPUT
			NetFlow* HOSTEMAC1SEL, // net ID: HOSTEMAC1SEL lsb: 0  msb: 0 INPUT
			NetFlow* HOSTMIIMSEL, // net ID: HOSTMIIMSEL lsb: 0  msb: 0 INPUT
			NetFlow* HOSTOPCODE, // net ID: HOSTOPCODE lsb: 0  msb: 1 INPUT
			NetFlow* HOSTREQ, // net ID: HOSTREQ lsb: 0  msb: 0 INPUT
			NetFlow* HOSTWRDATA, // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			NetFlow* PHYEMAC0COL, // net ID: PHYEMAC0COL lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMAC0CRS, // net ID: PHYEMAC0CRS lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMAC0GTXCLK, // net ID: PHYEMAC0GTXCLK lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMAC0MCLKIN, // net ID: PHYEMAC0MCLKIN lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMAC0MDIN, // net ID: PHYEMAC0MDIN lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMAC0MIITXCLK, // net ID: PHYEMAC0MIITXCLK lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMAC0PHYAD, // net ID: PHYEMAC0PHYAD lsb: 0  msb: 4 INPUT
			NetFlow* PHYEMAC0RXBUFERR, // net ID: PHYEMAC0RXBUFERR lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMAC0RXBUFSTATUS, // net ID: PHYEMAC0RXBUFSTATUS lsb: 0  msb: 1 INPUT
			NetFlow* PHYEMAC0RXCHARISCOMMA, // net ID: PHYEMAC0RXCHARISCOMMA lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMAC0RXCHARISK, // net ID: PHYEMAC0RXCHARISK lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMAC0RXCHECKINGCRC, // net ID: PHYEMAC0RXCHECKINGCRC lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMAC0RXCLK, // net ID: PHYEMAC0RXCLK lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMAC0RXCLKCORCNT, // net ID: PHYEMAC0RXCLKCORCNT lsb: 0  msb: 2 INPUT
			NetFlow* PHYEMAC0RXCOMMADET, // net ID: PHYEMAC0RXCOMMADET lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMAC0RXD, // net ID: PHYEMAC0RXD lsb: 0  msb: 7 INPUT
			NetFlow* PHYEMAC0RXDISPERR, // net ID: PHYEMAC0RXDISPERR lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMAC0RXDV, // net ID: PHYEMAC0RXDV lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMAC0RXER, // net ID: PHYEMAC0RXER lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMAC0RXLOSSOFSYNC, // net ID: PHYEMAC0RXLOSSOFSYNC lsb: 0  msb: 1 INPUT
			NetFlow* PHYEMAC0RXNOTINTABLE, // net ID: PHYEMAC0RXNOTINTABLE lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMAC0RXRUNDISP, // net ID: PHYEMAC0RXRUNDISP lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMAC0SIGNALDET, // net ID: PHYEMAC0SIGNALDET lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMAC0TXBUFERR, // net ID: PHYEMAC0TXBUFERR lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMAC1COL, // net ID: PHYEMAC1COL lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMAC1CRS, // net ID: PHYEMAC1CRS lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMAC1GTXCLK, // net ID: PHYEMAC1GTXCLK lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMAC1MCLKIN, // net ID: PHYEMAC1MCLKIN lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMAC1MDIN, // net ID: PHYEMAC1MDIN lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMAC1MIITXCLK, // net ID: PHYEMAC1MIITXCLK lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMAC1PHYAD, // net ID: PHYEMAC1PHYAD lsb: 0  msb: 4 INPUT
			NetFlow* PHYEMAC1RXBUFERR, // net ID: PHYEMAC1RXBUFERR lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMAC1RXBUFSTATUS, // net ID: PHYEMAC1RXBUFSTATUS lsb: 0  msb: 1 INPUT
			NetFlow* PHYEMAC1RXCHARISCOMMA, // net ID: PHYEMAC1RXCHARISCOMMA lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMAC1RXCHARISK, // net ID: PHYEMAC1RXCHARISK lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMAC1RXCHECKINGCRC, // net ID: PHYEMAC1RXCHECKINGCRC lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMAC1RXCLK, // net ID: PHYEMAC1RXCLK lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMAC1RXCLKCORCNT, // net ID: PHYEMAC1RXCLKCORCNT lsb: 0  msb: 2 INPUT
			NetFlow* PHYEMAC1RXCOMMADET, // net ID: PHYEMAC1RXCOMMADET lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMAC1RXD, // net ID: PHYEMAC1RXD lsb: 0  msb: 7 INPUT
			NetFlow* PHYEMAC1RXDISPERR, // net ID: PHYEMAC1RXDISPERR lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMAC1RXDV, // net ID: PHYEMAC1RXDV lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMAC1RXER, // net ID: PHYEMAC1RXER lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMAC1RXLOSSOFSYNC, // net ID: PHYEMAC1RXLOSSOFSYNC lsb: 0  msb: 1 INPUT
			NetFlow* PHYEMAC1RXNOTINTABLE, // net ID: PHYEMAC1RXNOTINTABLE lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMAC1RXRUNDISP, // net ID: PHYEMAC1RXRUNDISP lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMAC1SIGNALDET, // net ID: PHYEMAC1SIGNALDET lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMAC1TXBUFERR, // net ID: PHYEMAC1TXBUFERR lsb: 0  msb: 0 INPUT
			NetFlow* RESET, // net ID: RESET lsb: 0  msb: 0 INPUT
			NetFlow* TIEEMAC0CONFIGVEC, // net ID: TIEEMAC0CONFIGVEC lsb: 0  msb: 79 INPUT
			NetFlow* TIEEMAC0UNICASTADDR, // net ID: TIEEMAC0UNICASTADDR lsb: 0  msb: 47 INPUT
			NetFlow* TIEEMAC1CONFIGVEC, // net ID: TIEEMAC1CONFIGVEC lsb: 0  msb: 79 INPUT
			NetFlow* TIEEMAC1UNICASTADDR // net ID: TIEEMAC1UNICASTADDR lsb: 0  msb: 47 INPUT
			):Primitive(name){
			
			// Assign parameters and ports: 
			//Verilog Parameters:
			this->LOC = LOC; // Default: "UNPLACED"
			//Verilog Ports in definition order:
			this->DCRHOSTDONEIR = DCRHOSTDONEIR; // net ID: DCRHOSTDONEIR lsb: 0  msb: 0 OUTPUT
			this->EMAC0CLIENTANINTERRUPT = EMAC0CLIENTANINTERRUPT; // net ID: EMAC0CLIENTANINTERRUPT lsb: 0  msb: 0 OUTPUT
			this->EMAC0CLIENTRXBADFRAME = EMAC0CLIENTRXBADFRAME; // net ID: EMAC0CLIENTRXBADFRAME lsb: 0  msb: 0 OUTPUT
			this->EMAC0CLIENTRXCLIENTCLKOUT = EMAC0CLIENTRXCLIENTCLKOUT; // net ID: EMAC0CLIENTRXCLIENTCLKOUT lsb: 0  msb: 0 OUTPUT
			this->EMAC0CLIENTRXD = EMAC0CLIENTRXD; // net ID: EMAC0CLIENTRXD lsb: 0  msb: 0 OUTPUT
			this->EMAC0CLIENTRXDVLD = EMAC0CLIENTRXDVLD; // net ID: EMAC0CLIENTRXDVLD lsb: 0  msb: 0 OUTPUT
			this->EMAC0CLIENTRXDVLDMSW = EMAC0CLIENTRXDVLDMSW; // net ID: EMAC0CLIENTRXDVLDMSW lsb: 0  msb: 0 OUTPUT
			this->EMAC0CLIENTRXDVREG6 = EMAC0CLIENTRXDVREG6; // net ID: EMAC0CLIENTRXDVREG6 lsb: 0  msb: 0 OUTPUT
			this->EMAC0CLIENTRXFRAMEDROP = EMAC0CLIENTRXFRAMEDROP; // net ID: EMAC0CLIENTRXFRAMEDROP lsb: 0  msb: 0 OUTPUT
			this->EMAC0CLIENTRXGOODFRAME = EMAC0CLIENTRXGOODFRAME; // net ID: EMAC0CLIENTRXGOODFRAME lsb: 0  msb: 0 OUTPUT
			this->EMAC0CLIENTRXSTATS = EMAC0CLIENTRXSTATS; // net ID: EMAC0CLIENTRXSTATS lsb: 0  msb: 0 OUTPUT
			this->EMAC0CLIENTRXSTATSBYTEVLD = EMAC0CLIENTRXSTATSBYTEVLD; // net ID: EMAC0CLIENTRXSTATSBYTEVLD lsb: 0  msb: 0 OUTPUT
			this->EMAC0CLIENTRXSTATSVLD = EMAC0CLIENTRXSTATSVLD; // net ID: EMAC0CLIENTRXSTATSVLD lsb: 0  msb: 0 OUTPUT
			this->EMAC0CLIENTTXACK = EMAC0CLIENTTXACK; // net ID: EMAC0CLIENTTXACK lsb: 0  msb: 0 OUTPUT
			this->EMAC0CLIENTTXCLIENTCLKOUT = EMAC0CLIENTTXCLIENTCLKOUT; // net ID: EMAC0CLIENTTXCLIENTCLKOUT lsb: 0  msb: 0 OUTPUT
			this->EMAC0CLIENTTXCOLLISION = EMAC0CLIENTTXCOLLISION; // net ID: EMAC0CLIENTTXCOLLISION lsb: 0  msb: 0 OUTPUT
			this->EMAC0CLIENTTXGMIIMIICLKOUT = EMAC0CLIENTTXGMIIMIICLKOUT; // net ID: EMAC0CLIENTTXGMIIMIICLKOUT lsb: 0  msb: 0 OUTPUT
			this->EMAC0CLIENTTXRETRANSMIT = EMAC0CLIENTTXRETRANSMIT; // net ID: EMAC0CLIENTTXRETRANSMIT lsb: 0  msb: 0 OUTPUT
			this->EMAC0CLIENTTXSTATS = EMAC0CLIENTTXSTATS; // net ID: EMAC0CLIENTTXSTATS lsb: 0  msb: 0 OUTPUT
			this->EMAC0CLIENTTXSTATSBYTEVLD = EMAC0CLIENTTXSTATSBYTEVLD; // net ID: EMAC0CLIENTTXSTATSBYTEVLD lsb: 0  msb: 0 OUTPUT
			this->EMAC0CLIENTTXSTATSVLD = EMAC0CLIENTTXSTATSVLD; // net ID: EMAC0CLIENTTXSTATSVLD lsb: 0  msb: 0 OUTPUT
			this->EMAC0PHYENCOMMAALIGN = EMAC0PHYENCOMMAALIGN; // net ID: EMAC0PHYENCOMMAALIGN lsb: 0  msb: 0 OUTPUT
			this->EMAC0PHYLOOPBACKMSB = EMAC0PHYLOOPBACKMSB; // net ID: EMAC0PHYLOOPBACKMSB lsb: 0  msb: 0 OUTPUT
			this->EMAC0PHYMCLKOUT = EMAC0PHYMCLKOUT; // net ID: EMAC0PHYMCLKOUT lsb: 0  msb: 0 OUTPUT
			this->EMAC0PHYMDOUT = EMAC0PHYMDOUT; // net ID: EMAC0PHYMDOUT lsb: 0  msb: 0 OUTPUT
			this->EMAC0PHYMDTRI = EMAC0PHYMDTRI; // net ID: EMAC0PHYMDTRI lsb: 0  msb: 0 OUTPUT
			this->EMAC0PHYMGTRXRESET = EMAC0PHYMGTRXRESET; // net ID: EMAC0PHYMGTRXRESET lsb: 0  msb: 0 OUTPUT
			this->EMAC0PHYMGTTXRESET = EMAC0PHYMGTTXRESET; // net ID: EMAC0PHYMGTTXRESET lsb: 0  msb: 0 OUTPUT
			this->EMAC0PHYPOWERDOWN = EMAC0PHYPOWERDOWN; // net ID: EMAC0PHYPOWERDOWN lsb: 0  msb: 0 OUTPUT
			this->EMAC0PHYSYNCACQSTATUS = EMAC0PHYSYNCACQSTATUS; // net ID: EMAC0PHYSYNCACQSTATUS lsb: 0  msb: 0 OUTPUT
			this->EMAC0PHYTXCHARDISPMODE = EMAC0PHYTXCHARDISPMODE; // net ID: EMAC0PHYTXCHARDISPMODE lsb: 0  msb: 0 OUTPUT
			this->EMAC0PHYTXCHARDISPVAL = EMAC0PHYTXCHARDISPVAL; // net ID: EMAC0PHYTXCHARDISPVAL lsb: 0  msb: 0 OUTPUT
			this->EMAC0PHYTXCHARISK = EMAC0PHYTXCHARISK; // net ID: EMAC0PHYTXCHARISK lsb: 0  msb: 0 OUTPUT
			this->EMAC0PHYTXCLK = EMAC0PHYTXCLK; // net ID: EMAC0PHYTXCLK lsb: 0  msb: 0 OUTPUT
			this->EMAC0PHYTXD = EMAC0PHYTXD; // net ID: EMAC0PHYTXD lsb: 0  msb: 0 OUTPUT
			this->EMAC0PHYTXEN = EMAC0PHYTXEN; // net ID: EMAC0PHYTXEN lsb: 0  msb: 0 OUTPUT
			this->EMAC0PHYTXER = EMAC0PHYTXER; // net ID: EMAC0PHYTXER lsb: 0  msb: 0 OUTPUT
			this->EMAC1CLIENTANINTERRUPT = EMAC1CLIENTANINTERRUPT; // net ID: EMAC1CLIENTANINTERRUPT lsb: 0  msb: 0 OUTPUT
			this->EMAC1CLIENTRXBADFRAME = EMAC1CLIENTRXBADFRAME; // net ID: EMAC1CLIENTRXBADFRAME lsb: 0  msb: 0 OUTPUT
			this->EMAC1CLIENTRXCLIENTCLKOUT = EMAC1CLIENTRXCLIENTCLKOUT; // net ID: EMAC1CLIENTRXCLIENTCLKOUT lsb: 0  msb: 0 OUTPUT
			this->EMAC1CLIENTRXD = EMAC1CLIENTRXD; // net ID: EMAC1CLIENTRXD lsb: 0  msb: 0 OUTPUT
			this->EMAC1CLIENTRXDVLD = EMAC1CLIENTRXDVLD; // net ID: EMAC1CLIENTRXDVLD lsb: 0  msb: 0 OUTPUT
			this->EMAC1CLIENTRXDVLDMSW = EMAC1CLIENTRXDVLDMSW; // net ID: EMAC1CLIENTRXDVLDMSW lsb: 0  msb: 0 OUTPUT
			this->EMAC1CLIENTRXDVREG6 = EMAC1CLIENTRXDVREG6; // net ID: EMAC1CLIENTRXDVREG6 lsb: 0  msb: 0 OUTPUT
			this->EMAC1CLIENTRXFRAMEDROP = EMAC1CLIENTRXFRAMEDROP; // net ID: EMAC1CLIENTRXFRAMEDROP lsb: 0  msb: 0 OUTPUT
			this->EMAC1CLIENTRXGOODFRAME = EMAC1CLIENTRXGOODFRAME; // net ID: EMAC1CLIENTRXGOODFRAME lsb: 0  msb: 0 OUTPUT
			this->EMAC1CLIENTRXSTATS = EMAC1CLIENTRXSTATS; // net ID: EMAC1CLIENTRXSTATS lsb: 0  msb: 0 OUTPUT
			this->EMAC1CLIENTRXSTATSBYTEVLD = EMAC1CLIENTRXSTATSBYTEVLD; // net ID: EMAC1CLIENTRXSTATSBYTEVLD lsb: 0  msb: 0 OUTPUT
			this->EMAC1CLIENTRXSTATSVLD = EMAC1CLIENTRXSTATSVLD; // net ID: EMAC1CLIENTRXSTATSVLD lsb: 0  msb: 0 OUTPUT
			this->EMAC1CLIENTTXACK = EMAC1CLIENTTXACK; // net ID: EMAC1CLIENTTXACK lsb: 0  msb: 0 OUTPUT
			this->EMAC1CLIENTTXCLIENTCLKOUT = EMAC1CLIENTTXCLIENTCLKOUT; // net ID: EMAC1CLIENTTXCLIENTCLKOUT lsb: 0  msb: 0 OUTPUT
			this->EMAC1CLIENTTXCOLLISION = EMAC1CLIENTTXCOLLISION; // net ID: EMAC1CLIENTTXCOLLISION lsb: 0  msb: 0 OUTPUT
			this->EMAC1CLIENTTXGMIIMIICLKOUT = EMAC1CLIENTTXGMIIMIICLKOUT; // net ID: EMAC1CLIENTTXGMIIMIICLKOUT lsb: 0  msb: 0 OUTPUT
			this->EMAC1CLIENTTXRETRANSMIT = EMAC1CLIENTTXRETRANSMIT; // net ID: EMAC1CLIENTTXRETRANSMIT lsb: 0  msb: 0 OUTPUT
			this->EMAC1CLIENTTXSTATS = EMAC1CLIENTTXSTATS; // net ID: EMAC1CLIENTTXSTATS lsb: 0  msb: 0 OUTPUT
			this->EMAC1CLIENTTXSTATSBYTEVLD = EMAC1CLIENTTXSTATSBYTEVLD; // net ID: EMAC1CLIENTTXSTATSBYTEVLD lsb: 0  msb: 0 OUTPUT
			this->EMAC1CLIENTTXSTATSVLD = EMAC1CLIENTTXSTATSVLD; // net ID: EMAC1CLIENTTXSTATSVLD lsb: 0  msb: 0 OUTPUT
			this->EMAC1PHYENCOMMAALIGN = EMAC1PHYENCOMMAALIGN; // net ID: EMAC1PHYENCOMMAALIGN lsb: 0  msb: 0 OUTPUT
			this->EMAC1PHYLOOPBACKMSB = EMAC1PHYLOOPBACKMSB; // net ID: EMAC1PHYLOOPBACKMSB lsb: 0  msb: 0 OUTPUT
			this->EMAC1PHYMCLKOUT = EMAC1PHYMCLKOUT; // net ID: EMAC1PHYMCLKOUT lsb: 0  msb: 0 OUTPUT
			this->EMAC1PHYMDOUT = EMAC1PHYMDOUT; // net ID: EMAC1PHYMDOUT lsb: 0  msb: 0 OUTPUT
			this->EMAC1PHYMDTRI = EMAC1PHYMDTRI; // net ID: EMAC1PHYMDTRI lsb: 0  msb: 0 OUTPUT
			this->EMAC1PHYMGTRXRESET = EMAC1PHYMGTRXRESET; // net ID: EMAC1PHYMGTRXRESET lsb: 0  msb: 0 OUTPUT
			this->EMAC1PHYMGTTXRESET = EMAC1PHYMGTTXRESET; // net ID: EMAC1PHYMGTTXRESET lsb: 0  msb: 0 OUTPUT
			this->EMAC1PHYPOWERDOWN = EMAC1PHYPOWERDOWN; // net ID: EMAC1PHYPOWERDOWN lsb: 0  msb: 0 OUTPUT
			this->EMAC1PHYSYNCACQSTATUS = EMAC1PHYSYNCACQSTATUS; // net ID: EMAC1PHYSYNCACQSTATUS lsb: 0  msb: 0 OUTPUT
			this->EMAC1PHYTXCHARDISPMODE = EMAC1PHYTXCHARDISPMODE; // net ID: EMAC1PHYTXCHARDISPMODE lsb: 0  msb: 0 OUTPUT
			this->EMAC1PHYTXCHARDISPVAL = EMAC1PHYTXCHARDISPVAL; // net ID: EMAC1PHYTXCHARDISPVAL lsb: 0  msb: 0 OUTPUT
			this->EMAC1PHYTXCHARISK = EMAC1PHYTXCHARISK; // net ID: EMAC1PHYTXCHARISK lsb: 0  msb: 0 OUTPUT
			this->EMAC1PHYTXCLK = EMAC1PHYTXCLK; // net ID: EMAC1PHYTXCLK lsb: 0  msb: 0 OUTPUT
			this->EMAC1PHYTXD = EMAC1PHYTXD; // net ID: EMAC1PHYTXD lsb: 0  msb: 0 OUTPUT
			this->EMAC1PHYTXEN = EMAC1PHYTXEN; // net ID: EMAC1PHYTXEN lsb: 0  msb: 0 OUTPUT
			this->EMAC1PHYTXER = EMAC1PHYTXER; // net ID: EMAC1PHYTXER lsb: 0  msb: 0 OUTPUT
			this->EMACDCRACK = EMACDCRACK; // net ID: EMACDCRACK lsb: 0  msb: 0 OUTPUT
			this->EMACDCRDBUS = EMACDCRDBUS; // net ID: EMACDCRDBUS lsb: 0  msb: 0 OUTPUT
			this->HOSTMIIMRDY = HOSTMIIMRDY; // net ID: HOSTMIIMRDY lsb: 0  msb: 0 OUTPUT
			this->HOSTRDDATA = HOSTRDDATA; // net ID: HOSTRDDATA lsb: 0  msb: 0 OUTPUT
			this->CLIENTEMAC0DCMLOCKED = CLIENTEMAC0DCMLOCKED; // net ID: CLIENTEMAC0DCMLOCKED lsb: 0  msb: 0 INPUT
			this->CLIENTEMAC0PAUSEREQ = CLIENTEMAC0PAUSEREQ; // net ID: CLIENTEMAC0PAUSEREQ lsb: 0  msb: 0 INPUT
			this->CLIENTEMAC0PAUSEVAL = CLIENTEMAC0PAUSEVAL; // net ID: CLIENTEMAC0PAUSEVAL lsb: 0  msb: 15 INPUT
			this->CLIENTEMAC0RXCLIENTCLKIN = CLIENTEMAC0RXCLIENTCLKIN; // net ID: CLIENTEMAC0RXCLIENTCLKIN lsb: 0  msb: 0 INPUT
			this->CLIENTEMAC0TXCLIENTCLKIN = CLIENTEMAC0TXCLIENTCLKIN; // net ID: CLIENTEMAC0TXCLIENTCLKIN lsb: 0  msb: 0 INPUT
			this->CLIENTEMAC0TXD = CLIENTEMAC0TXD; // net ID: CLIENTEMAC0TXD lsb: 0  msb: 15 INPUT
			this->CLIENTEMAC0TXDVLD = CLIENTEMAC0TXDVLD; // net ID: CLIENTEMAC0TXDVLD lsb: 0  msb: 0 INPUT
			this->CLIENTEMAC0TXDVLDMSW = CLIENTEMAC0TXDVLDMSW; // net ID: CLIENTEMAC0TXDVLDMSW lsb: 0  msb: 0 INPUT
			this->CLIENTEMAC0TXFIRSTBYTE = CLIENTEMAC0TXFIRSTBYTE; // net ID: CLIENTEMAC0TXFIRSTBYTE lsb: 0  msb: 0 INPUT
			this->CLIENTEMAC0TXGMIIMIICLKIN = CLIENTEMAC0TXGMIIMIICLKIN; // net ID: CLIENTEMAC0TXGMIIMIICLKIN lsb: 0  msb: 0 INPUT
			this->CLIENTEMAC0TXIFGDELAY = CLIENTEMAC0TXIFGDELAY; // net ID: CLIENTEMAC0TXIFGDELAY lsb: 0  msb: 7 INPUT
			this->CLIENTEMAC0TXUNDERRUN = CLIENTEMAC0TXUNDERRUN; // net ID: CLIENTEMAC0TXUNDERRUN lsb: 0  msb: 0 INPUT
			this->CLIENTEMAC1DCMLOCKED = CLIENTEMAC1DCMLOCKED; // net ID: CLIENTEMAC1DCMLOCKED lsb: 0  msb: 0 INPUT
			this->CLIENTEMAC1PAUSEREQ = CLIENTEMAC1PAUSEREQ; // net ID: CLIENTEMAC1PAUSEREQ lsb: 0  msb: 0 INPUT
			this->CLIENTEMAC1PAUSEVAL = CLIENTEMAC1PAUSEVAL; // net ID: CLIENTEMAC1PAUSEVAL lsb: 0  msb: 15 INPUT
			this->CLIENTEMAC1RXCLIENTCLKIN = CLIENTEMAC1RXCLIENTCLKIN; // net ID: CLIENTEMAC1RXCLIENTCLKIN lsb: 0  msb: 0 INPUT
			this->CLIENTEMAC1TXCLIENTCLKIN = CLIENTEMAC1TXCLIENTCLKIN; // net ID: CLIENTEMAC1TXCLIENTCLKIN lsb: 0  msb: 0 INPUT
			this->CLIENTEMAC1TXD = CLIENTEMAC1TXD; // net ID: CLIENTEMAC1TXD lsb: 0  msb: 15 INPUT
			this->CLIENTEMAC1TXDVLD = CLIENTEMAC1TXDVLD; // net ID: CLIENTEMAC1TXDVLD lsb: 0  msb: 0 INPUT
			this->CLIENTEMAC1TXDVLDMSW = CLIENTEMAC1TXDVLDMSW; // net ID: CLIENTEMAC1TXDVLDMSW lsb: 0  msb: 0 INPUT
			this->CLIENTEMAC1TXFIRSTBYTE = CLIENTEMAC1TXFIRSTBYTE; // net ID: CLIENTEMAC1TXFIRSTBYTE lsb: 0  msb: 0 INPUT
			this->CLIENTEMAC1TXGMIIMIICLKIN = CLIENTEMAC1TXGMIIMIICLKIN; // net ID: CLIENTEMAC1TXGMIIMIICLKIN lsb: 0  msb: 0 INPUT
			this->CLIENTEMAC1TXIFGDELAY = CLIENTEMAC1TXIFGDELAY; // net ID: CLIENTEMAC1TXIFGDELAY lsb: 0  msb: 7 INPUT
			this->CLIENTEMAC1TXUNDERRUN = CLIENTEMAC1TXUNDERRUN; // net ID: CLIENTEMAC1TXUNDERRUN lsb: 0  msb: 0 INPUT
			this->DCREMACABUS = DCREMACABUS; // net ID: DCREMACABUS lsb: 9  msb: 8 INPUT
			this->DCREMACCLK = DCREMACCLK; // net ID: DCREMACCLK lsb: 0  msb: 0 INPUT
			this->DCREMACDBUS = DCREMACDBUS; // net ID: DCREMACDBUS lsb: 31  msb: 0 INPUT
			this->DCREMACENABLE = DCREMACENABLE; // net ID: DCREMACENABLE lsb: 0  msb: 0 INPUT
			this->DCREMACREAD = DCREMACREAD; // net ID: DCREMACREAD lsb: 0  msb: 0 INPUT
			this->DCREMACWRITE = DCREMACWRITE; // net ID: DCREMACWRITE lsb: 0  msb: 0 INPUT
			this->HOSTADDR = HOSTADDR; // net ID: HOSTADDR lsb: 0  msb: 9 INPUT
			this->HOSTCLK = HOSTCLK; // net ID: HOSTCLK lsb: 0  msb: 0 INPUT
			this->HOSTEMAC1SEL = HOSTEMAC1SEL; // net ID: HOSTEMAC1SEL lsb: 0  msb: 0 INPUT
			this->HOSTMIIMSEL = HOSTMIIMSEL; // net ID: HOSTMIIMSEL lsb: 0  msb: 0 INPUT
			this->HOSTOPCODE = HOSTOPCODE; // net ID: HOSTOPCODE lsb: 0  msb: 1 INPUT
			this->HOSTREQ = HOSTREQ; // net ID: HOSTREQ lsb: 0  msb: 0 INPUT
			this->HOSTWRDATA = HOSTWRDATA; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			this->PHYEMAC0COL = PHYEMAC0COL; // net ID: PHYEMAC0COL lsb: 0  msb: 0 INPUT
			this->PHYEMAC0CRS = PHYEMAC0CRS; // net ID: PHYEMAC0CRS lsb: 0  msb: 0 INPUT
			this->PHYEMAC0GTXCLK = PHYEMAC0GTXCLK; // net ID: PHYEMAC0GTXCLK lsb: 0  msb: 0 INPUT
			this->PHYEMAC0MCLKIN = PHYEMAC0MCLKIN; // net ID: PHYEMAC0MCLKIN lsb: 0  msb: 0 INPUT
			this->PHYEMAC0MDIN = PHYEMAC0MDIN; // net ID: PHYEMAC0MDIN lsb: 0  msb: 0 INPUT
			this->PHYEMAC0MIITXCLK = PHYEMAC0MIITXCLK; // net ID: PHYEMAC0MIITXCLK lsb: 0  msb: 0 INPUT
			this->PHYEMAC0PHYAD = PHYEMAC0PHYAD; // net ID: PHYEMAC0PHYAD lsb: 0  msb: 4 INPUT
			this->PHYEMAC0RXBUFERR = PHYEMAC0RXBUFERR; // net ID: PHYEMAC0RXBUFERR lsb: 0  msb: 0 INPUT
			this->PHYEMAC0RXBUFSTATUS = PHYEMAC0RXBUFSTATUS; // net ID: PHYEMAC0RXBUFSTATUS lsb: 0  msb: 1 INPUT
			this->PHYEMAC0RXCHARISCOMMA = PHYEMAC0RXCHARISCOMMA; // net ID: PHYEMAC0RXCHARISCOMMA lsb: 0  msb: 0 INPUT
			this->PHYEMAC0RXCHARISK = PHYEMAC0RXCHARISK; // net ID: PHYEMAC0RXCHARISK lsb: 0  msb: 0 INPUT
			this->PHYEMAC0RXCHECKINGCRC = PHYEMAC0RXCHECKINGCRC; // net ID: PHYEMAC0RXCHECKINGCRC lsb: 0  msb: 0 INPUT
			this->PHYEMAC0RXCLK = PHYEMAC0RXCLK; // net ID: PHYEMAC0RXCLK lsb: 0  msb: 0 INPUT
			this->PHYEMAC0RXCLKCORCNT = PHYEMAC0RXCLKCORCNT; // net ID: PHYEMAC0RXCLKCORCNT lsb: 0  msb: 2 INPUT
			this->PHYEMAC0RXCOMMADET = PHYEMAC0RXCOMMADET; // net ID: PHYEMAC0RXCOMMADET lsb: 0  msb: 0 INPUT
			this->PHYEMAC0RXD = PHYEMAC0RXD; // net ID: PHYEMAC0RXD lsb: 0  msb: 7 INPUT
			this->PHYEMAC0RXDISPERR = PHYEMAC0RXDISPERR; // net ID: PHYEMAC0RXDISPERR lsb: 0  msb: 0 INPUT
			this->PHYEMAC0RXDV = PHYEMAC0RXDV; // net ID: PHYEMAC0RXDV lsb: 0  msb: 0 INPUT
			this->PHYEMAC0RXER = PHYEMAC0RXER; // net ID: PHYEMAC0RXER lsb: 0  msb: 0 INPUT
			this->PHYEMAC0RXLOSSOFSYNC = PHYEMAC0RXLOSSOFSYNC; // net ID: PHYEMAC0RXLOSSOFSYNC lsb: 0  msb: 1 INPUT
			this->PHYEMAC0RXNOTINTABLE = PHYEMAC0RXNOTINTABLE; // net ID: PHYEMAC0RXNOTINTABLE lsb: 0  msb: 0 INPUT
			this->PHYEMAC0RXRUNDISP = PHYEMAC0RXRUNDISP; // net ID: PHYEMAC0RXRUNDISP lsb: 0  msb: 0 INPUT
			this->PHYEMAC0SIGNALDET = PHYEMAC0SIGNALDET; // net ID: PHYEMAC0SIGNALDET lsb: 0  msb: 0 INPUT
			this->PHYEMAC0TXBUFERR = PHYEMAC0TXBUFERR; // net ID: PHYEMAC0TXBUFERR lsb: 0  msb: 0 INPUT
			this->PHYEMAC1COL = PHYEMAC1COL; // net ID: PHYEMAC1COL lsb: 0  msb: 0 INPUT
			this->PHYEMAC1CRS = PHYEMAC1CRS; // net ID: PHYEMAC1CRS lsb: 0  msb: 0 INPUT
			this->PHYEMAC1GTXCLK = PHYEMAC1GTXCLK; // net ID: PHYEMAC1GTXCLK lsb: 0  msb: 0 INPUT
			this->PHYEMAC1MCLKIN = PHYEMAC1MCLKIN; // net ID: PHYEMAC1MCLKIN lsb: 0  msb: 0 INPUT
			this->PHYEMAC1MDIN = PHYEMAC1MDIN; // net ID: PHYEMAC1MDIN lsb: 0  msb: 0 INPUT
			this->PHYEMAC1MIITXCLK = PHYEMAC1MIITXCLK; // net ID: PHYEMAC1MIITXCLK lsb: 0  msb: 0 INPUT
			this->PHYEMAC1PHYAD = PHYEMAC1PHYAD; // net ID: PHYEMAC1PHYAD lsb: 0  msb: 4 INPUT
			this->PHYEMAC1RXBUFERR = PHYEMAC1RXBUFERR; // net ID: PHYEMAC1RXBUFERR lsb: 0  msb: 0 INPUT
			this->PHYEMAC1RXBUFSTATUS = PHYEMAC1RXBUFSTATUS; // net ID: PHYEMAC1RXBUFSTATUS lsb: 0  msb: 1 INPUT
			this->PHYEMAC1RXCHARISCOMMA = PHYEMAC1RXCHARISCOMMA; // net ID: PHYEMAC1RXCHARISCOMMA lsb: 0  msb: 0 INPUT
			this->PHYEMAC1RXCHARISK = PHYEMAC1RXCHARISK; // net ID: PHYEMAC1RXCHARISK lsb: 0  msb: 0 INPUT
			this->PHYEMAC1RXCHECKINGCRC = PHYEMAC1RXCHECKINGCRC; // net ID: PHYEMAC1RXCHECKINGCRC lsb: 0  msb: 0 INPUT
			this->PHYEMAC1RXCLK = PHYEMAC1RXCLK; // net ID: PHYEMAC1RXCLK lsb: 0  msb: 0 INPUT
			this->PHYEMAC1RXCLKCORCNT = PHYEMAC1RXCLKCORCNT; // net ID: PHYEMAC1RXCLKCORCNT lsb: 0  msb: 2 INPUT
			this->PHYEMAC1RXCOMMADET = PHYEMAC1RXCOMMADET; // net ID: PHYEMAC1RXCOMMADET lsb: 0  msb: 0 INPUT
			this->PHYEMAC1RXD = PHYEMAC1RXD; // net ID: PHYEMAC1RXD lsb: 0  msb: 7 INPUT
			this->PHYEMAC1RXDISPERR = PHYEMAC1RXDISPERR; // net ID: PHYEMAC1RXDISPERR lsb: 0  msb: 0 INPUT
			this->PHYEMAC1RXDV = PHYEMAC1RXDV; // net ID: PHYEMAC1RXDV lsb: 0  msb: 0 INPUT
			this->PHYEMAC1RXER = PHYEMAC1RXER; // net ID: PHYEMAC1RXER lsb: 0  msb: 0 INPUT
			this->PHYEMAC1RXLOSSOFSYNC = PHYEMAC1RXLOSSOFSYNC; // net ID: PHYEMAC1RXLOSSOFSYNC lsb: 0  msb: 1 INPUT
			this->PHYEMAC1RXNOTINTABLE = PHYEMAC1RXNOTINTABLE; // net ID: PHYEMAC1RXNOTINTABLE lsb: 0  msb: 0 INPUT
			this->PHYEMAC1RXRUNDISP = PHYEMAC1RXRUNDISP; // net ID: PHYEMAC1RXRUNDISP lsb: 0  msb: 0 INPUT
			this->PHYEMAC1SIGNALDET = PHYEMAC1SIGNALDET; // net ID: PHYEMAC1SIGNALDET lsb: 0  msb: 0 INPUT
			this->PHYEMAC1TXBUFERR = PHYEMAC1TXBUFERR; // net ID: PHYEMAC1TXBUFERR lsb: 0  msb: 0 INPUT
			this->RESET = RESET; // net ID: RESET lsb: 0  msb: 0 INPUT
			this->TIEEMAC0CONFIGVEC = TIEEMAC0CONFIGVEC; // net ID: TIEEMAC0CONFIGVEC lsb: 0  msb: 79 INPUT
			this->TIEEMAC0UNICASTADDR = TIEEMAC0UNICASTADDR; // net ID: TIEEMAC0UNICASTADDR lsb: 0  msb: 47 INPUT
			this->TIEEMAC1CONFIGVEC = TIEEMAC1CONFIGVEC; // net ID: TIEEMAC1CONFIGVEC lsb: 0  msb: 79 INPUT
			this->TIEEMAC1UNICASTADDR = TIEEMAC1UNICASTADDR; // net ID: TIEEMAC1UNICASTADDR lsb: 0  msb: 47 INPUT
			
			register_wait_on_event_nets();
			
		}
		
		void register_wait_on_event_nets(){
		// TODO
		}
		void calculate(int time){
		// TODO
		}
		};
		


}
