/******************************************************************************
 * Generated Cpp template for simulation primitives.
 * Author: Benedek Racz
 ******************************************************************************/

#include "NetFlow.h"
#include "sim_types.h"

namespace CPrimitives {

	class X_PPC440{

		//Verilog Parameters:
		parameter_string_t LOC;
		parameter_enum_t CLOCK_DELAY;
		parameter_enum_t DCR_AUTOLOCK_ENABLE;
		parameter_enum_t PPCDM_ASYNCMODE;
		parameter_enum_t PPCDS_ASYNCMODE;
		parameter_enum_t PPCS0_WIDTH_128N64;
		parameter_enum_t PPCS1_WIDTH_128N64;
		parameter_int_t APU_CONTROL;
		parameter_int_t APU_UDI0;
		parameter_int_t APU_UDI1;
		parameter_int_t APU_UDI10;
		parameter_int_t APU_UDI11;
		parameter_int_t APU_UDI12;
		parameter_int_t APU_UDI13;
		parameter_int_t APU_UDI14;
		parameter_int_t APU_UDI15;
		parameter_int_t APU_UDI2;
		parameter_int_t APU_UDI3;
		parameter_int_t APU_UDI4;
		parameter_int_t APU_UDI5;
		parameter_int_t APU_UDI6;
		parameter_int_t APU_UDI7;
		parameter_int_t APU_UDI8;
		parameter_int_t APU_UDI9;
		parameter_int_t DMA0_RXCHANNELCTRL;
		parameter_int_t DMA0_TXCHANNELCTRL;
		parameter_int_t DMA1_RXCHANNELCTRL;
		parameter_int_t DMA1_TXCHANNELCTRL;
		parameter_int_t DMA2_RXCHANNELCTRL;
		parameter_int_t DMA2_TXCHANNELCTRL;
		parameter_int_t DMA3_RXCHANNELCTRL;
		parameter_int_t DMA3_TXCHANNELCTRL;
		parameter_int_t INTERCONNECT_IMASK;
		parameter_int_t INTERCONNECT_TMPL_SEL;
		parameter_int_t MI_ARBCONFIG;
		parameter_int_t MI_BANKCONFLICT_MASK;
		parameter_int_t MI_CONTROL;
		parameter_int_t MI_ROWCONFLICT_MASK;
		parameter_int_t PPCM_ARBCONFIG;
		parameter_int_t PPCM_CONTROL;
		parameter_int_t PPCM_COUNTER;
		parameter_int_t PPCS0_ADDRMAP_TMPL0;
		parameter_int_t PPCS0_ADDRMAP_TMPL1;
		parameter_int_t PPCS0_ADDRMAP_TMPL2;
		parameter_int_t PPCS0_ADDRMAP_TMPL3;
		parameter_int_t PPCS0_CONTROL;
		parameter_int_t PPCS1_ADDRMAP_TMPL0;
		parameter_int_t PPCS1_ADDRMAP_TMPL1;
		parameter_int_t PPCS1_ADDRMAP_TMPL2;
		parameter_int_t PPCS1_ADDRMAP_TMPL3;
		parameter_int_t PPCS1_CONTROL;
		parameter_int_t XBAR_ADDRMAP_TMPL0;
		parameter_int_t XBAR_ADDRMAP_TMPL1;
		parameter_int_t XBAR_ADDRMAP_TMPL2;
		parameter_int_t XBAR_ADDRMAP_TMPL3;
		parameter_int_t DMA0_CONTROL;
		parameter_int_t DMA1_CONTROL;
		parameter_int_t DMA2_CONTROL;
		parameter_int_t DMA3_CONTROL;
		parameter_int_t DMA0_RXIRQTIMER;
		parameter_int_t DMA0_TXIRQTIMER;
		parameter_int_t DMA1_RXIRQTIMER;
		parameter_int_t DMA1_TXIRQTIMER;
		parameter_int_t DMA2_RXIRQTIMER;
		parameter_int_t DMA2_TXIRQTIMER;
		parameter_int_t DMA3_RXIRQTIMER;
		parameter_int_t DMA3_TXIRQTIMER;
		//Verilog Ports in definition order:
		NetFlow* APUFCMDECFPUOP; // OUTPUT
		NetFlow* APUFCMDECLDSTXFERSIZE; // OUTPUT
		NetFlow* APUFCMDECLOAD; // OUTPUT
		NetFlow* APUFCMDECNONAUTON; // OUTPUT
		NetFlow* APUFCMDECSTORE; // OUTPUT
		NetFlow* APUFCMDECUDI; // OUTPUT
		NetFlow* APUFCMDECUDIVALID; // OUTPUT
		NetFlow* APUFCMENDIAN; // OUTPUT
		NetFlow* APUFCMFLUSH; // OUTPUT
		NetFlow* APUFCMINSTRUCTION; // OUTPUT
		NetFlow* APUFCMINSTRVALID; // OUTPUT
		NetFlow* APUFCMLOADBYTEADDR; // OUTPUT
		NetFlow* APUFCMLOADDATA; // OUTPUT
		NetFlow* APUFCMLOADDVALID; // OUTPUT
		NetFlow* APUFCMMSRFE0; // OUTPUT
		NetFlow* APUFCMMSRFE1; // OUTPUT
		NetFlow* APUFCMNEXTINSTRREADY; // OUTPUT
		NetFlow* APUFCMOPERANDVALID; // OUTPUT
		NetFlow* APUFCMRADATA; // OUTPUT
		NetFlow* APUFCMRBDATA; // OUTPUT
		NetFlow* APUFCMWRITEBACKOK; // OUTPUT
		NetFlow* C440CPMCORESLEEPREQ; // OUTPUT
		NetFlow* C440CPMDECIRPTREQ; // OUTPUT
		NetFlow* C440CPMFITIRPTREQ; // OUTPUT
		NetFlow* C440CPMMSRCE; // OUTPUT
		NetFlow* C440CPMMSREE; // OUTPUT
		NetFlow* C440CPMTIMERRESETREQ; // OUTPUT
		NetFlow* C440CPMWDIRPTREQ; // OUTPUT
		NetFlow* C440DBGSYSTEMCONTROL; // OUTPUT
		NetFlow* C440JTGTDO; // OUTPUT
		NetFlow* C440JTGTDOEN; // OUTPUT
		NetFlow* C440MACHINECHECK; // OUTPUT
		NetFlow* C440RSTCHIPRESETREQ; // OUTPUT
		NetFlow* C440RSTCORERESETREQ; // OUTPUT
		NetFlow* C440RSTSYSTEMRESETREQ; // OUTPUT
		NetFlow* C440TRCBRANCHSTATUS; // OUTPUT
		NetFlow* C440TRCCYCLE; // OUTPUT
		NetFlow* C440TRCEXECUTIONSTATUS; // OUTPUT
		NetFlow* C440TRCTRACESTATUS; // OUTPUT
		NetFlow* C440TRCTRIGGEREVENTOUT; // OUTPUT
		NetFlow* C440TRCTRIGGEREVENTTYPE; // OUTPUT
		NetFlow* DMA0LLRSTENGINEACK; // OUTPUT
		NetFlow* DMA0LLRXDSTRDYN; // OUTPUT
		NetFlow* DMA0LLTXD; // OUTPUT
		NetFlow* DMA0LLTXEOFN; // OUTPUT
		NetFlow* DMA0LLTXEOPN; // OUTPUT
		NetFlow* DMA0LLTXREM; // OUTPUT
		NetFlow* DMA0LLTXSOFN; // OUTPUT
		NetFlow* DMA0LLTXSOPN; // OUTPUT
		NetFlow* DMA0LLTXSRCRDYN; // OUTPUT
		NetFlow* DMA0RXIRQ; // OUTPUT
		NetFlow* DMA0TXIRQ; // OUTPUT
		NetFlow* DMA1LLRSTENGINEACK; // OUTPUT
		NetFlow* DMA1LLRXDSTRDYN; // OUTPUT
		NetFlow* DMA1LLTXD; // OUTPUT
		NetFlow* DMA1LLTXEOFN; // OUTPUT
		NetFlow* DMA1LLTXEOPN; // OUTPUT
		NetFlow* DMA1LLTXREM; // OUTPUT
		NetFlow* DMA1LLTXSOFN; // OUTPUT
		NetFlow* DMA1LLTXSOPN; // OUTPUT
		NetFlow* DMA1LLTXSRCRDYN; // OUTPUT
		NetFlow* DMA1RXIRQ; // OUTPUT
		NetFlow* DMA1TXIRQ; // OUTPUT
		NetFlow* DMA2LLRSTENGINEACK; // OUTPUT
		NetFlow* DMA2LLRXDSTRDYN; // OUTPUT
		NetFlow* DMA2LLTXD; // OUTPUT
		NetFlow* DMA2LLTXEOFN; // OUTPUT
		NetFlow* DMA2LLTXEOPN; // OUTPUT
		NetFlow* DMA2LLTXREM; // OUTPUT
		NetFlow* DMA2LLTXSOFN; // OUTPUT
		NetFlow* DMA2LLTXSOPN; // OUTPUT
		NetFlow* DMA2LLTXSRCRDYN; // OUTPUT
		NetFlow* DMA2RXIRQ; // OUTPUT
		NetFlow* DMA2TXIRQ; // OUTPUT
		NetFlow* DMA3LLRSTENGINEACK; // OUTPUT
		NetFlow* DMA3LLRXDSTRDYN; // OUTPUT
		NetFlow* DMA3LLTXD; // OUTPUT
		NetFlow* DMA3LLTXEOFN; // OUTPUT
		NetFlow* DMA3LLTXEOPN; // OUTPUT
		NetFlow* DMA3LLTXREM; // OUTPUT
		NetFlow* DMA3LLTXSOFN; // OUTPUT
		NetFlow* DMA3LLTXSOPN; // OUTPUT
		NetFlow* DMA3LLTXSRCRDYN; // OUTPUT
		NetFlow* DMA3RXIRQ; // OUTPUT
		NetFlow* DMA3TXIRQ; // OUTPUT
		NetFlow* MIMCADDRESS; // OUTPUT
		NetFlow* MIMCADDRESSVALID; // OUTPUT
		NetFlow* MIMCBANKCONFLICT; // OUTPUT
		NetFlow* MIMCBYTEENABLE; // OUTPUT
		NetFlow* MIMCREADNOTWRITE; // OUTPUT
		NetFlow* MIMCROWCONFLICT; // OUTPUT
		NetFlow* MIMCWRITEDATA; // OUTPUT
		NetFlow* MIMCWRITEDATAVALID; // OUTPUT
		NetFlow* PPCCPMINTERCONNECTBUSY; // OUTPUT
		NetFlow* PPCDMDCRABUS; // OUTPUT
		NetFlow* PPCDMDCRDBUSOUT; // OUTPUT
		NetFlow* PPCDMDCRREAD; // OUTPUT
		NetFlow* PPCDMDCRUABUS; // OUTPUT
		NetFlow* PPCDMDCRWRITE; // OUTPUT
		NetFlow* PPCDSDCRACK; // OUTPUT
		NetFlow* PPCDSDCRDBUSIN; // OUTPUT
		NetFlow* PPCDSDCRTIMEOUTWAIT; // OUTPUT
		NetFlow* PPCEICINTERCONNECTIRQ; // OUTPUT
		NetFlow* PPCMPLBABORT; // OUTPUT
		NetFlow* PPCMPLBABUS; // OUTPUT
		NetFlow* PPCMPLBBE; // OUTPUT
		NetFlow* PPCMPLBBUSLOCK; // OUTPUT
		NetFlow* PPCMPLBLOCKERR; // OUTPUT
		NetFlow* PPCMPLBPRIORITY; // OUTPUT
		NetFlow* PPCMPLBRDBURST; // OUTPUT
		NetFlow* PPCMPLBREQUEST; // OUTPUT
		NetFlow* PPCMPLBRNW; // OUTPUT
		NetFlow* PPCMPLBSIZE; // OUTPUT
		NetFlow* PPCMPLBTATTRIBUTE; // OUTPUT
		NetFlow* PPCMPLBTYPE; // OUTPUT
		NetFlow* PPCMPLBUABUS; // OUTPUT
		NetFlow* PPCMPLBWRBURST; // OUTPUT
		NetFlow* PPCMPLBWRDBUS; // OUTPUT
		NetFlow* PPCS0PLBADDRACK; // OUTPUT
		NetFlow* PPCS0PLBMBUSY; // OUTPUT
		NetFlow* PPCS0PLBMIRQ; // OUTPUT
		NetFlow* PPCS0PLBMRDERR; // OUTPUT
		NetFlow* PPCS0PLBMWRERR; // OUTPUT
		NetFlow* PPCS0PLBRDBTERM; // OUTPUT
		NetFlow* PPCS0PLBRDCOMP; // OUTPUT
		NetFlow* PPCS0PLBRDDACK; // OUTPUT
		NetFlow* PPCS0PLBRDDBUS; // OUTPUT
		NetFlow* PPCS0PLBRDWDADDR; // OUTPUT
		NetFlow* PPCS0PLBREARBITRATE; // OUTPUT
		NetFlow* PPCS0PLBSSIZE; // OUTPUT
		NetFlow* PPCS0PLBWAIT; // OUTPUT
		NetFlow* PPCS0PLBWRBTERM; // OUTPUT
		NetFlow* PPCS0PLBWRCOMP; // OUTPUT
		NetFlow* PPCS0PLBWRDACK; // OUTPUT
		NetFlow* PPCS1PLBADDRACK; // OUTPUT
		NetFlow* PPCS1PLBMBUSY; // OUTPUT
		NetFlow* PPCS1PLBMIRQ; // OUTPUT
		NetFlow* PPCS1PLBMRDERR; // OUTPUT
		NetFlow* PPCS1PLBMWRERR; // OUTPUT
		NetFlow* PPCS1PLBRDBTERM; // OUTPUT
		NetFlow* PPCS1PLBRDCOMP; // OUTPUT
		NetFlow* PPCS1PLBRDDACK; // OUTPUT
		NetFlow* PPCS1PLBRDDBUS; // OUTPUT
		NetFlow* PPCS1PLBRDWDADDR; // OUTPUT
		NetFlow* PPCS1PLBREARBITRATE; // OUTPUT
		NetFlow* PPCS1PLBSSIZE; // OUTPUT
		NetFlow* PPCS1PLBWAIT; // OUTPUT
		NetFlow* PPCS1PLBWRBTERM; // OUTPUT
		NetFlow* PPCS1PLBWRCOMP; // OUTPUT
		NetFlow* PPCS1PLBWRDACK; // OUTPUT
		NetFlow* CPMC440CLK; // INPUT
		NetFlow* CPMC440CLKEN; // INPUT
		NetFlow* CPMC440CORECLOCKINACTIVE; // INPUT
		NetFlow* CPMC440TIMERCLOCK; // INPUT
		NetFlow* CPMDCRCLK; // INPUT
		NetFlow* CPMDMA0LLCLK; // INPUT
		NetFlow* CPMDMA1LLCLK; // INPUT
		NetFlow* CPMDMA2LLCLK; // INPUT
		NetFlow* CPMDMA3LLCLK; // INPUT
		NetFlow* CPMFCMCLK; // INPUT
		NetFlow* CPMINTERCONNECTCLK; // INPUT
		NetFlow* CPMINTERCONNECTCLKEN; // INPUT
		NetFlow* CPMINTERCONNECTCLKNTO1; // INPUT
		NetFlow* CPMMCCLK; // INPUT
		NetFlow* CPMPPCMPLBCLK; // INPUT
		NetFlow* CPMPPCS0PLBCLK; // INPUT
		NetFlow* CPMPPCS1PLBCLK; // INPUT
		NetFlow* DBGC440DEBUGHALT; // INPUT
		NetFlow* DBGC440SYSTEMSTATUS; // INPUT
		NetFlow* DBGC440UNCONDDEBUGEVENT; // INPUT
		NetFlow* DCRPPCDMACK; // INPUT
		NetFlow* DCRPPCDMDBUSIN; // INPUT
		NetFlow* DCRPPCDMTIMEOUTWAIT; // INPUT
		NetFlow* DCRPPCDSABUS; // INPUT
		NetFlow* DCRPPCDSDBUSOUT; // INPUT
		NetFlow* DCRPPCDSREAD; // INPUT
		NetFlow* DCRPPCDSWRITE; // INPUT
		NetFlow* EICC440CRITIRQ; // INPUT
		NetFlow* EICC440EXTIRQ; // INPUT
		NetFlow* FCMAPUCONFIRMINSTR; // INPUT
		NetFlow* FCMAPUCR; // INPUT
		NetFlow* FCMAPUDONE; // INPUT
		NetFlow* FCMAPUEXCEPTION; // INPUT
		NetFlow* FCMAPUFPSCRFEX; // INPUT
		NetFlow* FCMAPURESULT; // INPUT
		NetFlow* FCMAPURESULTVALID; // INPUT
		NetFlow* FCMAPUSLEEPNOTREADY; // INPUT
		NetFlow* FCMAPUSTOREDATA; // INPUT
		NetFlow* JTGC440TCK; // INPUT
		NetFlow* JTGC440TDI; // INPUT
		NetFlow* JTGC440TMS; // INPUT
		NetFlow* JTGC440TRSTNEG; // INPUT
		NetFlow* LLDMA0RSTENGINEREQ; // INPUT
		NetFlow* LLDMA0RXD; // INPUT
		NetFlow* LLDMA0RXEOFN; // INPUT
		NetFlow* LLDMA0RXEOPN; // INPUT
		NetFlow* LLDMA0RXREM; // INPUT
		NetFlow* LLDMA0RXSOFN; // INPUT
		NetFlow* LLDMA0RXSOPN; // INPUT
		NetFlow* LLDMA0RXSRCRDYN; // INPUT
		NetFlow* LLDMA0TXDSTRDYN; // INPUT
		NetFlow* LLDMA1RSTENGINEREQ; // INPUT
		NetFlow* LLDMA1RXD; // INPUT
		NetFlow* LLDMA1RXEOFN; // INPUT
		NetFlow* LLDMA1RXEOPN; // INPUT
		NetFlow* LLDMA1RXREM; // INPUT
		NetFlow* LLDMA1RXSOFN; // INPUT
		NetFlow* LLDMA1RXSOPN; // INPUT
		NetFlow* LLDMA1RXSRCRDYN; // INPUT
		NetFlow* LLDMA1TXDSTRDYN; // INPUT
		NetFlow* LLDMA2RSTENGINEREQ; // INPUT
		NetFlow* LLDMA2RXD; // INPUT
		NetFlow* LLDMA2RXEOFN; // INPUT
		NetFlow* LLDMA2RXEOPN; // INPUT
		NetFlow* LLDMA2RXREM; // INPUT
		NetFlow* LLDMA2RXSOFN; // INPUT
		NetFlow* LLDMA2RXSOPN; // INPUT
		NetFlow* LLDMA2RXSRCRDYN; // INPUT
		NetFlow* LLDMA2TXDSTRDYN; // INPUT
		NetFlow* LLDMA3RSTENGINEREQ; // INPUT
		NetFlow* LLDMA3RXD; // INPUT
		NetFlow* LLDMA3RXEOFN; // INPUT
		NetFlow* LLDMA3RXEOPN; // INPUT
		NetFlow* LLDMA3RXREM; // INPUT
		NetFlow* LLDMA3RXSOFN; // INPUT
		NetFlow* LLDMA3RXSOPN; // INPUT
		NetFlow* LLDMA3RXSRCRDYN; // INPUT
		NetFlow* LLDMA3TXDSTRDYN; // INPUT
		NetFlow* MCMIADDRREADYTOACCEPT; // INPUT
		NetFlow* MCMIREADDATA; // INPUT
		NetFlow* MCMIREADDATAERR; // INPUT
		NetFlow* MCMIREADDATAVALID; // INPUT
		NetFlow* PLBPPCMADDRACK; // INPUT
		NetFlow* PLBPPCMMBUSY; // INPUT
		NetFlow* PLBPPCMMIRQ; // INPUT
		NetFlow* PLBPPCMMRDERR; // INPUT
		NetFlow* PLBPPCMMWRERR; // INPUT
		NetFlow* PLBPPCMRDBTERM; // INPUT
		NetFlow* PLBPPCMRDDACK; // INPUT
		NetFlow* PLBPPCMRDDBUS; // INPUT
		NetFlow* PLBPPCMRDPENDPRI; // INPUT
		NetFlow* PLBPPCMRDPENDREQ; // INPUT
		NetFlow* PLBPPCMRDWDADDR; // INPUT
		NetFlow* PLBPPCMREARBITRATE; // INPUT
		NetFlow* PLBPPCMREQPRI; // INPUT
		NetFlow* PLBPPCMSSIZE; // INPUT
		NetFlow* PLBPPCMTIMEOUT; // INPUT
		NetFlow* PLBPPCMWRBTERM; // INPUT
		NetFlow* PLBPPCMWRDACK; // INPUT
		NetFlow* PLBPPCMWRPENDPRI; // INPUT
		NetFlow* PLBPPCMWRPENDREQ; // INPUT
		NetFlow* PLBPPCS0ABORT; // INPUT
		NetFlow* PLBPPCS0ABUS; // INPUT
		NetFlow* PLBPPCS0BE; // INPUT
		NetFlow* PLBPPCS0BUSLOCK; // INPUT
		NetFlow* PLBPPCS0LOCKERR; // INPUT
		NetFlow* PLBPPCS0MASTERID; // INPUT
		NetFlow* PLBPPCS0MSIZE; // INPUT
		NetFlow* PLBPPCS0PAVALID; // INPUT
		NetFlow* PLBPPCS0RDBURST; // INPUT
		NetFlow* PLBPPCS0RDPENDPRI; // INPUT
		NetFlow* PLBPPCS0RDPENDREQ; // INPUT
		NetFlow* PLBPPCS0RDPRIM; // INPUT
		NetFlow* PLBPPCS0REQPRI; // INPUT
		NetFlow* PLBPPCS0RNW; // INPUT
		NetFlow* PLBPPCS0SAVALID; // INPUT
		NetFlow* PLBPPCS0SIZE; // INPUT
		NetFlow* PLBPPCS0TATTRIBUTE; // INPUT
		NetFlow* PLBPPCS0TYPE; // INPUT
		NetFlow* PLBPPCS0UABUS; // INPUT
		NetFlow* PLBPPCS0WRBURST; // INPUT
		NetFlow* PLBPPCS0WRDBUS; // INPUT
		NetFlow* PLBPPCS0WRPENDPRI; // INPUT
		NetFlow* PLBPPCS0WRPENDREQ; // INPUT
		NetFlow* PLBPPCS0WRPRIM; // INPUT
		NetFlow* PLBPPCS1ABORT; // INPUT
		NetFlow* PLBPPCS1ABUS; // INPUT
		NetFlow* PLBPPCS1BE; // INPUT
		NetFlow* PLBPPCS1BUSLOCK; // INPUT
		NetFlow* PLBPPCS1LOCKERR; // INPUT
		NetFlow* PLBPPCS1MASTERID; // INPUT
		NetFlow* PLBPPCS1MSIZE; // INPUT
		NetFlow* PLBPPCS1PAVALID; // INPUT
		NetFlow* PLBPPCS1RDBURST; // INPUT
		NetFlow* PLBPPCS1RDPENDPRI; // INPUT
		NetFlow* PLBPPCS1RDPENDREQ; // INPUT
		NetFlow* PLBPPCS1RDPRIM; // INPUT
		NetFlow* PLBPPCS1REQPRI; // INPUT
		NetFlow* PLBPPCS1RNW; // INPUT
		NetFlow* PLBPPCS1SAVALID; // INPUT
		NetFlow* PLBPPCS1SIZE; // INPUT
		NetFlow* PLBPPCS1TATTRIBUTE; // INPUT
		NetFlow* PLBPPCS1TYPE; // INPUT
		NetFlow* PLBPPCS1UABUS; // INPUT
		NetFlow* PLBPPCS1WRBURST; // INPUT
		NetFlow* PLBPPCS1WRDBUS; // INPUT
		NetFlow* PLBPPCS1WRPENDPRI; // INPUT
		NetFlow* PLBPPCS1WRPENDREQ; // INPUT
		NetFlow* PLBPPCS1WRPRIM; // INPUT
		NetFlow* RSTC440RESETCHIP; // INPUT
		NetFlow* RSTC440RESETCORE; // INPUT
		NetFlow* RSTC440RESETSYSTEM; // INPUT
		NetFlow* TIEC440DCURDLDCACHEPLBPRIO; // INPUT
		NetFlow* TIEC440DCURDNONCACHEPLBPRIO; // INPUT
		NetFlow* TIEC440DCURDTOUCHPLBPRIO; // INPUT
		NetFlow* TIEC440DCURDURGENTPLBPRIO; // INPUT
		NetFlow* TIEC440DCUWRFLUSHPLBPRIO; // INPUT
		NetFlow* TIEC440DCUWRSTOREPLBPRIO; // INPUT
		NetFlow* TIEC440DCUWRURGENTPLBPRIO; // INPUT
		NetFlow* TIEC440ENDIANRESET; // INPUT
		NetFlow* TIEC440ERPNRESET; // INPUT
		NetFlow* TIEC440ICURDFETCHPLBPRIO; // INPUT
		NetFlow* TIEC440ICURDSPECPLBPRIO; // INPUT
		NetFlow* TIEC440ICURDTOUCHPLBPRIO; // INPUT
		NetFlow* TIEC440PIR; // INPUT
		NetFlow* TIEC440PVR; // INPUT
		NetFlow* TIEC440USERRESET; // INPUT
		NetFlow* TIEDCRBASEADDR; // INPUT
		NetFlow* TRCC440TRACEDISABLE; // INPUT
		NetFlow* TRCC440TRIGGEREVENTIN; // INPUT
		
	
		X_PPC440(
			//Verilog Parameters:
			parameter_string_t LOC, // Default: "UNPLACED"
			parameter_enum_t CLOCK_DELAY, // Default: "FALSE"
			parameter_enum_t DCR_AUTOLOCK_ENABLE, // Default: "TRUE"
			parameter_enum_t PPCDM_ASYNCMODE, // Default: "FALSE"
			parameter_enum_t PPCDS_ASYNCMODE, // Default: "FALSE"
			parameter_enum_t PPCS0_WIDTH_128N64, // Default: "TRUE"
			parameter_enum_t PPCS1_WIDTH_128N64, // Default: "TRUE"
			parameter_int_t APU_CONTROL, // Default: 17'h02000
			parameter_int_t APU_UDI0, // Default: 24'h000000
			parameter_int_t APU_UDI1, // Default: 24'h000000
			parameter_int_t APU_UDI10, // Default: 24'h000000
			parameter_int_t APU_UDI11, // Default: 24'h000000
			parameter_int_t APU_UDI12, // Default: 24'h000000
			parameter_int_t APU_UDI13, // Default: 24'h000000
			parameter_int_t APU_UDI14, // Default: 24'h000000
			parameter_int_t APU_UDI15, // Default: 24'h000000
			parameter_int_t APU_UDI2, // Default: 24'h000000
			parameter_int_t APU_UDI3, // Default: 24'h000000
			parameter_int_t APU_UDI4, // Default: 24'h000000
			parameter_int_t APU_UDI5, // Default: 24'h000000
			parameter_int_t APU_UDI6, // Default: 24'h000000
			parameter_int_t APU_UDI7, // Default: 24'h000000
			parameter_int_t APU_UDI8, // Default: 24'h000000
			parameter_int_t APU_UDI9, // Default: 24'h000000
			parameter_int_t DMA0_RXCHANNELCTRL, // Default: 32'h01010000
			parameter_int_t DMA0_TXCHANNELCTRL, // Default: 32'h01010000
			parameter_int_t DMA1_RXCHANNELCTRL, // Default: 32'h01010000
			parameter_int_t DMA1_TXCHANNELCTRL, // Default: 32'h01010000
			parameter_int_t DMA2_RXCHANNELCTRL, // Default: 32'h01010000
			parameter_int_t DMA2_TXCHANNELCTRL, // Default: 32'h01010000
			parameter_int_t DMA3_RXCHANNELCTRL, // Default: 32'h01010000
			parameter_int_t DMA3_TXCHANNELCTRL, // Default: 32'h01010000
			parameter_int_t INTERCONNECT_IMASK, // Default: 32'hFFFFFFFF
			parameter_int_t INTERCONNECT_TMPL_SEL, // Default: 32'h3FFFFFFF
			parameter_int_t MI_ARBCONFIG, // Default: 32'h00432010
			parameter_int_t MI_BANKCONFLICT_MASK, // Default: 32'h00000000
			parameter_int_t MI_CONTROL, // Default: 32'h0000008F
			parameter_int_t MI_ROWCONFLICT_MASK, // Default: 32'h00000000
			parameter_int_t PPCM_ARBCONFIG, // Default: 32'h00432010
			parameter_int_t PPCM_CONTROL, // Default: 32'h8000009F
			parameter_int_t PPCM_COUNTER, // Default: 32'h00000500
			parameter_int_t PPCS0_ADDRMAP_TMPL0, // Default: 32'hFFFFFFFF
			parameter_int_t PPCS0_ADDRMAP_TMPL1, // Default: 32'hFFFFFFFF
			parameter_int_t PPCS0_ADDRMAP_TMPL2, // Default: 32'hFFFFFFFF
			parameter_int_t PPCS0_ADDRMAP_TMPL3, // Default: 32'hFFFFFFFF
			parameter_int_t PPCS0_CONTROL, // Default: 32'h8033336C
			parameter_int_t PPCS1_ADDRMAP_TMPL0, // Default: 32'hFFFFFFFF
			parameter_int_t PPCS1_ADDRMAP_TMPL1, // Default: 32'hFFFFFFFF
			parameter_int_t PPCS1_ADDRMAP_TMPL2, // Default: 32'hFFFFFFFF
			parameter_int_t PPCS1_ADDRMAP_TMPL3, // Default: 32'hFFFFFFFF
			parameter_int_t PPCS1_CONTROL, // Default: 32'h8033336C
			parameter_int_t XBAR_ADDRMAP_TMPL0, // Default: 32'hFFFF0000
			parameter_int_t XBAR_ADDRMAP_TMPL1, // Default: 32'h00000000
			parameter_int_t XBAR_ADDRMAP_TMPL2, // Default: 32'h00000000
			parameter_int_t XBAR_ADDRMAP_TMPL3, // Default: 32'h00000000
			parameter_int_t DMA0_CONTROL, // Default: 8'h00
			parameter_int_t DMA1_CONTROL, // Default: 8'h00
			parameter_int_t DMA2_CONTROL, // Default: 8'h00
			parameter_int_t DMA3_CONTROL, // Default: 8'h00
			parameter_int_t DMA0_RXIRQTIMER, // Default: 10'h3FF
			parameter_int_t DMA0_TXIRQTIMER, // Default: 10'h3FF
			parameter_int_t DMA1_RXIRQTIMER, // Default: 10'h3FF
			parameter_int_t DMA1_TXIRQTIMER, // Default: 10'h3FF
			parameter_int_t DMA2_RXIRQTIMER, // Default: 10'h3FF
			parameter_int_t DMA2_TXIRQTIMER, // Default: 10'h3FF
			parameter_int_t DMA3_RXIRQTIMER, // Default: 10'h3FF
			parameter_int_t DMA3_TXIRQTIMER, // Default: 10'h3FF
			//Verilog Ports in definition order:
			NetFlow* APUFCMDECFPUOP, // OUTPUT
			NetFlow* APUFCMDECLDSTXFERSIZE, // OUTPUT
			NetFlow* APUFCMDECLOAD, // OUTPUT
			NetFlow* APUFCMDECNONAUTON, // OUTPUT
			NetFlow* APUFCMDECSTORE, // OUTPUT
			NetFlow* APUFCMDECUDI, // OUTPUT
			NetFlow* APUFCMDECUDIVALID, // OUTPUT
			NetFlow* APUFCMENDIAN, // OUTPUT
			NetFlow* APUFCMFLUSH, // OUTPUT
			NetFlow* APUFCMINSTRUCTION, // OUTPUT
			NetFlow* APUFCMINSTRVALID, // OUTPUT
			NetFlow* APUFCMLOADBYTEADDR, // OUTPUT
			NetFlow* APUFCMLOADDATA, // OUTPUT
			NetFlow* APUFCMLOADDVALID, // OUTPUT
			NetFlow* APUFCMMSRFE0, // OUTPUT
			NetFlow* APUFCMMSRFE1, // OUTPUT
			NetFlow* APUFCMNEXTINSTRREADY, // OUTPUT
			NetFlow* APUFCMOPERANDVALID, // OUTPUT
			NetFlow* APUFCMRADATA, // OUTPUT
			NetFlow* APUFCMRBDATA, // OUTPUT
			NetFlow* APUFCMWRITEBACKOK, // OUTPUT
			NetFlow* C440CPMCORESLEEPREQ, // OUTPUT
			NetFlow* C440CPMDECIRPTREQ, // OUTPUT
			NetFlow* C440CPMFITIRPTREQ, // OUTPUT
			NetFlow* C440CPMMSRCE, // OUTPUT
			NetFlow* C440CPMMSREE, // OUTPUT
			NetFlow* C440CPMTIMERRESETREQ, // OUTPUT
			NetFlow* C440CPMWDIRPTREQ, // OUTPUT
			NetFlow* C440DBGSYSTEMCONTROL, // OUTPUT
			NetFlow* C440JTGTDO, // OUTPUT
			NetFlow* C440JTGTDOEN, // OUTPUT
			NetFlow* C440MACHINECHECK, // OUTPUT
			NetFlow* C440RSTCHIPRESETREQ, // OUTPUT
			NetFlow* C440RSTCORERESETREQ, // OUTPUT
			NetFlow* C440RSTSYSTEMRESETREQ, // OUTPUT
			NetFlow* C440TRCBRANCHSTATUS, // OUTPUT
			NetFlow* C440TRCCYCLE, // OUTPUT
			NetFlow* C440TRCEXECUTIONSTATUS, // OUTPUT
			NetFlow* C440TRCTRACESTATUS, // OUTPUT
			NetFlow* C440TRCTRIGGEREVENTOUT, // OUTPUT
			NetFlow* C440TRCTRIGGEREVENTTYPE, // OUTPUT
			NetFlow* DMA0LLRSTENGINEACK, // OUTPUT
			NetFlow* DMA0LLRXDSTRDYN, // OUTPUT
			NetFlow* DMA0LLTXD, // OUTPUT
			NetFlow* DMA0LLTXEOFN, // OUTPUT
			NetFlow* DMA0LLTXEOPN, // OUTPUT
			NetFlow* DMA0LLTXREM, // OUTPUT
			NetFlow* DMA0LLTXSOFN, // OUTPUT
			NetFlow* DMA0LLTXSOPN, // OUTPUT
			NetFlow* DMA0LLTXSRCRDYN, // OUTPUT
			NetFlow* DMA0RXIRQ, // OUTPUT
			NetFlow* DMA0TXIRQ, // OUTPUT
			NetFlow* DMA1LLRSTENGINEACK, // OUTPUT
			NetFlow* DMA1LLRXDSTRDYN, // OUTPUT
			NetFlow* DMA1LLTXD, // OUTPUT
			NetFlow* DMA1LLTXEOFN, // OUTPUT
			NetFlow* DMA1LLTXEOPN, // OUTPUT
			NetFlow* DMA1LLTXREM, // OUTPUT
			NetFlow* DMA1LLTXSOFN, // OUTPUT
			NetFlow* DMA1LLTXSOPN, // OUTPUT
			NetFlow* DMA1LLTXSRCRDYN, // OUTPUT
			NetFlow* DMA1RXIRQ, // OUTPUT
			NetFlow* DMA1TXIRQ, // OUTPUT
			NetFlow* DMA2LLRSTENGINEACK, // OUTPUT
			NetFlow* DMA2LLRXDSTRDYN, // OUTPUT
			NetFlow* DMA2LLTXD, // OUTPUT
			NetFlow* DMA2LLTXEOFN, // OUTPUT
			NetFlow* DMA2LLTXEOPN, // OUTPUT
			NetFlow* DMA2LLTXREM, // OUTPUT
			NetFlow* DMA2LLTXSOFN, // OUTPUT
			NetFlow* DMA2LLTXSOPN, // OUTPUT
			NetFlow* DMA2LLTXSRCRDYN, // OUTPUT
			NetFlow* DMA2RXIRQ, // OUTPUT
			NetFlow* DMA2TXIRQ, // OUTPUT
			NetFlow* DMA3LLRSTENGINEACK, // OUTPUT
			NetFlow* DMA3LLRXDSTRDYN, // OUTPUT
			NetFlow* DMA3LLTXD, // OUTPUT
			NetFlow* DMA3LLTXEOFN, // OUTPUT
			NetFlow* DMA3LLTXEOPN, // OUTPUT
			NetFlow* DMA3LLTXREM, // OUTPUT
			NetFlow* DMA3LLTXSOFN, // OUTPUT
			NetFlow* DMA3LLTXSOPN, // OUTPUT
			NetFlow* DMA3LLTXSRCRDYN, // OUTPUT
			NetFlow* DMA3RXIRQ, // OUTPUT
			NetFlow* DMA3TXIRQ, // OUTPUT
			NetFlow* MIMCADDRESS, // OUTPUT
			NetFlow* MIMCADDRESSVALID, // OUTPUT
			NetFlow* MIMCBANKCONFLICT, // OUTPUT
			NetFlow* MIMCBYTEENABLE, // OUTPUT
			NetFlow* MIMCREADNOTWRITE, // OUTPUT
			NetFlow* MIMCROWCONFLICT, // OUTPUT
			NetFlow* MIMCWRITEDATA, // OUTPUT
			NetFlow* MIMCWRITEDATAVALID, // OUTPUT
			NetFlow* PPCCPMINTERCONNECTBUSY, // OUTPUT
			NetFlow* PPCDMDCRABUS, // OUTPUT
			NetFlow* PPCDMDCRDBUSOUT, // OUTPUT
			NetFlow* PPCDMDCRREAD, // OUTPUT
			NetFlow* PPCDMDCRUABUS, // OUTPUT
			NetFlow* PPCDMDCRWRITE, // OUTPUT
			NetFlow* PPCDSDCRACK, // OUTPUT
			NetFlow* PPCDSDCRDBUSIN, // OUTPUT
			NetFlow* PPCDSDCRTIMEOUTWAIT, // OUTPUT
			NetFlow* PPCEICINTERCONNECTIRQ, // OUTPUT
			NetFlow* PPCMPLBABORT, // OUTPUT
			NetFlow* PPCMPLBABUS, // OUTPUT
			NetFlow* PPCMPLBBE, // OUTPUT
			NetFlow* PPCMPLBBUSLOCK, // OUTPUT
			NetFlow* PPCMPLBLOCKERR, // OUTPUT
			NetFlow* PPCMPLBPRIORITY, // OUTPUT
			NetFlow* PPCMPLBRDBURST, // OUTPUT
			NetFlow* PPCMPLBREQUEST, // OUTPUT
			NetFlow* PPCMPLBRNW, // OUTPUT
			NetFlow* PPCMPLBSIZE, // OUTPUT
			NetFlow* PPCMPLBTATTRIBUTE, // OUTPUT
			NetFlow* PPCMPLBTYPE, // OUTPUT
			NetFlow* PPCMPLBUABUS, // OUTPUT
			NetFlow* PPCMPLBWRBURST, // OUTPUT
			NetFlow* PPCMPLBWRDBUS, // OUTPUT
			NetFlow* PPCS0PLBADDRACK, // OUTPUT
			NetFlow* PPCS0PLBMBUSY, // OUTPUT
			NetFlow* PPCS0PLBMIRQ, // OUTPUT
			NetFlow* PPCS0PLBMRDERR, // OUTPUT
			NetFlow* PPCS0PLBMWRERR, // OUTPUT
			NetFlow* PPCS0PLBRDBTERM, // OUTPUT
			NetFlow* PPCS0PLBRDCOMP, // OUTPUT
			NetFlow* PPCS0PLBRDDACK, // OUTPUT
			NetFlow* PPCS0PLBRDDBUS, // OUTPUT
			NetFlow* PPCS0PLBRDWDADDR, // OUTPUT
			NetFlow* PPCS0PLBREARBITRATE, // OUTPUT
			NetFlow* PPCS0PLBSSIZE, // OUTPUT
			NetFlow* PPCS0PLBWAIT, // OUTPUT
			NetFlow* PPCS0PLBWRBTERM, // OUTPUT
			NetFlow* PPCS0PLBWRCOMP, // OUTPUT
			NetFlow* PPCS0PLBWRDACK, // OUTPUT
			NetFlow* PPCS1PLBADDRACK, // OUTPUT
			NetFlow* PPCS1PLBMBUSY, // OUTPUT
			NetFlow* PPCS1PLBMIRQ, // OUTPUT
			NetFlow* PPCS1PLBMRDERR, // OUTPUT
			NetFlow* PPCS1PLBMWRERR, // OUTPUT
			NetFlow* PPCS1PLBRDBTERM, // OUTPUT
			NetFlow* PPCS1PLBRDCOMP, // OUTPUT
			NetFlow* PPCS1PLBRDDACK, // OUTPUT
			NetFlow* PPCS1PLBRDDBUS, // OUTPUT
			NetFlow* PPCS1PLBRDWDADDR, // OUTPUT
			NetFlow* PPCS1PLBREARBITRATE, // OUTPUT
			NetFlow* PPCS1PLBSSIZE, // OUTPUT
			NetFlow* PPCS1PLBWAIT, // OUTPUT
			NetFlow* PPCS1PLBWRBTERM, // OUTPUT
			NetFlow* PPCS1PLBWRCOMP, // OUTPUT
			NetFlow* PPCS1PLBWRDACK, // OUTPUT
			NetFlow* CPMC440CLK, // INPUT
			NetFlow* CPMC440CLKEN, // INPUT
			NetFlow* CPMC440CORECLOCKINACTIVE, // INPUT
			NetFlow* CPMC440TIMERCLOCK, // INPUT
			NetFlow* CPMDCRCLK, // INPUT
			NetFlow* CPMDMA0LLCLK, // INPUT
			NetFlow* CPMDMA1LLCLK, // INPUT
			NetFlow* CPMDMA2LLCLK, // INPUT
			NetFlow* CPMDMA3LLCLK, // INPUT
			NetFlow* CPMFCMCLK, // INPUT
			NetFlow* CPMINTERCONNECTCLK, // INPUT
			NetFlow* CPMINTERCONNECTCLKEN, // INPUT
			NetFlow* CPMINTERCONNECTCLKNTO1, // INPUT
			NetFlow* CPMMCCLK, // INPUT
			NetFlow* CPMPPCMPLBCLK, // INPUT
			NetFlow* CPMPPCS0PLBCLK, // INPUT
			NetFlow* CPMPPCS1PLBCLK, // INPUT
			NetFlow* DBGC440DEBUGHALT, // INPUT
			NetFlow* DBGC440SYSTEMSTATUS, // INPUT
			NetFlow* DBGC440UNCONDDEBUGEVENT, // INPUT
			NetFlow* DCRPPCDMACK, // INPUT
			NetFlow* DCRPPCDMDBUSIN, // INPUT
			NetFlow* DCRPPCDMTIMEOUTWAIT, // INPUT
			NetFlow* DCRPPCDSABUS, // INPUT
			NetFlow* DCRPPCDSDBUSOUT, // INPUT
			NetFlow* DCRPPCDSREAD, // INPUT
			NetFlow* DCRPPCDSWRITE, // INPUT
			NetFlow* EICC440CRITIRQ, // INPUT
			NetFlow* EICC440EXTIRQ, // INPUT
			NetFlow* FCMAPUCONFIRMINSTR, // INPUT
			NetFlow* FCMAPUCR, // INPUT
			NetFlow* FCMAPUDONE, // INPUT
			NetFlow* FCMAPUEXCEPTION, // INPUT
			NetFlow* FCMAPUFPSCRFEX, // INPUT
			NetFlow* FCMAPURESULT, // INPUT
			NetFlow* FCMAPURESULTVALID, // INPUT
			NetFlow* FCMAPUSLEEPNOTREADY, // INPUT
			NetFlow* FCMAPUSTOREDATA, // INPUT
			NetFlow* JTGC440TCK, // INPUT
			NetFlow* JTGC440TDI, // INPUT
			NetFlow* JTGC440TMS, // INPUT
			NetFlow* JTGC440TRSTNEG, // INPUT
			NetFlow* LLDMA0RSTENGINEREQ, // INPUT
			NetFlow* LLDMA0RXD, // INPUT
			NetFlow* LLDMA0RXEOFN, // INPUT
			NetFlow* LLDMA0RXEOPN, // INPUT
			NetFlow* LLDMA0RXREM, // INPUT
			NetFlow* LLDMA0RXSOFN, // INPUT
			NetFlow* LLDMA0RXSOPN, // INPUT
			NetFlow* LLDMA0RXSRCRDYN, // INPUT
			NetFlow* LLDMA0TXDSTRDYN, // INPUT
			NetFlow* LLDMA1RSTENGINEREQ, // INPUT
			NetFlow* LLDMA1RXD, // INPUT
			NetFlow* LLDMA1RXEOFN, // INPUT
			NetFlow* LLDMA1RXEOPN, // INPUT
			NetFlow* LLDMA1RXREM, // INPUT
			NetFlow* LLDMA1RXSOFN, // INPUT
			NetFlow* LLDMA1RXSOPN, // INPUT
			NetFlow* LLDMA1RXSRCRDYN, // INPUT
			NetFlow* LLDMA1TXDSTRDYN, // INPUT
			NetFlow* LLDMA2RSTENGINEREQ, // INPUT
			NetFlow* LLDMA2RXD, // INPUT
			NetFlow* LLDMA2RXEOFN, // INPUT
			NetFlow* LLDMA2RXEOPN, // INPUT
			NetFlow* LLDMA2RXREM, // INPUT
			NetFlow* LLDMA2RXSOFN, // INPUT
			NetFlow* LLDMA2RXSOPN, // INPUT
			NetFlow* LLDMA2RXSRCRDYN, // INPUT
			NetFlow* LLDMA2TXDSTRDYN, // INPUT
			NetFlow* LLDMA3RSTENGINEREQ, // INPUT
			NetFlow* LLDMA3RXD, // INPUT
			NetFlow* LLDMA3RXEOFN, // INPUT
			NetFlow* LLDMA3RXEOPN, // INPUT
			NetFlow* LLDMA3RXREM, // INPUT
			NetFlow* LLDMA3RXSOFN, // INPUT
			NetFlow* LLDMA3RXSOPN, // INPUT
			NetFlow* LLDMA3RXSRCRDYN, // INPUT
			NetFlow* LLDMA3TXDSTRDYN, // INPUT
			NetFlow* MCMIADDRREADYTOACCEPT, // INPUT
			NetFlow* MCMIREADDATA, // INPUT
			NetFlow* MCMIREADDATAERR, // INPUT
			NetFlow* MCMIREADDATAVALID, // INPUT
			NetFlow* PLBPPCMADDRACK, // INPUT
			NetFlow* PLBPPCMMBUSY, // INPUT
			NetFlow* PLBPPCMMIRQ, // INPUT
			NetFlow* PLBPPCMMRDERR, // INPUT
			NetFlow* PLBPPCMMWRERR, // INPUT
			NetFlow* PLBPPCMRDBTERM, // INPUT
			NetFlow* PLBPPCMRDDACK, // INPUT
			NetFlow* PLBPPCMRDDBUS, // INPUT
			NetFlow* PLBPPCMRDPENDPRI, // INPUT
			NetFlow* PLBPPCMRDPENDREQ, // INPUT
			NetFlow* PLBPPCMRDWDADDR, // INPUT
			NetFlow* PLBPPCMREARBITRATE, // INPUT
			NetFlow* PLBPPCMREQPRI, // INPUT
			NetFlow* PLBPPCMSSIZE, // INPUT
			NetFlow* PLBPPCMTIMEOUT, // INPUT
			NetFlow* PLBPPCMWRBTERM, // INPUT
			NetFlow* PLBPPCMWRDACK, // INPUT
			NetFlow* PLBPPCMWRPENDPRI, // INPUT
			NetFlow* PLBPPCMWRPENDREQ, // INPUT
			NetFlow* PLBPPCS0ABORT, // INPUT
			NetFlow* PLBPPCS0ABUS, // INPUT
			NetFlow* PLBPPCS0BE, // INPUT
			NetFlow* PLBPPCS0BUSLOCK, // INPUT
			NetFlow* PLBPPCS0LOCKERR, // INPUT
			NetFlow* PLBPPCS0MASTERID, // INPUT
			NetFlow* PLBPPCS0MSIZE, // INPUT
			NetFlow* PLBPPCS0PAVALID, // INPUT
			NetFlow* PLBPPCS0RDBURST, // INPUT
			NetFlow* PLBPPCS0RDPENDPRI, // INPUT
			NetFlow* PLBPPCS0RDPENDREQ, // INPUT
			NetFlow* PLBPPCS0RDPRIM, // INPUT
			NetFlow* PLBPPCS0REQPRI, // INPUT
			NetFlow* PLBPPCS0RNW, // INPUT
			NetFlow* PLBPPCS0SAVALID, // INPUT
			NetFlow* PLBPPCS0SIZE, // INPUT
			NetFlow* PLBPPCS0TATTRIBUTE, // INPUT
			NetFlow* PLBPPCS0TYPE, // INPUT
			NetFlow* PLBPPCS0UABUS, // INPUT
			NetFlow* PLBPPCS0WRBURST, // INPUT
			NetFlow* PLBPPCS0WRDBUS, // INPUT
			NetFlow* PLBPPCS0WRPENDPRI, // INPUT
			NetFlow* PLBPPCS0WRPENDREQ, // INPUT
			NetFlow* PLBPPCS0WRPRIM, // INPUT
			NetFlow* PLBPPCS1ABORT, // INPUT
			NetFlow* PLBPPCS1ABUS, // INPUT
			NetFlow* PLBPPCS1BE, // INPUT
			NetFlow* PLBPPCS1BUSLOCK, // INPUT
			NetFlow* PLBPPCS1LOCKERR, // INPUT
			NetFlow* PLBPPCS1MASTERID, // INPUT
			NetFlow* PLBPPCS1MSIZE, // INPUT
			NetFlow* PLBPPCS1PAVALID, // INPUT
			NetFlow* PLBPPCS1RDBURST, // INPUT
			NetFlow* PLBPPCS1RDPENDPRI, // INPUT
			NetFlow* PLBPPCS1RDPENDREQ, // INPUT
			NetFlow* PLBPPCS1RDPRIM, // INPUT
			NetFlow* PLBPPCS1REQPRI, // INPUT
			NetFlow* PLBPPCS1RNW, // INPUT
			NetFlow* PLBPPCS1SAVALID, // INPUT
			NetFlow* PLBPPCS1SIZE, // INPUT
			NetFlow* PLBPPCS1TATTRIBUTE, // INPUT
			NetFlow* PLBPPCS1TYPE, // INPUT
			NetFlow* PLBPPCS1UABUS, // INPUT
			NetFlow* PLBPPCS1WRBURST, // INPUT
			NetFlow* PLBPPCS1WRDBUS, // INPUT
			NetFlow* PLBPPCS1WRPENDPRI, // INPUT
			NetFlow* PLBPPCS1WRPENDREQ, // INPUT
			NetFlow* PLBPPCS1WRPRIM, // INPUT
			NetFlow* RSTC440RESETCHIP, // INPUT
			NetFlow* RSTC440RESETCORE, // INPUT
			NetFlow* RSTC440RESETSYSTEM, // INPUT
			NetFlow* TIEC440DCURDLDCACHEPLBPRIO, // INPUT
			NetFlow* TIEC440DCURDNONCACHEPLBPRIO, // INPUT
			NetFlow* TIEC440DCURDTOUCHPLBPRIO, // INPUT
			NetFlow* TIEC440DCURDURGENTPLBPRIO, // INPUT
			NetFlow* TIEC440DCUWRFLUSHPLBPRIO, // INPUT
			NetFlow* TIEC440DCUWRSTOREPLBPRIO, // INPUT
			NetFlow* TIEC440DCUWRURGENTPLBPRIO, // INPUT
			NetFlow* TIEC440ENDIANRESET, // INPUT
			NetFlow* TIEC440ERPNRESET, // INPUT
			NetFlow* TIEC440ICURDFETCHPLBPRIO, // INPUT
			NetFlow* TIEC440ICURDSPECPLBPRIO, // INPUT
			NetFlow* TIEC440ICURDTOUCHPLBPRIO, // INPUT
			NetFlow* TIEC440PIR, // INPUT
			NetFlow* TIEC440PVR, // INPUT
			NetFlow* TIEC440USERRESET, // INPUT
			NetFlow* TIEDCRBASEADDR, // INPUT
			NetFlow* TRCC440TRACEDISABLE, // INPUT
			NetFlow* TRCC440TRIGGEREVENTIN // INPUT
			){
		
			// Assign parameters and ports: 
			//Verilog Parameters:
			this->LOC = LOC; // Default: "UNPLACED"
			this->CLOCK_DELAY = CLOCK_DELAY; // Default: "FALSE"
			this->DCR_AUTOLOCK_ENABLE = DCR_AUTOLOCK_ENABLE; // Default: "TRUE"
			this->PPCDM_ASYNCMODE = PPCDM_ASYNCMODE; // Default: "FALSE"
			this->PPCDS_ASYNCMODE = PPCDS_ASYNCMODE; // Default: "FALSE"
			this->PPCS0_WIDTH_128N64 = PPCS0_WIDTH_128N64; // Default: "TRUE"
			this->PPCS1_WIDTH_128N64 = PPCS1_WIDTH_128N64; // Default: "TRUE"
			this->APU_CONTROL = APU_CONTROL; // Default: 17'h02000
			this->APU_UDI0 = APU_UDI0; // Default: 24'h000000
			this->APU_UDI1 = APU_UDI1; // Default: 24'h000000
			this->APU_UDI10 = APU_UDI10; // Default: 24'h000000
			this->APU_UDI11 = APU_UDI11; // Default: 24'h000000
			this->APU_UDI12 = APU_UDI12; // Default: 24'h000000
			this->APU_UDI13 = APU_UDI13; // Default: 24'h000000
			this->APU_UDI14 = APU_UDI14; // Default: 24'h000000
			this->APU_UDI15 = APU_UDI15; // Default: 24'h000000
			this->APU_UDI2 = APU_UDI2; // Default: 24'h000000
			this->APU_UDI3 = APU_UDI3; // Default: 24'h000000
			this->APU_UDI4 = APU_UDI4; // Default: 24'h000000
			this->APU_UDI5 = APU_UDI5; // Default: 24'h000000
			this->APU_UDI6 = APU_UDI6; // Default: 24'h000000
			this->APU_UDI7 = APU_UDI7; // Default: 24'h000000
			this->APU_UDI8 = APU_UDI8; // Default: 24'h000000
			this->APU_UDI9 = APU_UDI9; // Default: 24'h000000
			this->DMA0_RXCHANNELCTRL = DMA0_RXCHANNELCTRL; // Default: 32'h01010000
			this->DMA0_TXCHANNELCTRL = DMA0_TXCHANNELCTRL; // Default: 32'h01010000
			this->DMA1_RXCHANNELCTRL = DMA1_RXCHANNELCTRL; // Default: 32'h01010000
			this->DMA1_TXCHANNELCTRL = DMA1_TXCHANNELCTRL; // Default: 32'h01010000
			this->DMA2_RXCHANNELCTRL = DMA2_RXCHANNELCTRL; // Default: 32'h01010000
			this->DMA2_TXCHANNELCTRL = DMA2_TXCHANNELCTRL; // Default: 32'h01010000
			this->DMA3_RXCHANNELCTRL = DMA3_RXCHANNELCTRL; // Default: 32'h01010000
			this->DMA3_TXCHANNELCTRL = DMA3_TXCHANNELCTRL; // Default: 32'h01010000
			this->INTERCONNECT_IMASK = INTERCONNECT_IMASK; // Default: 32'hFFFFFFFF
			this->INTERCONNECT_TMPL_SEL = INTERCONNECT_TMPL_SEL; // Default: 32'h3FFFFFFF
			this->MI_ARBCONFIG = MI_ARBCONFIG; // Default: 32'h00432010
			this->MI_BANKCONFLICT_MASK = MI_BANKCONFLICT_MASK; // Default: 32'h00000000
			this->MI_CONTROL = MI_CONTROL; // Default: 32'h0000008F
			this->MI_ROWCONFLICT_MASK = MI_ROWCONFLICT_MASK; // Default: 32'h00000000
			this->PPCM_ARBCONFIG = PPCM_ARBCONFIG; // Default: 32'h00432010
			this->PPCM_CONTROL = PPCM_CONTROL; // Default: 32'h8000009F
			this->PPCM_COUNTER = PPCM_COUNTER; // Default: 32'h00000500
			this->PPCS0_ADDRMAP_TMPL0 = PPCS0_ADDRMAP_TMPL0; // Default: 32'hFFFFFFFF
			this->PPCS0_ADDRMAP_TMPL1 = PPCS0_ADDRMAP_TMPL1; // Default: 32'hFFFFFFFF
			this->PPCS0_ADDRMAP_TMPL2 = PPCS0_ADDRMAP_TMPL2; // Default: 32'hFFFFFFFF
			this->PPCS0_ADDRMAP_TMPL3 = PPCS0_ADDRMAP_TMPL3; // Default: 32'hFFFFFFFF
			this->PPCS0_CONTROL = PPCS0_CONTROL; // Default: 32'h8033336C
			this->PPCS1_ADDRMAP_TMPL0 = PPCS1_ADDRMAP_TMPL0; // Default: 32'hFFFFFFFF
			this->PPCS1_ADDRMAP_TMPL1 = PPCS1_ADDRMAP_TMPL1; // Default: 32'hFFFFFFFF
			this->PPCS1_ADDRMAP_TMPL2 = PPCS1_ADDRMAP_TMPL2; // Default: 32'hFFFFFFFF
			this->PPCS1_ADDRMAP_TMPL3 = PPCS1_ADDRMAP_TMPL3; // Default: 32'hFFFFFFFF
			this->PPCS1_CONTROL = PPCS1_CONTROL; // Default: 32'h8033336C
			this->XBAR_ADDRMAP_TMPL0 = XBAR_ADDRMAP_TMPL0; // Default: 32'hFFFF0000
			this->XBAR_ADDRMAP_TMPL1 = XBAR_ADDRMAP_TMPL1; // Default: 32'h00000000
			this->XBAR_ADDRMAP_TMPL2 = XBAR_ADDRMAP_TMPL2; // Default: 32'h00000000
			this->XBAR_ADDRMAP_TMPL3 = XBAR_ADDRMAP_TMPL3; // Default: 32'h00000000
			this->DMA0_CONTROL = DMA0_CONTROL; // Default: 8'h00
			this->DMA1_CONTROL = DMA1_CONTROL; // Default: 8'h00
			this->DMA2_CONTROL = DMA2_CONTROL; // Default: 8'h00
			this->DMA3_CONTROL = DMA3_CONTROL; // Default: 8'h00
			this->DMA0_RXIRQTIMER = DMA0_RXIRQTIMER; // Default: 10'h3FF
			this->DMA0_TXIRQTIMER = DMA0_TXIRQTIMER; // Default: 10'h3FF
			this->DMA1_RXIRQTIMER = DMA1_RXIRQTIMER; // Default: 10'h3FF
			this->DMA1_TXIRQTIMER = DMA1_TXIRQTIMER; // Default: 10'h3FF
			this->DMA2_RXIRQTIMER = DMA2_RXIRQTIMER; // Default: 10'h3FF
			this->DMA2_TXIRQTIMER = DMA2_TXIRQTIMER; // Default: 10'h3FF
			this->DMA3_RXIRQTIMER = DMA3_RXIRQTIMER; // Default: 10'h3FF
			this->DMA3_TXIRQTIMER = DMA3_TXIRQTIMER; // Default: 10'h3FF
			//Verilog Ports in definition order:
			this->APUFCMDECFPUOP = APUFCMDECFPUOP; // OUTPUT
			this->APUFCMDECLDSTXFERSIZE = APUFCMDECLDSTXFERSIZE; // OUTPUT
			this->APUFCMDECLOAD = APUFCMDECLOAD; // OUTPUT
			this->APUFCMDECNONAUTON = APUFCMDECNONAUTON; // OUTPUT
			this->APUFCMDECSTORE = APUFCMDECSTORE; // OUTPUT
			this->APUFCMDECUDI = APUFCMDECUDI; // OUTPUT
			this->APUFCMDECUDIVALID = APUFCMDECUDIVALID; // OUTPUT
			this->APUFCMENDIAN = APUFCMENDIAN; // OUTPUT
			this->APUFCMFLUSH = APUFCMFLUSH; // OUTPUT
			this->APUFCMINSTRUCTION = APUFCMINSTRUCTION; // OUTPUT
			this->APUFCMINSTRVALID = APUFCMINSTRVALID; // OUTPUT
			this->APUFCMLOADBYTEADDR = APUFCMLOADBYTEADDR; // OUTPUT
			this->APUFCMLOADDATA = APUFCMLOADDATA; // OUTPUT
			this->APUFCMLOADDVALID = APUFCMLOADDVALID; // OUTPUT
			this->APUFCMMSRFE0 = APUFCMMSRFE0; // OUTPUT
			this->APUFCMMSRFE1 = APUFCMMSRFE1; // OUTPUT
			this->APUFCMNEXTINSTRREADY = APUFCMNEXTINSTRREADY; // OUTPUT
			this->APUFCMOPERANDVALID = APUFCMOPERANDVALID; // OUTPUT
			this->APUFCMRADATA = APUFCMRADATA; // OUTPUT
			this->APUFCMRBDATA = APUFCMRBDATA; // OUTPUT
			this->APUFCMWRITEBACKOK = APUFCMWRITEBACKOK; // OUTPUT
			this->C440CPMCORESLEEPREQ = C440CPMCORESLEEPREQ; // OUTPUT
			this->C440CPMDECIRPTREQ = C440CPMDECIRPTREQ; // OUTPUT
			this->C440CPMFITIRPTREQ = C440CPMFITIRPTREQ; // OUTPUT
			this->C440CPMMSRCE = C440CPMMSRCE; // OUTPUT
			this->C440CPMMSREE = C440CPMMSREE; // OUTPUT
			this->C440CPMTIMERRESETREQ = C440CPMTIMERRESETREQ; // OUTPUT
			this->C440CPMWDIRPTREQ = C440CPMWDIRPTREQ; // OUTPUT
			this->C440DBGSYSTEMCONTROL = C440DBGSYSTEMCONTROL; // OUTPUT
			this->C440JTGTDO = C440JTGTDO; // OUTPUT
			this->C440JTGTDOEN = C440JTGTDOEN; // OUTPUT
			this->C440MACHINECHECK = C440MACHINECHECK; // OUTPUT
			this->C440RSTCHIPRESETREQ = C440RSTCHIPRESETREQ; // OUTPUT
			this->C440RSTCORERESETREQ = C440RSTCORERESETREQ; // OUTPUT
			this->C440RSTSYSTEMRESETREQ = C440RSTSYSTEMRESETREQ; // OUTPUT
			this->C440TRCBRANCHSTATUS = C440TRCBRANCHSTATUS; // OUTPUT
			this->C440TRCCYCLE = C440TRCCYCLE; // OUTPUT
			this->C440TRCEXECUTIONSTATUS = C440TRCEXECUTIONSTATUS; // OUTPUT
			this->C440TRCTRACESTATUS = C440TRCTRACESTATUS; // OUTPUT
			this->C440TRCTRIGGEREVENTOUT = C440TRCTRIGGEREVENTOUT; // OUTPUT
			this->C440TRCTRIGGEREVENTTYPE = C440TRCTRIGGEREVENTTYPE; // OUTPUT
			this->DMA0LLRSTENGINEACK = DMA0LLRSTENGINEACK; // OUTPUT
			this->DMA0LLRXDSTRDYN = DMA0LLRXDSTRDYN; // OUTPUT
			this->DMA0LLTXD = DMA0LLTXD; // OUTPUT
			this->DMA0LLTXEOFN = DMA0LLTXEOFN; // OUTPUT
			this->DMA0LLTXEOPN = DMA0LLTXEOPN; // OUTPUT
			this->DMA0LLTXREM = DMA0LLTXREM; // OUTPUT
			this->DMA0LLTXSOFN = DMA0LLTXSOFN; // OUTPUT
			this->DMA0LLTXSOPN = DMA0LLTXSOPN; // OUTPUT
			this->DMA0LLTXSRCRDYN = DMA0LLTXSRCRDYN; // OUTPUT
			this->DMA0RXIRQ = DMA0RXIRQ; // OUTPUT
			this->DMA0TXIRQ = DMA0TXIRQ; // OUTPUT
			this->DMA1LLRSTENGINEACK = DMA1LLRSTENGINEACK; // OUTPUT
			this->DMA1LLRXDSTRDYN = DMA1LLRXDSTRDYN; // OUTPUT
			this->DMA1LLTXD = DMA1LLTXD; // OUTPUT
			this->DMA1LLTXEOFN = DMA1LLTXEOFN; // OUTPUT
			this->DMA1LLTXEOPN = DMA1LLTXEOPN; // OUTPUT
			this->DMA1LLTXREM = DMA1LLTXREM; // OUTPUT
			this->DMA1LLTXSOFN = DMA1LLTXSOFN; // OUTPUT
			this->DMA1LLTXSOPN = DMA1LLTXSOPN; // OUTPUT
			this->DMA1LLTXSRCRDYN = DMA1LLTXSRCRDYN; // OUTPUT
			this->DMA1RXIRQ = DMA1RXIRQ; // OUTPUT
			this->DMA1TXIRQ = DMA1TXIRQ; // OUTPUT
			this->DMA2LLRSTENGINEACK = DMA2LLRSTENGINEACK; // OUTPUT
			this->DMA2LLRXDSTRDYN = DMA2LLRXDSTRDYN; // OUTPUT
			this->DMA2LLTXD = DMA2LLTXD; // OUTPUT
			this->DMA2LLTXEOFN = DMA2LLTXEOFN; // OUTPUT
			this->DMA2LLTXEOPN = DMA2LLTXEOPN; // OUTPUT
			this->DMA2LLTXREM = DMA2LLTXREM; // OUTPUT
			this->DMA2LLTXSOFN = DMA2LLTXSOFN; // OUTPUT
			this->DMA2LLTXSOPN = DMA2LLTXSOPN; // OUTPUT
			this->DMA2LLTXSRCRDYN = DMA2LLTXSRCRDYN; // OUTPUT
			this->DMA2RXIRQ = DMA2RXIRQ; // OUTPUT
			this->DMA2TXIRQ = DMA2TXIRQ; // OUTPUT
			this->DMA3LLRSTENGINEACK = DMA3LLRSTENGINEACK; // OUTPUT
			this->DMA3LLRXDSTRDYN = DMA3LLRXDSTRDYN; // OUTPUT
			this->DMA3LLTXD = DMA3LLTXD; // OUTPUT
			this->DMA3LLTXEOFN = DMA3LLTXEOFN; // OUTPUT
			this->DMA3LLTXEOPN = DMA3LLTXEOPN; // OUTPUT
			this->DMA3LLTXREM = DMA3LLTXREM; // OUTPUT
			this->DMA3LLTXSOFN = DMA3LLTXSOFN; // OUTPUT
			this->DMA3LLTXSOPN = DMA3LLTXSOPN; // OUTPUT
			this->DMA3LLTXSRCRDYN = DMA3LLTXSRCRDYN; // OUTPUT
			this->DMA3RXIRQ = DMA3RXIRQ; // OUTPUT
			this->DMA3TXIRQ = DMA3TXIRQ; // OUTPUT
			this->MIMCADDRESS = MIMCADDRESS; // OUTPUT
			this->MIMCADDRESSVALID = MIMCADDRESSVALID; // OUTPUT
			this->MIMCBANKCONFLICT = MIMCBANKCONFLICT; // OUTPUT
			this->MIMCBYTEENABLE = MIMCBYTEENABLE; // OUTPUT
			this->MIMCREADNOTWRITE = MIMCREADNOTWRITE; // OUTPUT
			this->MIMCROWCONFLICT = MIMCROWCONFLICT; // OUTPUT
			this->MIMCWRITEDATA = MIMCWRITEDATA; // OUTPUT
			this->MIMCWRITEDATAVALID = MIMCWRITEDATAVALID; // OUTPUT
			this->PPCCPMINTERCONNECTBUSY = PPCCPMINTERCONNECTBUSY; // OUTPUT
			this->PPCDMDCRABUS = PPCDMDCRABUS; // OUTPUT
			this->PPCDMDCRDBUSOUT = PPCDMDCRDBUSOUT; // OUTPUT
			this->PPCDMDCRREAD = PPCDMDCRREAD; // OUTPUT
			this->PPCDMDCRUABUS = PPCDMDCRUABUS; // OUTPUT
			this->PPCDMDCRWRITE = PPCDMDCRWRITE; // OUTPUT
			this->PPCDSDCRACK = PPCDSDCRACK; // OUTPUT
			this->PPCDSDCRDBUSIN = PPCDSDCRDBUSIN; // OUTPUT
			this->PPCDSDCRTIMEOUTWAIT = PPCDSDCRTIMEOUTWAIT; // OUTPUT
			this->PPCEICINTERCONNECTIRQ = PPCEICINTERCONNECTIRQ; // OUTPUT
			this->PPCMPLBABORT = PPCMPLBABORT; // OUTPUT
			this->PPCMPLBABUS = PPCMPLBABUS; // OUTPUT
			this->PPCMPLBBE = PPCMPLBBE; // OUTPUT
			this->PPCMPLBBUSLOCK = PPCMPLBBUSLOCK; // OUTPUT
			this->PPCMPLBLOCKERR = PPCMPLBLOCKERR; // OUTPUT
			this->PPCMPLBPRIORITY = PPCMPLBPRIORITY; // OUTPUT
			this->PPCMPLBRDBURST = PPCMPLBRDBURST; // OUTPUT
			this->PPCMPLBREQUEST = PPCMPLBREQUEST; // OUTPUT
			this->PPCMPLBRNW = PPCMPLBRNW; // OUTPUT
			this->PPCMPLBSIZE = PPCMPLBSIZE; // OUTPUT
			this->PPCMPLBTATTRIBUTE = PPCMPLBTATTRIBUTE; // OUTPUT
			this->PPCMPLBTYPE = PPCMPLBTYPE; // OUTPUT
			this->PPCMPLBUABUS = PPCMPLBUABUS; // OUTPUT
			this->PPCMPLBWRBURST = PPCMPLBWRBURST; // OUTPUT
			this->PPCMPLBWRDBUS = PPCMPLBWRDBUS; // OUTPUT
			this->PPCS0PLBADDRACK = PPCS0PLBADDRACK; // OUTPUT
			this->PPCS0PLBMBUSY = PPCS0PLBMBUSY; // OUTPUT
			this->PPCS0PLBMIRQ = PPCS0PLBMIRQ; // OUTPUT
			this->PPCS0PLBMRDERR = PPCS0PLBMRDERR; // OUTPUT
			this->PPCS0PLBMWRERR = PPCS0PLBMWRERR; // OUTPUT
			this->PPCS0PLBRDBTERM = PPCS0PLBRDBTERM; // OUTPUT
			this->PPCS0PLBRDCOMP = PPCS0PLBRDCOMP; // OUTPUT
			this->PPCS0PLBRDDACK = PPCS0PLBRDDACK; // OUTPUT
			this->PPCS0PLBRDDBUS = PPCS0PLBRDDBUS; // OUTPUT
			this->PPCS0PLBRDWDADDR = PPCS0PLBRDWDADDR; // OUTPUT
			this->PPCS0PLBREARBITRATE = PPCS0PLBREARBITRATE; // OUTPUT
			this->PPCS0PLBSSIZE = PPCS0PLBSSIZE; // OUTPUT
			this->PPCS0PLBWAIT = PPCS0PLBWAIT; // OUTPUT
			this->PPCS0PLBWRBTERM = PPCS0PLBWRBTERM; // OUTPUT
			this->PPCS0PLBWRCOMP = PPCS0PLBWRCOMP; // OUTPUT
			this->PPCS0PLBWRDACK = PPCS0PLBWRDACK; // OUTPUT
			this->PPCS1PLBADDRACK = PPCS1PLBADDRACK; // OUTPUT
			this->PPCS1PLBMBUSY = PPCS1PLBMBUSY; // OUTPUT
			this->PPCS1PLBMIRQ = PPCS1PLBMIRQ; // OUTPUT
			this->PPCS1PLBMRDERR = PPCS1PLBMRDERR; // OUTPUT
			this->PPCS1PLBMWRERR = PPCS1PLBMWRERR; // OUTPUT
			this->PPCS1PLBRDBTERM = PPCS1PLBRDBTERM; // OUTPUT
			this->PPCS1PLBRDCOMP = PPCS1PLBRDCOMP; // OUTPUT
			this->PPCS1PLBRDDACK = PPCS1PLBRDDACK; // OUTPUT
			this->PPCS1PLBRDDBUS = PPCS1PLBRDDBUS; // OUTPUT
			this->PPCS1PLBRDWDADDR = PPCS1PLBRDWDADDR; // OUTPUT
			this->PPCS1PLBREARBITRATE = PPCS1PLBREARBITRATE; // OUTPUT
			this->PPCS1PLBSSIZE = PPCS1PLBSSIZE; // OUTPUT
			this->PPCS1PLBWAIT = PPCS1PLBWAIT; // OUTPUT
			this->PPCS1PLBWRBTERM = PPCS1PLBWRBTERM; // OUTPUT
			this->PPCS1PLBWRCOMP = PPCS1PLBWRCOMP; // OUTPUT
			this->PPCS1PLBWRDACK = PPCS1PLBWRDACK; // OUTPUT
			this->CPMC440CLK = CPMC440CLK; // INPUT
			this->CPMC440CLKEN = CPMC440CLKEN; // INPUT
			this->CPMC440CORECLOCKINACTIVE = CPMC440CORECLOCKINACTIVE; // INPUT
			this->CPMC440TIMERCLOCK = CPMC440TIMERCLOCK; // INPUT
			this->CPMDCRCLK = CPMDCRCLK; // INPUT
			this->CPMDMA0LLCLK = CPMDMA0LLCLK; // INPUT
			this->CPMDMA1LLCLK = CPMDMA1LLCLK; // INPUT
			this->CPMDMA2LLCLK = CPMDMA2LLCLK; // INPUT
			this->CPMDMA3LLCLK = CPMDMA3LLCLK; // INPUT
			this->CPMFCMCLK = CPMFCMCLK; // INPUT
			this->CPMINTERCONNECTCLK = CPMINTERCONNECTCLK; // INPUT
			this->CPMINTERCONNECTCLKEN = CPMINTERCONNECTCLKEN; // INPUT
			this->CPMINTERCONNECTCLKNTO1 = CPMINTERCONNECTCLKNTO1; // INPUT
			this->CPMMCCLK = CPMMCCLK; // INPUT
			this->CPMPPCMPLBCLK = CPMPPCMPLBCLK; // INPUT
			this->CPMPPCS0PLBCLK = CPMPPCS0PLBCLK; // INPUT
			this->CPMPPCS1PLBCLK = CPMPPCS1PLBCLK; // INPUT
			this->DBGC440DEBUGHALT = DBGC440DEBUGHALT; // INPUT
			this->DBGC440SYSTEMSTATUS = DBGC440SYSTEMSTATUS; // INPUT
			this->DBGC440UNCONDDEBUGEVENT = DBGC440UNCONDDEBUGEVENT; // INPUT
			this->DCRPPCDMACK = DCRPPCDMACK; // INPUT
			this->DCRPPCDMDBUSIN = DCRPPCDMDBUSIN; // INPUT
			this->DCRPPCDMTIMEOUTWAIT = DCRPPCDMTIMEOUTWAIT; // INPUT
			this->DCRPPCDSABUS = DCRPPCDSABUS; // INPUT
			this->DCRPPCDSDBUSOUT = DCRPPCDSDBUSOUT; // INPUT
			this->DCRPPCDSREAD = DCRPPCDSREAD; // INPUT
			this->DCRPPCDSWRITE = DCRPPCDSWRITE; // INPUT
			this->EICC440CRITIRQ = EICC440CRITIRQ; // INPUT
			this->EICC440EXTIRQ = EICC440EXTIRQ; // INPUT
			this->FCMAPUCONFIRMINSTR = FCMAPUCONFIRMINSTR; // INPUT
			this->FCMAPUCR = FCMAPUCR; // INPUT
			this->FCMAPUDONE = FCMAPUDONE; // INPUT
			this->FCMAPUEXCEPTION = FCMAPUEXCEPTION; // INPUT
			this->FCMAPUFPSCRFEX = FCMAPUFPSCRFEX; // INPUT
			this->FCMAPURESULT = FCMAPURESULT; // INPUT
			this->FCMAPURESULTVALID = FCMAPURESULTVALID; // INPUT
			this->FCMAPUSLEEPNOTREADY = FCMAPUSLEEPNOTREADY; // INPUT
			this->FCMAPUSTOREDATA = FCMAPUSTOREDATA; // INPUT
			this->JTGC440TCK = JTGC440TCK; // INPUT
			this->JTGC440TDI = JTGC440TDI; // INPUT
			this->JTGC440TMS = JTGC440TMS; // INPUT
			this->JTGC440TRSTNEG = JTGC440TRSTNEG; // INPUT
			this->LLDMA0RSTENGINEREQ = LLDMA0RSTENGINEREQ; // INPUT
			this->LLDMA0RXD = LLDMA0RXD; // INPUT
			this->LLDMA0RXEOFN = LLDMA0RXEOFN; // INPUT
			this->LLDMA0RXEOPN = LLDMA0RXEOPN; // INPUT
			this->LLDMA0RXREM = LLDMA0RXREM; // INPUT
			this->LLDMA0RXSOFN = LLDMA0RXSOFN; // INPUT
			this->LLDMA0RXSOPN = LLDMA0RXSOPN; // INPUT
			this->LLDMA0RXSRCRDYN = LLDMA0RXSRCRDYN; // INPUT
			this->LLDMA0TXDSTRDYN = LLDMA0TXDSTRDYN; // INPUT
			this->LLDMA1RSTENGINEREQ = LLDMA1RSTENGINEREQ; // INPUT
			this->LLDMA1RXD = LLDMA1RXD; // INPUT
			this->LLDMA1RXEOFN = LLDMA1RXEOFN; // INPUT
			this->LLDMA1RXEOPN = LLDMA1RXEOPN; // INPUT
			this->LLDMA1RXREM = LLDMA1RXREM; // INPUT
			this->LLDMA1RXSOFN = LLDMA1RXSOFN; // INPUT
			this->LLDMA1RXSOPN = LLDMA1RXSOPN; // INPUT
			this->LLDMA1RXSRCRDYN = LLDMA1RXSRCRDYN; // INPUT
			this->LLDMA1TXDSTRDYN = LLDMA1TXDSTRDYN; // INPUT
			this->LLDMA2RSTENGINEREQ = LLDMA2RSTENGINEREQ; // INPUT
			this->LLDMA2RXD = LLDMA2RXD; // INPUT
			this->LLDMA2RXEOFN = LLDMA2RXEOFN; // INPUT
			this->LLDMA2RXEOPN = LLDMA2RXEOPN; // INPUT
			this->LLDMA2RXREM = LLDMA2RXREM; // INPUT
			this->LLDMA2RXSOFN = LLDMA2RXSOFN; // INPUT
			this->LLDMA2RXSOPN = LLDMA2RXSOPN; // INPUT
			this->LLDMA2RXSRCRDYN = LLDMA2RXSRCRDYN; // INPUT
			this->LLDMA2TXDSTRDYN = LLDMA2TXDSTRDYN; // INPUT
			this->LLDMA3RSTENGINEREQ = LLDMA3RSTENGINEREQ; // INPUT
			this->LLDMA3RXD = LLDMA3RXD; // INPUT
			this->LLDMA3RXEOFN = LLDMA3RXEOFN; // INPUT
			this->LLDMA3RXEOPN = LLDMA3RXEOPN; // INPUT
			this->LLDMA3RXREM = LLDMA3RXREM; // INPUT
			this->LLDMA3RXSOFN = LLDMA3RXSOFN; // INPUT
			this->LLDMA3RXSOPN = LLDMA3RXSOPN; // INPUT
			this->LLDMA3RXSRCRDYN = LLDMA3RXSRCRDYN; // INPUT
			this->LLDMA3TXDSTRDYN = LLDMA3TXDSTRDYN; // INPUT
			this->MCMIADDRREADYTOACCEPT = MCMIADDRREADYTOACCEPT; // INPUT
			this->MCMIREADDATA = MCMIREADDATA; // INPUT
			this->MCMIREADDATAERR = MCMIREADDATAERR; // INPUT
			this->MCMIREADDATAVALID = MCMIREADDATAVALID; // INPUT
			this->PLBPPCMADDRACK = PLBPPCMADDRACK; // INPUT
			this->PLBPPCMMBUSY = PLBPPCMMBUSY; // INPUT
			this->PLBPPCMMIRQ = PLBPPCMMIRQ; // INPUT
			this->PLBPPCMMRDERR = PLBPPCMMRDERR; // INPUT
			this->PLBPPCMMWRERR = PLBPPCMMWRERR; // INPUT
			this->PLBPPCMRDBTERM = PLBPPCMRDBTERM; // INPUT
			this->PLBPPCMRDDACK = PLBPPCMRDDACK; // INPUT
			this->PLBPPCMRDDBUS = PLBPPCMRDDBUS; // INPUT
			this->PLBPPCMRDPENDPRI = PLBPPCMRDPENDPRI; // INPUT
			this->PLBPPCMRDPENDREQ = PLBPPCMRDPENDREQ; // INPUT
			this->PLBPPCMRDWDADDR = PLBPPCMRDWDADDR; // INPUT
			this->PLBPPCMREARBITRATE = PLBPPCMREARBITRATE; // INPUT
			this->PLBPPCMREQPRI = PLBPPCMREQPRI; // INPUT
			this->PLBPPCMSSIZE = PLBPPCMSSIZE; // INPUT
			this->PLBPPCMTIMEOUT = PLBPPCMTIMEOUT; // INPUT
			this->PLBPPCMWRBTERM = PLBPPCMWRBTERM; // INPUT
			this->PLBPPCMWRDACK = PLBPPCMWRDACK; // INPUT
			this->PLBPPCMWRPENDPRI = PLBPPCMWRPENDPRI; // INPUT
			this->PLBPPCMWRPENDREQ = PLBPPCMWRPENDREQ; // INPUT
			this->PLBPPCS0ABORT = PLBPPCS0ABORT; // INPUT
			this->PLBPPCS0ABUS = PLBPPCS0ABUS; // INPUT
			this->PLBPPCS0BE = PLBPPCS0BE; // INPUT
			this->PLBPPCS0BUSLOCK = PLBPPCS0BUSLOCK; // INPUT
			this->PLBPPCS0LOCKERR = PLBPPCS0LOCKERR; // INPUT
			this->PLBPPCS0MASTERID = PLBPPCS0MASTERID; // INPUT
			this->PLBPPCS0MSIZE = PLBPPCS0MSIZE; // INPUT
			this->PLBPPCS0PAVALID = PLBPPCS0PAVALID; // INPUT
			this->PLBPPCS0RDBURST = PLBPPCS0RDBURST; // INPUT
			this->PLBPPCS0RDPENDPRI = PLBPPCS0RDPENDPRI; // INPUT
			this->PLBPPCS0RDPENDREQ = PLBPPCS0RDPENDREQ; // INPUT
			this->PLBPPCS0RDPRIM = PLBPPCS0RDPRIM; // INPUT
			this->PLBPPCS0REQPRI = PLBPPCS0REQPRI; // INPUT
			this->PLBPPCS0RNW = PLBPPCS0RNW; // INPUT
			this->PLBPPCS0SAVALID = PLBPPCS0SAVALID; // INPUT
			this->PLBPPCS0SIZE = PLBPPCS0SIZE; // INPUT
			this->PLBPPCS0TATTRIBUTE = PLBPPCS0TATTRIBUTE; // INPUT
			this->PLBPPCS0TYPE = PLBPPCS0TYPE; // INPUT
			this->PLBPPCS0UABUS = PLBPPCS0UABUS; // INPUT
			this->PLBPPCS0WRBURST = PLBPPCS0WRBURST; // INPUT
			this->PLBPPCS0WRDBUS = PLBPPCS0WRDBUS; // INPUT
			this->PLBPPCS0WRPENDPRI = PLBPPCS0WRPENDPRI; // INPUT
			this->PLBPPCS0WRPENDREQ = PLBPPCS0WRPENDREQ; // INPUT
			this->PLBPPCS0WRPRIM = PLBPPCS0WRPRIM; // INPUT
			this->PLBPPCS1ABORT = PLBPPCS1ABORT; // INPUT
			this->PLBPPCS1ABUS = PLBPPCS1ABUS; // INPUT
			this->PLBPPCS1BE = PLBPPCS1BE; // INPUT
			this->PLBPPCS1BUSLOCK = PLBPPCS1BUSLOCK; // INPUT
			this->PLBPPCS1LOCKERR = PLBPPCS1LOCKERR; // INPUT
			this->PLBPPCS1MASTERID = PLBPPCS1MASTERID; // INPUT
			this->PLBPPCS1MSIZE = PLBPPCS1MSIZE; // INPUT
			this->PLBPPCS1PAVALID = PLBPPCS1PAVALID; // INPUT
			this->PLBPPCS1RDBURST = PLBPPCS1RDBURST; // INPUT
			this->PLBPPCS1RDPENDPRI = PLBPPCS1RDPENDPRI; // INPUT
			this->PLBPPCS1RDPENDREQ = PLBPPCS1RDPENDREQ; // INPUT
			this->PLBPPCS1RDPRIM = PLBPPCS1RDPRIM; // INPUT
			this->PLBPPCS1REQPRI = PLBPPCS1REQPRI; // INPUT
			this->PLBPPCS1RNW = PLBPPCS1RNW; // INPUT
			this->PLBPPCS1SAVALID = PLBPPCS1SAVALID; // INPUT
			this->PLBPPCS1SIZE = PLBPPCS1SIZE; // INPUT
			this->PLBPPCS1TATTRIBUTE = PLBPPCS1TATTRIBUTE; // INPUT
			this->PLBPPCS1TYPE = PLBPPCS1TYPE; // INPUT
			this->PLBPPCS1UABUS = PLBPPCS1UABUS; // INPUT
			this->PLBPPCS1WRBURST = PLBPPCS1WRBURST; // INPUT
			this->PLBPPCS1WRDBUS = PLBPPCS1WRDBUS; // INPUT
			this->PLBPPCS1WRPENDPRI = PLBPPCS1WRPENDPRI; // INPUT
			this->PLBPPCS1WRPENDREQ = PLBPPCS1WRPENDREQ; // INPUT
			this->PLBPPCS1WRPRIM = PLBPPCS1WRPRIM; // INPUT
			this->RSTC440RESETCHIP = RSTC440RESETCHIP; // INPUT
			this->RSTC440RESETCORE = RSTC440RESETCORE; // INPUT
			this->RSTC440RESETSYSTEM = RSTC440RESETSYSTEM; // INPUT
			this->TIEC440DCURDLDCACHEPLBPRIO = TIEC440DCURDLDCACHEPLBPRIO; // INPUT
			this->TIEC440DCURDNONCACHEPLBPRIO = TIEC440DCURDNONCACHEPLBPRIO; // INPUT
			this->TIEC440DCURDTOUCHPLBPRIO = TIEC440DCURDTOUCHPLBPRIO; // INPUT
			this->TIEC440DCURDURGENTPLBPRIO = TIEC440DCURDURGENTPLBPRIO; // INPUT
			this->TIEC440DCUWRFLUSHPLBPRIO = TIEC440DCUWRFLUSHPLBPRIO; // INPUT
			this->TIEC440DCUWRSTOREPLBPRIO = TIEC440DCUWRSTOREPLBPRIO; // INPUT
			this->TIEC440DCUWRURGENTPLBPRIO = TIEC440DCUWRURGENTPLBPRIO; // INPUT
			this->TIEC440ENDIANRESET = TIEC440ENDIANRESET; // INPUT
			this->TIEC440ERPNRESET = TIEC440ERPNRESET; // INPUT
			this->TIEC440ICURDFETCHPLBPRIO = TIEC440ICURDFETCHPLBPRIO; // INPUT
			this->TIEC440ICURDSPECPLBPRIO = TIEC440ICURDSPECPLBPRIO; // INPUT
			this->TIEC440ICURDTOUCHPLBPRIO = TIEC440ICURDTOUCHPLBPRIO; // INPUT
			this->TIEC440PIR = TIEC440PIR; // INPUT
			this->TIEC440PVR = TIEC440PVR; // INPUT
			this->TIEC440USERRESET = TIEC440USERRESET; // INPUT
			this->TIEDCRBASEADDR = TIEDCRBASEADDR; // INPUT
			this->TRCC440TRACEDISABLE = TRCC440TRACEDISABLE; // INPUT
			this->TRCC440TRIGGEREVENTIN = TRCC440TRIGGEREVENTIN; // INPUT
		
			register_wait_on_event_nets();
		
		}
		
		void register_wait_on_event_nets(){
		// TODO
		}
		void calculate(int time){
		// TODO
		}
	};
	

}
