/******************************************************************************
 * Generated Cpp template for simulation primitives.
 * Author: Benedek Racz
 ******************************************************************************/

#ifndef X_PPC405_ADV_H
#define X_PPC405_ADV_H

#include "NetFlow.h"
#include "sim_types.h"
#include "Primitive.h"

namespace CPrimitives {
	
	class X_PPC405_ADV: public Primitive{

		//Verilog Parameters:
		parameter_string_t LOC;
		parameter_int_t in_delay;
		parameter_int_t out_delay;
		//Verilog Ports in definition order:
		NetFlow* APUFCMDECODED_A0_B; // net ID: APUFCMDECODED lsb: 0  msb: 0 OUTPUT
		NetFlow* APUFCMDECUDIVALID_A0_B; // net ID: APUFCMDECUDIVALID lsb: 0  msb: 0 OUTPUT
		NetFlow* APUFCMENDIAN_A0_B; // net ID: APUFCMENDIAN lsb: 0  msb: 0 OUTPUT
		NetFlow* APUFCMFLUSH_A0_B; // net ID: APUFCMFLUSH lsb: 0  msb: 0 OUTPUT
		NetFlow* APUFCMINSTRVALID_A0_B; // net ID: APUFCMINSTRVALID lsb: 0  msb: 0 OUTPUT
		NetFlow* APUFCMLOADDVALID_A0_B; // net ID: APUFCMLOADDVALID lsb: 0  msb: 0 OUTPUT
		NetFlow* APUFCMOPERANDVALID_A0_B; // net ID: APUFCMOPERANDVALID lsb: 0  msb: 0 OUTPUT
		NetFlow* APUFCMWRITEBACKOK_A0_B; // net ID: APUFCMWRITEBACKOK lsb: 0  msb: 0 OUTPUT
		NetFlow* APUFCMXERCA_A0_B; // net ID: APUFCMXERCA lsb: 0  msb: 0 OUTPUT
		NetFlow* C405CPMCORESLEEPREQ_A0_B; // net ID: C405CPMCORESLEEPREQ lsb: 0  msb: 0 OUTPUT
		NetFlow* C405CPMMSRCE_A0_B; // net ID: C405CPMMSRCE lsb: 0  msb: 0 OUTPUT
		NetFlow* C405CPMMSREE_A0_B; // net ID: C405CPMMSREE lsb: 0  msb: 0 OUTPUT
		NetFlow* C405CPMTIMERIRQ_A0_B; // net ID: C405CPMTIMERIRQ lsb: 0  msb: 0 OUTPUT
		NetFlow* C405CPMTIMERRESETREQ_A0_B; // net ID: C405CPMTIMERRESETREQ lsb: 0  msb: 0 OUTPUT
		NetFlow* C405DBGLOADDATAONAPUDBUS_A0_B; // net ID: C405DBGLOADDATAONAPUDBUS lsb: 0  msb: 0 OUTPUT
		NetFlow* C405DBGMSRWE_A0_B; // net ID: C405DBGMSRWE lsb: 0  msb: 0 OUTPUT
		NetFlow* C405DBGSTOPACK_A0_B; // net ID: C405DBGSTOPACK lsb: 0  msb: 0 OUTPUT
		NetFlow* C405DBGWBCOMPLETE_A0_B; // net ID: C405DBGWBCOMPLETE lsb: 0  msb: 0 OUTPUT
		NetFlow* C405DBGWBFULL_A0_B; // net ID: C405DBGWBFULL lsb: 0  msb: 0 OUTPUT
		NetFlow* C405JTGCAPTUREDR_A0_B; // net ID: C405JTGCAPTUREDR lsb: 0  msb: 0 OUTPUT
		NetFlow* C405JTGEXTEST_A0_B; // net ID: C405JTGEXTEST lsb: 0  msb: 0 OUTPUT
		NetFlow* C405JTGPGMOUT_A0_B; // net ID: C405JTGPGMOUT lsb: 0  msb: 0 OUTPUT
		NetFlow* C405JTGSHIFTDR_A0_B; // net ID: C405JTGSHIFTDR lsb: 0  msb: 0 OUTPUT
		NetFlow* C405JTGTDO_A0_B; // net ID: C405JTGTDO lsb: 0  msb: 0 OUTPUT
		NetFlow* C405JTGTDOEN_A0_B; // net ID: C405JTGTDOEN lsb: 0  msb: 0 OUTPUT
		NetFlow* C405JTGUPDATEDR_A0_B; // net ID: C405JTGUPDATEDR lsb: 0  msb: 0 OUTPUT
		NetFlow* C405PLBDCUABORT_A0_B; // net ID: C405PLBDCUABORT lsb: 0  msb: 0 OUTPUT
		NetFlow* C405PLBDCUCACHEABLE_A0_B; // net ID: C405PLBDCUCACHEABLE lsb: 0  msb: 0 OUTPUT
		NetFlow* C405PLBDCUGUARDED_A0_B; // net ID: C405PLBDCUGUARDED lsb: 0  msb: 0 OUTPUT
		NetFlow* C405PLBDCUREQUEST_A0_B; // net ID: C405PLBDCUREQUEST lsb: 0  msb: 0 OUTPUT
		NetFlow* C405PLBDCURNW_A0_B; // net ID: C405PLBDCURNW lsb: 0  msb: 0 OUTPUT
		NetFlow* C405PLBDCUSIZE2_A0_B; // net ID: C405PLBDCUSIZE2 lsb: 0  msb: 0 OUTPUT
		NetFlow* C405PLBDCUU0ATTR_A0_B; // net ID: C405PLBDCUU0ATTR lsb: 0  msb: 0 OUTPUT
		NetFlow* C405PLBDCUWRITETHRU_A0_B; // net ID: C405PLBDCUWRITETHRU lsb: 0  msb: 0 OUTPUT
		NetFlow* C405PLBICUABORT_A0_B; // net ID: C405PLBICUABORT lsb: 0  msb: 0 OUTPUT
		NetFlow* C405PLBICUCACHEABLE_A0_B; // net ID: C405PLBICUCACHEABLE lsb: 0  msb: 0 OUTPUT
		NetFlow* C405PLBICUREQUEST_A0_B; // net ID: C405PLBICUREQUEST lsb: 0  msb: 0 OUTPUT
		NetFlow* C405PLBICUU0ATTR_A0_B; // net ID: C405PLBICUU0ATTR lsb: 0  msb: 0 OUTPUT
		NetFlow* C405RSTCHIPRESETREQ_A0_B; // net ID: C405RSTCHIPRESETREQ lsb: 0  msb: 0 OUTPUT
		NetFlow* C405RSTCORERESETREQ_A0_B; // net ID: C405RSTCORERESETREQ lsb: 0  msb: 0 OUTPUT
		NetFlow* C405RSTSYSRESETREQ_A0_B; // net ID: C405RSTSYSRESETREQ lsb: 0  msb: 0 OUTPUT
		NetFlow* C405TRCCYCLE_A0_B; // net ID: C405TRCCYCLE lsb: 0  msb: 0 OUTPUT
		NetFlow* C405TRCTRIGGEREVENTOUT_A0_B; // net ID: C405TRCTRIGGEREVENTOUT lsb: 0  msb: 0 OUTPUT
		NetFlow* C405XXXMACHINECHECK_A0_B; // net ID: C405XXXMACHINECHECK lsb: 0  msb: 0 OUTPUT
		NetFlow* DCREMACCLK_A0_B; // net ID: DCREMACCLK lsb: 0  msb: 0 OUTPUT
		NetFlow* DCREMACENABLER_A0_B; // net ID: DCREMACENABLER lsb: 0  msb: 0 OUTPUT
		NetFlow* DCREMACREAD_A0_B; // net ID: DCREMACREAD lsb: 0  msb: 0 OUTPUT
		NetFlow* DCREMACWRITE_A0_B; // net ID: DCREMACWRITE lsb: 0  msb: 0 OUTPUT
		NetFlow* DSOCMBRAMEN_A0_B; // net ID: DSOCMBRAMEN lsb: 0  msb: 0 OUTPUT
		NetFlow* DSOCMBUSY_A0_B; // net ID: DSOCMBUSY lsb: 0  msb: 0 OUTPUT
		NetFlow* DSOCMRDADDRVALID_A0_B; // net ID: DSOCMRDADDRVALID lsb: 0  msb: 0 OUTPUT
		NetFlow* DSOCMWRADDRVALID_A0_B; // net ID: DSOCMWRADDRVALID lsb: 0  msb: 0 OUTPUT
		NetFlow* EXTDCRREAD_A0_B; // net ID: EXTDCRREAD lsb: 0  msb: 0 OUTPUT
		NetFlow* EXTDCRWRITE_A0_B; // net ID: EXTDCRWRITE lsb: 0  msb: 0 OUTPUT
		NetFlow* ISOCMBRAMEN_A0_B; // net ID: ISOCMBRAMEN lsb: 0  msb: 0 OUTPUT
		NetFlow* ISOCMBRAMEVENWRITEEN_A0_B; // net ID: ISOCMBRAMEVENWRITEEN lsb: 0  msb: 0 OUTPUT
		NetFlow* ISOCMBRAMODDWRITEEN_A0_B; // net ID: ISOCMBRAMODDWRITEEN lsb: 0  msb: 0 OUTPUT
		NetFlow* ISOCMDCRBRAMEVENEN_A0_B; // net ID: ISOCMDCRBRAMEVENEN lsb: 0  msb: 0 OUTPUT
		NetFlow* ISOCMDCRBRAMODDEN_A0_B; // net ID: ISOCMDCRBRAMODDEN lsb: 0  msb: 0 OUTPUT
		NetFlow* ISOCMDCRBRAMRDSELECT_A0_B; // net ID: ISOCMDCRBRAMRDSELECT lsb: 0  msb: 0 OUTPUT
		NetFlow* BRAMDSOCMCLK_A0_B; // net ID: BRAMDSOCMCLK lsb: 0  msb: 0 INPUT
		NetFlow* BRAMISOCMCLK_A0_B; // net ID: BRAMISOCMCLK lsb: 0  msb: 0 INPUT
		NetFlow* CPMC405CLOCK_A0_B; // net ID: CPMC405CLOCK lsb: 0  msb: 0 INPUT
		NetFlow* CPMC405CORECLKINACTIVE_A0_B; // net ID: CPMC405CORECLKINACTIVE lsb: 0  msb: 0 INPUT
		NetFlow* CPMC405CPUCLKEN_A0_B; // net ID: CPMC405CPUCLKEN lsb: 0  msb: 0 INPUT
		NetFlow* CPMC405JTAGCLKEN_A0_B; // net ID: CPMC405JTAGCLKEN lsb: 0  msb: 0 INPUT
		NetFlow* CPMC405SYNCBYPASS_A0_B; // net ID: CPMC405SYNCBYPASS lsb: 0  msb: 0 INPUT
		NetFlow* CPMC405TIMERCLKEN_A0_B; // net ID: CPMC405TIMERCLKEN lsb: 0  msb: 0 INPUT
		NetFlow* CPMC405TIMERTICK_A0_B; // net ID: CPMC405TIMERTICK lsb: 0  msb: 0 INPUT
		NetFlow* CPMDCRCLK_A0_B; // net ID: CPMDCRCLK lsb: 0  msb: 0 INPUT
		NetFlow* CPMFCMCLK_A0_B; // net ID: CPMFCMCLK lsb: 0  msb: 0 INPUT
		NetFlow* DBGC405DEBUGHALT_A0_B; // net ID: DBGC405DEBUGHALT lsb: 0  msb: 0 INPUT
		NetFlow* DBGC405EXTBUSHOLDACK_A0_B; // net ID: DBGC405EXTBUSHOLDACK lsb: 0  msb: 0 INPUT
		NetFlow* DBGC405UNCONDDEBUGEVENT_A0_B; // net ID: DBGC405UNCONDDEBUGEVENT lsb: 0  msb: 0 INPUT
		NetFlow* DSOCMRWCOMPLETE_A0_B; // net ID: DSOCMRWCOMPLETE lsb: 0  msb: 0 INPUT
		NetFlow* EICC405CRITINPUTIRQ_A0_B; // net ID: EICC405CRITINPUTIRQ lsb: 0  msb: 0 INPUT
		NetFlow* EICC405EXTINPUTIRQ_A0_B; // net ID: EICC405EXTINPUTIRQ lsb: 0  msb: 0 INPUT
		NetFlow* EMACDCRACK_A0_B; // net ID: EMACDCRACK lsb: 0  msb: 0 INPUT
		NetFlow* EXTDCRACK_A0_B; // net ID: EXTDCRACK lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDCREN_A0_B; // net ID: FCMAPUDCDCREN lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDFORCEALIGN_A0_B; // net ID: FCMAPUDCDFORCEALIGN lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDFORCEBESTEERING_A0_B; // net ID: FCMAPUDCDFORCEBESTEERING lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDFPUOP_A0_B; // net ID: FCMAPUDCDFPUOP lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDGPRWRITE_A0_B; // net ID: FCMAPUDCDGPRWRITE lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDLDSTBYTE_A0_B; // net ID: FCMAPUDCDLDSTBYTE lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDLDSTDW_A0_B; // net ID: FCMAPUDCDLDSTDW lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDLDSTHW_A0_B; // net ID: FCMAPUDCDLDSTHW lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDLDSTQW_A0_B; // net ID: FCMAPUDCDLDSTQW lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDLDSTWD_A0_B; // net ID: FCMAPUDCDLDSTWD lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDLOAD_A0_B; // net ID: FCMAPUDCDLOAD lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDPRIVOP_A0_B; // net ID: FCMAPUDCDPRIVOP lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDRAEN_A0_B; // net ID: FCMAPUDCDRAEN lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDRBEN_A0_B; // net ID: FCMAPUDCDRBEN lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDSTORE_A0_B; // net ID: FCMAPUDCDSTORE lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDTRAPBE_A0_B; // net ID: FCMAPUDCDTRAPBE lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDTRAPLE_A0_B; // net ID: FCMAPUDCDTRAPLE lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDUPDATE_A0_B; // net ID: FCMAPUDCDUPDATE lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDXERCAEN_A0_B; // net ID: FCMAPUDCDXERCAEN lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDXEROVEN_A0_B; // net ID: FCMAPUDCDXEROVEN lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDECODEBUSY_A0_B; // net ID: FCMAPUDECODEBUSY lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDONE_A0_B; // net ID: FCMAPUDONE lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUEXCEPTION_A0_B; // net ID: FCMAPUEXCEPTION lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUEXEBLOCKINGMCO_A0_B; // net ID: FCMAPUEXEBLOCKINGMCO lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUEXENONBLOCKINGMCO_A0_B; // net ID: FCMAPUEXENONBLOCKINGMCO lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUINSTRACK_A0_B; // net ID: FCMAPUINSTRACK lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPULOADWAIT_A0_B; // net ID: FCMAPULOADWAIT lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPURESULTVALID_A0_B; // net ID: FCMAPURESULTVALID lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUSLEEPNOTREADY_A0_B; // net ID: FCMAPUSLEEPNOTREADY lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUXERCA_A0_B; // net ID: FCMAPUXERCA lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUXEROV_A0_B; // net ID: FCMAPUXEROV lsb: 0  msb: 0 INPUT
		NetFlow* JTGC405BNDSCANTDO_A0_B; // net ID: JTGC405BNDSCANTDO lsb: 0  msb: 0 INPUT
		NetFlow* JTGC405TCK_A0_B; // net ID: JTGC405TCK lsb: 0  msb: 0 INPUT
		NetFlow* JTGC405TDI_A0_B; // net ID: JTGC405TDI lsb: 0  msb: 0 INPUT
		NetFlow* JTGC405TMS_A0_B; // net ID: JTGC405TMS lsb: 0  msb: 0 INPUT
		NetFlow* JTGC405TRSTNEG_A0_B; // net ID: JTGC405TRSTNEG lsb: 0  msb: 0 INPUT
		NetFlow* MCBCPUCLKEN_A0_B; // net ID: MCBCPUCLKEN lsb: 0  msb: 0 INPUT
		NetFlow* MCBJTAGEN_A0_B; // net ID: MCBJTAGEN lsb: 0  msb: 0 INPUT
		NetFlow* MCBTIMEREN_A0_B; // net ID: MCBTIMEREN lsb: 0  msb: 0 INPUT
		NetFlow* MCPPCRST_A0_B; // net ID: MCPPCRST lsb: 0  msb: 0 INPUT
		NetFlow* PLBC405DCUADDRACK_A0_B; // net ID: PLBC405DCUADDRACK lsb: 0  msb: 0 INPUT
		NetFlow* PLBC405DCUBUSY_A0_B; // net ID: PLBC405DCUBUSY lsb: 0  msb: 0 INPUT
		NetFlow* PLBC405DCUERR_A0_B; // net ID: PLBC405DCUERR lsb: 0  msb: 0 INPUT
		NetFlow* PLBC405DCURDDACK_A0_B; // net ID: PLBC405DCURDDACK lsb: 0  msb: 0 INPUT
		NetFlow* PLBC405DCUSSIZE1_A0_B; // net ID: PLBC405DCUSSIZE1 lsb: 0  msb: 0 INPUT
		NetFlow* PLBC405DCUWRDACK_A0_B; // net ID: PLBC405DCUWRDACK lsb: 0  msb: 0 INPUT
		NetFlow* PLBC405ICUADDRACK_A0_B; // net ID: PLBC405ICUADDRACK lsb: 0  msb: 0 INPUT
		NetFlow* PLBC405ICUBUSY_A0_B; // net ID: PLBC405ICUBUSY lsb: 0  msb: 0 INPUT
		NetFlow* PLBC405ICUERR_A0_B; // net ID: PLBC405ICUERR lsb: 0  msb: 0 INPUT
		NetFlow* PLBC405ICURDDACK_A0_B; // net ID: PLBC405ICURDDACK lsb: 0  msb: 0 INPUT
		NetFlow* PLBC405ICUSSIZE1_A0_B; // net ID: PLBC405ICUSSIZE1 lsb: 0  msb: 0 INPUT
		NetFlow* PLBCLK_A0_B; // net ID: PLBCLK lsb: 0  msb: 0 INPUT
		NetFlow* RSTC405RESETCHIP_A0_B; // net ID: RSTC405RESETCHIP lsb: 0  msb: 0 INPUT
		NetFlow* RSTC405RESETCORE_A0_B; // net ID: RSTC405RESETCORE lsb: 0  msb: 0 INPUT
		NetFlow* RSTC405RESETSYS_A0_B; // net ID: RSTC405RESETSYS lsb: 0  msb: 0 INPUT
		NetFlow* TIEC405DETERMINISTICMULT_A0_B; // net ID: TIEC405DETERMINISTICMULT lsb: 0  msb: 0 INPUT
		NetFlow* TIEC405DISOPERANDFWD_A0_B; // net ID: TIEC405DISOPERANDFWD lsb: 0  msb: 0 INPUT
		NetFlow* TIEC405MMUEN_A0_B; // net ID: TIEC405MMUEN lsb: 0  msb: 0 INPUT
		NetFlow* TIEPVRBIT10_A0_B; // net ID: TIEPVRBIT10 lsb: 0  msb: 0 INPUT
		NetFlow* TIEPVRBIT11_A0_B; // net ID: TIEPVRBIT11 lsb: 0  msb: 0 INPUT
		NetFlow* TIEPVRBIT28_A0_B; // net ID: TIEPVRBIT28 lsb: 0  msb: 0 INPUT
		NetFlow* TIEPVRBIT29_A0_B; // net ID: TIEPVRBIT29 lsb: 0  msb: 0 INPUT
		NetFlow* TIEPVRBIT30_A0_B; // net ID: TIEPVRBIT30 lsb: 0  msb: 0 INPUT
		NetFlow* TIEPVRBIT31_A0_B; // net ID: TIEPVRBIT31 lsb: 0  msb: 0 INPUT
		NetFlow* TIEPVRBIT8_A0_B; // net ID: TIEPVRBIT8 lsb: 0  msb: 0 INPUT
		NetFlow* TIEPVRBIT9_A0_B; // net ID: TIEPVRBIT9 lsb: 0  msb: 0 INPUT
		NetFlow* TRCC405TRACEDISABLE_A0_B; // net ID: TRCC405TRACEDISABLE lsb: 0  msb: 0 INPUT
		NetFlow* TRCC405TRIGGEREVENTIN_A0_B; // net ID: TRCC405TRIGGEREVENTIN lsb: 0  msb: 0 INPUT
		
		public: X_PPC405_ADV(
			const char * name,
			//Verilog Parameters:
			parameter_string_t LOC, // Default: "UNPLACED"
			parameter_int_t in_delay, // Default: 1
			parameter_int_t out_delay, // Default: 0
			//Verilog Ports in definition order:
			NetFlow* APUFCMDECODED_A0_B, // net ID: APUFCMDECODED lsb: 0  msb: 0 OUTPUT
			NetFlow* APUFCMDECUDIVALID_A0_B, // net ID: APUFCMDECUDIVALID lsb: 0  msb: 0 OUTPUT
			NetFlow* APUFCMENDIAN_A0_B, // net ID: APUFCMENDIAN lsb: 0  msb: 0 OUTPUT
			NetFlow* APUFCMFLUSH_A0_B, // net ID: APUFCMFLUSH lsb: 0  msb: 0 OUTPUT
			NetFlow* APUFCMINSTRVALID_A0_B, // net ID: APUFCMINSTRVALID lsb: 0  msb: 0 OUTPUT
			NetFlow* APUFCMLOADDVALID_A0_B, // net ID: APUFCMLOADDVALID lsb: 0  msb: 0 OUTPUT
			NetFlow* APUFCMOPERANDVALID_A0_B, // net ID: APUFCMOPERANDVALID lsb: 0  msb: 0 OUTPUT
			NetFlow* APUFCMWRITEBACKOK_A0_B, // net ID: APUFCMWRITEBACKOK lsb: 0  msb: 0 OUTPUT
			NetFlow* APUFCMXERCA_A0_B, // net ID: APUFCMXERCA lsb: 0  msb: 0 OUTPUT
			NetFlow* C405CPMCORESLEEPREQ_A0_B, // net ID: C405CPMCORESLEEPREQ lsb: 0  msb: 0 OUTPUT
			NetFlow* C405CPMMSRCE_A0_B, // net ID: C405CPMMSRCE lsb: 0  msb: 0 OUTPUT
			NetFlow* C405CPMMSREE_A0_B, // net ID: C405CPMMSREE lsb: 0  msb: 0 OUTPUT
			NetFlow* C405CPMTIMERIRQ_A0_B, // net ID: C405CPMTIMERIRQ lsb: 0  msb: 0 OUTPUT
			NetFlow* C405CPMTIMERRESETREQ_A0_B, // net ID: C405CPMTIMERRESETREQ lsb: 0  msb: 0 OUTPUT
			NetFlow* C405DBGLOADDATAONAPUDBUS_A0_B, // net ID: C405DBGLOADDATAONAPUDBUS lsb: 0  msb: 0 OUTPUT
			NetFlow* C405DBGMSRWE_A0_B, // net ID: C405DBGMSRWE lsb: 0  msb: 0 OUTPUT
			NetFlow* C405DBGSTOPACK_A0_B, // net ID: C405DBGSTOPACK lsb: 0  msb: 0 OUTPUT
			NetFlow* C405DBGWBCOMPLETE_A0_B, // net ID: C405DBGWBCOMPLETE lsb: 0  msb: 0 OUTPUT
			NetFlow* C405DBGWBFULL_A0_B, // net ID: C405DBGWBFULL lsb: 0  msb: 0 OUTPUT
			NetFlow* C405JTGCAPTUREDR_A0_B, // net ID: C405JTGCAPTUREDR lsb: 0  msb: 0 OUTPUT
			NetFlow* C405JTGEXTEST_A0_B, // net ID: C405JTGEXTEST lsb: 0  msb: 0 OUTPUT
			NetFlow* C405JTGPGMOUT_A0_B, // net ID: C405JTGPGMOUT lsb: 0  msb: 0 OUTPUT
			NetFlow* C405JTGSHIFTDR_A0_B, // net ID: C405JTGSHIFTDR lsb: 0  msb: 0 OUTPUT
			NetFlow* C405JTGTDO_A0_B, // net ID: C405JTGTDO lsb: 0  msb: 0 OUTPUT
			NetFlow* C405JTGTDOEN_A0_B, // net ID: C405JTGTDOEN lsb: 0  msb: 0 OUTPUT
			NetFlow* C405JTGUPDATEDR_A0_B, // net ID: C405JTGUPDATEDR lsb: 0  msb: 0 OUTPUT
			NetFlow* C405PLBDCUABORT_A0_B, // net ID: C405PLBDCUABORT lsb: 0  msb: 0 OUTPUT
			NetFlow* C405PLBDCUCACHEABLE_A0_B, // net ID: C405PLBDCUCACHEABLE lsb: 0  msb: 0 OUTPUT
			NetFlow* C405PLBDCUGUARDED_A0_B, // net ID: C405PLBDCUGUARDED lsb: 0  msb: 0 OUTPUT
			NetFlow* C405PLBDCUREQUEST_A0_B, // net ID: C405PLBDCUREQUEST lsb: 0  msb: 0 OUTPUT
			NetFlow* C405PLBDCURNW_A0_B, // net ID: C405PLBDCURNW lsb: 0  msb: 0 OUTPUT
			NetFlow* C405PLBDCUSIZE2_A0_B, // net ID: C405PLBDCUSIZE2 lsb: 0  msb: 0 OUTPUT
			NetFlow* C405PLBDCUU0ATTR_A0_B, // net ID: C405PLBDCUU0ATTR lsb: 0  msb: 0 OUTPUT
			NetFlow* C405PLBDCUWRITETHRU_A0_B, // net ID: C405PLBDCUWRITETHRU lsb: 0  msb: 0 OUTPUT
			NetFlow* C405PLBICUABORT_A0_B, // net ID: C405PLBICUABORT lsb: 0  msb: 0 OUTPUT
			NetFlow* C405PLBICUCACHEABLE_A0_B, // net ID: C405PLBICUCACHEABLE lsb: 0  msb: 0 OUTPUT
			NetFlow* C405PLBICUREQUEST_A0_B, // net ID: C405PLBICUREQUEST lsb: 0  msb: 0 OUTPUT
			NetFlow* C405PLBICUU0ATTR_A0_B, // net ID: C405PLBICUU0ATTR lsb: 0  msb: 0 OUTPUT
			NetFlow* C405RSTCHIPRESETREQ_A0_B, // net ID: C405RSTCHIPRESETREQ lsb: 0  msb: 0 OUTPUT
			NetFlow* C405RSTCORERESETREQ_A0_B, // net ID: C405RSTCORERESETREQ lsb: 0  msb: 0 OUTPUT
			NetFlow* C405RSTSYSRESETREQ_A0_B, // net ID: C405RSTSYSRESETREQ lsb: 0  msb: 0 OUTPUT
			NetFlow* C405TRCCYCLE_A0_B, // net ID: C405TRCCYCLE lsb: 0  msb: 0 OUTPUT
			NetFlow* C405TRCTRIGGEREVENTOUT_A0_B, // net ID: C405TRCTRIGGEREVENTOUT lsb: 0  msb: 0 OUTPUT
			NetFlow* C405XXXMACHINECHECK_A0_B, // net ID: C405XXXMACHINECHECK lsb: 0  msb: 0 OUTPUT
			NetFlow* DCREMACCLK_A0_B, // net ID: DCREMACCLK lsb: 0  msb: 0 OUTPUT
			NetFlow* DCREMACENABLER_A0_B, // net ID: DCREMACENABLER lsb: 0  msb: 0 OUTPUT
			NetFlow* DCREMACREAD_A0_B, // net ID: DCREMACREAD lsb: 0  msb: 0 OUTPUT
			NetFlow* DCREMACWRITE_A0_B, // net ID: DCREMACWRITE lsb: 0  msb: 0 OUTPUT
			NetFlow* DSOCMBRAMEN_A0_B, // net ID: DSOCMBRAMEN lsb: 0  msb: 0 OUTPUT
			NetFlow* DSOCMBUSY_A0_B, // net ID: DSOCMBUSY lsb: 0  msb: 0 OUTPUT
			NetFlow* DSOCMRDADDRVALID_A0_B, // net ID: DSOCMRDADDRVALID lsb: 0  msb: 0 OUTPUT
			NetFlow* DSOCMWRADDRVALID_A0_B, // net ID: DSOCMWRADDRVALID lsb: 0  msb: 0 OUTPUT
			NetFlow* EXTDCRREAD_A0_B, // net ID: EXTDCRREAD lsb: 0  msb: 0 OUTPUT
			NetFlow* EXTDCRWRITE_A0_B, // net ID: EXTDCRWRITE lsb: 0  msb: 0 OUTPUT
			NetFlow* ISOCMBRAMEN_A0_B, // net ID: ISOCMBRAMEN lsb: 0  msb: 0 OUTPUT
			NetFlow* ISOCMBRAMEVENWRITEEN_A0_B, // net ID: ISOCMBRAMEVENWRITEEN lsb: 0  msb: 0 OUTPUT
			NetFlow* ISOCMBRAMODDWRITEEN_A0_B, // net ID: ISOCMBRAMODDWRITEEN lsb: 0  msb: 0 OUTPUT
			NetFlow* ISOCMDCRBRAMEVENEN_A0_B, // net ID: ISOCMDCRBRAMEVENEN lsb: 0  msb: 0 OUTPUT
			NetFlow* ISOCMDCRBRAMODDEN_A0_B, // net ID: ISOCMDCRBRAMODDEN lsb: 0  msb: 0 OUTPUT
			NetFlow* ISOCMDCRBRAMRDSELECT_A0_B, // net ID: ISOCMDCRBRAMRDSELECT lsb: 0  msb: 0 OUTPUT
			NetFlow* BRAMDSOCMCLK_A0_B, // net ID: BRAMDSOCMCLK lsb: 0  msb: 0 INPUT
			NetFlow* BRAMISOCMCLK_A0_B, // net ID: BRAMISOCMCLK lsb: 0  msb: 0 INPUT
			NetFlow* CPMC405CLOCK_A0_B, // net ID: CPMC405CLOCK lsb: 0  msb: 0 INPUT
			NetFlow* CPMC405CORECLKINACTIVE_A0_B, // net ID: CPMC405CORECLKINACTIVE lsb: 0  msb: 0 INPUT
			NetFlow* CPMC405CPUCLKEN_A0_B, // net ID: CPMC405CPUCLKEN lsb: 0  msb: 0 INPUT
			NetFlow* CPMC405JTAGCLKEN_A0_B, // net ID: CPMC405JTAGCLKEN lsb: 0  msb: 0 INPUT
			NetFlow* CPMC405SYNCBYPASS_A0_B, // net ID: CPMC405SYNCBYPASS lsb: 0  msb: 0 INPUT
			NetFlow* CPMC405TIMERCLKEN_A0_B, // net ID: CPMC405TIMERCLKEN lsb: 0  msb: 0 INPUT
			NetFlow* CPMC405TIMERTICK_A0_B, // net ID: CPMC405TIMERTICK lsb: 0  msb: 0 INPUT
			NetFlow* CPMDCRCLK_A0_B, // net ID: CPMDCRCLK lsb: 0  msb: 0 INPUT
			NetFlow* CPMFCMCLK_A0_B, // net ID: CPMFCMCLK lsb: 0  msb: 0 INPUT
			NetFlow* DBGC405DEBUGHALT_A0_B, // net ID: DBGC405DEBUGHALT lsb: 0  msb: 0 INPUT
			NetFlow* DBGC405EXTBUSHOLDACK_A0_B, // net ID: DBGC405EXTBUSHOLDACK lsb: 0  msb: 0 INPUT
			NetFlow* DBGC405UNCONDDEBUGEVENT_A0_B, // net ID: DBGC405UNCONDDEBUGEVENT lsb: 0  msb: 0 INPUT
			NetFlow* DSOCMRWCOMPLETE_A0_B, // net ID: DSOCMRWCOMPLETE lsb: 0  msb: 0 INPUT
			NetFlow* EICC405CRITINPUTIRQ_A0_B, // net ID: EICC405CRITINPUTIRQ lsb: 0  msb: 0 INPUT
			NetFlow* EICC405EXTINPUTIRQ_A0_B, // net ID: EICC405EXTINPUTIRQ lsb: 0  msb: 0 INPUT
			NetFlow* EMACDCRACK_A0_B, // net ID: EMACDCRACK lsb: 0  msb: 0 INPUT
			NetFlow* EXTDCRACK_A0_B, // net ID: EXTDCRACK lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDCREN_A0_B, // net ID: FCMAPUDCDCREN lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDFORCEALIGN_A0_B, // net ID: FCMAPUDCDFORCEALIGN lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDFORCEBESTEERING_A0_B, // net ID: FCMAPUDCDFORCEBESTEERING lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDFPUOP_A0_B, // net ID: FCMAPUDCDFPUOP lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDGPRWRITE_A0_B, // net ID: FCMAPUDCDGPRWRITE lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDLDSTBYTE_A0_B, // net ID: FCMAPUDCDLDSTBYTE lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDLDSTDW_A0_B, // net ID: FCMAPUDCDLDSTDW lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDLDSTHW_A0_B, // net ID: FCMAPUDCDLDSTHW lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDLDSTQW_A0_B, // net ID: FCMAPUDCDLDSTQW lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDLDSTWD_A0_B, // net ID: FCMAPUDCDLDSTWD lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDLOAD_A0_B, // net ID: FCMAPUDCDLOAD lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDPRIVOP_A0_B, // net ID: FCMAPUDCDPRIVOP lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDRAEN_A0_B, // net ID: FCMAPUDCDRAEN lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDRBEN_A0_B, // net ID: FCMAPUDCDRBEN lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDSTORE_A0_B, // net ID: FCMAPUDCDSTORE lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDTRAPBE_A0_B, // net ID: FCMAPUDCDTRAPBE lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDTRAPLE_A0_B, // net ID: FCMAPUDCDTRAPLE lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDUPDATE_A0_B, // net ID: FCMAPUDCDUPDATE lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDXERCAEN_A0_B, // net ID: FCMAPUDCDXERCAEN lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDXEROVEN_A0_B, // net ID: FCMAPUDCDXEROVEN lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDECODEBUSY_A0_B, // net ID: FCMAPUDECODEBUSY lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDONE_A0_B, // net ID: FCMAPUDONE lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUEXCEPTION_A0_B, // net ID: FCMAPUEXCEPTION lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUEXEBLOCKINGMCO_A0_B, // net ID: FCMAPUEXEBLOCKINGMCO lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUEXENONBLOCKINGMCO_A0_B, // net ID: FCMAPUEXENONBLOCKINGMCO lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUINSTRACK_A0_B, // net ID: FCMAPUINSTRACK lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPULOADWAIT_A0_B, // net ID: FCMAPULOADWAIT lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPURESULTVALID_A0_B, // net ID: FCMAPURESULTVALID lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUSLEEPNOTREADY_A0_B, // net ID: FCMAPUSLEEPNOTREADY lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUXERCA_A0_B, // net ID: FCMAPUXERCA lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUXEROV_A0_B, // net ID: FCMAPUXEROV lsb: 0  msb: 0 INPUT
			NetFlow* JTGC405BNDSCANTDO_A0_B, // net ID: JTGC405BNDSCANTDO lsb: 0  msb: 0 INPUT
			NetFlow* JTGC405TCK_A0_B, // net ID: JTGC405TCK lsb: 0  msb: 0 INPUT
			NetFlow* JTGC405TDI_A0_B, // net ID: JTGC405TDI lsb: 0  msb: 0 INPUT
			NetFlow* JTGC405TMS_A0_B, // net ID: JTGC405TMS lsb: 0  msb: 0 INPUT
			NetFlow* JTGC405TRSTNEG_A0_B, // net ID: JTGC405TRSTNEG lsb: 0  msb: 0 INPUT
			NetFlow* MCBCPUCLKEN_A0_B, // net ID: MCBCPUCLKEN lsb: 0  msb: 0 INPUT
			NetFlow* MCBJTAGEN_A0_B, // net ID: MCBJTAGEN lsb: 0  msb: 0 INPUT
			NetFlow* MCBTIMEREN_A0_B, // net ID: MCBTIMEREN lsb: 0  msb: 0 INPUT
			NetFlow* MCPPCRST_A0_B, // net ID: MCPPCRST lsb: 0  msb: 0 INPUT
			NetFlow* PLBC405DCUADDRACK_A0_B, // net ID: PLBC405DCUADDRACK lsb: 0  msb: 0 INPUT
			NetFlow* PLBC405DCUBUSY_A0_B, // net ID: PLBC405DCUBUSY lsb: 0  msb: 0 INPUT
			NetFlow* PLBC405DCUERR_A0_B, // net ID: PLBC405DCUERR lsb: 0  msb: 0 INPUT
			NetFlow* PLBC405DCURDDACK_A0_B, // net ID: PLBC405DCURDDACK lsb: 0  msb: 0 INPUT
			NetFlow* PLBC405DCUSSIZE1_A0_B, // net ID: PLBC405DCUSSIZE1 lsb: 0  msb: 0 INPUT
			NetFlow* PLBC405DCUWRDACK_A0_B, // net ID: PLBC405DCUWRDACK lsb: 0  msb: 0 INPUT
			NetFlow* PLBC405ICUADDRACK_A0_B, // net ID: PLBC405ICUADDRACK lsb: 0  msb: 0 INPUT
			NetFlow* PLBC405ICUBUSY_A0_B, // net ID: PLBC405ICUBUSY lsb: 0  msb: 0 INPUT
			NetFlow* PLBC405ICUERR_A0_B, // net ID: PLBC405ICUERR lsb: 0  msb: 0 INPUT
			NetFlow* PLBC405ICURDDACK_A0_B, // net ID: PLBC405ICURDDACK lsb: 0  msb: 0 INPUT
			NetFlow* PLBC405ICUSSIZE1_A0_B, // net ID: PLBC405ICUSSIZE1 lsb: 0  msb: 0 INPUT
			NetFlow* PLBCLK_A0_B, // net ID: PLBCLK lsb: 0  msb: 0 INPUT
			NetFlow* RSTC405RESETCHIP_A0_B, // net ID: RSTC405RESETCHIP lsb: 0  msb: 0 INPUT
			NetFlow* RSTC405RESETCORE_A0_B, // net ID: RSTC405RESETCORE lsb: 0  msb: 0 INPUT
			NetFlow* RSTC405RESETSYS_A0_B, // net ID: RSTC405RESETSYS lsb: 0  msb: 0 INPUT
			NetFlow* TIEC405DETERMINISTICMULT_A0_B, // net ID: TIEC405DETERMINISTICMULT lsb: 0  msb: 0 INPUT
			NetFlow* TIEC405DISOPERANDFWD_A0_B, // net ID: TIEC405DISOPERANDFWD lsb: 0  msb: 0 INPUT
			NetFlow* TIEC405MMUEN_A0_B, // net ID: TIEC405MMUEN lsb: 0  msb: 0 INPUT
			NetFlow* TIEPVRBIT10_A0_B, // net ID: TIEPVRBIT10 lsb: 0  msb: 0 INPUT
			NetFlow* TIEPVRBIT11_A0_B, // net ID: TIEPVRBIT11 lsb: 0  msb: 0 INPUT
			NetFlow* TIEPVRBIT28_A0_B, // net ID: TIEPVRBIT28 lsb: 0  msb: 0 INPUT
			NetFlow* TIEPVRBIT29_A0_B, // net ID: TIEPVRBIT29 lsb: 0  msb: 0 INPUT
			NetFlow* TIEPVRBIT30_A0_B, // net ID: TIEPVRBIT30 lsb: 0  msb: 0 INPUT
			NetFlow* TIEPVRBIT31_A0_B, // net ID: TIEPVRBIT31 lsb: 0  msb: 0 INPUT
			NetFlow* TIEPVRBIT8_A0_B, // net ID: TIEPVRBIT8 lsb: 0  msb: 0 INPUT
			NetFlow* TIEPVRBIT9_A0_B, // net ID: TIEPVRBIT9 lsb: 0  msb: 0 INPUT
			NetFlow* TRCC405TRACEDISABLE_A0_B, // net ID: TRCC405TRACEDISABLE lsb: 0  msb: 0 INPUT
			NetFlow* TRCC405TRIGGEREVENTIN_A0_B // net ID: TRCC405TRIGGEREVENTIN lsb: 0  msb: 0 INPUT
			):Primitive(name){
			
			// Assign parameters and ports: 
			//Verilog Parameters:
			this->LOC = LOC; // Default: "UNPLACED"
			this->in_delay = in_delay; // Default: 1
			this->out_delay = out_delay; // Default: 0
			//Verilog Ports in definition order:
			this->APUFCMDECODED_A0_B = APUFCMDECODED_A0_B; // net ID: APUFCMDECODED lsb: 0  msb: 0 OUTPUT
			this->APUFCMDECUDIVALID_A0_B = APUFCMDECUDIVALID_A0_B; // net ID: APUFCMDECUDIVALID lsb: 0  msb: 0 OUTPUT
			this->APUFCMENDIAN_A0_B = APUFCMENDIAN_A0_B; // net ID: APUFCMENDIAN lsb: 0  msb: 0 OUTPUT
			this->APUFCMFLUSH_A0_B = APUFCMFLUSH_A0_B; // net ID: APUFCMFLUSH lsb: 0  msb: 0 OUTPUT
			this->APUFCMINSTRVALID_A0_B = APUFCMINSTRVALID_A0_B; // net ID: APUFCMINSTRVALID lsb: 0  msb: 0 OUTPUT
			this->APUFCMLOADDVALID_A0_B = APUFCMLOADDVALID_A0_B; // net ID: APUFCMLOADDVALID lsb: 0  msb: 0 OUTPUT
			this->APUFCMOPERANDVALID_A0_B = APUFCMOPERANDVALID_A0_B; // net ID: APUFCMOPERANDVALID lsb: 0  msb: 0 OUTPUT
			this->APUFCMWRITEBACKOK_A0_B = APUFCMWRITEBACKOK_A0_B; // net ID: APUFCMWRITEBACKOK lsb: 0  msb: 0 OUTPUT
			this->APUFCMXERCA_A0_B = APUFCMXERCA_A0_B; // net ID: APUFCMXERCA lsb: 0  msb: 0 OUTPUT
			this->C405CPMCORESLEEPREQ_A0_B = C405CPMCORESLEEPREQ_A0_B; // net ID: C405CPMCORESLEEPREQ lsb: 0  msb: 0 OUTPUT
			this->C405CPMMSRCE_A0_B = C405CPMMSRCE_A0_B; // net ID: C405CPMMSRCE lsb: 0  msb: 0 OUTPUT
			this->C405CPMMSREE_A0_B = C405CPMMSREE_A0_B; // net ID: C405CPMMSREE lsb: 0  msb: 0 OUTPUT
			this->C405CPMTIMERIRQ_A0_B = C405CPMTIMERIRQ_A0_B; // net ID: C405CPMTIMERIRQ lsb: 0  msb: 0 OUTPUT
			this->C405CPMTIMERRESETREQ_A0_B = C405CPMTIMERRESETREQ_A0_B; // net ID: C405CPMTIMERRESETREQ lsb: 0  msb: 0 OUTPUT
			this->C405DBGLOADDATAONAPUDBUS_A0_B = C405DBGLOADDATAONAPUDBUS_A0_B; // net ID: C405DBGLOADDATAONAPUDBUS lsb: 0  msb: 0 OUTPUT
			this->C405DBGMSRWE_A0_B = C405DBGMSRWE_A0_B; // net ID: C405DBGMSRWE lsb: 0  msb: 0 OUTPUT
			this->C405DBGSTOPACK_A0_B = C405DBGSTOPACK_A0_B; // net ID: C405DBGSTOPACK lsb: 0  msb: 0 OUTPUT
			this->C405DBGWBCOMPLETE_A0_B = C405DBGWBCOMPLETE_A0_B; // net ID: C405DBGWBCOMPLETE lsb: 0  msb: 0 OUTPUT
			this->C405DBGWBFULL_A0_B = C405DBGWBFULL_A0_B; // net ID: C405DBGWBFULL lsb: 0  msb: 0 OUTPUT
			this->C405JTGCAPTUREDR_A0_B = C405JTGCAPTUREDR_A0_B; // net ID: C405JTGCAPTUREDR lsb: 0  msb: 0 OUTPUT
			this->C405JTGEXTEST_A0_B = C405JTGEXTEST_A0_B; // net ID: C405JTGEXTEST lsb: 0  msb: 0 OUTPUT
			this->C405JTGPGMOUT_A0_B = C405JTGPGMOUT_A0_B; // net ID: C405JTGPGMOUT lsb: 0  msb: 0 OUTPUT
			this->C405JTGSHIFTDR_A0_B = C405JTGSHIFTDR_A0_B; // net ID: C405JTGSHIFTDR lsb: 0  msb: 0 OUTPUT
			this->C405JTGTDO_A0_B = C405JTGTDO_A0_B; // net ID: C405JTGTDO lsb: 0  msb: 0 OUTPUT
			this->C405JTGTDOEN_A0_B = C405JTGTDOEN_A0_B; // net ID: C405JTGTDOEN lsb: 0  msb: 0 OUTPUT
			this->C405JTGUPDATEDR_A0_B = C405JTGUPDATEDR_A0_B; // net ID: C405JTGUPDATEDR lsb: 0  msb: 0 OUTPUT
			this->C405PLBDCUABORT_A0_B = C405PLBDCUABORT_A0_B; // net ID: C405PLBDCUABORT lsb: 0  msb: 0 OUTPUT
			this->C405PLBDCUCACHEABLE_A0_B = C405PLBDCUCACHEABLE_A0_B; // net ID: C405PLBDCUCACHEABLE lsb: 0  msb: 0 OUTPUT
			this->C405PLBDCUGUARDED_A0_B = C405PLBDCUGUARDED_A0_B; // net ID: C405PLBDCUGUARDED lsb: 0  msb: 0 OUTPUT
			this->C405PLBDCUREQUEST_A0_B = C405PLBDCUREQUEST_A0_B; // net ID: C405PLBDCUREQUEST lsb: 0  msb: 0 OUTPUT
			this->C405PLBDCURNW_A0_B = C405PLBDCURNW_A0_B; // net ID: C405PLBDCURNW lsb: 0  msb: 0 OUTPUT
			this->C405PLBDCUSIZE2_A0_B = C405PLBDCUSIZE2_A0_B; // net ID: C405PLBDCUSIZE2 lsb: 0  msb: 0 OUTPUT
			this->C405PLBDCUU0ATTR_A0_B = C405PLBDCUU0ATTR_A0_B; // net ID: C405PLBDCUU0ATTR lsb: 0  msb: 0 OUTPUT
			this->C405PLBDCUWRITETHRU_A0_B = C405PLBDCUWRITETHRU_A0_B; // net ID: C405PLBDCUWRITETHRU lsb: 0  msb: 0 OUTPUT
			this->C405PLBICUABORT_A0_B = C405PLBICUABORT_A0_B; // net ID: C405PLBICUABORT lsb: 0  msb: 0 OUTPUT
			this->C405PLBICUCACHEABLE_A0_B = C405PLBICUCACHEABLE_A0_B; // net ID: C405PLBICUCACHEABLE lsb: 0  msb: 0 OUTPUT
			this->C405PLBICUREQUEST_A0_B = C405PLBICUREQUEST_A0_B; // net ID: C405PLBICUREQUEST lsb: 0  msb: 0 OUTPUT
			this->C405PLBICUU0ATTR_A0_B = C405PLBICUU0ATTR_A0_B; // net ID: C405PLBICUU0ATTR lsb: 0  msb: 0 OUTPUT
			this->C405RSTCHIPRESETREQ_A0_B = C405RSTCHIPRESETREQ_A0_B; // net ID: C405RSTCHIPRESETREQ lsb: 0  msb: 0 OUTPUT
			this->C405RSTCORERESETREQ_A0_B = C405RSTCORERESETREQ_A0_B; // net ID: C405RSTCORERESETREQ lsb: 0  msb: 0 OUTPUT
			this->C405RSTSYSRESETREQ_A0_B = C405RSTSYSRESETREQ_A0_B; // net ID: C405RSTSYSRESETREQ lsb: 0  msb: 0 OUTPUT
			this->C405TRCCYCLE_A0_B = C405TRCCYCLE_A0_B; // net ID: C405TRCCYCLE lsb: 0  msb: 0 OUTPUT
			this->C405TRCTRIGGEREVENTOUT_A0_B = C405TRCTRIGGEREVENTOUT_A0_B; // net ID: C405TRCTRIGGEREVENTOUT lsb: 0  msb: 0 OUTPUT
			this->C405XXXMACHINECHECK_A0_B = C405XXXMACHINECHECK_A0_B; // net ID: C405XXXMACHINECHECK lsb: 0  msb: 0 OUTPUT
			this->DCREMACCLK_A0_B = DCREMACCLK_A0_B; // net ID: DCREMACCLK lsb: 0  msb: 0 OUTPUT
			this->DCREMACENABLER_A0_B = DCREMACENABLER_A0_B; // net ID: DCREMACENABLER lsb: 0  msb: 0 OUTPUT
			this->DCREMACREAD_A0_B = DCREMACREAD_A0_B; // net ID: DCREMACREAD lsb: 0  msb: 0 OUTPUT
			this->DCREMACWRITE_A0_B = DCREMACWRITE_A0_B; // net ID: DCREMACWRITE lsb: 0  msb: 0 OUTPUT
			this->DSOCMBRAMEN_A0_B = DSOCMBRAMEN_A0_B; // net ID: DSOCMBRAMEN lsb: 0  msb: 0 OUTPUT
			this->DSOCMBUSY_A0_B = DSOCMBUSY_A0_B; // net ID: DSOCMBUSY lsb: 0  msb: 0 OUTPUT
			this->DSOCMRDADDRVALID_A0_B = DSOCMRDADDRVALID_A0_B; // net ID: DSOCMRDADDRVALID lsb: 0  msb: 0 OUTPUT
			this->DSOCMWRADDRVALID_A0_B = DSOCMWRADDRVALID_A0_B; // net ID: DSOCMWRADDRVALID lsb: 0  msb: 0 OUTPUT
			this->EXTDCRREAD_A0_B = EXTDCRREAD_A0_B; // net ID: EXTDCRREAD lsb: 0  msb: 0 OUTPUT
			this->EXTDCRWRITE_A0_B = EXTDCRWRITE_A0_B; // net ID: EXTDCRWRITE lsb: 0  msb: 0 OUTPUT
			this->ISOCMBRAMEN_A0_B = ISOCMBRAMEN_A0_B; // net ID: ISOCMBRAMEN lsb: 0  msb: 0 OUTPUT
			this->ISOCMBRAMEVENWRITEEN_A0_B = ISOCMBRAMEVENWRITEEN_A0_B; // net ID: ISOCMBRAMEVENWRITEEN lsb: 0  msb: 0 OUTPUT
			this->ISOCMBRAMODDWRITEEN_A0_B = ISOCMBRAMODDWRITEEN_A0_B; // net ID: ISOCMBRAMODDWRITEEN lsb: 0  msb: 0 OUTPUT
			this->ISOCMDCRBRAMEVENEN_A0_B = ISOCMDCRBRAMEVENEN_A0_B; // net ID: ISOCMDCRBRAMEVENEN lsb: 0  msb: 0 OUTPUT
			this->ISOCMDCRBRAMODDEN_A0_B = ISOCMDCRBRAMODDEN_A0_B; // net ID: ISOCMDCRBRAMODDEN lsb: 0  msb: 0 OUTPUT
			this->ISOCMDCRBRAMRDSELECT_A0_B = ISOCMDCRBRAMRDSELECT_A0_B; // net ID: ISOCMDCRBRAMRDSELECT lsb: 0  msb: 0 OUTPUT
			this->BRAMDSOCMCLK_A0_B = BRAMDSOCMCLK_A0_B; // net ID: BRAMDSOCMCLK lsb: 0  msb: 0 INPUT
			this->BRAMISOCMCLK_A0_B = BRAMISOCMCLK_A0_B; // net ID: BRAMISOCMCLK lsb: 0  msb: 0 INPUT
			this->CPMC405CLOCK_A0_B = CPMC405CLOCK_A0_B; // net ID: CPMC405CLOCK lsb: 0  msb: 0 INPUT
			this->CPMC405CORECLKINACTIVE_A0_B = CPMC405CORECLKINACTIVE_A0_B; // net ID: CPMC405CORECLKINACTIVE lsb: 0  msb: 0 INPUT
			this->CPMC405CPUCLKEN_A0_B = CPMC405CPUCLKEN_A0_B; // net ID: CPMC405CPUCLKEN lsb: 0  msb: 0 INPUT
			this->CPMC405JTAGCLKEN_A0_B = CPMC405JTAGCLKEN_A0_B; // net ID: CPMC405JTAGCLKEN lsb: 0  msb: 0 INPUT
			this->CPMC405SYNCBYPASS_A0_B = CPMC405SYNCBYPASS_A0_B; // net ID: CPMC405SYNCBYPASS lsb: 0  msb: 0 INPUT
			this->CPMC405TIMERCLKEN_A0_B = CPMC405TIMERCLKEN_A0_B; // net ID: CPMC405TIMERCLKEN lsb: 0  msb: 0 INPUT
			this->CPMC405TIMERTICK_A0_B = CPMC405TIMERTICK_A0_B; // net ID: CPMC405TIMERTICK lsb: 0  msb: 0 INPUT
			this->CPMDCRCLK_A0_B = CPMDCRCLK_A0_B; // net ID: CPMDCRCLK lsb: 0  msb: 0 INPUT
			this->CPMFCMCLK_A0_B = CPMFCMCLK_A0_B; // net ID: CPMFCMCLK lsb: 0  msb: 0 INPUT
			this->DBGC405DEBUGHALT_A0_B = DBGC405DEBUGHALT_A0_B; // net ID: DBGC405DEBUGHALT lsb: 0  msb: 0 INPUT
			this->DBGC405EXTBUSHOLDACK_A0_B = DBGC405EXTBUSHOLDACK_A0_B; // net ID: DBGC405EXTBUSHOLDACK lsb: 0  msb: 0 INPUT
			this->DBGC405UNCONDDEBUGEVENT_A0_B = DBGC405UNCONDDEBUGEVENT_A0_B; // net ID: DBGC405UNCONDDEBUGEVENT lsb: 0  msb: 0 INPUT
			this->DSOCMRWCOMPLETE_A0_B = DSOCMRWCOMPLETE_A0_B; // net ID: DSOCMRWCOMPLETE lsb: 0  msb: 0 INPUT
			this->EICC405CRITINPUTIRQ_A0_B = EICC405CRITINPUTIRQ_A0_B; // net ID: EICC405CRITINPUTIRQ lsb: 0  msb: 0 INPUT
			this->EICC405EXTINPUTIRQ_A0_B = EICC405EXTINPUTIRQ_A0_B; // net ID: EICC405EXTINPUTIRQ lsb: 0  msb: 0 INPUT
			this->EMACDCRACK_A0_B = EMACDCRACK_A0_B; // net ID: EMACDCRACK lsb: 0  msb: 0 INPUT
			this->EXTDCRACK_A0_B = EXTDCRACK_A0_B; // net ID: EXTDCRACK lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDCREN_A0_B = FCMAPUDCDCREN_A0_B; // net ID: FCMAPUDCDCREN lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDFORCEALIGN_A0_B = FCMAPUDCDFORCEALIGN_A0_B; // net ID: FCMAPUDCDFORCEALIGN lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDFORCEBESTEERING_A0_B = FCMAPUDCDFORCEBESTEERING_A0_B; // net ID: FCMAPUDCDFORCEBESTEERING lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDFPUOP_A0_B = FCMAPUDCDFPUOP_A0_B; // net ID: FCMAPUDCDFPUOP lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDGPRWRITE_A0_B = FCMAPUDCDGPRWRITE_A0_B; // net ID: FCMAPUDCDGPRWRITE lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDLDSTBYTE_A0_B = FCMAPUDCDLDSTBYTE_A0_B; // net ID: FCMAPUDCDLDSTBYTE lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDLDSTDW_A0_B = FCMAPUDCDLDSTDW_A0_B; // net ID: FCMAPUDCDLDSTDW lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDLDSTHW_A0_B = FCMAPUDCDLDSTHW_A0_B; // net ID: FCMAPUDCDLDSTHW lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDLDSTQW_A0_B = FCMAPUDCDLDSTQW_A0_B; // net ID: FCMAPUDCDLDSTQW lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDLDSTWD_A0_B = FCMAPUDCDLDSTWD_A0_B; // net ID: FCMAPUDCDLDSTWD lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDLOAD_A0_B = FCMAPUDCDLOAD_A0_B; // net ID: FCMAPUDCDLOAD lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDPRIVOP_A0_B = FCMAPUDCDPRIVOP_A0_B; // net ID: FCMAPUDCDPRIVOP lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDRAEN_A0_B = FCMAPUDCDRAEN_A0_B; // net ID: FCMAPUDCDRAEN lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDRBEN_A0_B = FCMAPUDCDRBEN_A0_B; // net ID: FCMAPUDCDRBEN lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDSTORE_A0_B = FCMAPUDCDSTORE_A0_B; // net ID: FCMAPUDCDSTORE lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDTRAPBE_A0_B = FCMAPUDCDTRAPBE_A0_B; // net ID: FCMAPUDCDTRAPBE lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDTRAPLE_A0_B = FCMAPUDCDTRAPLE_A0_B; // net ID: FCMAPUDCDTRAPLE lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDUPDATE_A0_B = FCMAPUDCDUPDATE_A0_B; // net ID: FCMAPUDCDUPDATE lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDXERCAEN_A0_B = FCMAPUDCDXERCAEN_A0_B; // net ID: FCMAPUDCDXERCAEN lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDXEROVEN_A0_B = FCMAPUDCDXEROVEN_A0_B; // net ID: FCMAPUDCDXEROVEN lsb: 0  msb: 0 INPUT
			this->FCMAPUDECODEBUSY_A0_B = FCMAPUDECODEBUSY_A0_B; // net ID: FCMAPUDECODEBUSY lsb: 0  msb: 0 INPUT
			this->FCMAPUDONE_A0_B = FCMAPUDONE_A0_B; // net ID: FCMAPUDONE lsb: 0  msb: 0 INPUT
			this->FCMAPUEXCEPTION_A0_B = FCMAPUEXCEPTION_A0_B; // net ID: FCMAPUEXCEPTION lsb: 0  msb: 0 INPUT
			this->FCMAPUEXEBLOCKINGMCO_A0_B = FCMAPUEXEBLOCKINGMCO_A0_B; // net ID: FCMAPUEXEBLOCKINGMCO lsb: 0  msb: 0 INPUT
			this->FCMAPUEXENONBLOCKINGMCO_A0_B = FCMAPUEXENONBLOCKINGMCO_A0_B; // net ID: FCMAPUEXENONBLOCKINGMCO lsb: 0  msb: 0 INPUT
			this->FCMAPUINSTRACK_A0_B = FCMAPUINSTRACK_A0_B; // net ID: FCMAPUINSTRACK lsb: 0  msb: 0 INPUT
			this->FCMAPULOADWAIT_A0_B = FCMAPULOADWAIT_A0_B; // net ID: FCMAPULOADWAIT lsb: 0  msb: 0 INPUT
			this->FCMAPURESULTVALID_A0_B = FCMAPURESULTVALID_A0_B; // net ID: FCMAPURESULTVALID lsb: 0  msb: 0 INPUT
			this->FCMAPUSLEEPNOTREADY_A0_B = FCMAPUSLEEPNOTREADY_A0_B; // net ID: FCMAPUSLEEPNOTREADY lsb: 0  msb: 0 INPUT
			this->FCMAPUXERCA_A0_B = FCMAPUXERCA_A0_B; // net ID: FCMAPUXERCA lsb: 0  msb: 0 INPUT
			this->FCMAPUXEROV_A0_B = FCMAPUXEROV_A0_B; // net ID: FCMAPUXEROV lsb: 0  msb: 0 INPUT
			this->JTGC405BNDSCANTDO_A0_B = JTGC405BNDSCANTDO_A0_B; // net ID: JTGC405BNDSCANTDO lsb: 0  msb: 0 INPUT
			this->JTGC405TCK_A0_B = JTGC405TCK_A0_B; // net ID: JTGC405TCK lsb: 0  msb: 0 INPUT
			this->JTGC405TDI_A0_B = JTGC405TDI_A0_B; // net ID: JTGC405TDI lsb: 0  msb: 0 INPUT
			this->JTGC405TMS_A0_B = JTGC405TMS_A0_B; // net ID: JTGC405TMS lsb: 0  msb: 0 INPUT
			this->JTGC405TRSTNEG_A0_B = JTGC405TRSTNEG_A0_B; // net ID: JTGC405TRSTNEG lsb: 0  msb: 0 INPUT
			this->MCBCPUCLKEN_A0_B = MCBCPUCLKEN_A0_B; // net ID: MCBCPUCLKEN lsb: 0  msb: 0 INPUT
			this->MCBJTAGEN_A0_B = MCBJTAGEN_A0_B; // net ID: MCBJTAGEN lsb: 0  msb: 0 INPUT
			this->MCBTIMEREN_A0_B = MCBTIMEREN_A0_B; // net ID: MCBTIMEREN lsb: 0  msb: 0 INPUT
			this->MCPPCRST_A0_B = MCPPCRST_A0_B; // net ID: MCPPCRST lsb: 0  msb: 0 INPUT
			this->PLBC405DCUADDRACK_A0_B = PLBC405DCUADDRACK_A0_B; // net ID: PLBC405DCUADDRACK lsb: 0  msb: 0 INPUT
			this->PLBC405DCUBUSY_A0_B = PLBC405DCUBUSY_A0_B; // net ID: PLBC405DCUBUSY lsb: 0  msb: 0 INPUT
			this->PLBC405DCUERR_A0_B = PLBC405DCUERR_A0_B; // net ID: PLBC405DCUERR lsb: 0  msb: 0 INPUT
			this->PLBC405DCURDDACK_A0_B = PLBC405DCURDDACK_A0_B; // net ID: PLBC405DCURDDACK lsb: 0  msb: 0 INPUT
			this->PLBC405DCUSSIZE1_A0_B = PLBC405DCUSSIZE1_A0_B; // net ID: PLBC405DCUSSIZE1 lsb: 0  msb: 0 INPUT
			this->PLBC405DCUWRDACK_A0_B = PLBC405DCUWRDACK_A0_B; // net ID: PLBC405DCUWRDACK lsb: 0  msb: 0 INPUT
			this->PLBC405ICUADDRACK_A0_B = PLBC405ICUADDRACK_A0_B; // net ID: PLBC405ICUADDRACK lsb: 0  msb: 0 INPUT
			this->PLBC405ICUBUSY_A0_B = PLBC405ICUBUSY_A0_B; // net ID: PLBC405ICUBUSY lsb: 0  msb: 0 INPUT
			this->PLBC405ICUERR_A0_B = PLBC405ICUERR_A0_B; // net ID: PLBC405ICUERR lsb: 0  msb: 0 INPUT
			this->PLBC405ICURDDACK_A0_B = PLBC405ICURDDACK_A0_B; // net ID: PLBC405ICURDDACK lsb: 0  msb: 0 INPUT
			this->PLBC405ICUSSIZE1_A0_B = PLBC405ICUSSIZE1_A0_B; // net ID: PLBC405ICUSSIZE1 lsb: 0  msb: 0 INPUT
			this->PLBCLK_A0_B = PLBCLK_A0_B; // net ID: PLBCLK lsb: 0  msb: 0 INPUT
			this->RSTC405RESETCHIP_A0_B = RSTC405RESETCHIP_A0_B; // net ID: RSTC405RESETCHIP lsb: 0  msb: 0 INPUT
			this->RSTC405RESETCORE_A0_B = RSTC405RESETCORE_A0_B; // net ID: RSTC405RESETCORE lsb: 0  msb: 0 INPUT
			this->RSTC405RESETSYS_A0_B = RSTC405RESETSYS_A0_B; // net ID: RSTC405RESETSYS lsb: 0  msb: 0 INPUT
			this->TIEC405DETERMINISTICMULT_A0_B = TIEC405DETERMINISTICMULT_A0_B; // net ID: TIEC405DETERMINISTICMULT lsb: 0  msb: 0 INPUT
			this->TIEC405DISOPERANDFWD_A0_B = TIEC405DISOPERANDFWD_A0_B; // net ID: TIEC405DISOPERANDFWD lsb: 0  msb: 0 INPUT
			this->TIEC405MMUEN_A0_B = TIEC405MMUEN_A0_B; // net ID: TIEC405MMUEN lsb: 0  msb: 0 INPUT
			this->TIEPVRBIT10_A0_B = TIEPVRBIT10_A0_B; // net ID: TIEPVRBIT10 lsb: 0  msb: 0 INPUT
			this->TIEPVRBIT11_A0_B = TIEPVRBIT11_A0_B; // net ID: TIEPVRBIT11 lsb: 0  msb: 0 INPUT
			this->TIEPVRBIT28_A0_B = TIEPVRBIT28_A0_B; // net ID: TIEPVRBIT28 lsb: 0  msb: 0 INPUT
			this->TIEPVRBIT29_A0_B = TIEPVRBIT29_A0_B; // net ID: TIEPVRBIT29 lsb: 0  msb: 0 INPUT
			this->TIEPVRBIT30_A0_B = TIEPVRBIT30_A0_B; // net ID: TIEPVRBIT30 lsb: 0  msb: 0 INPUT
			this->TIEPVRBIT31_A0_B = TIEPVRBIT31_A0_B; // net ID: TIEPVRBIT31 lsb: 0  msb: 0 INPUT
			this->TIEPVRBIT8_A0_B = TIEPVRBIT8_A0_B; // net ID: TIEPVRBIT8 lsb: 0  msb: 0 INPUT
			this->TIEPVRBIT9_A0_B = TIEPVRBIT9_A0_B; // net ID: TIEPVRBIT9 lsb: 0  msb: 0 INPUT
			this->TRCC405TRACEDISABLE_A0_B = TRCC405TRACEDISABLE_A0_B; // net ID: TRCC405TRACEDISABLE lsb: 0  msb: 0 INPUT
			this->TRCC405TRIGGEREVENTIN_A0_B = TRCC405TRIGGEREVENTIN_A0_B; // net ID: TRCC405TRIGGEREVENTIN lsb: 0  msb: 0 INPUT
			
			register_wait_on_event_nets();
			
		}
		
		void register_wait_on_event_nets(){
		// TODO
		}
		
		void calculate(simtime_t time){
		// TODO
		}
		};
		
}
#endif // X_PPC405_ADV_H
