/******************************************************************************
 * Generated Cpp template for simulation primitives.
 * Author: Benedek Racz
 ******************************************************************************/

#include "NetFlow.h"
#include "sim_types.h"
#include "Primitive.h"

namespace CPrimitives {
	
	class X_PPC405_ADV: public Primitive{

		//Verilog Parameters:
		parameter_string_t LOC;
		parameter_string_t in_delay;
		parameter_string_t out_delay;
		//Verilog Ports in definition order:
		NetFlow* APUFCMDECODED; // net ID: APUFCMDECODED lsb: 0  msb: 0 OUTPUT
		NetFlow* APUFCMDECUDI; // net ID: APUFCMDECUDI lsb: 0  msb: 0 OUTPUT
		NetFlow* APUFCMDECUDIVALID; // net ID: APUFCMDECUDIVALID lsb: 0  msb: 0 OUTPUT
		NetFlow* APUFCMENDIAN; // net ID: APUFCMENDIAN lsb: 0  msb: 0 OUTPUT
		NetFlow* APUFCMFLUSH; // net ID: APUFCMFLUSH lsb: 0  msb: 0 OUTPUT
		NetFlow* APUFCMINSTRUCTION; // net ID: APUFCMINSTRUCTION lsb: 0  msb: 0 OUTPUT
		NetFlow* APUFCMINSTRVALID; // net ID: APUFCMINSTRVALID lsb: 0  msb: 0 OUTPUT
		NetFlow* APUFCMLOADBYTEEN; // net ID: APUFCMLOADBYTEEN lsb: 0  msb: 0 OUTPUT
		NetFlow* APUFCMLOADDATA; // net ID: APUFCMLOADDATA lsb: 0  msb: 0 OUTPUT
		NetFlow* APUFCMLOADDVALID; // net ID: APUFCMLOADDVALID lsb: 0  msb: 0 OUTPUT
		NetFlow* APUFCMOPERANDVALID; // net ID: APUFCMOPERANDVALID lsb: 0  msb: 0 OUTPUT
		NetFlow* APUFCMRADATA; // net ID: APUFCMRADATA lsb: 0  msb: 0 OUTPUT
		NetFlow* APUFCMRBDATA; // net ID: APUFCMRBDATA lsb: 0  msb: 0 OUTPUT
		NetFlow* APUFCMWRITEBACKOK; // net ID: APUFCMWRITEBACKOK lsb: 0  msb: 0 OUTPUT
		NetFlow* APUFCMXERCA; // net ID: APUFCMXERCA lsb: 0  msb: 0 OUTPUT
		NetFlow* C405CPMCORESLEEPREQ; // net ID: C405CPMCORESLEEPREQ lsb: 0  msb: 0 OUTPUT
		NetFlow* C405CPMMSRCE; // net ID: C405CPMMSRCE lsb: 0  msb: 0 OUTPUT
		NetFlow* C405CPMMSREE; // net ID: C405CPMMSREE lsb: 0  msb: 0 OUTPUT
		NetFlow* C405CPMTIMERIRQ; // net ID: C405CPMTIMERIRQ lsb: 0  msb: 0 OUTPUT
		NetFlow* C405CPMTIMERRESETREQ; // net ID: C405CPMTIMERRESETREQ lsb: 0  msb: 0 OUTPUT
		NetFlow* C405DBGLOADDATAONAPUDBUS; // net ID: C405DBGLOADDATAONAPUDBUS lsb: 0  msb: 0 OUTPUT
		NetFlow* C405DBGMSRWE; // net ID: C405DBGMSRWE lsb: 0  msb: 0 OUTPUT
		NetFlow* C405DBGSTOPACK; // net ID: C405DBGSTOPACK lsb: 0  msb: 0 OUTPUT
		NetFlow* C405DBGWBCOMPLETE; // net ID: C405DBGWBCOMPLETE lsb: 0  msb: 0 OUTPUT
		NetFlow* C405DBGWBFULL; // net ID: C405DBGWBFULL lsb: 0  msb: 0 OUTPUT
		NetFlow* C405DBGWBIAR; // net ID: C405DBGWBIAR lsb: 0  msb: 0 OUTPUT
		NetFlow* C405JTGCAPTUREDR; // net ID: C405JTGCAPTUREDR lsb: 0  msb: 0 OUTPUT
		NetFlow* C405JTGEXTEST; // net ID: C405JTGEXTEST lsb: 0  msb: 0 OUTPUT
		NetFlow* C405JTGPGMOUT; // net ID: C405JTGPGMOUT lsb: 0  msb: 0 OUTPUT
		NetFlow* C405JTGSHIFTDR; // net ID: C405JTGSHIFTDR lsb: 0  msb: 0 OUTPUT
		NetFlow* C405JTGTDO; // net ID: C405JTGTDO lsb: 0  msb: 0 OUTPUT
		NetFlow* C405JTGTDOEN; // net ID: C405JTGTDOEN lsb: 0  msb: 0 OUTPUT
		NetFlow* C405JTGUPDATEDR; // net ID: C405JTGUPDATEDR lsb: 0  msb: 0 OUTPUT
		NetFlow* C405PLBDCUABORT; // net ID: C405PLBDCUABORT lsb: 0  msb: 0 OUTPUT
		NetFlow* C405PLBDCUABUS; // net ID: C405PLBDCUABUS lsb: 0  msb: 0 OUTPUT
		NetFlow* C405PLBDCUBE; // net ID: C405PLBDCUBE lsb: 0  msb: 0 OUTPUT
		NetFlow* C405PLBDCUCACHEABLE; // net ID: C405PLBDCUCACHEABLE lsb: 0  msb: 0 OUTPUT
		NetFlow* C405PLBDCUGUARDED; // net ID: C405PLBDCUGUARDED lsb: 0  msb: 0 OUTPUT
		NetFlow* C405PLBDCUPRIORITY; // net ID: C405PLBDCUPRIORITY lsb: 0  msb: 0 OUTPUT
		NetFlow* C405PLBDCUREQUEST; // net ID: C405PLBDCUREQUEST lsb: 0  msb: 0 OUTPUT
		NetFlow* C405PLBDCURNW; // net ID: C405PLBDCURNW lsb: 0  msb: 0 OUTPUT
		NetFlow* C405PLBDCUSIZE2; // net ID: C405PLBDCUSIZE2 lsb: 0  msb: 0 OUTPUT
		NetFlow* C405PLBDCUU0ATTR; // net ID: C405PLBDCUU0ATTR lsb: 0  msb: 0 OUTPUT
		NetFlow* C405PLBDCUWRDBUS; // net ID: C405PLBDCUWRDBUS lsb: 0  msb: 0 OUTPUT
		NetFlow* C405PLBDCUWRITETHRU; // net ID: C405PLBDCUWRITETHRU lsb: 0  msb: 0 OUTPUT
		NetFlow* C405PLBICUABORT; // net ID: C405PLBICUABORT lsb: 0  msb: 0 OUTPUT
		NetFlow* C405PLBICUABUS; // net ID: C405PLBICUABUS lsb: 0  msb: 0 OUTPUT
		NetFlow* C405PLBICUCACHEABLE; // net ID: C405PLBICUCACHEABLE lsb: 0  msb: 0 OUTPUT
		NetFlow* C405PLBICUPRIORITY; // net ID: C405PLBICUPRIORITY lsb: 0  msb: 0 OUTPUT
		NetFlow* C405PLBICUREQUEST; // net ID: C405PLBICUREQUEST lsb: 0  msb: 0 OUTPUT
		NetFlow* C405PLBICUSIZE; // net ID: C405PLBICUSIZE lsb: 0  msb: 0 OUTPUT
		NetFlow* C405PLBICUU0ATTR; // net ID: C405PLBICUU0ATTR lsb: 0  msb: 0 OUTPUT
		NetFlow* C405RSTCHIPRESETREQ; // net ID: C405RSTCHIPRESETREQ lsb: 0  msb: 0 OUTPUT
		NetFlow* C405RSTCORERESETREQ; // net ID: C405RSTCORERESETREQ lsb: 0  msb: 0 OUTPUT
		NetFlow* C405RSTSYSRESETREQ; // net ID: C405RSTSYSRESETREQ lsb: 0  msb: 0 OUTPUT
		NetFlow* C405TRCCYCLE; // net ID: C405TRCCYCLE lsb: 0  msb: 0 OUTPUT
		NetFlow* C405TRCEVENEXECUTIONSTATUS; // net ID: C405TRCEVENEXECUTIONSTATUS lsb: 0  msb: 0 OUTPUT
		NetFlow* C405TRCODDEXECUTIONSTATUS; // net ID: C405TRCODDEXECUTIONSTATUS lsb: 0  msb: 0 OUTPUT
		NetFlow* C405TRCTRACESTATUS; // net ID: C405TRCTRACESTATUS lsb: 0  msb: 0 OUTPUT
		NetFlow* C405TRCTRIGGEREVENTOUT; // net ID: C405TRCTRIGGEREVENTOUT lsb: 0  msb: 0 OUTPUT
		NetFlow* C405TRCTRIGGEREVENTTYPE; // net ID: C405TRCTRIGGEREVENTTYPE lsb: 0  msb: 0 OUTPUT
		NetFlow* C405XXXMACHINECHECK; // net ID: C405XXXMACHINECHECK lsb: 0  msb: 0 OUTPUT
		NetFlow* DCREMACABUS; // net ID: DCREMACABUS lsb: 0  msb: 0 OUTPUT
		NetFlow* DCREMACCLK; // net ID: DCREMACCLK lsb: 0  msb: 0 OUTPUT
		NetFlow* DCREMACDBUS; // net ID: DCREMACDBUS lsb: 0  msb: 0 OUTPUT
		NetFlow* DCREMACENABLER; // net ID: DCREMACENABLER lsb: 0  msb: 0 OUTPUT
		NetFlow* DCREMACREAD; // net ID: DCREMACREAD lsb: 0  msb: 0 OUTPUT
		NetFlow* DCREMACWRITE; // net ID: DCREMACWRITE lsb: 0  msb: 0 OUTPUT
		NetFlow* DSOCMBRAMABUS; // net ID: DSOCMBRAMABUS lsb: 0  msb: 0 OUTPUT
		NetFlow* DSOCMBRAMBYTEWRITE; // net ID: DSOCMBRAMBYTEWRITE lsb: 0  msb: 0 OUTPUT
		NetFlow* DSOCMBRAMEN; // net ID: DSOCMBRAMEN lsb: 0  msb: 0 OUTPUT
		NetFlow* DSOCMBRAMWRDBUS; // net ID: DSOCMBRAMWRDBUS lsb: 0  msb: 0 OUTPUT
		NetFlow* DSOCMBUSY; // net ID: DSOCMBUSY lsb: 0  msb: 0 OUTPUT
		NetFlow* DSOCMRDADDRVALID; // net ID: DSOCMRDADDRVALID lsb: 0  msb: 0 OUTPUT
		NetFlow* DSOCMWRADDRVALID; // net ID: DSOCMWRADDRVALID lsb: 0  msb: 0 OUTPUT
		NetFlow* EXTDCRABUS; // net ID: EXTDCRABUS lsb: 0  msb: 0 OUTPUT
		NetFlow* EXTDCRDBUSOUT; // net ID: EXTDCRDBUSOUT lsb: 0  msb: 0 OUTPUT
		NetFlow* EXTDCRREAD; // net ID: EXTDCRREAD lsb: 0  msb: 0 OUTPUT
		NetFlow* EXTDCRWRITE; // net ID: EXTDCRWRITE lsb: 0  msb: 0 OUTPUT
		NetFlow* ISOCMBRAMEN; // net ID: ISOCMBRAMEN lsb: 0  msb: 0 OUTPUT
		NetFlow* ISOCMBRAMEVENWRITEEN; // net ID: ISOCMBRAMEVENWRITEEN lsb: 0  msb: 0 OUTPUT
		NetFlow* ISOCMBRAMODDWRITEEN; // net ID: ISOCMBRAMODDWRITEEN lsb: 0  msb: 0 OUTPUT
		NetFlow* ISOCMBRAMRDABUS; // net ID: ISOCMBRAMRDABUS lsb: 0  msb: 0 OUTPUT
		NetFlow* ISOCMBRAMWRABUS; // net ID: ISOCMBRAMWRABUS lsb: 0  msb: 0 OUTPUT
		NetFlow* ISOCMBRAMWRDBUS; // net ID: ISOCMBRAMWRDBUS lsb: 0  msb: 0 OUTPUT
		NetFlow* ISOCMDCRBRAMEVENEN; // net ID: ISOCMDCRBRAMEVENEN lsb: 0  msb: 0 OUTPUT
		NetFlow* ISOCMDCRBRAMODDEN; // net ID: ISOCMDCRBRAMODDEN lsb: 0  msb: 0 OUTPUT
		NetFlow* ISOCMDCRBRAMRDSELECT; // net ID: ISOCMDCRBRAMRDSELECT lsb: 0  msb: 0 OUTPUT
		NetFlow* BRAMDSOCMCLK; // net ID: BRAMDSOCMCLK lsb: 0  msb: 0 INPUT
		NetFlow* BRAMDSOCMRDDBUS; // net ID: BRAMDSOCMRDDBUS lsb: 31  msb: 0 INPUT
		NetFlow* BRAMISOCMCLK; // net ID: BRAMISOCMCLK lsb: 0  msb: 0 INPUT
		NetFlow* BRAMISOCMDCRRDDBUS; // net ID: BRAMISOCMDCRRDDBUS lsb: 31  msb: 0 INPUT
		NetFlow* BRAMISOCMRDDBUS; // net ID: BRAMISOCMRDDBUS lsb: 63  msb: 0 INPUT
		NetFlow* CPMC405CLOCK; // net ID: CPMC405CLOCK lsb: 0  msb: 0 INPUT
		NetFlow* CPMC405CORECLKINACTIVE; // net ID: CPMC405CORECLKINACTIVE lsb: 0  msb: 0 INPUT
		NetFlow* CPMC405CPUCLKEN; // net ID: CPMC405CPUCLKEN lsb: 0  msb: 0 INPUT
		NetFlow* CPMC405JTAGCLKEN; // net ID: CPMC405JTAGCLKEN lsb: 0  msb: 0 INPUT
		NetFlow* CPMC405SYNCBYPASS; // net ID: CPMC405SYNCBYPASS lsb: 0  msb: 0 INPUT
		NetFlow* CPMC405TIMERCLKEN; // net ID: CPMC405TIMERCLKEN lsb: 0  msb: 0 INPUT
		NetFlow* CPMC405TIMERTICK; // net ID: CPMC405TIMERTICK lsb: 0  msb: 0 INPUT
		NetFlow* CPMDCRCLK; // net ID: CPMDCRCLK lsb: 0  msb: 0 INPUT
		NetFlow* CPMFCMCLK; // net ID: CPMFCMCLK lsb: 0  msb: 0 INPUT
		NetFlow* DBGC405DEBUGHALT; // net ID: DBGC405DEBUGHALT lsb: 0  msb: 0 INPUT
		NetFlow* DBGC405EXTBUSHOLDACK; // net ID: DBGC405EXTBUSHOLDACK lsb: 0  msb: 0 INPUT
		NetFlow* DBGC405UNCONDDEBUGEVENT; // net ID: DBGC405UNCONDDEBUGEVENT lsb: 0  msb: 0 INPUT
		NetFlow* DSARCVALUE; // net ID: DSARCVALUE lsb: 7  msb: 0 INPUT
		NetFlow* DSCNTLVALUE; // net ID: DSCNTLVALUE lsb: 7  msb: 0 INPUT
		NetFlow* DSOCMRWCOMPLETE; // net ID: DSOCMRWCOMPLETE lsb: 0  msb: 0 INPUT
		NetFlow* EICC405CRITINPUTIRQ; // net ID: EICC405CRITINPUTIRQ lsb: 0  msb: 0 INPUT
		NetFlow* EICC405EXTINPUTIRQ; // net ID: EICC405EXTINPUTIRQ lsb: 0  msb: 0 INPUT
		NetFlow* EMACDCRACK; // net ID: EMACDCRACK lsb: 0  msb: 0 INPUT
		NetFlow* EMACDCRDBUS; // net ID: EMACDCRDBUS lsb: 31  msb: 0 INPUT
		NetFlow* EXTDCRACK; // net ID: EXTDCRACK lsb: 0  msb: 0 INPUT
		NetFlow* EXTDCRDBUSIN; // net ID: EXTDCRDBUSIN lsb: 31  msb: 0 INPUT
		NetFlow* FCMAPUCR; // net ID: FCMAPUCR lsb: 3  msb: 0 INPUT
		NetFlow* FCMAPUDCDCREN; // net ID: FCMAPUDCDCREN lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDFORCEALIGN; // net ID: FCMAPUDCDFORCEALIGN lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDFORCEBESTEERING; // net ID: FCMAPUDCDFORCEBESTEERING lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDFPUOP; // net ID: FCMAPUDCDFPUOP lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDGPRWRITE; // net ID: FCMAPUDCDGPRWRITE lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDLDSTBYTE; // net ID: FCMAPUDCDLDSTBYTE lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDLDSTDW; // net ID: FCMAPUDCDLDSTDW lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDLDSTHW; // net ID: FCMAPUDCDLDSTHW lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDLDSTQW; // net ID: FCMAPUDCDLDSTQW lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDLDSTWD; // net ID: FCMAPUDCDLDSTWD lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDLOAD; // net ID: FCMAPUDCDLOAD lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDPRIVOP; // net ID: FCMAPUDCDPRIVOP lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDRAEN; // net ID: FCMAPUDCDRAEN lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDRBEN; // net ID: FCMAPUDCDRBEN lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDSTORE; // net ID: FCMAPUDCDSTORE lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDTRAPBE; // net ID: FCMAPUDCDTRAPBE lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDTRAPLE; // net ID: FCMAPUDCDTRAPLE lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDUPDATE; // net ID: FCMAPUDCDUPDATE lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDXERCAEN; // net ID: FCMAPUDCDXERCAEN lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDCDXEROVEN; // net ID: FCMAPUDCDXEROVEN lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDECODEBUSY; // net ID: FCMAPUDECODEBUSY lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUDONE; // net ID: FCMAPUDONE lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUEXCEPTION; // net ID: FCMAPUEXCEPTION lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUEXEBLOCKINGMCO; // net ID: FCMAPUEXEBLOCKINGMCO lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUEXECRFIELD; // net ID: FCMAPUEXECRFIELD lsb: 2  msb: 0 INPUT
		NetFlow* FCMAPUEXENONBLOCKINGMCO; // net ID: FCMAPUEXENONBLOCKINGMCO lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUINSTRACK; // net ID: FCMAPUINSTRACK lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPULOADWAIT; // net ID: FCMAPULOADWAIT lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPURESULT; // net ID: FCMAPURESULT lsb: 31  msb: 0 INPUT
		NetFlow* FCMAPURESULTVALID; // net ID: FCMAPURESULTVALID lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUSLEEPNOTREADY; // net ID: FCMAPUSLEEPNOTREADY lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUXERCA; // net ID: FCMAPUXERCA lsb: 0  msb: 0 INPUT
		NetFlow* FCMAPUXEROV; // net ID: FCMAPUXEROV lsb: 0  msb: 0 INPUT
		NetFlow* ISARCVALUE; // net ID: ISARCVALUE lsb: 7  msb: 0 INPUT
		NetFlow* ISCNTLVALUE; // net ID: ISCNTLVALUE lsb: 7  msb: 0 INPUT
		NetFlow* JTGC405BNDSCANTDO; // net ID: JTGC405BNDSCANTDO lsb: 0  msb: 0 INPUT
		NetFlow* JTGC405TCK; // net ID: JTGC405TCK lsb: 0  msb: 0 INPUT
		NetFlow* JTGC405TDI; // net ID: JTGC405TDI lsb: 0  msb: 0 INPUT
		NetFlow* JTGC405TMS; // net ID: JTGC405TMS lsb: 0  msb: 0 INPUT
		NetFlow* JTGC405TRSTNEG; // net ID: JTGC405TRSTNEG lsb: 0  msb: 0 INPUT
		NetFlow* MCBCPUCLKEN; // net ID: MCBCPUCLKEN lsb: 0  msb: 0 INPUT
		NetFlow* MCBJTAGEN; // net ID: MCBJTAGEN lsb: 0  msb: 0 INPUT
		NetFlow* MCBTIMEREN; // net ID: MCBTIMEREN lsb: 0  msb: 0 INPUT
		NetFlow* MCPPCRST; // net ID: MCPPCRST lsb: 0  msb: 0 INPUT
		NetFlow* PLBC405DCUADDRACK; // net ID: PLBC405DCUADDRACK lsb: 0  msb: 0 INPUT
		NetFlow* PLBC405DCUBUSY; // net ID: PLBC405DCUBUSY lsb: 0  msb: 0 INPUT
		NetFlow* PLBC405DCUERR; // net ID: PLBC405DCUERR lsb: 0  msb: 0 INPUT
		NetFlow* PLBC405DCURDDACK; // net ID: PLBC405DCURDDACK lsb: 0  msb: 0 INPUT
		NetFlow* PLBC405DCURDDBUS; // net ID: PLBC405DCURDDBUS lsb: 63  msb: 0 INPUT
		NetFlow* PLBC405DCURDWDADDR; // net ID: PLBC405DCURDWDADDR lsb: 3  msb: 1 INPUT
		NetFlow* PLBC405DCUSSIZE1; // net ID: PLBC405DCUSSIZE1 lsb: 0  msb: 0 INPUT
		NetFlow* PLBC405DCUWRDACK; // net ID: PLBC405DCUWRDACK lsb: 0  msb: 0 INPUT
		NetFlow* PLBC405ICUADDRACK; // net ID: PLBC405ICUADDRACK lsb: 0  msb: 0 INPUT
		NetFlow* PLBC405ICUBUSY; // net ID: PLBC405ICUBUSY lsb: 0  msb: 0 INPUT
		NetFlow* PLBC405ICUERR; // net ID: PLBC405ICUERR lsb: 0  msb: 0 INPUT
		NetFlow* PLBC405ICURDDACK; // net ID: PLBC405ICURDDACK lsb: 0  msb: 0 INPUT
		NetFlow* PLBC405ICURDDBUS; // net ID: PLBC405ICURDDBUS lsb: 63  msb: 0 INPUT
		NetFlow* PLBC405ICURDWDADDR; // net ID: PLBC405ICURDWDADDR lsb: 3  msb: 1 INPUT
		NetFlow* PLBC405ICUSSIZE1; // net ID: PLBC405ICUSSIZE1 lsb: 0  msb: 0 INPUT
		NetFlow* PLBCLK; // net ID: PLBCLK lsb: 0  msb: 0 INPUT
		NetFlow* RSTC405RESETCHIP; // net ID: RSTC405RESETCHIP lsb: 0  msb: 0 INPUT
		NetFlow* RSTC405RESETCORE; // net ID: RSTC405RESETCORE lsb: 0  msb: 0 INPUT
		NetFlow* RSTC405RESETSYS; // net ID: RSTC405RESETSYS lsb: 0  msb: 0 INPUT
		NetFlow* TIEAPUCONTROL; // net ID: TIEAPUCONTROL lsb: 15  msb: 0 INPUT
		NetFlow* TIEAPUUDI1; // net ID: TIEAPUUDI1 lsb: 23  msb: 0 INPUT
		NetFlow* TIEAPUUDI2; // net ID: TIEAPUUDI2 lsb: 23  msb: 0 INPUT
		NetFlow* TIEAPUUDI3; // net ID: TIEAPUUDI3 lsb: 23  msb: 0 INPUT
		NetFlow* TIEAPUUDI4; // net ID: TIEAPUUDI4 lsb: 23  msb: 0 INPUT
		NetFlow* TIEAPUUDI5; // net ID: TIEAPUUDI5 lsb: 23  msb: 0 INPUT
		NetFlow* TIEAPUUDI6; // net ID: TIEAPUUDI6 lsb: 23  msb: 0 INPUT
		NetFlow* TIEAPUUDI7; // net ID: TIEAPUUDI7 lsb: 23  msb: 0 INPUT
		NetFlow* TIEAPUUDI8; // net ID: TIEAPUUDI8 lsb: 23  msb: 0 INPUT
		NetFlow* TIEC405DETERMINISTICMULT; // net ID: TIEC405DETERMINISTICMULT lsb: 0  msb: 0 INPUT
		NetFlow* TIEC405DISOPERANDFWD; // net ID: TIEC405DISOPERANDFWD lsb: 0  msb: 0 INPUT
		NetFlow* TIEC405MMUEN; // net ID: TIEC405MMUEN lsb: 0  msb: 0 INPUT
		NetFlow* TIEDCRADDR; // net ID: TIEDCRADDR lsb: 5  msb: 0 INPUT
		NetFlow* TIEPVRBIT10; // net ID: TIEPVRBIT10 lsb: 0  msb: 0 INPUT
		NetFlow* TIEPVRBIT11; // net ID: TIEPVRBIT11 lsb: 0  msb: 0 INPUT
		NetFlow* TIEPVRBIT28; // net ID: TIEPVRBIT28 lsb: 0  msb: 0 INPUT
		NetFlow* TIEPVRBIT29; // net ID: TIEPVRBIT29 lsb: 0  msb: 0 INPUT
		NetFlow* TIEPVRBIT30; // net ID: TIEPVRBIT30 lsb: 0  msb: 0 INPUT
		NetFlow* TIEPVRBIT31; // net ID: TIEPVRBIT31 lsb: 0  msb: 0 INPUT
		NetFlow* TIEPVRBIT8; // net ID: TIEPVRBIT8 lsb: 0  msb: 0 INPUT
		NetFlow* TIEPVRBIT9; // net ID: TIEPVRBIT9 lsb: 0  msb: 0 INPUT
		NetFlow* TRCC405TRACEDISABLE; // net ID: TRCC405TRACEDISABLE lsb: 0  msb: 0 INPUT
		NetFlow* TRCC405TRIGGEREVENTIN; // net ID: TRCC405TRIGGEREVENTIN lsb: 0  msb: 0 INPUT
		
		X_PPC405_ADV(
			const char * name,
			//Verilog Parameters:
			parameter_string_t LOC, // Default: "UNPLACED"
			parameter_string_t in_delay, // Default: 1
			parameter_string_t out_delay, // Default: 0
			//Verilog Ports in definition order:
			NetFlow* APUFCMDECODED, // net ID: APUFCMDECODED lsb: 0  msb: 0 OUTPUT
			NetFlow* APUFCMDECUDI, // net ID: APUFCMDECUDI lsb: 0  msb: 0 OUTPUT
			NetFlow* APUFCMDECUDIVALID, // net ID: APUFCMDECUDIVALID lsb: 0  msb: 0 OUTPUT
			NetFlow* APUFCMENDIAN, // net ID: APUFCMENDIAN lsb: 0  msb: 0 OUTPUT
			NetFlow* APUFCMFLUSH, // net ID: APUFCMFLUSH lsb: 0  msb: 0 OUTPUT
			NetFlow* APUFCMINSTRUCTION, // net ID: APUFCMINSTRUCTION lsb: 0  msb: 0 OUTPUT
			NetFlow* APUFCMINSTRVALID, // net ID: APUFCMINSTRVALID lsb: 0  msb: 0 OUTPUT
			NetFlow* APUFCMLOADBYTEEN, // net ID: APUFCMLOADBYTEEN lsb: 0  msb: 0 OUTPUT
			NetFlow* APUFCMLOADDATA, // net ID: APUFCMLOADDATA lsb: 0  msb: 0 OUTPUT
			NetFlow* APUFCMLOADDVALID, // net ID: APUFCMLOADDVALID lsb: 0  msb: 0 OUTPUT
			NetFlow* APUFCMOPERANDVALID, // net ID: APUFCMOPERANDVALID lsb: 0  msb: 0 OUTPUT
			NetFlow* APUFCMRADATA, // net ID: APUFCMRADATA lsb: 0  msb: 0 OUTPUT
			NetFlow* APUFCMRBDATA, // net ID: APUFCMRBDATA lsb: 0  msb: 0 OUTPUT
			NetFlow* APUFCMWRITEBACKOK, // net ID: APUFCMWRITEBACKOK lsb: 0  msb: 0 OUTPUT
			NetFlow* APUFCMXERCA, // net ID: APUFCMXERCA lsb: 0  msb: 0 OUTPUT
			NetFlow* C405CPMCORESLEEPREQ, // net ID: C405CPMCORESLEEPREQ lsb: 0  msb: 0 OUTPUT
			NetFlow* C405CPMMSRCE, // net ID: C405CPMMSRCE lsb: 0  msb: 0 OUTPUT
			NetFlow* C405CPMMSREE, // net ID: C405CPMMSREE lsb: 0  msb: 0 OUTPUT
			NetFlow* C405CPMTIMERIRQ, // net ID: C405CPMTIMERIRQ lsb: 0  msb: 0 OUTPUT
			NetFlow* C405CPMTIMERRESETREQ, // net ID: C405CPMTIMERRESETREQ lsb: 0  msb: 0 OUTPUT
			NetFlow* C405DBGLOADDATAONAPUDBUS, // net ID: C405DBGLOADDATAONAPUDBUS lsb: 0  msb: 0 OUTPUT
			NetFlow* C405DBGMSRWE, // net ID: C405DBGMSRWE lsb: 0  msb: 0 OUTPUT
			NetFlow* C405DBGSTOPACK, // net ID: C405DBGSTOPACK lsb: 0  msb: 0 OUTPUT
			NetFlow* C405DBGWBCOMPLETE, // net ID: C405DBGWBCOMPLETE lsb: 0  msb: 0 OUTPUT
			NetFlow* C405DBGWBFULL, // net ID: C405DBGWBFULL lsb: 0  msb: 0 OUTPUT
			NetFlow* C405DBGWBIAR, // net ID: C405DBGWBIAR lsb: 0  msb: 0 OUTPUT
			NetFlow* C405JTGCAPTUREDR, // net ID: C405JTGCAPTUREDR lsb: 0  msb: 0 OUTPUT
			NetFlow* C405JTGEXTEST, // net ID: C405JTGEXTEST lsb: 0  msb: 0 OUTPUT
			NetFlow* C405JTGPGMOUT, // net ID: C405JTGPGMOUT lsb: 0  msb: 0 OUTPUT
			NetFlow* C405JTGSHIFTDR, // net ID: C405JTGSHIFTDR lsb: 0  msb: 0 OUTPUT
			NetFlow* C405JTGTDO, // net ID: C405JTGTDO lsb: 0  msb: 0 OUTPUT
			NetFlow* C405JTGTDOEN, // net ID: C405JTGTDOEN lsb: 0  msb: 0 OUTPUT
			NetFlow* C405JTGUPDATEDR, // net ID: C405JTGUPDATEDR lsb: 0  msb: 0 OUTPUT
			NetFlow* C405PLBDCUABORT, // net ID: C405PLBDCUABORT lsb: 0  msb: 0 OUTPUT
			NetFlow* C405PLBDCUABUS, // net ID: C405PLBDCUABUS lsb: 0  msb: 0 OUTPUT
			NetFlow* C405PLBDCUBE, // net ID: C405PLBDCUBE lsb: 0  msb: 0 OUTPUT
			NetFlow* C405PLBDCUCACHEABLE, // net ID: C405PLBDCUCACHEABLE lsb: 0  msb: 0 OUTPUT
			NetFlow* C405PLBDCUGUARDED, // net ID: C405PLBDCUGUARDED lsb: 0  msb: 0 OUTPUT
			NetFlow* C405PLBDCUPRIORITY, // net ID: C405PLBDCUPRIORITY lsb: 0  msb: 0 OUTPUT
			NetFlow* C405PLBDCUREQUEST, // net ID: C405PLBDCUREQUEST lsb: 0  msb: 0 OUTPUT
			NetFlow* C405PLBDCURNW, // net ID: C405PLBDCURNW lsb: 0  msb: 0 OUTPUT
			NetFlow* C405PLBDCUSIZE2, // net ID: C405PLBDCUSIZE2 lsb: 0  msb: 0 OUTPUT
			NetFlow* C405PLBDCUU0ATTR, // net ID: C405PLBDCUU0ATTR lsb: 0  msb: 0 OUTPUT
			NetFlow* C405PLBDCUWRDBUS, // net ID: C405PLBDCUWRDBUS lsb: 0  msb: 0 OUTPUT
			NetFlow* C405PLBDCUWRITETHRU, // net ID: C405PLBDCUWRITETHRU lsb: 0  msb: 0 OUTPUT
			NetFlow* C405PLBICUABORT, // net ID: C405PLBICUABORT lsb: 0  msb: 0 OUTPUT
			NetFlow* C405PLBICUABUS, // net ID: C405PLBICUABUS lsb: 0  msb: 0 OUTPUT
			NetFlow* C405PLBICUCACHEABLE, // net ID: C405PLBICUCACHEABLE lsb: 0  msb: 0 OUTPUT
			NetFlow* C405PLBICUPRIORITY, // net ID: C405PLBICUPRIORITY lsb: 0  msb: 0 OUTPUT
			NetFlow* C405PLBICUREQUEST, // net ID: C405PLBICUREQUEST lsb: 0  msb: 0 OUTPUT
			NetFlow* C405PLBICUSIZE, // net ID: C405PLBICUSIZE lsb: 0  msb: 0 OUTPUT
			NetFlow* C405PLBICUU0ATTR, // net ID: C405PLBICUU0ATTR lsb: 0  msb: 0 OUTPUT
			NetFlow* C405RSTCHIPRESETREQ, // net ID: C405RSTCHIPRESETREQ lsb: 0  msb: 0 OUTPUT
			NetFlow* C405RSTCORERESETREQ, // net ID: C405RSTCORERESETREQ lsb: 0  msb: 0 OUTPUT
			NetFlow* C405RSTSYSRESETREQ, // net ID: C405RSTSYSRESETREQ lsb: 0  msb: 0 OUTPUT
			NetFlow* C405TRCCYCLE, // net ID: C405TRCCYCLE lsb: 0  msb: 0 OUTPUT
			NetFlow* C405TRCEVENEXECUTIONSTATUS, // net ID: C405TRCEVENEXECUTIONSTATUS lsb: 0  msb: 0 OUTPUT
			NetFlow* C405TRCODDEXECUTIONSTATUS, // net ID: C405TRCODDEXECUTIONSTATUS lsb: 0  msb: 0 OUTPUT
			NetFlow* C405TRCTRACESTATUS, // net ID: C405TRCTRACESTATUS lsb: 0  msb: 0 OUTPUT
			NetFlow* C405TRCTRIGGEREVENTOUT, // net ID: C405TRCTRIGGEREVENTOUT lsb: 0  msb: 0 OUTPUT
			NetFlow* C405TRCTRIGGEREVENTTYPE, // net ID: C405TRCTRIGGEREVENTTYPE lsb: 0  msb: 0 OUTPUT
			NetFlow* C405XXXMACHINECHECK, // net ID: C405XXXMACHINECHECK lsb: 0  msb: 0 OUTPUT
			NetFlow* DCREMACABUS, // net ID: DCREMACABUS lsb: 0  msb: 0 OUTPUT
			NetFlow* DCREMACCLK, // net ID: DCREMACCLK lsb: 0  msb: 0 OUTPUT
			NetFlow* DCREMACDBUS, // net ID: DCREMACDBUS lsb: 0  msb: 0 OUTPUT
			NetFlow* DCREMACENABLER, // net ID: DCREMACENABLER lsb: 0  msb: 0 OUTPUT
			NetFlow* DCREMACREAD, // net ID: DCREMACREAD lsb: 0  msb: 0 OUTPUT
			NetFlow* DCREMACWRITE, // net ID: DCREMACWRITE lsb: 0  msb: 0 OUTPUT
			NetFlow* DSOCMBRAMABUS, // net ID: DSOCMBRAMABUS lsb: 0  msb: 0 OUTPUT
			NetFlow* DSOCMBRAMBYTEWRITE, // net ID: DSOCMBRAMBYTEWRITE lsb: 0  msb: 0 OUTPUT
			NetFlow* DSOCMBRAMEN, // net ID: DSOCMBRAMEN lsb: 0  msb: 0 OUTPUT
			NetFlow* DSOCMBRAMWRDBUS, // net ID: DSOCMBRAMWRDBUS lsb: 0  msb: 0 OUTPUT
			NetFlow* DSOCMBUSY, // net ID: DSOCMBUSY lsb: 0  msb: 0 OUTPUT
			NetFlow* DSOCMRDADDRVALID, // net ID: DSOCMRDADDRVALID lsb: 0  msb: 0 OUTPUT
			NetFlow* DSOCMWRADDRVALID, // net ID: DSOCMWRADDRVALID lsb: 0  msb: 0 OUTPUT
			NetFlow* EXTDCRABUS, // net ID: EXTDCRABUS lsb: 0  msb: 0 OUTPUT
			NetFlow* EXTDCRDBUSOUT, // net ID: EXTDCRDBUSOUT lsb: 0  msb: 0 OUTPUT
			NetFlow* EXTDCRREAD, // net ID: EXTDCRREAD lsb: 0  msb: 0 OUTPUT
			NetFlow* EXTDCRWRITE, // net ID: EXTDCRWRITE lsb: 0  msb: 0 OUTPUT
			NetFlow* ISOCMBRAMEN, // net ID: ISOCMBRAMEN lsb: 0  msb: 0 OUTPUT
			NetFlow* ISOCMBRAMEVENWRITEEN, // net ID: ISOCMBRAMEVENWRITEEN lsb: 0  msb: 0 OUTPUT
			NetFlow* ISOCMBRAMODDWRITEEN, // net ID: ISOCMBRAMODDWRITEEN lsb: 0  msb: 0 OUTPUT
			NetFlow* ISOCMBRAMRDABUS, // net ID: ISOCMBRAMRDABUS lsb: 0  msb: 0 OUTPUT
			NetFlow* ISOCMBRAMWRABUS, // net ID: ISOCMBRAMWRABUS lsb: 0  msb: 0 OUTPUT
			NetFlow* ISOCMBRAMWRDBUS, // net ID: ISOCMBRAMWRDBUS lsb: 0  msb: 0 OUTPUT
			NetFlow* ISOCMDCRBRAMEVENEN, // net ID: ISOCMDCRBRAMEVENEN lsb: 0  msb: 0 OUTPUT
			NetFlow* ISOCMDCRBRAMODDEN, // net ID: ISOCMDCRBRAMODDEN lsb: 0  msb: 0 OUTPUT
			NetFlow* ISOCMDCRBRAMRDSELECT, // net ID: ISOCMDCRBRAMRDSELECT lsb: 0  msb: 0 OUTPUT
			NetFlow* BRAMDSOCMCLK, // net ID: BRAMDSOCMCLK lsb: 0  msb: 0 INPUT
			NetFlow* BRAMDSOCMRDDBUS, // net ID: BRAMDSOCMRDDBUS lsb: 31  msb: 0 INPUT
			NetFlow* BRAMISOCMCLK, // net ID: BRAMISOCMCLK lsb: 0  msb: 0 INPUT
			NetFlow* BRAMISOCMDCRRDDBUS, // net ID: BRAMISOCMDCRRDDBUS lsb: 31  msb: 0 INPUT
			NetFlow* BRAMISOCMRDDBUS, // net ID: BRAMISOCMRDDBUS lsb: 63  msb: 0 INPUT
			NetFlow* CPMC405CLOCK, // net ID: CPMC405CLOCK lsb: 0  msb: 0 INPUT
			NetFlow* CPMC405CORECLKINACTIVE, // net ID: CPMC405CORECLKINACTIVE lsb: 0  msb: 0 INPUT
			NetFlow* CPMC405CPUCLKEN, // net ID: CPMC405CPUCLKEN lsb: 0  msb: 0 INPUT
			NetFlow* CPMC405JTAGCLKEN, // net ID: CPMC405JTAGCLKEN lsb: 0  msb: 0 INPUT
			NetFlow* CPMC405SYNCBYPASS, // net ID: CPMC405SYNCBYPASS lsb: 0  msb: 0 INPUT
			NetFlow* CPMC405TIMERCLKEN, // net ID: CPMC405TIMERCLKEN lsb: 0  msb: 0 INPUT
			NetFlow* CPMC405TIMERTICK, // net ID: CPMC405TIMERTICK lsb: 0  msb: 0 INPUT
			NetFlow* CPMDCRCLK, // net ID: CPMDCRCLK lsb: 0  msb: 0 INPUT
			NetFlow* CPMFCMCLK, // net ID: CPMFCMCLK lsb: 0  msb: 0 INPUT
			NetFlow* DBGC405DEBUGHALT, // net ID: DBGC405DEBUGHALT lsb: 0  msb: 0 INPUT
			NetFlow* DBGC405EXTBUSHOLDACK, // net ID: DBGC405EXTBUSHOLDACK lsb: 0  msb: 0 INPUT
			NetFlow* DBGC405UNCONDDEBUGEVENT, // net ID: DBGC405UNCONDDEBUGEVENT lsb: 0  msb: 0 INPUT
			NetFlow* DSARCVALUE, // net ID: DSARCVALUE lsb: 7  msb: 0 INPUT
			NetFlow* DSCNTLVALUE, // net ID: DSCNTLVALUE lsb: 7  msb: 0 INPUT
			NetFlow* DSOCMRWCOMPLETE, // net ID: DSOCMRWCOMPLETE lsb: 0  msb: 0 INPUT
			NetFlow* EICC405CRITINPUTIRQ, // net ID: EICC405CRITINPUTIRQ lsb: 0  msb: 0 INPUT
			NetFlow* EICC405EXTINPUTIRQ, // net ID: EICC405EXTINPUTIRQ lsb: 0  msb: 0 INPUT
			NetFlow* EMACDCRACK, // net ID: EMACDCRACK lsb: 0  msb: 0 INPUT
			NetFlow* EMACDCRDBUS, // net ID: EMACDCRDBUS lsb: 31  msb: 0 INPUT
			NetFlow* EXTDCRACK, // net ID: EXTDCRACK lsb: 0  msb: 0 INPUT
			NetFlow* EXTDCRDBUSIN, // net ID: EXTDCRDBUSIN lsb: 31  msb: 0 INPUT
			NetFlow* FCMAPUCR, // net ID: FCMAPUCR lsb: 3  msb: 0 INPUT
			NetFlow* FCMAPUDCDCREN, // net ID: FCMAPUDCDCREN lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDFORCEALIGN, // net ID: FCMAPUDCDFORCEALIGN lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDFORCEBESTEERING, // net ID: FCMAPUDCDFORCEBESTEERING lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDFPUOP, // net ID: FCMAPUDCDFPUOP lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDGPRWRITE, // net ID: FCMAPUDCDGPRWRITE lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDLDSTBYTE, // net ID: FCMAPUDCDLDSTBYTE lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDLDSTDW, // net ID: FCMAPUDCDLDSTDW lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDLDSTHW, // net ID: FCMAPUDCDLDSTHW lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDLDSTQW, // net ID: FCMAPUDCDLDSTQW lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDLDSTWD, // net ID: FCMAPUDCDLDSTWD lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDLOAD, // net ID: FCMAPUDCDLOAD lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDPRIVOP, // net ID: FCMAPUDCDPRIVOP lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDRAEN, // net ID: FCMAPUDCDRAEN lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDRBEN, // net ID: FCMAPUDCDRBEN lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDSTORE, // net ID: FCMAPUDCDSTORE lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDTRAPBE, // net ID: FCMAPUDCDTRAPBE lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDTRAPLE, // net ID: FCMAPUDCDTRAPLE lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDUPDATE, // net ID: FCMAPUDCDUPDATE lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDXERCAEN, // net ID: FCMAPUDCDXERCAEN lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDCDXEROVEN, // net ID: FCMAPUDCDXEROVEN lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDECODEBUSY, // net ID: FCMAPUDECODEBUSY lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUDONE, // net ID: FCMAPUDONE lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUEXCEPTION, // net ID: FCMAPUEXCEPTION lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUEXEBLOCKINGMCO, // net ID: FCMAPUEXEBLOCKINGMCO lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUEXECRFIELD, // net ID: FCMAPUEXECRFIELD lsb: 2  msb: 0 INPUT
			NetFlow* FCMAPUEXENONBLOCKINGMCO, // net ID: FCMAPUEXENONBLOCKINGMCO lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUINSTRACK, // net ID: FCMAPUINSTRACK lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPULOADWAIT, // net ID: FCMAPULOADWAIT lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPURESULT, // net ID: FCMAPURESULT lsb: 31  msb: 0 INPUT
			NetFlow* FCMAPURESULTVALID, // net ID: FCMAPURESULTVALID lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUSLEEPNOTREADY, // net ID: FCMAPUSLEEPNOTREADY lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUXERCA, // net ID: FCMAPUXERCA lsb: 0  msb: 0 INPUT
			NetFlow* FCMAPUXEROV, // net ID: FCMAPUXEROV lsb: 0  msb: 0 INPUT
			NetFlow* ISARCVALUE, // net ID: ISARCVALUE lsb: 7  msb: 0 INPUT
			NetFlow* ISCNTLVALUE, // net ID: ISCNTLVALUE lsb: 7  msb: 0 INPUT
			NetFlow* JTGC405BNDSCANTDO, // net ID: JTGC405BNDSCANTDO lsb: 0  msb: 0 INPUT
			NetFlow* JTGC405TCK, // net ID: JTGC405TCK lsb: 0  msb: 0 INPUT
			NetFlow* JTGC405TDI, // net ID: JTGC405TDI lsb: 0  msb: 0 INPUT
			NetFlow* JTGC405TMS, // net ID: JTGC405TMS lsb: 0  msb: 0 INPUT
			NetFlow* JTGC405TRSTNEG, // net ID: JTGC405TRSTNEG lsb: 0  msb: 0 INPUT
			NetFlow* MCBCPUCLKEN, // net ID: MCBCPUCLKEN lsb: 0  msb: 0 INPUT
			NetFlow* MCBJTAGEN, // net ID: MCBJTAGEN lsb: 0  msb: 0 INPUT
			NetFlow* MCBTIMEREN, // net ID: MCBTIMEREN lsb: 0  msb: 0 INPUT
			NetFlow* MCPPCRST, // net ID: MCPPCRST lsb: 0  msb: 0 INPUT
			NetFlow* PLBC405DCUADDRACK, // net ID: PLBC405DCUADDRACK lsb: 0  msb: 0 INPUT
			NetFlow* PLBC405DCUBUSY, // net ID: PLBC405DCUBUSY lsb: 0  msb: 0 INPUT
			NetFlow* PLBC405DCUERR, // net ID: PLBC405DCUERR lsb: 0  msb: 0 INPUT
			NetFlow* PLBC405DCURDDACK, // net ID: PLBC405DCURDDACK lsb: 0  msb: 0 INPUT
			NetFlow* PLBC405DCURDDBUS, // net ID: PLBC405DCURDDBUS lsb: 63  msb: 0 INPUT
			NetFlow* PLBC405DCURDWDADDR, // net ID: PLBC405DCURDWDADDR lsb: 3  msb: 1 INPUT
			NetFlow* PLBC405DCUSSIZE1, // net ID: PLBC405DCUSSIZE1 lsb: 0  msb: 0 INPUT
			NetFlow* PLBC405DCUWRDACK, // net ID: PLBC405DCUWRDACK lsb: 0  msb: 0 INPUT
			NetFlow* PLBC405ICUADDRACK, // net ID: PLBC405ICUADDRACK lsb: 0  msb: 0 INPUT
			NetFlow* PLBC405ICUBUSY, // net ID: PLBC405ICUBUSY lsb: 0  msb: 0 INPUT
			NetFlow* PLBC405ICUERR, // net ID: PLBC405ICUERR lsb: 0  msb: 0 INPUT
			NetFlow* PLBC405ICURDDACK, // net ID: PLBC405ICURDDACK lsb: 0  msb: 0 INPUT
			NetFlow* PLBC405ICURDDBUS, // net ID: PLBC405ICURDDBUS lsb: 63  msb: 0 INPUT
			NetFlow* PLBC405ICURDWDADDR, // net ID: PLBC405ICURDWDADDR lsb: 3  msb: 1 INPUT
			NetFlow* PLBC405ICUSSIZE1, // net ID: PLBC405ICUSSIZE1 lsb: 0  msb: 0 INPUT
			NetFlow* PLBCLK, // net ID: PLBCLK lsb: 0  msb: 0 INPUT
			NetFlow* RSTC405RESETCHIP, // net ID: RSTC405RESETCHIP lsb: 0  msb: 0 INPUT
			NetFlow* RSTC405RESETCORE, // net ID: RSTC405RESETCORE lsb: 0  msb: 0 INPUT
			NetFlow* RSTC405RESETSYS, // net ID: RSTC405RESETSYS lsb: 0  msb: 0 INPUT
			NetFlow* TIEAPUCONTROL, // net ID: TIEAPUCONTROL lsb: 15  msb: 0 INPUT
			NetFlow* TIEAPUUDI1, // net ID: TIEAPUUDI1 lsb: 23  msb: 0 INPUT
			NetFlow* TIEAPUUDI2, // net ID: TIEAPUUDI2 lsb: 23  msb: 0 INPUT
			NetFlow* TIEAPUUDI3, // net ID: TIEAPUUDI3 lsb: 23  msb: 0 INPUT
			NetFlow* TIEAPUUDI4, // net ID: TIEAPUUDI4 lsb: 23  msb: 0 INPUT
			NetFlow* TIEAPUUDI5, // net ID: TIEAPUUDI5 lsb: 23  msb: 0 INPUT
			NetFlow* TIEAPUUDI6, // net ID: TIEAPUUDI6 lsb: 23  msb: 0 INPUT
			NetFlow* TIEAPUUDI7, // net ID: TIEAPUUDI7 lsb: 23  msb: 0 INPUT
			NetFlow* TIEAPUUDI8, // net ID: TIEAPUUDI8 lsb: 23  msb: 0 INPUT
			NetFlow* TIEC405DETERMINISTICMULT, // net ID: TIEC405DETERMINISTICMULT lsb: 0  msb: 0 INPUT
			NetFlow* TIEC405DISOPERANDFWD, // net ID: TIEC405DISOPERANDFWD lsb: 0  msb: 0 INPUT
			NetFlow* TIEC405MMUEN, // net ID: TIEC405MMUEN lsb: 0  msb: 0 INPUT
			NetFlow* TIEDCRADDR, // net ID: TIEDCRADDR lsb: 5  msb: 0 INPUT
			NetFlow* TIEPVRBIT10, // net ID: TIEPVRBIT10 lsb: 0  msb: 0 INPUT
			NetFlow* TIEPVRBIT11, // net ID: TIEPVRBIT11 lsb: 0  msb: 0 INPUT
			NetFlow* TIEPVRBIT28, // net ID: TIEPVRBIT28 lsb: 0  msb: 0 INPUT
			NetFlow* TIEPVRBIT29, // net ID: TIEPVRBIT29 lsb: 0  msb: 0 INPUT
			NetFlow* TIEPVRBIT30, // net ID: TIEPVRBIT30 lsb: 0  msb: 0 INPUT
			NetFlow* TIEPVRBIT31, // net ID: TIEPVRBIT31 lsb: 0  msb: 0 INPUT
			NetFlow* TIEPVRBIT8, // net ID: TIEPVRBIT8 lsb: 0  msb: 0 INPUT
			NetFlow* TIEPVRBIT9, // net ID: TIEPVRBIT9 lsb: 0  msb: 0 INPUT
			NetFlow* TRCC405TRACEDISABLE, // net ID: TRCC405TRACEDISABLE lsb: 0  msb: 0 INPUT
			NetFlow* TRCC405TRIGGEREVENTIN // net ID: TRCC405TRIGGEREVENTIN lsb: 0  msb: 0 INPUT
			):Primitive(name){
			
			// Assign parameters and ports: 
			//Verilog Parameters:
			this->LOC = LOC; // Default: "UNPLACED"
			this->in_delay = in_delay; // Default: 1
			this->out_delay = out_delay; // Default: 0
			//Verilog Ports in definition order:
			this->APUFCMDECODED = APUFCMDECODED; // net ID: APUFCMDECODED lsb: 0  msb: 0 OUTPUT
			this->APUFCMDECUDI = APUFCMDECUDI; // net ID: APUFCMDECUDI lsb: 0  msb: 0 OUTPUT
			this->APUFCMDECUDIVALID = APUFCMDECUDIVALID; // net ID: APUFCMDECUDIVALID lsb: 0  msb: 0 OUTPUT
			this->APUFCMENDIAN = APUFCMENDIAN; // net ID: APUFCMENDIAN lsb: 0  msb: 0 OUTPUT
			this->APUFCMFLUSH = APUFCMFLUSH; // net ID: APUFCMFLUSH lsb: 0  msb: 0 OUTPUT
			this->APUFCMINSTRUCTION = APUFCMINSTRUCTION; // net ID: APUFCMINSTRUCTION lsb: 0  msb: 0 OUTPUT
			this->APUFCMINSTRVALID = APUFCMINSTRVALID; // net ID: APUFCMINSTRVALID lsb: 0  msb: 0 OUTPUT
			this->APUFCMLOADBYTEEN = APUFCMLOADBYTEEN; // net ID: APUFCMLOADBYTEEN lsb: 0  msb: 0 OUTPUT
			this->APUFCMLOADDATA = APUFCMLOADDATA; // net ID: APUFCMLOADDATA lsb: 0  msb: 0 OUTPUT
			this->APUFCMLOADDVALID = APUFCMLOADDVALID; // net ID: APUFCMLOADDVALID lsb: 0  msb: 0 OUTPUT
			this->APUFCMOPERANDVALID = APUFCMOPERANDVALID; // net ID: APUFCMOPERANDVALID lsb: 0  msb: 0 OUTPUT
			this->APUFCMRADATA = APUFCMRADATA; // net ID: APUFCMRADATA lsb: 0  msb: 0 OUTPUT
			this->APUFCMRBDATA = APUFCMRBDATA; // net ID: APUFCMRBDATA lsb: 0  msb: 0 OUTPUT
			this->APUFCMWRITEBACKOK = APUFCMWRITEBACKOK; // net ID: APUFCMWRITEBACKOK lsb: 0  msb: 0 OUTPUT
			this->APUFCMXERCA = APUFCMXERCA; // net ID: APUFCMXERCA lsb: 0  msb: 0 OUTPUT
			this->C405CPMCORESLEEPREQ = C405CPMCORESLEEPREQ; // net ID: C405CPMCORESLEEPREQ lsb: 0  msb: 0 OUTPUT
			this->C405CPMMSRCE = C405CPMMSRCE; // net ID: C405CPMMSRCE lsb: 0  msb: 0 OUTPUT
			this->C405CPMMSREE = C405CPMMSREE; // net ID: C405CPMMSREE lsb: 0  msb: 0 OUTPUT
			this->C405CPMTIMERIRQ = C405CPMTIMERIRQ; // net ID: C405CPMTIMERIRQ lsb: 0  msb: 0 OUTPUT
			this->C405CPMTIMERRESETREQ = C405CPMTIMERRESETREQ; // net ID: C405CPMTIMERRESETREQ lsb: 0  msb: 0 OUTPUT
			this->C405DBGLOADDATAONAPUDBUS = C405DBGLOADDATAONAPUDBUS; // net ID: C405DBGLOADDATAONAPUDBUS lsb: 0  msb: 0 OUTPUT
			this->C405DBGMSRWE = C405DBGMSRWE; // net ID: C405DBGMSRWE lsb: 0  msb: 0 OUTPUT
			this->C405DBGSTOPACK = C405DBGSTOPACK; // net ID: C405DBGSTOPACK lsb: 0  msb: 0 OUTPUT
			this->C405DBGWBCOMPLETE = C405DBGWBCOMPLETE; // net ID: C405DBGWBCOMPLETE lsb: 0  msb: 0 OUTPUT
			this->C405DBGWBFULL = C405DBGWBFULL; // net ID: C405DBGWBFULL lsb: 0  msb: 0 OUTPUT
			this->C405DBGWBIAR = C405DBGWBIAR; // net ID: C405DBGWBIAR lsb: 0  msb: 0 OUTPUT
			this->C405JTGCAPTUREDR = C405JTGCAPTUREDR; // net ID: C405JTGCAPTUREDR lsb: 0  msb: 0 OUTPUT
			this->C405JTGEXTEST = C405JTGEXTEST; // net ID: C405JTGEXTEST lsb: 0  msb: 0 OUTPUT
			this->C405JTGPGMOUT = C405JTGPGMOUT; // net ID: C405JTGPGMOUT lsb: 0  msb: 0 OUTPUT
			this->C405JTGSHIFTDR = C405JTGSHIFTDR; // net ID: C405JTGSHIFTDR lsb: 0  msb: 0 OUTPUT
			this->C405JTGTDO = C405JTGTDO; // net ID: C405JTGTDO lsb: 0  msb: 0 OUTPUT
			this->C405JTGTDOEN = C405JTGTDOEN; // net ID: C405JTGTDOEN lsb: 0  msb: 0 OUTPUT
			this->C405JTGUPDATEDR = C405JTGUPDATEDR; // net ID: C405JTGUPDATEDR lsb: 0  msb: 0 OUTPUT
			this->C405PLBDCUABORT = C405PLBDCUABORT; // net ID: C405PLBDCUABORT lsb: 0  msb: 0 OUTPUT
			this->C405PLBDCUABUS = C405PLBDCUABUS; // net ID: C405PLBDCUABUS lsb: 0  msb: 0 OUTPUT
			this->C405PLBDCUBE = C405PLBDCUBE; // net ID: C405PLBDCUBE lsb: 0  msb: 0 OUTPUT
			this->C405PLBDCUCACHEABLE = C405PLBDCUCACHEABLE; // net ID: C405PLBDCUCACHEABLE lsb: 0  msb: 0 OUTPUT
			this->C405PLBDCUGUARDED = C405PLBDCUGUARDED; // net ID: C405PLBDCUGUARDED lsb: 0  msb: 0 OUTPUT
			this->C405PLBDCUPRIORITY = C405PLBDCUPRIORITY; // net ID: C405PLBDCUPRIORITY lsb: 0  msb: 0 OUTPUT
			this->C405PLBDCUREQUEST = C405PLBDCUREQUEST; // net ID: C405PLBDCUREQUEST lsb: 0  msb: 0 OUTPUT
			this->C405PLBDCURNW = C405PLBDCURNW; // net ID: C405PLBDCURNW lsb: 0  msb: 0 OUTPUT
			this->C405PLBDCUSIZE2 = C405PLBDCUSIZE2; // net ID: C405PLBDCUSIZE2 lsb: 0  msb: 0 OUTPUT
			this->C405PLBDCUU0ATTR = C405PLBDCUU0ATTR; // net ID: C405PLBDCUU0ATTR lsb: 0  msb: 0 OUTPUT
			this->C405PLBDCUWRDBUS = C405PLBDCUWRDBUS; // net ID: C405PLBDCUWRDBUS lsb: 0  msb: 0 OUTPUT
			this->C405PLBDCUWRITETHRU = C405PLBDCUWRITETHRU; // net ID: C405PLBDCUWRITETHRU lsb: 0  msb: 0 OUTPUT
			this->C405PLBICUABORT = C405PLBICUABORT; // net ID: C405PLBICUABORT lsb: 0  msb: 0 OUTPUT
			this->C405PLBICUABUS = C405PLBICUABUS; // net ID: C405PLBICUABUS lsb: 0  msb: 0 OUTPUT
			this->C405PLBICUCACHEABLE = C405PLBICUCACHEABLE; // net ID: C405PLBICUCACHEABLE lsb: 0  msb: 0 OUTPUT
			this->C405PLBICUPRIORITY = C405PLBICUPRIORITY; // net ID: C405PLBICUPRIORITY lsb: 0  msb: 0 OUTPUT
			this->C405PLBICUREQUEST = C405PLBICUREQUEST; // net ID: C405PLBICUREQUEST lsb: 0  msb: 0 OUTPUT
			this->C405PLBICUSIZE = C405PLBICUSIZE; // net ID: C405PLBICUSIZE lsb: 0  msb: 0 OUTPUT
			this->C405PLBICUU0ATTR = C405PLBICUU0ATTR; // net ID: C405PLBICUU0ATTR lsb: 0  msb: 0 OUTPUT
			this->C405RSTCHIPRESETREQ = C405RSTCHIPRESETREQ; // net ID: C405RSTCHIPRESETREQ lsb: 0  msb: 0 OUTPUT
			this->C405RSTCORERESETREQ = C405RSTCORERESETREQ; // net ID: C405RSTCORERESETREQ lsb: 0  msb: 0 OUTPUT
			this->C405RSTSYSRESETREQ = C405RSTSYSRESETREQ; // net ID: C405RSTSYSRESETREQ lsb: 0  msb: 0 OUTPUT
			this->C405TRCCYCLE = C405TRCCYCLE; // net ID: C405TRCCYCLE lsb: 0  msb: 0 OUTPUT
			this->C405TRCEVENEXECUTIONSTATUS = C405TRCEVENEXECUTIONSTATUS; // net ID: C405TRCEVENEXECUTIONSTATUS lsb: 0  msb: 0 OUTPUT
			this->C405TRCODDEXECUTIONSTATUS = C405TRCODDEXECUTIONSTATUS; // net ID: C405TRCODDEXECUTIONSTATUS lsb: 0  msb: 0 OUTPUT
			this->C405TRCTRACESTATUS = C405TRCTRACESTATUS; // net ID: C405TRCTRACESTATUS lsb: 0  msb: 0 OUTPUT
			this->C405TRCTRIGGEREVENTOUT = C405TRCTRIGGEREVENTOUT; // net ID: C405TRCTRIGGEREVENTOUT lsb: 0  msb: 0 OUTPUT
			this->C405TRCTRIGGEREVENTTYPE = C405TRCTRIGGEREVENTTYPE; // net ID: C405TRCTRIGGEREVENTTYPE lsb: 0  msb: 0 OUTPUT
			this->C405XXXMACHINECHECK = C405XXXMACHINECHECK; // net ID: C405XXXMACHINECHECK lsb: 0  msb: 0 OUTPUT
			this->DCREMACABUS = DCREMACABUS; // net ID: DCREMACABUS lsb: 0  msb: 0 OUTPUT
			this->DCREMACCLK = DCREMACCLK; // net ID: DCREMACCLK lsb: 0  msb: 0 OUTPUT
			this->DCREMACDBUS = DCREMACDBUS; // net ID: DCREMACDBUS lsb: 0  msb: 0 OUTPUT
			this->DCREMACENABLER = DCREMACENABLER; // net ID: DCREMACENABLER lsb: 0  msb: 0 OUTPUT
			this->DCREMACREAD = DCREMACREAD; // net ID: DCREMACREAD lsb: 0  msb: 0 OUTPUT
			this->DCREMACWRITE = DCREMACWRITE; // net ID: DCREMACWRITE lsb: 0  msb: 0 OUTPUT
			this->DSOCMBRAMABUS = DSOCMBRAMABUS; // net ID: DSOCMBRAMABUS lsb: 0  msb: 0 OUTPUT
			this->DSOCMBRAMBYTEWRITE = DSOCMBRAMBYTEWRITE; // net ID: DSOCMBRAMBYTEWRITE lsb: 0  msb: 0 OUTPUT
			this->DSOCMBRAMEN = DSOCMBRAMEN; // net ID: DSOCMBRAMEN lsb: 0  msb: 0 OUTPUT
			this->DSOCMBRAMWRDBUS = DSOCMBRAMWRDBUS; // net ID: DSOCMBRAMWRDBUS lsb: 0  msb: 0 OUTPUT
			this->DSOCMBUSY = DSOCMBUSY; // net ID: DSOCMBUSY lsb: 0  msb: 0 OUTPUT
			this->DSOCMRDADDRVALID = DSOCMRDADDRVALID; // net ID: DSOCMRDADDRVALID lsb: 0  msb: 0 OUTPUT
			this->DSOCMWRADDRVALID = DSOCMWRADDRVALID; // net ID: DSOCMWRADDRVALID lsb: 0  msb: 0 OUTPUT
			this->EXTDCRABUS = EXTDCRABUS; // net ID: EXTDCRABUS lsb: 0  msb: 0 OUTPUT
			this->EXTDCRDBUSOUT = EXTDCRDBUSOUT; // net ID: EXTDCRDBUSOUT lsb: 0  msb: 0 OUTPUT
			this->EXTDCRREAD = EXTDCRREAD; // net ID: EXTDCRREAD lsb: 0  msb: 0 OUTPUT
			this->EXTDCRWRITE = EXTDCRWRITE; // net ID: EXTDCRWRITE lsb: 0  msb: 0 OUTPUT
			this->ISOCMBRAMEN = ISOCMBRAMEN; // net ID: ISOCMBRAMEN lsb: 0  msb: 0 OUTPUT
			this->ISOCMBRAMEVENWRITEEN = ISOCMBRAMEVENWRITEEN; // net ID: ISOCMBRAMEVENWRITEEN lsb: 0  msb: 0 OUTPUT
			this->ISOCMBRAMODDWRITEEN = ISOCMBRAMODDWRITEEN; // net ID: ISOCMBRAMODDWRITEEN lsb: 0  msb: 0 OUTPUT
			this->ISOCMBRAMRDABUS = ISOCMBRAMRDABUS; // net ID: ISOCMBRAMRDABUS lsb: 0  msb: 0 OUTPUT
			this->ISOCMBRAMWRABUS = ISOCMBRAMWRABUS; // net ID: ISOCMBRAMWRABUS lsb: 0  msb: 0 OUTPUT
			this->ISOCMBRAMWRDBUS = ISOCMBRAMWRDBUS; // net ID: ISOCMBRAMWRDBUS lsb: 0  msb: 0 OUTPUT
			this->ISOCMDCRBRAMEVENEN = ISOCMDCRBRAMEVENEN; // net ID: ISOCMDCRBRAMEVENEN lsb: 0  msb: 0 OUTPUT
			this->ISOCMDCRBRAMODDEN = ISOCMDCRBRAMODDEN; // net ID: ISOCMDCRBRAMODDEN lsb: 0  msb: 0 OUTPUT
			this->ISOCMDCRBRAMRDSELECT = ISOCMDCRBRAMRDSELECT; // net ID: ISOCMDCRBRAMRDSELECT lsb: 0  msb: 0 OUTPUT
			this->BRAMDSOCMCLK = BRAMDSOCMCLK; // net ID: BRAMDSOCMCLK lsb: 0  msb: 0 INPUT
			this->BRAMDSOCMRDDBUS = BRAMDSOCMRDDBUS; // net ID: BRAMDSOCMRDDBUS lsb: 31  msb: 0 INPUT
			this->BRAMISOCMCLK = BRAMISOCMCLK; // net ID: BRAMISOCMCLK lsb: 0  msb: 0 INPUT
			this->BRAMISOCMDCRRDDBUS = BRAMISOCMDCRRDDBUS; // net ID: BRAMISOCMDCRRDDBUS lsb: 31  msb: 0 INPUT
			this->BRAMISOCMRDDBUS = BRAMISOCMRDDBUS; // net ID: BRAMISOCMRDDBUS lsb: 63  msb: 0 INPUT
			this->CPMC405CLOCK = CPMC405CLOCK; // net ID: CPMC405CLOCK lsb: 0  msb: 0 INPUT
			this->CPMC405CORECLKINACTIVE = CPMC405CORECLKINACTIVE; // net ID: CPMC405CORECLKINACTIVE lsb: 0  msb: 0 INPUT
			this->CPMC405CPUCLKEN = CPMC405CPUCLKEN; // net ID: CPMC405CPUCLKEN lsb: 0  msb: 0 INPUT
			this->CPMC405JTAGCLKEN = CPMC405JTAGCLKEN; // net ID: CPMC405JTAGCLKEN lsb: 0  msb: 0 INPUT
			this->CPMC405SYNCBYPASS = CPMC405SYNCBYPASS; // net ID: CPMC405SYNCBYPASS lsb: 0  msb: 0 INPUT
			this->CPMC405TIMERCLKEN = CPMC405TIMERCLKEN; // net ID: CPMC405TIMERCLKEN lsb: 0  msb: 0 INPUT
			this->CPMC405TIMERTICK = CPMC405TIMERTICK; // net ID: CPMC405TIMERTICK lsb: 0  msb: 0 INPUT
			this->CPMDCRCLK = CPMDCRCLK; // net ID: CPMDCRCLK lsb: 0  msb: 0 INPUT
			this->CPMFCMCLK = CPMFCMCLK; // net ID: CPMFCMCLK lsb: 0  msb: 0 INPUT
			this->DBGC405DEBUGHALT = DBGC405DEBUGHALT; // net ID: DBGC405DEBUGHALT lsb: 0  msb: 0 INPUT
			this->DBGC405EXTBUSHOLDACK = DBGC405EXTBUSHOLDACK; // net ID: DBGC405EXTBUSHOLDACK lsb: 0  msb: 0 INPUT
			this->DBGC405UNCONDDEBUGEVENT = DBGC405UNCONDDEBUGEVENT; // net ID: DBGC405UNCONDDEBUGEVENT lsb: 0  msb: 0 INPUT
			this->DSARCVALUE = DSARCVALUE; // net ID: DSARCVALUE lsb: 7  msb: 0 INPUT
			this->DSCNTLVALUE = DSCNTLVALUE; // net ID: DSCNTLVALUE lsb: 7  msb: 0 INPUT
			this->DSOCMRWCOMPLETE = DSOCMRWCOMPLETE; // net ID: DSOCMRWCOMPLETE lsb: 0  msb: 0 INPUT
			this->EICC405CRITINPUTIRQ = EICC405CRITINPUTIRQ; // net ID: EICC405CRITINPUTIRQ lsb: 0  msb: 0 INPUT
			this->EICC405EXTINPUTIRQ = EICC405EXTINPUTIRQ; // net ID: EICC405EXTINPUTIRQ lsb: 0  msb: 0 INPUT
			this->EMACDCRACK = EMACDCRACK; // net ID: EMACDCRACK lsb: 0  msb: 0 INPUT
			this->EMACDCRDBUS = EMACDCRDBUS; // net ID: EMACDCRDBUS lsb: 31  msb: 0 INPUT
			this->EXTDCRACK = EXTDCRACK; // net ID: EXTDCRACK lsb: 0  msb: 0 INPUT
			this->EXTDCRDBUSIN = EXTDCRDBUSIN; // net ID: EXTDCRDBUSIN lsb: 31  msb: 0 INPUT
			this->FCMAPUCR = FCMAPUCR; // net ID: FCMAPUCR lsb: 3  msb: 0 INPUT
			this->FCMAPUDCDCREN = FCMAPUDCDCREN; // net ID: FCMAPUDCDCREN lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDFORCEALIGN = FCMAPUDCDFORCEALIGN; // net ID: FCMAPUDCDFORCEALIGN lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDFORCEBESTEERING = FCMAPUDCDFORCEBESTEERING; // net ID: FCMAPUDCDFORCEBESTEERING lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDFPUOP = FCMAPUDCDFPUOP; // net ID: FCMAPUDCDFPUOP lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDGPRWRITE = FCMAPUDCDGPRWRITE; // net ID: FCMAPUDCDGPRWRITE lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDLDSTBYTE = FCMAPUDCDLDSTBYTE; // net ID: FCMAPUDCDLDSTBYTE lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDLDSTDW = FCMAPUDCDLDSTDW; // net ID: FCMAPUDCDLDSTDW lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDLDSTHW = FCMAPUDCDLDSTHW; // net ID: FCMAPUDCDLDSTHW lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDLDSTQW = FCMAPUDCDLDSTQW; // net ID: FCMAPUDCDLDSTQW lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDLDSTWD = FCMAPUDCDLDSTWD; // net ID: FCMAPUDCDLDSTWD lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDLOAD = FCMAPUDCDLOAD; // net ID: FCMAPUDCDLOAD lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDPRIVOP = FCMAPUDCDPRIVOP; // net ID: FCMAPUDCDPRIVOP lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDRAEN = FCMAPUDCDRAEN; // net ID: FCMAPUDCDRAEN lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDRBEN = FCMAPUDCDRBEN; // net ID: FCMAPUDCDRBEN lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDSTORE = FCMAPUDCDSTORE; // net ID: FCMAPUDCDSTORE lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDTRAPBE = FCMAPUDCDTRAPBE; // net ID: FCMAPUDCDTRAPBE lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDTRAPLE = FCMAPUDCDTRAPLE; // net ID: FCMAPUDCDTRAPLE lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDUPDATE = FCMAPUDCDUPDATE; // net ID: FCMAPUDCDUPDATE lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDXERCAEN = FCMAPUDCDXERCAEN; // net ID: FCMAPUDCDXERCAEN lsb: 0  msb: 0 INPUT
			this->FCMAPUDCDXEROVEN = FCMAPUDCDXEROVEN; // net ID: FCMAPUDCDXEROVEN lsb: 0  msb: 0 INPUT
			this->FCMAPUDECODEBUSY = FCMAPUDECODEBUSY; // net ID: FCMAPUDECODEBUSY lsb: 0  msb: 0 INPUT
			this->FCMAPUDONE = FCMAPUDONE; // net ID: FCMAPUDONE lsb: 0  msb: 0 INPUT
			this->FCMAPUEXCEPTION = FCMAPUEXCEPTION; // net ID: FCMAPUEXCEPTION lsb: 0  msb: 0 INPUT
			this->FCMAPUEXEBLOCKINGMCO = FCMAPUEXEBLOCKINGMCO; // net ID: FCMAPUEXEBLOCKINGMCO lsb: 0  msb: 0 INPUT
			this->FCMAPUEXECRFIELD = FCMAPUEXECRFIELD; // net ID: FCMAPUEXECRFIELD lsb: 2  msb: 0 INPUT
			this->FCMAPUEXENONBLOCKINGMCO = FCMAPUEXENONBLOCKINGMCO; // net ID: FCMAPUEXENONBLOCKINGMCO lsb: 0  msb: 0 INPUT
			this->FCMAPUINSTRACK = FCMAPUINSTRACK; // net ID: FCMAPUINSTRACK lsb: 0  msb: 0 INPUT
			this->FCMAPULOADWAIT = FCMAPULOADWAIT; // net ID: FCMAPULOADWAIT lsb: 0  msb: 0 INPUT
			this->FCMAPURESULT = FCMAPURESULT; // net ID: FCMAPURESULT lsb: 31  msb: 0 INPUT
			this->FCMAPURESULTVALID = FCMAPURESULTVALID; // net ID: FCMAPURESULTVALID lsb: 0  msb: 0 INPUT
			this->FCMAPUSLEEPNOTREADY = FCMAPUSLEEPNOTREADY; // net ID: FCMAPUSLEEPNOTREADY lsb: 0  msb: 0 INPUT
			this->FCMAPUXERCA = FCMAPUXERCA; // net ID: FCMAPUXERCA lsb: 0  msb: 0 INPUT
			this->FCMAPUXEROV = FCMAPUXEROV; // net ID: FCMAPUXEROV lsb: 0  msb: 0 INPUT
			this->ISARCVALUE = ISARCVALUE; // net ID: ISARCVALUE lsb: 7  msb: 0 INPUT
			this->ISCNTLVALUE = ISCNTLVALUE; // net ID: ISCNTLVALUE lsb: 7  msb: 0 INPUT
			this->JTGC405BNDSCANTDO = JTGC405BNDSCANTDO; // net ID: JTGC405BNDSCANTDO lsb: 0  msb: 0 INPUT
			this->JTGC405TCK = JTGC405TCK; // net ID: JTGC405TCK lsb: 0  msb: 0 INPUT
			this->JTGC405TDI = JTGC405TDI; // net ID: JTGC405TDI lsb: 0  msb: 0 INPUT
			this->JTGC405TMS = JTGC405TMS; // net ID: JTGC405TMS lsb: 0  msb: 0 INPUT
			this->JTGC405TRSTNEG = JTGC405TRSTNEG; // net ID: JTGC405TRSTNEG lsb: 0  msb: 0 INPUT
			this->MCBCPUCLKEN = MCBCPUCLKEN; // net ID: MCBCPUCLKEN lsb: 0  msb: 0 INPUT
			this->MCBJTAGEN = MCBJTAGEN; // net ID: MCBJTAGEN lsb: 0  msb: 0 INPUT
			this->MCBTIMEREN = MCBTIMEREN; // net ID: MCBTIMEREN lsb: 0  msb: 0 INPUT
			this->MCPPCRST = MCPPCRST; // net ID: MCPPCRST lsb: 0  msb: 0 INPUT
			this->PLBC405DCUADDRACK = PLBC405DCUADDRACK; // net ID: PLBC405DCUADDRACK lsb: 0  msb: 0 INPUT
			this->PLBC405DCUBUSY = PLBC405DCUBUSY; // net ID: PLBC405DCUBUSY lsb: 0  msb: 0 INPUT
			this->PLBC405DCUERR = PLBC405DCUERR; // net ID: PLBC405DCUERR lsb: 0  msb: 0 INPUT
			this->PLBC405DCURDDACK = PLBC405DCURDDACK; // net ID: PLBC405DCURDDACK lsb: 0  msb: 0 INPUT
			this->PLBC405DCURDDBUS = PLBC405DCURDDBUS; // net ID: PLBC405DCURDDBUS lsb: 63  msb: 0 INPUT
			this->PLBC405DCURDWDADDR = PLBC405DCURDWDADDR; // net ID: PLBC405DCURDWDADDR lsb: 3  msb: 1 INPUT
			this->PLBC405DCUSSIZE1 = PLBC405DCUSSIZE1; // net ID: PLBC405DCUSSIZE1 lsb: 0  msb: 0 INPUT
			this->PLBC405DCUWRDACK = PLBC405DCUWRDACK; // net ID: PLBC405DCUWRDACK lsb: 0  msb: 0 INPUT
			this->PLBC405ICUADDRACK = PLBC405ICUADDRACK; // net ID: PLBC405ICUADDRACK lsb: 0  msb: 0 INPUT
			this->PLBC405ICUBUSY = PLBC405ICUBUSY; // net ID: PLBC405ICUBUSY lsb: 0  msb: 0 INPUT
			this->PLBC405ICUERR = PLBC405ICUERR; // net ID: PLBC405ICUERR lsb: 0  msb: 0 INPUT
			this->PLBC405ICURDDACK = PLBC405ICURDDACK; // net ID: PLBC405ICURDDACK lsb: 0  msb: 0 INPUT
			this->PLBC405ICURDDBUS = PLBC405ICURDDBUS; // net ID: PLBC405ICURDDBUS lsb: 63  msb: 0 INPUT
			this->PLBC405ICURDWDADDR = PLBC405ICURDWDADDR; // net ID: PLBC405ICURDWDADDR lsb: 3  msb: 1 INPUT
			this->PLBC405ICUSSIZE1 = PLBC405ICUSSIZE1; // net ID: PLBC405ICUSSIZE1 lsb: 0  msb: 0 INPUT
			this->PLBCLK = PLBCLK; // net ID: PLBCLK lsb: 0  msb: 0 INPUT
			this->RSTC405RESETCHIP = RSTC405RESETCHIP; // net ID: RSTC405RESETCHIP lsb: 0  msb: 0 INPUT
			this->RSTC405RESETCORE = RSTC405RESETCORE; // net ID: RSTC405RESETCORE lsb: 0  msb: 0 INPUT
			this->RSTC405RESETSYS = RSTC405RESETSYS; // net ID: RSTC405RESETSYS lsb: 0  msb: 0 INPUT
			this->TIEAPUCONTROL = TIEAPUCONTROL; // net ID: TIEAPUCONTROL lsb: 15  msb: 0 INPUT
			this->TIEAPUUDI1 = TIEAPUUDI1; // net ID: TIEAPUUDI1 lsb: 23  msb: 0 INPUT
			this->TIEAPUUDI2 = TIEAPUUDI2; // net ID: TIEAPUUDI2 lsb: 23  msb: 0 INPUT
			this->TIEAPUUDI3 = TIEAPUUDI3; // net ID: TIEAPUUDI3 lsb: 23  msb: 0 INPUT
			this->TIEAPUUDI4 = TIEAPUUDI4; // net ID: TIEAPUUDI4 lsb: 23  msb: 0 INPUT
			this->TIEAPUUDI5 = TIEAPUUDI5; // net ID: TIEAPUUDI5 lsb: 23  msb: 0 INPUT
			this->TIEAPUUDI6 = TIEAPUUDI6; // net ID: TIEAPUUDI6 lsb: 23  msb: 0 INPUT
			this->TIEAPUUDI7 = TIEAPUUDI7; // net ID: TIEAPUUDI7 lsb: 23  msb: 0 INPUT
			this->TIEAPUUDI8 = TIEAPUUDI8; // net ID: TIEAPUUDI8 lsb: 23  msb: 0 INPUT
			this->TIEC405DETERMINISTICMULT = TIEC405DETERMINISTICMULT; // net ID: TIEC405DETERMINISTICMULT lsb: 0  msb: 0 INPUT
			this->TIEC405DISOPERANDFWD = TIEC405DISOPERANDFWD; // net ID: TIEC405DISOPERANDFWD lsb: 0  msb: 0 INPUT
			this->TIEC405MMUEN = TIEC405MMUEN; // net ID: TIEC405MMUEN lsb: 0  msb: 0 INPUT
			this->TIEDCRADDR = TIEDCRADDR; // net ID: TIEDCRADDR lsb: 5  msb: 0 INPUT
			this->TIEPVRBIT10 = TIEPVRBIT10; // net ID: TIEPVRBIT10 lsb: 0  msb: 0 INPUT
			this->TIEPVRBIT11 = TIEPVRBIT11; // net ID: TIEPVRBIT11 lsb: 0  msb: 0 INPUT
			this->TIEPVRBIT28 = TIEPVRBIT28; // net ID: TIEPVRBIT28 lsb: 0  msb: 0 INPUT
			this->TIEPVRBIT29 = TIEPVRBIT29; // net ID: TIEPVRBIT29 lsb: 0  msb: 0 INPUT
			this->TIEPVRBIT30 = TIEPVRBIT30; // net ID: TIEPVRBIT30 lsb: 0  msb: 0 INPUT
			this->TIEPVRBIT31 = TIEPVRBIT31; // net ID: TIEPVRBIT31 lsb: 0  msb: 0 INPUT
			this->TIEPVRBIT8 = TIEPVRBIT8; // net ID: TIEPVRBIT8 lsb: 0  msb: 0 INPUT
			this->TIEPVRBIT9 = TIEPVRBIT9; // net ID: TIEPVRBIT9 lsb: 0  msb: 0 INPUT
			this->TRCC405TRACEDISABLE = TRCC405TRACEDISABLE; // net ID: TRCC405TRACEDISABLE lsb: 0  msb: 0 INPUT
			this->TRCC405TRIGGEREVENTIN = TRCC405TRIGGEREVENTIN; // net ID: TRCC405TRIGGEREVENTIN lsb: 0  msb: 0 INPUT
			
			register_wait_on_event_nets();
			
		}
		
		void register_wait_on_event_nets(){
		// TODO
		}
		void calculate(int time){
		// TODO
		}
		};
		


}
