/******************************************************************************
 * Generated Cpp template for simulation primitives.
 * Author: Benedek Racz
 ******************************************************************************/

#include "NetFlow.h"
#include "sim_types.h"

namespace CPrimitives {

	class X_PPC405_ADV{

		//Verilog Parameters:
		parameter_string_t LOC;
		parameter_int_t in_delay;
		parameter_int_t out_delay;
		//Verilog Ports in definition order:
		NetFlow* APUFCMDECODED; // OUTPUT
		NetFlow* APUFCMDECUDI; // OUTPUT
		NetFlow* APUFCMDECUDIVALID; // OUTPUT
		NetFlow* APUFCMENDIAN; // OUTPUT
		NetFlow* APUFCMFLUSH; // OUTPUT
		NetFlow* APUFCMINSTRUCTION; // OUTPUT
		NetFlow* APUFCMINSTRVALID; // OUTPUT
		NetFlow* APUFCMLOADBYTEEN; // OUTPUT
		NetFlow* APUFCMLOADDATA; // OUTPUT
		NetFlow* APUFCMLOADDVALID; // OUTPUT
		NetFlow* APUFCMOPERANDVALID; // OUTPUT
		NetFlow* APUFCMRADATA; // OUTPUT
		NetFlow* APUFCMRBDATA; // OUTPUT
		NetFlow* APUFCMWRITEBACKOK; // OUTPUT
		NetFlow* APUFCMXERCA; // OUTPUT
		NetFlow* C405CPMCORESLEEPREQ; // OUTPUT
		NetFlow* C405CPMMSRCE; // OUTPUT
		NetFlow* C405CPMMSREE; // OUTPUT
		NetFlow* C405CPMTIMERIRQ; // OUTPUT
		NetFlow* C405CPMTIMERRESETREQ; // OUTPUT
		NetFlow* C405DBGLOADDATAONAPUDBUS; // OUTPUT
		NetFlow* C405DBGMSRWE; // OUTPUT
		NetFlow* C405DBGSTOPACK; // OUTPUT
		NetFlow* C405DBGWBCOMPLETE; // OUTPUT
		NetFlow* C405DBGWBFULL; // OUTPUT
		NetFlow* C405DBGWBIAR; // OUTPUT
		NetFlow* C405JTGCAPTUREDR; // OUTPUT
		NetFlow* C405JTGEXTEST; // OUTPUT
		NetFlow* C405JTGPGMOUT; // OUTPUT
		NetFlow* C405JTGSHIFTDR; // OUTPUT
		NetFlow* C405JTGTDO; // OUTPUT
		NetFlow* C405JTGTDOEN; // OUTPUT
		NetFlow* C405JTGUPDATEDR; // OUTPUT
		NetFlow* C405PLBDCUABORT; // OUTPUT
		NetFlow* C405PLBDCUABUS; // OUTPUT
		NetFlow* C405PLBDCUBE; // OUTPUT
		NetFlow* C405PLBDCUCACHEABLE; // OUTPUT
		NetFlow* C405PLBDCUGUARDED; // OUTPUT
		NetFlow* C405PLBDCUPRIORITY; // OUTPUT
		NetFlow* C405PLBDCUREQUEST; // OUTPUT
		NetFlow* C405PLBDCURNW; // OUTPUT
		NetFlow* C405PLBDCUSIZE2; // OUTPUT
		NetFlow* C405PLBDCUU0ATTR; // OUTPUT
		NetFlow* C405PLBDCUWRDBUS; // OUTPUT
		NetFlow* C405PLBDCUWRITETHRU; // OUTPUT
		NetFlow* C405PLBICUABORT; // OUTPUT
		NetFlow* C405PLBICUABUS; // OUTPUT
		NetFlow* C405PLBICUCACHEABLE; // OUTPUT
		NetFlow* C405PLBICUPRIORITY; // OUTPUT
		NetFlow* C405PLBICUREQUEST; // OUTPUT
		NetFlow* C405PLBICUSIZE; // OUTPUT
		NetFlow* C405PLBICUU0ATTR; // OUTPUT
		NetFlow* C405RSTCHIPRESETREQ; // OUTPUT
		NetFlow* C405RSTCORERESETREQ; // OUTPUT
		NetFlow* C405RSTSYSRESETREQ; // OUTPUT
		NetFlow* C405TRCCYCLE; // OUTPUT
		NetFlow* C405TRCEVENEXECUTIONSTATUS; // OUTPUT
		NetFlow* C405TRCODDEXECUTIONSTATUS; // OUTPUT
		NetFlow* C405TRCTRACESTATUS; // OUTPUT
		NetFlow* C405TRCTRIGGEREVENTOUT; // OUTPUT
		NetFlow* C405TRCTRIGGEREVENTTYPE; // OUTPUT
		NetFlow* C405XXXMACHINECHECK; // OUTPUT
		NetFlow* DCREMACABUS; // OUTPUT
		NetFlow* DCREMACCLK; // OUTPUT
		NetFlow* DCREMACDBUS; // OUTPUT
		NetFlow* DCREMACENABLER; // OUTPUT
		NetFlow* DCREMACREAD; // OUTPUT
		NetFlow* DCREMACWRITE; // OUTPUT
		NetFlow* DSOCMBRAMABUS; // OUTPUT
		NetFlow* DSOCMBRAMBYTEWRITE; // OUTPUT
		NetFlow* DSOCMBRAMEN; // OUTPUT
		NetFlow* DSOCMBRAMWRDBUS; // OUTPUT
		NetFlow* DSOCMBUSY; // OUTPUT
		NetFlow* DSOCMRDADDRVALID; // OUTPUT
		NetFlow* DSOCMWRADDRVALID; // OUTPUT
		NetFlow* EXTDCRABUS; // OUTPUT
		NetFlow* EXTDCRDBUSOUT; // OUTPUT
		NetFlow* EXTDCRREAD; // OUTPUT
		NetFlow* EXTDCRWRITE; // OUTPUT
		NetFlow* ISOCMBRAMEN; // OUTPUT
		NetFlow* ISOCMBRAMEVENWRITEEN; // OUTPUT
		NetFlow* ISOCMBRAMODDWRITEEN; // OUTPUT
		NetFlow* ISOCMBRAMRDABUS; // OUTPUT
		NetFlow* ISOCMBRAMWRABUS; // OUTPUT
		NetFlow* ISOCMBRAMWRDBUS; // OUTPUT
		NetFlow* ISOCMDCRBRAMEVENEN; // OUTPUT
		NetFlow* ISOCMDCRBRAMODDEN; // OUTPUT
		NetFlow* ISOCMDCRBRAMRDSELECT; // OUTPUT
		NetFlow* BRAMDSOCMCLK; // INPUT
		NetFlow* BRAMDSOCMRDDBUS; // INPUT
		NetFlow* BRAMISOCMCLK; // INPUT
		NetFlow* BRAMISOCMDCRRDDBUS; // INPUT
		NetFlow* BRAMISOCMRDDBUS; // INPUT
		NetFlow* CPMC405CLOCK; // INPUT
		NetFlow* CPMC405CORECLKINACTIVE; // INPUT
		NetFlow* CPMC405CPUCLKEN; // INPUT
		NetFlow* CPMC405JTAGCLKEN; // INPUT
		NetFlow* CPMC405SYNCBYPASS; // INPUT
		NetFlow* CPMC405TIMERCLKEN; // INPUT
		NetFlow* CPMC405TIMERTICK; // INPUT
		NetFlow* CPMDCRCLK; // INPUT
		NetFlow* CPMFCMCLK; // INPUT
		NetFlow* DBGC405DEBUGHALT; // INPUT
		NetFlow* DBGC405EXTBUSHOLDACK; // INPUT
		NetFlow* DBGC405UNCONDDEBUGEVENT; // INPUT
		NetFlow* DSARCVALUE; // INPUT
		NetFlow* DSCNTLVALUE; // INPUT
		NetFlow* DSOCMRWCOMPLETE; // INPUT
		NetFlow* EICC405CRITINPUTIRQ; // INPUT
		NetFlow* EICC405EXTINPUTIRQ; // INPUT
		NetFlow* EMACDCRACK; // INPUT
		NetFlow* EMACDCRDBUS; // INPUT
		NetFlow* EXTDCRACK; // INPUT
		NetFlow* EXTDCRDBUSIN; // INPUT
		NetFlow* FCMAPUCR; // INPUT
		NetFlow* FCMAPUDCDCREN; // INPUT
		NetFlow* FCMAPUDCDFORCEALIGN; // INPUT
		NetFlow* FCMAPUDCDFORCEBESTEERING; // INPUT
		NetFlow* FCMAPUDCDFPUOP; // INPUT
		NetFlow* FCMAPUDCDGPRWRITE; // INPUT
		NetFlow* FCMAPUDCDLDSTBYTE; // INPUT
		NetFlow* FCMAPUDCDLDSTDW; // INPUT
		NetFlow* FCMAPUDCDLDSTHW; // INPUT
		NetFlow* FCMAPUDCDLDSTQW; // INPUT
		NetFlow* FCMAPUDCDLDSTWD; // INPUT
		NetFlow* FCMAPUDCDLOAD; // INPUT
		NetFlow* FCMAPUDCDPRIVOP; // INPUT
		NetFlow* FCMAPUDCDRAEN; // INPUT
		NetFlow* FCMAPUDCDRBEN; // INPUT
		NetFlow* FCMAPUDCDSTORE; // INPUT
		NetFlow* FCMAPUDCDTRAPBE; // INPUT
		NetFlow* FCMAPUDCDTRAPLE; // INPUT
		NetFlow* FCMAPUDCDUPDATE; // INPUT
		NetFlow* FCMAPUDCDXERCAEN; // INPUT
		NetFlow* FCMAPUDCDXEROVEN; // INPUT
		NetFlow* FCMAPUDECODEBUSY; // INPUT
		NetFlow* FCMAPUDONE; // INPUT
		NetFlow* FCMAPUEXCEPTION; // INPUT
		NetFlow* FCMAPUEXEBLOCKINGMCO; // INPUT
		NetFlow* FCMAPUEXECRFIELD; // INPUT
		NetFlow* FCMAPUEXENONBLOCKINGMCO; // INPUT
		NetFlow* FCMAPUINSTRACK; // INPUT
		NetFlow* FCMAPULOADWAIT; // INPUT
		NetFlow* FCMAPURESULT; // INPUT
		NetFlow* FCMAPURESULTVALID; // INPUT
		NetFlow* FCMAPUSLEEPNOTREADY; // INPUT
		NetFlow* FCMAPUXERCA; // INPUT
		NetFlow* FCMAPUXEROV; // INPUT
		NetFlow* ISARCVALUE; // INPUT
		NetFlow* ISCNTLVALUE; // INPUT
		NetFlow* JTGC405BNDSCANTDO; // INPUT
		NetFlow* JTGC405TCK; // INPUT
		NetFlow* JTGC405TDI; // INPUT
		NetFlow* JTGC405TMS; // INPUT
		NetFlow* JTGC405TRSTNEG; // INPUT
		NetFlow* MCBCPUCLKEN; // INPUT
		NetFlow* MCBJTAGEN; // INPUT
		NetFlow* MCBTIMEREN; // INPUT
		NetFlow* MCPPCRST; // INPUT
		NetFlow* PLBC405DCUADDRACK; // INPUT
		NetFlow* PLBC405DCUBUSY; // INPUT
		NetFlow* PLBC405DCUERR; // INPUT
		NetFlow* PLBC405DCURDDACK; // INPUT
		NetFlow* PLBC405DCURDDBUS; // INPUT
		NetFlow* PLBC405DCURDWDADDR; // INPUT
		NetFlow* PLBC405DCUSSIZE1; // INPUT
		NetFlow* PLBC405DCUWRDACK; // INPUT
		NetFlow* PLBC405ICUADDRACK; // INPUT
		NetFlow* PLBC405ICUBUSY; // INPUT
		NetFlow* PLBC405ICUERR; // INPUT
		NetFlow* PLBC405ICURDDACK; // INPUT
		NetFlow* PLBC405ICURDDBUS; // INPUT
		NetFlow* PLBC405ICURDWDADDR; // INPUT
		NetFlow* PLBC405ICUSSIZE1; // INPUT
		NetFlow* PLBCLK; // INPUT
		NetFlow* RSTC405RESETCHIP; // INPUT
		NetFlow* RSTC405RESETCORE; // INPUT
		NetFlow* RSTC405RESETSYS; // INPUT
		NetFlow* TIEAPUCONTROL; // INPUT
		NetFlow* TIEAPUUDI1; // INPUT
		NetFlow* TIEAPUUDI2; // INPUT
		NetFlow* TIEAPUUDI3; // INPUT
		NetFlow* TIEAPUUDI4; // INPUT
		NetFlow* TIEAPUUDI5; // INPUT
		NetFlow* TIEAPUUDI6; // INPUT
		NetFlow* TIEAPUUDI7; // INPUT
		NetFlow* TIEAPUUDI8; // INPUT
		NetFlow* TIEC405DETERMINISTICMULT; // INPUT
		NetFlow* TIEC405DISOPERANDFWD; // INPUT
		NetFlow* TIEC405MMUEN; // INPUT
		NetFlow* TIEDCRADDR; // INPUT
		NetFlow* TIEPVRBIT10; // INPUT
		NetFlow* TIEPVRBIT11; // INPUT
		NetFlow* TIEPVRBIT28; // INPUT
		NetFlow* TIEPVRBIT29; // INPUT
		NetFlow* TIEPVRBIT30; // INPUT
		NetFlow* TIEPVRBIT31; // INPUT
		NetFlow* TIEPVRBIT8; // INPUT
		NetFlow* TIEPVRBIT9; // INPUT
		NetFlow* TRCC405TRACEDISABLE; // INPUT
		NetFlow* TRCC405TRIGGEREVENTIN; // INPUT
		
	
		X_PPC405_ADV(
			//Verilog Parameters:
			parameter_string_t LOC, // Default: "UNPLACED"
			parameter_int_t in_delay, // Default: 1
			parameter_int_t out_delay, // Default: 0
			//Verilog Ports in definition order:
			NetFlow* APUFCMDECODED, // OUTPUT
			NetFlow* APUFCMDECUDI, // OUTPUT
			NetFlow* APUFCMDECUDIVALID, // OUTPUT
			NetFlow* APUFCMENDIAN, // OUTPUT
			NetFlow* APUFCMFLUSH, // OUTPUT
			NetFlow* APUFCMINSTRUCTION, // OUTPUT
			NetFlow* APUFCMINSTRVALID, // OUTPUT
			NetFlow* APUFCMLOADBYTEEN, // OUTPUT
			NetFlow* APUFCMLOADDATA, // OUTPUT
			NetFlow* APUFCMLOADDVALID, // OUTPUT
			NetFlow* APUFCMOPERANDVALID, // OUTPUT
			NetFlow* APUFCMRADATA, // OUTPUT
			NetFlow* APUFCMRBDATA, // OUTPUT
			NetFlow* APUFCMWRITEBACKOK, // OUTPUT
			NetFlow* APUFCMXERCA, // OUTPUT
			NetFlow* C405CPMCORESLEEPREQ, // OUTPUT
			NetFlow* C405CPMMSRCE, // OUTPUT
			NetFlow* C405CPMMSREE, // OUTPUT
			NetFlow* C405CPMTIMERIRQ, // OUTPUT
			NetFlow* C405CPMTIMERRESETREQ, // OUTPUT
			NetFlow* C405DBGLOADDATAONAPUDBUS, // OUTPUT
			NetFlow* C405DBGMSRWE, // OUTPUT
			NetFlow* C405DBGSTOPACK, // OUTPUT
			NetFlow* C405DBGWBCOMPLETE, // OUTPUT
			NetFlow* C405DBGWBFULL, // OUTPUT
			NetFlow* C405DBGWBIAR, // OUTPUT
			NetFlow* C405JTGCAPTUREDR, // OUTPUT
			NetFlow* C405JTGEXTEST, // OUTPUT
			NetFlow* C405JTGPGMOUT, // OUTPUT
			NetFlow* C405JTGSHIFTDR, // OUTPUT
			NetFlow* C405JTGTDO, // OUTPUT
			NetFlow* C405JTGTDOEN, // OUTPUT
			NetFlow* C405JTGUPDATEDR, // OUTPUT
			NetFlow* C405PLBDCUABORT, // OUTPUT
			NetFlow* C405PLBDCUABUS, // OUTPUT
			NetFlow* C405PLBDCUBE, // OUTPUT
			NetFlow* C405PLBDCUCACHEABLE, // OUTPUT
			NetFlow* C405PLBDCUGUARDED, // OUTPUT
			NetFlow* C405PLBDCUPRIORITY, // OUTPUT
			NetFlow* C405PLBDCUREQUEST, // OUTPUT
			NetFlow* C405PLBDCURNW, // OUTPUT
			NetFlow* C405PLBDCUSIZE2, // OUTPUT
			NetFlow* C405PLBDCUU0ATTR, // OUTPUT
			NetFlow* C405PLBDCUWRDBUS, // OUTPUT
			NetFlow* C405PLBDCUWRITETHRU, // OUTPUT
			NetFlow* C405PLBICUABORT, // OUTPUT
			NetFlow* C405PLBICUABUS, // OUTPUT
			NetFlow* C405PLBICUCACHEABLE, // OUTPUT
			NetFlow* C405PLBICUPRIORITY, // OUTPUT
			NetFlow* C405PLBICUREQUEST, // OUTPUT
			NetFlow* C405PLBICUSIZE, // OUTPUT
			NetFlow* C405PLBICUU0ATTR, // OUTPUT
			NetFlow* C405RSTCHIPRESETREQ, // OUTPUT
			NetFlow* C405RSTCORERESETREQ, // OUTPUT
			NetFlow* C405RSTSYSRESETREQ, // OUTPUT
			NetFlow* C405TRCCYCLE, // OUTPUT
			NetFlow* C405TRCEVENEXECUTIONSTATUS, // OUTPUT
			NetFlow* C405TRCODDEXECUTIONSTATUS, // OUTPUT
			NetFlow* C405TRCTRACESTATUS, // OUTPUT
			NetFlow* C405TRCTRIGGEREVENTOUT, // OUTPUT
			NetFlow* C405TRCTRIGGEREVENTTYPE, // OUTPUT
			NetFlow* C405XXXMACHINECHECK, // OUTPUT
			NetFlow* DCREMACABUS, // OUTPUT
			NetFlow* DCREMACCLK, // OUTPUT
			NetFlow* DCREMACDBUS, // OUTPUT
			NetFlow* DCREMACENABLER, // OUTPUT
			NetFlow* DCREMACREAD, // OUTPUT
			NetFlow* DCREMACWRITE, // OUTPUT
			NetFlow* DSOCMBRAMABUS, // OUTPUT
			NetFlow* DSOCMBRAMBYTEWRITE, // OUTPUT
			NetFlow* DSOCMBRAMEN, // OUTPUT
			NetFlow* DSOCMBRAMWRDBUS, // OUTPUT
			NetFlow* DSOCMBUSY, // OUTPUT
			NetFlow* DSOCMRDADDRVALID, // OUTPUT
			NetFlow* DSOCMWRADDRVALID, // OUTPUT
			NetFlow* EXTDCRABUS, // OUTPUT
			NetFlow* EXTDCRDBUSOUT, // OUTPUT
			NetFlow* EXTDCRREAD, // OUTPUT
			NetFlow* EXTDCRWRITE, // OUTPUT
			NetFlow* ISOCMBRAMEN, // OUTPUT
			NetFlow* ISOCMBRAMEVENWRITEEN, // OUTPUT
			NetFlow* ISOCMBRAMODDWRITEEN, // OUTPUT
			NetFlow* ISOCMBRAMRDABUS, // OUTPUT
			NetFlow* ISOCMBRAMWRABUS, // OUTPUT
			NetFlow* ISOCMBRAMWRDBUS, // OUTPUT
			NetFlow* ISOCMDCRBRAMEVENEN, // OUTPUT
			NetFlow* ISOCMDCRBRAMODDEN, // OUTPUT
			NetFlow* ISOCMDCRBRAMRDSELECT, // OUTPUT
			NetFlow* BRAMDSOCMCLK, // INPUT
			NetFlow* BRAMDSOCMRDDBUS, // INPUT
			NetFlow* BRAMISOCMCLK, // INPUT
			NetFlow* BRAMISOCMDCRRDDBUS, // INPUT
			NetFlow* BRAMISOCMRDDBUS, // INPUT
			NetFlow* CPMC405CLOCK, // INPUT
			NetFlow* CPMC405CORECLKINACTIVE, // INPUT
			NetFlow* CPMC405CPUCLKEN, // INPUT
			NetFlow* CPMC405JTAGCLKEN, // INPUT
			NetFlow* CPMC405SYNCBYPASS, // INPUT
			NetFlow* CPMC405TIMERCLKEN, // INPUT
			NetFlow* CPMC405TIMERTICK, // INPUT
			NetFlow* CPMDCRCLK, // INPUT
			NetFlow* CPMFCMCLK, // INPUT
			NetFlow* DBGC405DEBUGHALT, // INPUT
			NetFlow* DBGC405EXTBUSHOLDACK, // INPUT
			NetFlow* DBGC405UNCONDDEBUGEVENT, // INPUT
			NetFlow* DSARCVALUE, // INPUT
			NetFlow* DSCNTLVALUE, // INPUT
			NetFlow* DSOCMRWCOMPLETE, // INPUT
			NetFlow* EICC405CRITINPUTIRQ, // INPUT
			NetFlow* EICC405EXTINPUTIRQ, // INPUT
			NetFlow* EMACDCRACK, // INPUT
			NetFlow* EMACDCRDBUS, // INPUT
			NetFlow* EXTDCRACK, // INPUT
			NetFlow* EXTDCRDBUSIN, // INPUT
			NetFlow* FCMAPUCR, // INPUT
			NetFlow* FCMAPUDCDCREN, // INPUT
			NetFlow* FCMAPUDCDFORCEALIGN, // INPUT
			NetFlow* FCMAPUDCDFORCEBESTEERING, // INPUT
			NetFlow* FCMAPUDCDFPUOP, // INPUT
			NetFlow* FCMAPUDCDGPRWRITE, // INPUT
			NetFlow* FCMAPUDCDLDSTBYTE, // INPUT
			NetFlow* FCMAPUDCDLDSTDW, // INPUT
			NetFlow* FCMAPUDCDLDSTHW, // INPUT
			NetFlow* FCMAPUDCDLDSTQW, // INPUT
			NetFlow* FCMAPUDCDLDSTWD, // INPUT
			NetFlow* FCMAPUDCDLOAD, // INPUT
			NetFlow* FCMAPUDCDPRIVOP, // INPUT
			NetFlow* FCMAPUDCDRAEN, // INPUT
			NetFlow* FCMAPUDCDRBEN, // INPUT
			NetFlow* FCMAPUDCDSTORE, // INPUT
			NetFlow* FCMAPUDCDTRAPBE, // INPUT
			NetFlow* FCMAPUDCDTRAPLE, // INPUT
			NetFlow* FCMAPUDCDUPDATE, // INPUT
			NetFlow* FCMAPUDCDXERCAEN, // INPUT
			NetFlow* FCMAPUDCDXEROVEN, // INPUT
			NetFlow* FCMAPUDECODEBUSY, // INPUT
			NetFlow* FCMAPUDONE, // INPUT
			NetFlow* FCMAPUEXCEPTION, // INPUT
			NetFlow* FCMAPUEXEBLOCKINGMCO, // INPUT
			NetFlow* FCMAPUEXECRFIELD, // INPUT
			NetFlow* FCMAPUEXENONBLOCKINGMCO, // INPUT
			NetFlow* FCMAPUINSTRACK, // INPUT
			NetFlow* FCMAPULOADWAIT, // INPUT
			NetFlow* FCMAPURESULT, // INPUT
			NetFlow* FCMAPURESULTVALID, // INPUT
			NetFlow* FCMAPUSLEEPNOTREADY, // INPUT
			NetFlow* FCMAPUXERCA, // INPUT
			NetFlow* FCMAPUXEROV, // INPUT
			NetFlow* ISARCVALUE, // INPUT
			NetFlow* ISCNTLVALUE, // INPUT
			NetFlow* JTGC405BNDSCANTDO, // INPUT
			NetFlow* JTGC405TCK, // INPUT
			NetFlow* JTGC405TDI, // INPUT
			NetFlow* JTGC405TMS, // INPUT
			NetFlow* JTGC405TRSTNEG, // INPUT
			NetFlow* MCBCPUCLKEN, // INPUT
			NetFlow* MCBJTAGEN, // INPUT
			NetFlow* MCBTIMEREN, // INPUT
			NetFlow* MCPPCRST, // INPUT
			NetFlow* PLBC405DCUADDRACK, // INPUT
			NetFlow* PLBC405DCUBUSY, // INPUT
			NetFlow* PLBC405DCUERR, // INPUT
			NetFlow* PLBC405DCURDDACK, // INPUT
			NetFlow* PLBC405DCURDDBUS, // INPUT
			NetFlow* PLBC405DCURDWDADDR, // INPUT
			NetFlow* PLBC405DCUSSIZE1, // INPUT
			NetFlow* PLBC405DCUWRDACK, // INPUT
			NetFlow* PLBC405ICUADDRACK, // INPUT
			NetFlow* PLBC405ICUBUSY, // INPUT
			NetFlow* PLBC405ICUERR, // INPUT
			NetFlow* PLBC405ICURDDACK, // INPUT
			NetFlow* PLBC405ICURDDBUS, // INPUT
			NetFlow* PLBC405ICURDWDADDR, // INPUT
			NetFlow* PLBC405ICUSSIZE1, // INPUT
			NetFlow* PLBCLK, // INPUT
			NetFlow* RSTC405RESETCHIP, // INPUT
			NetFlow* RSTC405RESETCORE, // INPUT
			NetFlow* RSTC405RESETSYS, // INPUT
			NetFlow* TIEAPUCONTROL, // INPUT
			NetFlow* TIEAPUUDI1, // INPUT
			NetFlow* TIEAPUUDI2, // INPUT
			NetFlow* TIEAPUUDI3, // INPUT
			NetFlow* TIEAPUUDI4, // INPUT
			NetFlow* TIEAPUUDI5, // INPUT
			NetFlow* TIEAPUUDI6, // INPUT
			NetFlow* TIEAPUUDI7, // INPUT
			NetFlow* TIEAPUUDI8, // INPUT
			NetFlow* TIEC405DETERMINISTICMULT, // INPUT
			NetFlow* TIEC405DISOPERANDFWD, // INPUT
			NetFlow* TIEC405MMUEN, // INPUT
			NetFlow* TIEDCRADDR, // INPUT
			NetFlow* TIEPVRBIT10, // INPUT
			NetFlow* TIEPVRBIT11, // INPUT
			NetFlow* TIEPVRBIT28, // INPUT
			NetFlow* TIEPVRBIT29, // INPUT
			NetFlow* TIEPVRBIT30, // INPUT
			NetFlow* TIEPVRBIT31, // INPUT
			NetFlow* TIEPVRBIT8, // INPUT
			NetFlow* TIEPVRBIT9, // INPUT
			NetFlow* TRCC405TRACEDISABLE, // INPUT
			NetFlow* TRCC405TRIGGEREVENTIN // INPUT
			){
		
			// Assign parameters and ports: 
			//Verilog Parameters:
			this->LOC = LOC; // Default: "UNPLACED"
			this->in_delay = in_delay; // Default: 1
			this->out_delay = out_delay; // Default: 0
			//Verilog Ports in definition order:
			this->APUFCMDECODED = APUFCMDECODED; // OUTPUT
			this->APUFCMDECUDI = APUFCMDECUDI; // OUTPUT
			this->APUFCMDECUDIVALID = APUFCMDECUDIVALID; // OUTPUT
			this->APUFCMENDIAN = APUFCMENDIAN; // OUTPUT
			this->APUFCMFLUSH = APUFCMFLUSH; // OUTPUT
			this->APUFCMINSTRUCTION = APUFCMINSTRUCTION; // OUTPUT
			this->APUFCMINSTRVALID = APUFCMINSTRVALID; // OUTPUT
			this->APUFCMLOADBYTEEN = APUFCMLOADBYTEEN; // OUTPUT
			this->APUFCMLOADDATA = APUFCMLOADDATA; // OUTPUT
			this->APUFCMLOADDVALID = APUFCMLOADDVALID; // OUTPUT
			this->APUFCMOPERANDVALID = APUFCMOPERANDVALID; // OUTPUT
			this->APUFCMRADATA = APUFCMRADATA; // OUTPUT
			this->APUFCMRBDATA = APUFCMRBDATA; // OUTPUT
			this->APUFCMWRITEBACKOK = APUFCMWRITEBACKOK; // OUTPUT
			this->APUFCMXERCA = APUFCMXERCA; // OUTPUT
			this->C405CPMCORESLEEPREQ = C405CPMCORESLEEPREQ; // OUTPUT
			this->C405CPMMSRCE = C405CPMMSRCE; // OUTPUT
			this->C405CPMMSREE = C405CPMMSREE; // OUTPUT
			this->C405CPMTIMERIRQ = C405CPMTIMERIRQ; // OUTPUT
			this->C405CPMTIMERRESETREQ = C405CPMTIMERRESETREQ; // OUTPUT
			this->C405DBGLOADDATAONAPUDBUS = C405DBGLOADDATAONAPUDBUS; // OUTPUT
			this->C405DBGMSRWE = C405DBGMSRWE; // OUTPUT
			this->C405DBGSTOPACK = C405DBGSTOPACK; // OUTPUT
			this->C405DBGWBCOMPLETE = C405DBGWBCOMPLETE; // OUTPUT
			this->C405DBGWBFULL = C405DBGWBFULL; // OUTPUT
			this->C405DBGWBIAR = C405DBGWBIAR; // OUTPUT
			this->C405JTGCAPTUREDR = C405JTGCAPTUREDR; // OUTPUT
			this->C405JTGEXTEST = C405JTGEXTEST; // OUTPUT
			this->C405JTGPGMOUT = C405JTGPGMOUT; // OUTPUT
			this->C405JTGSHIFTDR = C405JTGSHIFTDR; // OUTPUT
			this->C405JTGTDO = C405JTGTDO; // OUTPUT
			this->C405JTGTDOEN = C405JTGTDOEN; // OUTPUT
			this->C405JTGUPDATEDR = C405JTGUPDATEDR; // OUTPUT
			this->C405PLBDCUABORT = C405PLBDCUABORT; // OUTPUT
			this->C405PLBDCUABUS = C405PLBDCUABUS; // OUTPUT
			this->C405PLBDCUBE = C405PLBDCUBE; // OUTPUT
			this->C405PLBDCUCACHEABLE = C405PLBDCUCACHEABLE; // OUTPUT
			this->C405PLBDCUGUARDED = C405PLBDCUGUARDED; // OUTPUT
			this->C405PLBDCUPRIORITY = C405PLBDCUPRIORITY; // OUTPUT
			this->C405PLBDCUREQUEST = C405PLBDCUREQUEST; // OUTPUT
			this->C405PLBDCURNW = C405PLBDCURNW; // OUTPUT
			this->C405PLBDCUSIZE2 = C405PLBDCUSIZE2; // OUTPUT
			this->C405PLBDCUU0ATTR = C405PLBDCUU0ATTR; // OUTPUT
			this->C405PLBDCUWRDBUS = C405PLBDCUWRDBUS; // OUTPUT
			this->C405PLBDCUWRITETHRU = C405PLBDCUWRITETHRU; // OUTPUT
			this->C405PLBICUABORT = C405PLBICUABORT; // OUTPUT
			this->C405PLBICUABUS = C405PLBICUABUS; // OUTPUT
			this->C405PLBICUCACHEABLE = C405PLBICUCACHEABLE; // OUTPUT
			this->C405PLBICUPRIORITY = C405PLBICUPRIORITY; // OUTPUT
			this->C405PLBICUREQUEST = C405PLBICUREQUEST; // OUTPUT
			this->C405PLBICUSIZE = C405PLBICUSIZE; // OUTPUT
			this->C405PLBICUU0ATTR = C405PLBICUU0ATTR; // OUTPUT
			this->C405RSTCHIPRESETREQ = C405RSTCHIPRESETREQ; // OUTPUT
			this->C405RSTCORERESETREQ = C405RSTCORERESETREQ; // OUTPUT
			this->C405RSTSYSRESETREQ = C405RSTSYSRESETREQ; // OUTPUT
			this->C405TRCCYCLE = C405TRCCYCLE; // OUTPUT
			this->C405TRCEVENEXECUTIONSTATUS = C405TRCEVENEXECUTIONSTATUS; // OUTPUT
			this->C405TRCODDEXECUTIONSTATUS = C405TRCODDEXECUTIONSTATUS; // OUTPUT
			this->C405TRCTRACESTATUS = C405TRCTRACESTATUS; // OUTPUT
			this->C405TRCTRIGGEREVENTOUT = C405TRCTRIGGEREVENTOUT; // OUTPUT
			this->C405TRCTRIGGEREVENTTYPE = C405TRCTRIGGEREVENTTYPE; // OUTPUT
			this->C405XXXMACHINECHECK = C405XXXMACHINECHECK; // OUTPUT
			this->DCREMACABUS = DCREMACABUS; // OUTPUT
			this->DCREMACCLK = DCREMACCLK; // OUTPUT
			this->DCREMACDBUS = DCREMACDBUS; // OUTPUT
			this->DCREMACENABLER = DCREMACENABLER; // OUTPUT
			this->DCREMACREAD = DCREMACREAD; // OUTPUT
			this->DCREMACWRITE = DCREMACWRITE; // OUTPUT
			this->DSOCMBRAMABUS = DSOCMBRAMABUS; // OUTPUT
			this->DSOCMBRAMBYTEWRITE = DSOCMBRAMBYTEWRITE; // OUTPUT
			this->DSOCMBRAMEN = DSOCMBRAMEN; // OUTPUT
			this->DSOCMBRAMWRDBUS = DSOCMBRAMWRDBUS; // OUTPUT
			this->DSOCMBUSY = DSOCMBUSY; // OUTPUT
			this->DSOCMRDADDRVALID = DSOCMRDADDRVALID; // OUTPUT
			this->DSOCMWRADDRVALID = DSOCMWRADDRVALID; // OUTPUT
			this->EXTDCRABUS = EXTDCRABUS; // OUTPUT
			this->EXTDCRDBUSOUT = EXTDCRDBUSOUT; // OUTPUT
			this->EXTDCRREAD = EXTDCRREAD; // OUTPUT
			this->EXTDCRWRITE = EXTDCRWRITE; // OUTPUT
			this->ISOCMBRAMEN = ISOCMBRAMEN; // OUTPUT
			this->ISOCMBRAMEVENWRITEEN = ISOCMBRAMEVENWRITEEN; // OUTPUT
			this->ISOCMBRAMODDWRITEEN = ISOCMBRAMODDWRITEEN; // OUTPUT
			this->ISOCMBRAMRDABUS = ISOCMBRAMRDABUS; // OUTPUT
			this->ISOCMBRAMWRABUS = ISOCMBRAMWRABUS; // OUTPUT
			this->ISOCMBRAMWRDBUS = ISOCMBRAMWRDBUS; // OUTPUT
			this->ISOCMDCRBRAMEVENEN = ISOCMDCRBRAMEVENEN; // OUTPUT
			this->ISOCMDCRBRAMODDEN = ISOCMDCRBRAMODDEN; // OUTPUT
			this->ISOCMDCRBRAMRDSELECT = ISOCMDCRBRAMRDSELECT; // OUTPUT
			this->BRAMDSOCMCLK = BRAMDSOCMCLK; // INPUT
			this->BRAMDSOCMRDDBUS = BRAMDSOCMRDDBUS; // INPUT
			this->BRAMISOCMCLK = BRAMISOCMCLK; // INPUT
			this->BRAMISOCMDCRRDDBUS = BRAMISOCMDCRRDDBUS; // INPUT
			this->BRAMISOCMRDDBUS = BRAMISOCMRDDBUS; // INPUT
			this->CPMC405CLOCK = CPMC405CLOCK; // INPUT
			this->CPMC405CORECLKINACTIVE = CPMC405CORECLKINACTIVE; // INPUT
			this->CPMC405CPUCLKEN = CPMC405CPUCLKEN; // INPUT
			this->CPMC405JTAGCLKEN = CPMC405JTAGCLKEN; // INPUT
			this->CPMC405SYNCBYPASS = CPMC405SYNCBYPASS; // INPUT
			this->CPMC405TIMERCLKEN = CPMC405TIMERCLKEN; // INPUT
			this->CPMC405TIMERTICK = CPMC405TIMERTICK; // INPUT
			this->CPMDCRCLK = CPMDCRCLK; // INPUT
			this->CPMFCMCLK = CPMFCMCLK; // INPUT
			this->DBGC405DEBUGHALT = DBGC405DEBUGHALT; // INPUT
			this->DBGC405EXTBUSHOLDACK = DBGC405EXTBUSHOLDACK; // INPUT
			this->DBGC405UNCONDDEBUGEVENT = DBGC405UNCONDDEBUGEVENT; // INPUT
			this->DSARCVALUE = DSARCVALUE; // INPUT
			this->DSCNTLVALUE = DSCNTLVALUE; // INPUT
			this->DSOCMRWCOMPLETE = DSOCMRWCOMPLETE; // INPUT
			this->EICC405CRITINPUTIRQ = EICC405CRITINPUTIRQ; // INPUT
			this->EICC405EXTINPUTIRQ = EICC405EXTINPUTIRQ; // INPUT
			this->EMACDCRACK = EMACDCRACK; // INPUT
			this->EMACDCRDBUS = EMACDCRDBUS; // INPUT
			this->EXTDCRACK = EXTDCRACK; // INPUT
			this->EXTDCRDBUSIN = EXTDCRDBUSIN; // INPUT
			this->FCMAPUCR = FCMAPUCR; // INPUT
			this->FCMAPUDCDCREN = FCMAPUDCDCREN; // INPUT
			this->FCMAPUDCDFORCEALIGN = FCMAPUDCDFORCEALIGN; // INPUT
			this->FCMAPUDCDFORCEBESTEERING = FCMAPUDCDFORCEBESTEERING; // INPUT
			this->FCMAPUDCDFPUOP = FCMAPUDCDFPUOP; // INPUT
			this->FCMAPUDCDGPRWRITE = FCMAPUDCDGPRWRITE; // INPUT
			this->FCMAPUDCDLDSTBYTE = FCMAPUDCDLDSTBYTE; // INPUT
			this->FCMAPUDCDLDSTDW = FCMAPUDCDLDSTDW; // INPUT
			this->FCMAPUDCDLDSTHW = FCMAPUDCDLDSTHW; // INPUT
			this->FCMAPUDCDLDSTQW = FCMAPUDCDLDSTQW; // INPUT
			this->FCMAPUDCDLDSTWD = FCMAPUDCDLDSTWD; // INPUT
			this->FCMAPUDCDLOAD = FCMAPUDCDLOAD; // INPUT
			this->FCMAPUDCDPRIVOP = FCMAPUDCDPRIVOP; // INPUT
			this->FCMAPUDCDRAEN = FCMAPUDCDRAEN; // INPUT
			this->FCMAPUDCDRBEN = FCMAPUDCDRBEN; // INPUT
			this->FCMAPUDCDSTORE = FCMAPUDCDSTORE; // INPUT
			this->FCMAPUDCDTRAPBE = FCMAPUDCDTRAPBE; // INPUT
			this->FCMAPUDCDTRAPLE = FCMAPUDCDTRAPLE; // INPUT
			this->FCMAPUDCDUPDATE = FCMAPUDCDUPDATE; // INPUT
			this->FCMAPUDCDXERCAEN = FCMAPUDCDXERCAEN; // INPUT
			this->FCMAPUDCDXEROVEN = FCMAPUDCDXEROVEN; // INPUT
			this->FCMAPUDECODEBUSY = FCMAPUDECODEBUSY; // INPUT
			this->FCMAPUDONE = FCMAPUDONE; // INPUT
			this->FCMAPUEXCEPTION = FCMAPUEXCEPTION; // INPUT
			this->FCMAPUEXEBLOCKINGMCO = FCMAPUEXEBLOCKINGMCO; // INPUT
			this->FCMAPUEXECRFIELD = FCMAPUEXECRFIELD; // INPUT
			this->FCMAPUEXENONBLOCKINGMCO = FCMAPUEXENONBLOCKINGMCO; // INPUT
			this->FCMAPUINSTRACK = FCMAPUINSTRACK; // INPUT
			this->FCMAPULOADWAIT = FCMAPULOADWAIT; // INPUT
			this->FCMAPURESULT = FCMAPURESULT; // INPUT
			this->FCMAPURESULTVALID = FCMAPURESULTVALID; // INPUT
			this->FCMAPUSLEEPNOTREADY = FCMAPUSLEEPNOTREADY; // INPUT
			this->FCMAPUXERCA = FCMAPUXERCA; // INPUT
			this->FCMAPUXEROV = FCMAPUXEROV; // INPUT
			this->ISARCVALUE = ISARCVALUE; // INPUT
			this->ISCNTLVALUE = ISCNTLVALUE; // INPUT
			this->JTGC405BNDSCANTDO = JTGC405BNDSCANTDO; // INPUT
			this->JTGC405TCK = JTGC405TCK; // INPUT
			this->JTGC405TDI = JTGC405TDI; // INPUT
			this->JTGC405TMS = JTGC405TMS; // INPUT
			this->JTGC405TRSTNEG = JTGC405TRSTNEG; // INPUT
			this->MCBCPUCLKEN = MCBCPUCLKEN; // INPUT
			this->MCBJTAGEN = MCBJTAGEN; // INPUT
			this->MCBTIMEREN = MCBTIMEREN; // INPUT
			this->MCPPCRST = MCPPCRST; // INPUT
			this->PLBC405DCUADDRACK = PLBC405DCUADDRACK; // INPUT
			this->PLBC405DCUBUSY = PLBC405DCUBUSY; // INPUT
			this->PLBC405DCUERR = PLBC405DCUERR; // INPUT
			this->PLBC405DCURDDACK = PLBC405DCURDDACK; // INPUT
			this->PLBC405DCURDDBUS = PLBC405DCURDDBUS; // INPUT
			this->PLBC405DCURDWDADDR = PLBC405DCURDWDADDR; // INPUT
			this->PLBC405DCUSSIZE1 = PLBC405DCUSSIZE1; // INPUT
			this->PLBC405DCUWRDACK = PLBC405DCUWRDACK; // INPUT
			this->PLBC405ICUADDRACK = PLBC405ICUADDRACK; // INPUT
			this->PLBC405ICUBUSY = PLBC405ICUBUSY; // INPUT
			this->PLBC405ICUERR = PLBC405ICUERR; // INPUT
			this->PLBC405ICURDDACK = PLBC405ICURDDACK; // INPUT
			this->PLBC405ICURDDBUS = PLBC405ICURDDBUS; // INPUT
			this->PLBC405ICURDWDADDR = PLBC405ICURDWDADDR; // INPUT
			this->PLBC405ICUSSIZE1 = PLBC405ICUSSIZE1; // INPUT
			this->PLBCLK = PLBCLK; // INPUT
			this->RSTC405RESETCHIP = RSTC405RESETCHIP; // INPUT
			this->RSTC405RESETCORE = RSTC405RESETCORE; // INPUT
			this->RSTC405RESETSYS = RSTC405RESETSYS; // INPUT
			this->TIEAPUCONTROL = TIEAPUCONTROL; // INPUT
			this->TIEAPUUDI1 = TIEAPUUDI1; // INPUT
			this->TIEAPUUDI2 = TIEAPUUDI2; // INPUT
			this->TIEAPUUDI3 = TIEAPUUDI3; // INPUT
			this->TIEAPUUDI4 = TIEAPUUDI4; // INPUT
			this->TIEAPUUDI5 = TIEAPUUDI5; // INPUT
			this->TIEAPUUDI6 = TIEAPUUDI6; // INPUT
			this->TIEAPUUDI7 = TIEAPUUDI7; // INPUT
			this->TIEAPUUDI8 = TIEAPUUDI8; // INPUT
			this->TIEC405DETERMINISTICMULT = TIEC405DETERMINISTICMULT; // INPUT
			this->TIEC405DISOPERANDFWD = TIEC405DISOPERANDFWD; // INPUT
			this->TIEC405MMUEN = TIEC405MMUEN; // INPUT
			this->TIEDCRADDR = TIEDCRADDR; // INPUT
			this->TIEPVRBIT10 = TIEPVRBIT10; // INPUT
			this->TIEPVRBIT11 = TIEPVRBIT11; // INPUT
			this->TIEPVRBIT28 = TIEPVRBIT28; // INPUT
			this->TIEPVRBIT29 = TIEPVRBIT29; // INPUT
			this->TIEPVRBIT30 = TIEPVRBIT30; // INPUT
			this->TIEPVRBIT31 = TIEPVRBIT31; // INPUT
			this->TIEPVRBIT8 = TIEPVRBIT8; // INPUT
			this->TIEPVRBIT9 = TIEPVRBIT9; // INPUT
			this->TRCC405TRACEDISABLE = TRCC405TRACEDISABLE; // INPUT
			this->TRCC405TRIGGEREVENTIN = TRCC405TRIGGEREVENTIN; // INPUT
		
			register_wait_on_event_nets();
		
		}
		
		void register_wait_on_event_nets(){
		// TODO
		}
		void calculate(int time){
		// TODO
		}
	};
	

}
