/******************************************************************************
 * Generated Cpp template for simulation primitives.
 * Author: Benedek Racz
 ******************************************************************************/

#include "NetFlow.h"
#include "sim_types.h"

namespace CPrimitives {

	class X_PS7{

		//Verilog Parameters:
		parameter_string_t LOC;
		//Verilog Ports in definition order:
		NetFlow* DMA0DATYPE; // OUTPUT
		NetFlow* DMA0DAVALID; // OUTPUT
		NetFlow* DMA0DRREADY; // OUTPUT
		NetFlow* DMA0RSTN; // OUTPUT
		NetFlow* DMA1DATYPE; // OUTPUT
		NetFlow* DMA1DAVALID; // OUTPUT
		NetFlow* DMA1DRREADY; // OUTPUT
		NetFlow* DMA1RSTN; // OUTPUT
		NetFlow* DMA2DATYPE; // OUTPUT
		NetFlow* DMA2DAVALID; // OUTPUT
		NetFlow* DMA2DRREADY; // OUTPUT
		NetFlow* DMA2RSTN; // OUTPUT
		NetFlow* DMA3DATYPE; // OUTPUT
		NetFlow* DMA3DAVALID; // OUTPUT
		NetFlow* DMA3DRREADY; // OUTPUT
		NetFlow* DMA3RSTN; // OUTPUT
		NetFlow* EMIOCAN0PHYTX; // OUTPUT
		NetFlow* EMIOCAN1PHYTX; // OUTPUT
		NetFlow* EMIOENET0GMIITXD; // OUTPUT
		NetFlow* EMIOENET0GMIITXEN; // OUTPUT
		NetFlow* EMIOENET0GMIITXER; // OUTPUT
		NetFlow* EMIOENET0MDIOMDC; // OUTPUT
		NetFlow* EMIOENET0MDIOO; // OUTPUT
		NetFlow* EMIOENET0MDIOTN; // OUTPUT
		NetFlow* EMIOENET0PTPDELAYREQRX; // OUTPUT
		NetFlow* EMIOENET0PTPDELAYREQTX; // OUTPUT
		NetFlow* EMIOENET0PTPPDELAYREQRX; // OUTPUT
		NetFlow* EMIOENET0PTPPDELAYREQTX; // OUTPUT
		NetFlow* EMIOENET0PTPPDELAYRESPRX; // OUTPUT
		NetFlow* EMIOENET0PTPPDELAYRESPTX; // OUTPUT
		NetFlow* EMIOENET0PTPSYNCFRAMERX; // OUTPUT
		NetFlow* EMIOENET0PTPSYNCFRAMETX; // OUTPUT
		NetFlow* EMIOENET0SOFRX; // OUTPUT
		NetFlow* EMIOENET0SOFTX; // OUTPUT
		NetFlow* EMIOENET1GMIITXD; // OUTPUT
		NetFlow* EMIOENET1GMIITXEN; // OUTPUT
		NetFlow* EMIOENET1GMIITXER; // OUTPUT
		NetFlow* EMIOENET1MDIOMDC; // OUTPUT
		NetFlow* EMIOENET1MDIOO; // OUTPUT
		NetFlow* EMIOENET1MDIOTN; // OUTPUT
		NetFlow* EMIOENET1PTPDELAYREQRX; // OUTPUT
		NetFlow* EMIOENET1PTPDELAYREQTX; // OUTPUT
		NetFlow* EMIOENET1PTPPDELAYREQRX; // OUTPUT
		NetFlow* EMIOENET1PTPPDELAYREQTX; // OUTPUT
		NetFlow* EMIOENET1PTPPDELAYRESPRX; // OUTPUT
		NetFlow* EMIOENET1PTPPDELAYRESPTX; // OUTPUT
		NetFlow* EMIOENET1PTPSYNCFRAMERX; // OUTPUT
		NetFlow* EMIOENET1PTPSYNCFRAMETX; // OUTPUT
		NetFlow* EMIOENET1SOFRX; // OUTPUT
		NetFlow* EMIOENET1SOFTX; // OUTPUT
		NetFlow* EMIOGPIOO; // OUTPUT
		NetFlow* EMIOGPIOTN; // OUTPUT
		NetFlow* EMIOI2C0SCLO; // OUTPUT
		NetFlow* EMIOI2C0SCLTN; // OUTPUT
		NetFlow* EMIOI2C0SDAO; // OUTPUT
		NetFlow* EMIOI2C0SDATN; // OUTPUT
		NetFlow* EMIOI2C1SCLO; // OUTPUT
		NetFlow* EMIOI2C1SCLTN; // OUTPUT
		NetFlow* EMIOI2C1SDAO; // OUTPUT
		NetFlow* EMIOI2C1SDATN; // OUTPUT
		NetFlow* EMIOPJTAGTDO; // OUTPUT
		NetFlow* EMIOPJTAGTDTN; // OUTPUT
		NetFlow* EMIOSDIO0BUSPOW; // OUTPUT
		NetFlow* EMIOSDIO0BUSVOLT; // OUTPUT
		NetFlow* EMIOSDIO0CLK; // OUTPUT
		NetFlow* EMIOSDIO0CMDO; // OUTPUT
		NetFlow* EMIOSDIO0CMDTN; // OUTPUT
		NetFlow* EMIOSDIO0DATAO; // OUTPUT
		NetFlow* EMIOSDIO0DATATN; // OUTPUT
		NetFlow* EMIOSDIO0LED; // OUTPUT
		NetFlow* EMIOSDIO1BUSPOW; // OUTPUT
		NetFlow* EMIOSDIO1BUSVOLT; // OUTPUT
		NetFlow* EMIOSDIO1CLK; // OUTPUT
		NetFlow* EMIOSDIO1CMDO; // OUTPUT
		NetFlow* EMIOSDIO1CMDTN; // OUTPUT
		NetFlow* EMIOSDIO1DATAO; // OUTPUT
		NetFlow* EMIOSDIO1DATATN; // OUTPUT
		NetFlow* EMIOSDIO1LED; // OUTPUT
		NetFlow* EMIOSPI0MO; // OUTPUT
		NetFlow* EMIOSPI0MOTN; // OUTPUT
		NetFlow* EMIOSPI0SCLKO; // OUTPUT
		NetFlow* EMIOSPI0SCLKTN; // OUTPUT
		NetFlow* EMIOSPI0SO; // OUTPUT
		NetFlow* EMIOSPI0SSNTN; // OUTPUT
		NetFlow* EMIOSPI0SSON; // OUTPUT
		NetFlow* EMIOSPI0STN; // OUTPUT
		NetFlow* EMIOSPI1MO; // OUTPUT
		NetFlow* EMIOSPI1MOTN; // OUTPUT
		NetFlow* EMIOSPI1SCLKO; // OUTPUT
		NetFlow* EMIOSPI1SCLKTN; // OUTPUT
		NetFlow* EMIOSPI1SO; // OUTPUT
		NetFlow* EMIOSPI1SSNTN; // OUTPUT
		NetFlow* EMIOSPI1SSON; // OUTPUT
		NetFlow* EMIOSPI1STN; // OUTPUT
		NetFlow* EMIOTRACECTL; // OUTPUT
		NetFlow* EMIOTRACEDATA; // OUTPUT
		NetFlow* EMIOTTC0WAVEO; // OUTPUT
		NetFlow* EMIOTTC1WAVEO; // OUTPUT
		NetFlow* EMIOUART0DTRN; // OUTPUT
		NetFlow* EMIOUART0RTSN; // OUTPUT
		NetFlow* EMIOUART0TX; // OUTPUT
		NetFlow* EMIOUART1DTRN; // OUTPUT
		NetFlow* EMIOUART1RTSN; // OUTPUT
		NetFlow* EMIOUART1TX; // OUTPUT
		NetFlow* EMIOUSB0PORTINDCTL; // OUTPUT
		NetFlow* EMIOUSB0VBUSPWRSELECT; // OUTPUT
		NetFlow* EMIOUSB1PORTINDCTL; // OUTPUT
		NetFlow* EMIOUSB1VBUSPWRSELECT; // OUTPUT
		NetFlow* EMIOWDTRSTO; // OUTPUT
		NetFlow* EVENTEVENTO; // OUTPUT
		NetFlow* EVENTSTANDBYWFE; // OUTPUT
		NetFlow* EVENTSTANDBYWFI; // OUTPUT
		NetFlow* FCLKCLK; // OUTPUT
		NetFlow* FCLKRESETN; // OUTPUT
		NetFlow* FTMTF2PTRIGACK; // OUTPUT
		NetFlow* FTMTP2FDEBUG; // OUTPUT
		NetFlow* FTMTP2FTRIG; // OUTPUT
		NetFlow* IRQP2F; // OUTPUT
		NetFlow* MAXIGP0ARADDR; // OUTPUT
		NetFlow* MAXIGP0ARBURST; // OUTPUT
		NetFlow* MAXIGP0ARCACHE; // OUTPUT
		NetFlow* MAXIGP0ARESETN; // OUTPUT
		NetFlow* MAXIGP0ARID; // OUTPUT
		NetFlow* MAXIGP0ARLEN; // OUTPUT
		NetFlow* MAXIGP0ARLOCK; // OUTPUT
		NetFlow* MAXIGP0ARPROT; // OUTPUT
		NetFlow* MAXIGP0ARQOS; // OUTPUT
		NetFlow* MAXIGP0ARSIZE; // OUTPUT
		NetFlow* MAXIGP0ARVALID; // OUTPUT
		NetFlow* MAXIGP0AWADDR; // OUTPUT
		NetFlow* MAXIGP0AWBURST; // OUTPUT
		NetFlow* MAXIGP0AWCACHE; // OUTPUT
		NetFlow* MAXIGP0AWID; // OUTPUT
		NetFlow* MAXIGP0AWLEN; // OUTPUT
		NetFlow* MAXIGP0AWLOCK; // OUTPUT
		NetFlow* MAXIGP0AWPROT; // OUTPUT
		NetFlow* MAXIGP0AWQOS; // OUTPUT
		NetFlow* MAXIGP0AWSIZE; // OUTPUT
		NetFlow* MAXIGP0AWVALID; // OUTPUT
		NetFlow* MAXIGP0BREADY; // OUTPUT
		NetFlow* MAXIGP0RREADY; // OUTPUT
		NetFlow* MAXIGP0WDATA; // OUTPUT
		NetFlow* MAXIGP0WID; // OUTPUT
		NetFlow* MAXIGP0WLAST; // OUTPUT
		NetFlow* MAXIGP0WSTRB; // OUTPUT
		NetFlow* MAXIGP0WVALID; // OUTPUT
		NetFlow* MAXIGP1ARADDR; // OUTPUT
		NetFlow* MAXIGP1ARBURST; // OUTPUT
		NetFlow* MAXIGP1ARCACHE; // OUTPUT
		NetFlow* MAXIGP1ARESETN; // OUTPUT
		NetFlow* MAXIGP1ARID; // OUTPUT
		NetFlow* MAXIGP1ARLEN; // OUTPUT
		NetFlow* MAXIGP1ARLOCK; // OUTPUT
		NetFlow* MAXIGP1ARPROT; // OUTPUT
		NetFlow* MAXIGP1ARQOS; // OUTPUT
		NetFlow* MAXIGP1ARSIZE; // OUTPUT
		NetFlow* MAXIGP1ARVALID; // OUTPUT
		NetFlow* MAXIGP1AWADDR; // OUTPUT
		NetFlow* MAXIGP1AWBURST; // OUTPUT
		NetFlow* MAXIGP1AWCACHE; // OUTPUT
		NetFlow* MAXIGP1AWID; // OUTPUT
		NetFlow* MAXIGP1AWLEN; // OUTPUT
		NetFlow* MAXIGP1AWLOCK; // OUTPUT
		NetFlow* MAXIGP1AWPROT; // OUTPUT
		NetFlow* MAXIGP1AWQOS; // OUTPUT
		NetFlow* MAXIGP1AWSIZE; // OUTPUT
		NetFlow* MAXIGP1AWVALID; // OUTPUT
		NetFlow* MAXIGP1BREADY; // OUTPUT
		NetFlow* MAXIGP1RREADY; // OUTPUT
		NetFlow* MAXIGP1WDATA; // OUTPUT
		NetFlow* MAXIGP1WID; // OUTPUT
		NetFlow* MAXIGP1WLAST; // OUTPUT
		NetFlow* MAXIGP1WSTRB; // OUTPUT
		NetFlow* MAXIGP1WVALID; // OUTPUT
		NetFlow* SAXIACPARESETN; // OUTPUT
		NetFlow* SAXIACPARREADY; // OUTPUT
		NetFlow* SAXIACPAWREADY; // OUTPUT
		NetFlow* SAXIACPBID; // OUTPUT
		NetFlow* SAXIACPBRESP; // OUTPUT
		NetFlow* SAXIACPBVALID; // OUTPUT
		NetFlow* SAXIACPRDATA; // OUTPUT
		NetFlow* SAXIACPRID; // OUTPUT
		NetFlow* SAXIACPRLAST; // OUTPUT
		NetFlow* SAXIACPRRESP; // OUTPUT
		NetFlow* SAXIACPRVALID; // OUTPUT
		NetFlow* SAXIACPWREADY; // OUTPUT
		NetFlow* SAXIGP0ARESETN; // OUTPUT
		NetFlow* SAXIGP0ARREADY; // OUTPUT
		NetFlow* SAXIGP0AWREADY; // OUTPUT
		NetFlow* SAXIGP0BID; // OUTPUT
		NetFlow* SAXIGP0BRESP; // OUTPUT
		NetFlow* SAXIGP0BVALID; // OUTPUT
		NetFlow* SAXIGP0RDATA; // OUTPUT
		NetFlow* SAXIGP0RID; // OUTPUT
		NetFlow* SAXIGP0RLAST; // OUTPUT
		NetFlow* SAXIGP0RRESP; // OUTPUT
		NetFlow* SAXIGP0RVALID; // OUTPUT
		NetFlow* SAXIGP0WREADY; // OUTPUT
		NetFlow* SAXIGP1ARESETN; // OUTPUT
		NetFlow* SAXIGP1ARREADY; // OUTPUT
		NetFlow* SAXIGP1AWREADY; // OUTPUT
		NetFlow* SAXIGP1BID; // OUTPUT
		NetFlow* SAXIGP1BRESP; // OUTPUT
		NetFlow* SAXIGP1BVALID; // OUTPUT
		NetFlow* SAXIGP1RDATA; // OUTPUT
		NetFlow* SAXIGP1RID; // OUTPUT
		NetFlow* SAXIGP1RLAST; // OUTPUT
		NetFlow* SAXIGP1RRESP; // OUTPUT
		NetFlow* SAXIGP1RVALID; // OUTPUT
		NetFlow* SAXIGP1WREADY; // OUTPUT
		NetFlow* SAXIHP0ARESETN; // OUTPUT
		NetFlow* SAXIHP0ARREADY; // OUTPUT
		NetFlow* SAXIHP0AWREADY; // OUTPUT
		NetFlow* SAXIHP0BID; // OUTPUT
		NetFlow* SAXIHP0BRESP; // OUTPUT
		NetFlow* SAXIHP0BVALID; // OUTPUT
		NetFlow* SAXIHP0RACOUNT; // OUTPUT
		NetFlow* SAXIHP0RCOUNT; // OUTPUT
		NetFlow* SAXIHP0RDATA; // OUTPUT
		NetFlow* SAXIHP0RID; // OUTPUT
		NetFlow* SAXIHP0RLAST; // OUTPUT
		NetFlow* SAXIHP0RRESP; // OUTPUT
		NetFlow* SAXIHP0RVALID; // OUTPUT
		NetFlow* SAXIHP0WACOUNT; // OUTPUT
		NetFlow* SAXIHP0WCOUNT; // OUTPUT
		NetFlow* SAXIHP0WREADY; // OUTPUT
		NetFlow* SAXIHP1ARESETN; // OUTPUT
		NetFlow* SAXIHP1ARREADY; // OUTPUT
		NetFlow* SAXIHP1AWREADY; // OUTPUT
		NetFlow* SAXIHP1BID; // OUTPUT
		NetFlow* SAXIHP1BRESP; // OUTPUT
		NetFlow* SAXIHP1BVALID; // OUTPUT
		NetFlow* SAXIHP1RACOUNT; // OUTPUT
		NetFlow* SAXIHP1RCOUNT; // OUTPUT
		NetFlow* SAXIHP1RDATA; // OUTPUT
		NetFlow* SAXIHP1RID; // OUTPUT
		NetFlow* SAXIHP1RLAST; // OUTPUT
		NetFlow* SAXIHP1RRESP; // OUTPUT
		NetFlow* SAXIHP1RVALID; // OUTPUT
		NetFlow* SAXIHP1WACOUNT; // OUTPUT
		NetFlow* SAXIHP1WCOUNT; // OUTPUT
		NetFlow* SAXIHP1WREADY; // OUTPUT
		NetFlow* SAXIHP2ARESETN; // OUTPUT
		NetFlow* SAXIHP2ARREADY; // OUTPUT
		NetFlow* SAXIHP2AWREADY; // OUTPUT
		NetFlow* SAXIHP2BID; // OUTPUT
		NetFlow* SAXIHP2BRESP; // OUTPUT
		NetFlow* SAXIHP2BVALID; // OUTPUT
		NetFlow* SAXIHP2RACOUNT; // OUTPUT
		NetFlow* SAXIHP2RCOUNT; // OUTPUT
		NetFlow* SAXIHP2RDATA; // OUTPUT
		NetFlow* SAXIHP2RID; // OUTPUT
		NetFlow* SAXIHP2RLAST; // OUTPUT
		NetFlow* SAXIHP2RRESP; // OUTPUT
		NetFlow* SAXIHP2RVALID; // OUTPUT
		NetFlow* SAXIHP2WACOUNT; // OUTPUT
		NetFlow* SAXIHP2WCOUNT; // OUTPUT
		NetFlow* SAXIHP2WREADY; // OUTPUT
		NetFlow* SAXIHP3ARESETN; // OUTPUT
		NetFlow* SAXIHP3ARREADY; // OUTPUT
		NetFlow* SAXIHP3AWREADY; // OUTPUT
		NetFlow* SAXIHP3BID; // OUTPUT
		NetFlow* SAXIHP3BRESP; // OUTPUT
		NetFlow* SAXIHP3BVALID; // OUTPUT
		NetFlow* SAXIHP3RACOUNT; // OUTPUT
		NetFlow* SAXIHP3RCOUNT; // OUTPUT
		NetFlow* SAXIHP3RDATA; // OUTPUT
		NetFlow* SAXIHP3RID; // OUTPUT
		NetFlow* SAXIHP3RLAST; // OUTPUT
		NetFlow* SAXIHP3RRESP; // OUTPUT
		NetFlow* SAXIHP3RVALID; // OUTPUT
		NetFlow* SAXIHP3WACOUNT; // OUTPUT
		NetFlow* SAXIHP3WCOUNT; // OUTPUT
		NetFlow* SAXIHP3WREADY; // OUTPUT
		NetFlow* DDRA; // INOUT
		NetFlow* DDRBA; // INOUT
		NetFlow* DDRCASB; // INOUT
		NetFlow* DDRCKE; // INOUT
		NetFlow* DDRCKN; // INOUT
		NetFlow* DDRCKP; // INOUT
		NetFlow* DDRCSB; // INOUT
		NetFlow* DDRDM; // INOUT
		NetFlow* DDRDQ; // INOUT
		NetFlow* DDRDQSN; // INOUT
		NetFlow* DDRDQSP; // INOUT
		NetFlow* DDRDRSTB; // INOUT
		NetFlow* DDRODT; // INOUT
		NetFlow* DDRRASB; // INOUT
		NetFlow* DDRVRN; // INOUT
		NetFlow* DDRVRP; // INOUT
		NetFlow* DDRWEB; // INOUT
		NetFlow* MIO; // INOUT
		NetFlow* PSCLK; // INOUT
		NetFlow* PSPORB; // INOUT
		NetFlow* PSSRSTB; // INOUT
		NetFlow* DDRARB; // INPUT
		NetFlow* DMA0ACLK; // INPUT
		NetFlow* DMA0DAREADY; // INPUT
		NetFlow* DMA0DRLAST; // INPUT
		NetFlow* DMA0DRTYPE; // INPUT
		NetFlow* DMA0DRVALID; // INPUT
		NetFlow* DMA1ACLK; // INPUT
		NetFlow* DMA1DAREADY; // INPUT
		NetFlow* DMA1DRLAST; // INPUT
		NetFlow* DMA1DRTYPE; // INPUT
		NetFlow* DMA1DRVALID; // INPUT
		NetFlow* DMA2ACLK; // INPUT
		NetFlow* DMA2DAREADY; // INPUT
		NetFlow* DMA2DRLAST; // INPUT
		NetFlow* DMA2DRTYPE; // INPUT
		NetFlow* DMA2DRVALID; // INPUT
		NetFlow* DMA3ACLK; // INPUT
		NetFlow* DMA3DAREADY; // INPUT
		NetFlow* DMA3DRLAST; // INPUT
		NetFlow* DMA3DRTYPE; // INPUT
		NetFlow* DMA3DRVALID; // INPUT
		NetFlow* EMIOCAN0PHYRX; // INPUT
		NetFlow* EMIOCAN1PHYRX; // INPUT
		NetFlow* EMIOENET0EXTINTIN; // INPUT
		NetFlow* EMIOENET0GMIICOL; // INPUT
		NetFlow* EMIOENET0GMIICRS; // INPUT
		NetFlow* EMIOENET0GMIIRXCLK; // INPUT
		NetFlow* EMIOENET0GMIIRXD; // INPUT
		NetFlow* EMIOENET0GMIIRXDV; // INPUT
		NetFlow* EMIOENET0GMIIRXER; // INPUT
		NetFlow* EMIOENET0GMIITXCLK; // INPUT
		NetFlow* EMIOENET0MDIOI; // INPUT
		NetFlow* EMIOENET1EXTINTIN; // INPUT
		NetFlow* EMIOENET1GMIICOL; // INPUT
		NetFlow* EMIOENET1GMIICRS; // INPUT
		NetFlow* EMIOENET1GMIIRXCLK; // INPUT
		NetFlow* EMIOENET1GMIIRXD; // INPUT
		NetFlow* EMIOENET1GMIIRXDV; // INPUT
		NetFlow* EMIOENET1GMIIRXER; // INPUT
		NetFlow* EMIOENET1GMIITXCLK; // INPUT
		NetFlow* EMIOENET1MDIOI; // INPUT
		NetFlow* EMIOGPIOI; // INPUT
		NetFlow* EMIOI2C0SCLI; // INPUT
		NetFlow* EMIOI2C0SDAI; // INPUT
		NetFlow* EMIOI2C1SCLI; // INPUT
		NetFlow* EMIOI2C1SDAI; // INPUT
		NetFlow* EMIOPJTAGTCK; // INPUT
		NetFlow* EMIOPJTAGTDI; // INPUT
		NetFlow* EMIOPJTAGTMS; // INPUT
		NetFlow* EMIOSDIO0CDN; // INPUT
		NetFlow* EMIOSDIO0CLKFB; // INPUT
		NetFlow* EMIOSDIO0CMDI; // INPUT
		NetFlow* EMIOSDIO0DATAI; // INPUT
		NetFlow* EMIOSDIO0WP; // INPUT
		NetFlow* EMIOSDIO1CDN; // INPUT
		NetFlow* EMIOSDIO1CLKFB; // INPUT
		NetFlow* EMIOSDIO1CMDI; // INPUT
		NetFlow* EMIOSDIO1DATAI; // INPUT
		NetFlow* EMIOSDIO1WP; // INPUT
		NetFlow* EMIOSPI0MI; // INPUT
		NetFlow* EMIOSPI0SCLKI; // INPUT
		NetFlow* EMIOSPI0SI; // INPUT
		NetFlow* EMIOSPI0SSIN; // INPUT
		NetFlow* EMIOSPI1MI; // INPUT
		NetFlow* EMIOSPI1SCLKI; // INPUT
		NetFlow* EMIOSPI1SI; // INPUT
		NetFlow* EMIOSPI1SSIN; // INPUT
		NetFlow* EMIOSRAMINTIN; // INPUT
		NetFlow* EMIOTRACECLK; // INPUT
		NetFlow* EMIOTTC0CLKI; // INPUT
		NetFlow* EMIOTTC1CLKI; // INPUT
		NetFlow* EMIOUART0CTSN; // INPUT
		NetFlow* EMIOUART0DCDN; // INPUT
		NetFlow* EMIOUART0DSRN; // INPUT
		NetFlow* EMIOUART0RIN; // INPUT
		NetFlow* EMIOUART0RX; // INPUT
		NetFlow* EMIOUART1CTSN; // INPUT
		NetFlow* EMIOUART1DCDN; // INPUT
		NetFlow* EMIOUART1DSRN; // INPUT
		NetFlow* EMIOUART1RIN; // INPUT
		NetFlow* EMIOUART1RX; // INPUT
		NetFlow* EMIOUSB0VBUSPWRFAULT; // INPUT
		NetFlow* EMIOUSB1VBUSPWRFAULT; // INPUT
		NetFlow* EMIOWDTCLKI; // INPUT
		NetFlow* EVENTEVENTI; // INPUT
		NetFlow* FCLKCLKTRIGN; // INPUT
		NetFlow* FPGAIDLEN; // INPUT
		NetFlow* FTMDTRACEINATID; // INPUT
		NetFlow* FTMDTRACEINCLOCK; // INPUT
		NetFlow* FTMDTRACEINDATA; // INPUT
		NetFlow* FTMDTRACEINVALID; // INPUT
		NetFlow* FTMTF2PDEBUG; // INPUT
		NetFlow* FTMTF2PTRIG; // INPUT
		NetFlow* FTMTP2FTRIGACK; // INPUT
		NetFlow* IRQF2P; // INPUT
		NetFlow* MAXIGP0ACLK; // INPUT
		NetFlow* MAXIGP0ARREADY; // INPUT
		NetFlow* MAXIGP0AWREADY; // INPUT
		NetFlow* MAXIGP0BID; // INPUT
		NetFlow* MAXIGP0BRESP; // INPUT
		NetFlow* MAXIGP0BVALID; // INPUT
		NetFlow* MAXIGP0RDATA; // INPUT
		NetFlow* MAXIGP0RID; // INPUT
		NetFlow* MAXIGP0RLAST; // INPUT
		NetFlow* MAXIGP0RRESP; // INPUT
		NetFlow* MAXIGP0RVALID; // INPUT
		NetFlow* MAXIGP0WREADY; // INPUT
		NetFlow* MAXIGP1ACLK; // INPUT
		NetFlow* MAXIGP1ARREADY; // INPUT
		NetFlow* MAXIGP1AWREADY; // INPUT
		NetFlow* MAXIGP1BID; // INPUT
		NetFlow* MAXIGP1BRESP; // INPUT
		NetFlow* MAXIGP1BVALID; // INPUT
		NetFlow* MAXIGP1RDATA; // INPUT
		NetFlow* MAXIGP1RID; // INPUT
		NetFlow* MAXIGP1RLAST; // INPUT
		NetFlow* MAXIGP1RRESP; // INPUT
		NetFlow* MAXIGP1RVALID; // INPUT
		NetFlow* MAXIGP1WREADY; // INPUT
		NetFlow* SAXIACPACLK; // INPUT
		NetFlow* SAXIACPARADDR; // INPUT
		NetFlow* SAXIACPARBURST; // INPUT
		NetFlow* SAXIACPARCACHE; // INPUT
		NetFlow* SAXIACPARID; // INPUT
		NetFlow* SAXIACPARLEN; // INPUT
		NetFlow* SAXIACPARLOCK; // INPUT
		NetFlow* SAXIACPARPROT; // INPUT
		NetFlow* SAXIACPARQOS; // INPUT
		NetFlow* SAXIACPARSIZE; // INPUT
		NetFlow* SAXIACPARUSER; // INPUT
		NetFlow* SAXIACPARVALID; // INPUT
		NetFlow* SAXIACPAWADDR; // INPUT
		NetFlow* SAXIACPAWBURST; // INPUT
		NetFlow* SAXIACPAWCACHE; // INPUT
		NetFlow* SAXIACPAWID; // INPUT
		NetFlow* SAXIACPAWLEN; // INPUT
		NetFlow* SAXIACPAWLOCK; // INPUT
		NetFlow* SAXIACPAWPROT; // INPUT
		NetFlow* SAXIACPAWQOS; // INPUT
		NetFlow* SAXIACPAWSIZE; // INPUT
		NetFlow* SAXIACPAWUSER; // INPUT
		NetFlow* SAXIACPAWVALID; // INPUT
		NetFlow* SAXIACPBREADY; // INPUT
		NetFlow* SAXIACPRREADY; // INPUT
		NetFlow* SAXIACPWDATA; // INPUT
		NetFlow* SAXIACPWID; // INPUT
		NetFlow* SAXIACPWLAST; // INPUT
		NetFlow* SAXIACPWSTRB; // INPUT
		NetFlow* SAXIACPWVALID; // INPUT
		NetFlow* SAXIGP0ACLK; // INPUT
		NetFlow* SAXIGP0ARADDR; // INPUT
		NetFlow* SAXIGP0ARBURST; // INPUT
		NetFlow* SAXIGP0ARCACHE; // INPUT
		NetFlow* SAXIGP0ARID; // INPUT
		NetFlow* SAXIGP0ARLEN; // INPUT
		NetFlow* SAXIGP0ARLOCK; // INPUT
		NetFlow* SAXIGP0ARPROT; // INPUT
		NetFlow* SAXIGP0ARQOS; // INPUT
		NetFlow* SAXIGP0ARSIZE; // INPUT
		NetFlow* SAXIGP0ARVALID; // INPUT
		NetFlow* SAXIGP0AWADDR; // INPUT
		NetFlow* SAXIGP0AWBURST; // INPUT
		NetFlow* SAXIGP0AWCACHE; // INPUT
		NetFlow* SAXIGP0AWID; // INPUT
		NetFlow* SAXIGP0AWLEN; // INPUT
		NetFlow* SAXIGP0AWLOCK; // INPUT
		NetFlow* SAXIGP0AWPROT; // INPUT
		NetFlow* SAXIGP0AWQOS; // INPUT
		NetFlow* SAXIGP0AWSIZE; // INPUT
		NetFlow* SAXIGP0AWVALID; // INPUT
		NetFlow* SAXIGP0BREADY; // INPUT
		NetFlow* SAXIGP0RREADY; // INPUT
		NetFlow* SAXIGP0WDATA; // INPUT
		NetFlow* SAXIGP0WID; // INPUT
		NetFlow* SAXIGP0WLAST; // INPUT
		NetFlow* SAXIGP0WSTRB; // INPUT
		NetFlow* SAXIGP0WVALID; // INPUT
		NetFlow* SAXIGP1ACLK; // INPUT
		NetFlow* SAXIGP1ARADDR; // INPUT
		NetFlow* SAXIGP1ARBURST; // INPUT
		NetFlow* SAXIGP1ARCACHE; // INPUT
		NetFlow* SAXIGP1ARID; // INPUT
		NetFlow* SAXIGP1ARLEN; // INPUT
		NetFlow* SAXIGP1ARLOCK; // INPUT
		NetFlow* SAXIGP1ARPROT; // INPUT
		NetFlow* SAXIGP1ARQOS; // INPUT
		NetFlow* SAXIGP1ARSIZE; // INPUT
		NetFlow* SAXIGP1ARVALID; // INPUT
		NetFlow* SAXIGP1AWADDR; // INPUT
		NetFlow* SAXIGP1AWBURST; // INPUT
		NetFlow* SAXIGP1AWCACHE; // INPUT
		NetFlow* SAXIGP1AWID; // INPUT
		NetFlow* SAXIGP1AWLEN; // INPUT
		NetFlow* SAXIGP1AWLOCK; // INPUT
		NetFlow* SAXIGP1AWPROT; // INPUT
		NetFlow* SAXIGP1AWQOS; // INPUT
		NetFlow* SAXIGP1AWSIZE; // INPUT
		NetFlow* SAXIGP1AWVALID; // INPUT
		NetFlow* SAXIGP1BREADY; // INPUT
		NetFlow* SAXIGP1RREADY; // INPUT
		NetFlow* SAXIGP1WDATA; // INPUT
		NetFlow* SAXIGP1WID; // INPUT
		NetFlow* SAXIGP1WLAST; // INPUT
		NetFlow* SAXIGP1WSTRB; // INPUT
		NetFlow* SAXIGP1WVALID; // INPUT
		NetFlow* SAXIHP0ACLK; // INPUT
		NetFlow* SAXIHP0ARADDR; // INPUT
		NetFlow* SAXIHP0ARBURST; // INPUT
		NetFlow* SAXIHP0ARCACHE; // INPUT
		NetFlow* SAXIHP0ARID; // INPUT
		NetFlow* SAXIHP0ARLEN; // INPUT
		NetFlow* SAXIHP0ARLOCK; // INPUT
		NetFlow* SAXIHP0ARPROT; // INPUT
		NetFlow* SAXIHP0ARQOS; // INPUT
		NetFlow* SAXIHP0ARSIZE; // INPUT
		NetFlow* SAXIHP0ARVALID; // INPUT
		NetFlow* SAXIHP0AWADDR; // INPUT
		NetFlow* SAXIHP0AWBURST; // INPUT
		NetFlow* SAXIHP0AWCACHE; // INPUT
		NetFlow* SAXIHP0AWID; // INPUT
		NetFlow* SAXIHP0AWLEN; // INPUT
		NetFlow* SAXIHP0AWLOCK; // INPUT
		NetFlow* SAXIHP0AWPROT; // INPUT
		NetFlow* SAXIHP0AWQOS; // INPUT
		NetFlow* SAXIHP0AWSIZE; // INPUT
		NetFlow* SAXIHP0AWVALID; // INPUT
		NetFlow* SAXIHP0BREADY; // INPUT
		NetFlow* SAXIHP0RDISSUECAP1EN; // INPUT
		NetFlow* SAXIHP0RREADY; // INPUT
		NetFlow* SAXIHP0WDATA; // INPUT
		NetFlow* SAXIHP0WID; // INPUT
		NetFlow* SAXIHP0WLAST; // INPUT
		NetFlow* SAXIHP0WRISSUECAP1EN; // INPUT
		NetFlow* SAXIHP0WSTRB; // INPUT
		NetFlow* SAXIHP0WVALID; // INPUT
		NetFlow* SAXIHP1ACLK; // INPUT
		NetFlow* SAXIHP1ARADDR; // INPUT
		NetFlow* SAXIHP1ARBURST; // INPUT
		NetFlow* SAXIHP1ARCACHE; // INPUT
		NetFlow* SAXIHP1ARID; // INPUT
		NetFlow* SAXIHP1ARLEN; // INPUT
		NetFlow* SAXIHP1ARLOCK; // INPUT
		NetFlow* SAXIHP1ARPROT; // INPUT
		NetFlow* SAXIHP1ARQOS; // INPUT
		NetFlow* SAXIHP1ARSIZE; // INPUT
		NetFlow* SAXIHP1ARVALID; // INPUT
		NetFlow* SAXIHP1AWADDR; // INPUT
		NetFlow* SAXIHP1AWBURST; // INPUT
		NetFlow* SAXIHP1AWCACHE; // INPUT
		NetFlow* SAXIHP1AWID; // INPUT
		NetFlow* SAXIHP1AWLEN; // INPUT
		NetFlow* SAXIHP1AWLOCK; // INPUT
		NetFlow* SAXIHP1AWPROT; // INPUT
		NetFlow* SAXIHP1AWQOS; // INPUT
		NetFlow* SAXIHP1AWSIZE; // INPUT
		NetFlow* SAXIHP1AWVALID; // INPUT
		NetFlow* SAXIHP1BREADY; // INPUT
		NetFlow* SAXIHP1RDISSUECAP1EN; // INPUT
		NetFlow* SAXIHP1RREADY; // INPUT
		NetFlow* SAXIHP1WDATA; // INPUT
		NetFlow* SAXIHP1WID; // INPUT
		NetFlow* SAXIHP1WLAST; // INPUT
		NetFlow* SAXIHP1WRISSUECAP1EN; // INPUT
		NetFlow* SAXIHP1WSTRB; // INPUT
		NetFlow* SAXIHP1WVALID; // INPUT
		NetFlow* SAXIHP2ACLK; // INPUT
		NetFlow* SAXIHP2ARADDR; // INPUT
		NetFlow* SAXIHP2ARBURST; // INPUT
		NetFlow* SAXIHP2ARCACHE; // INPUT
		NetFlow* SAXIHP2ARID; // INPUT
		NetFlow* SAXIHP2ARLEN; // INPUT
		NetFlow* SAXIHP2ARLOCK; // INPUT
		NetFlow* SAXIHP2ARPROT; // INPUT
		NetFlow* SAXIHP2ARQOS; // INPUT
		NetFlow* SAXIHP2ARSIZE; // INPUT
		NetFlow* SAXIHP2ARVALID; // INPUT
		NetFlow* SAXIHP2AWADDR; // INPUT
		NetFlow* SAXIHP2AWBURST; // INPUT
		NetFlow* SAXIHP2AWCACHE; // INPUT
		NetFlow* SAXIHP2AWID; // INPUT
		NetFlow* SAXIHP2AWLEN; // INPUT
		NetFlow* SAXIHP2AWLOCK; // INPUT
		NetFlow* SAXIHP2AWPROT; // INPUT
		NetFlow* SAXIHP2AWQOS; // INPUT
		NetFlow* SAXIHP2AWSIZE; // INPUT
		NetFlow* SAXIHP2AWVALID; // INPUT
		NetFlow* SAXIHP2BREADY; // INPUT
		NetFlow* SAXIHP2RDISSUECAP1EN; // INPUT
		NetFlow* SAXIHP2RREADY; // INPUT
		NetFlow* SAXIHP2WDATA; // INPUT
		NetFlow* SAXIHP2WID; // INPUT
		NetFlow* SAXIHP2WLAST; // INPUT
		NetFlow* SAXIHP2WRISSUECAP1EN; // INPUT
		NetFlow* SAXIHP2WSTRB; // INPUT
		NetFlow* SAXIHP2WVALID; // INPUT
		NetFlow* SAXIHP3ACLK; // INPUT
		NetFlow* SAXIHP3ARADDR; // INPUT
		NetFlow* SAXIHP3ARBURST; // INPUT
		NetFlow* SAXIHP3ARCACHE; // INPUT
		NetFlow* SAXIHP3ARID; // INPUT
		NetFlow* SAXIHP3ARLEN; // INPUT
		NetFlow* SAXIHP3ARLOCK; // INPUT
		NetFlow* SAXIHP3ARPROT; // INPUT
		NetFlow* SAXIHP3ARQOS; // INPUT
		NetFlow* SAXIHP3ARSIZE; // INPUT
		NetFlow* SAXIHP3ARVALID; // INPUT
		NetFlow* SAXIHP3AWADDR; // INPUT
		NetFlow* SAXIHP3AWBURST; // INPUT
		NetFlow* SAXIHP3AWCACHE; // INPUT
		NetFlow* SAXIHP3AWID; // INPUT
		NetFlow* SAXIHP3AWLEN; // INPUT
		NetFlow* SAXIHP3AWLOCK; // INPUT
		NetFlow* SAXIHP3AWPROT; // INPUT
		NetFlow* SAXIHP3AWQOS; // INPUT
		NetFlow* SAXIHP3AWSIZE; // INPUT
		NetFlow* SAXIHP3AWVALID; // INPUT
		NetFlow* SAXIHP3BREADY; // INPUT
		NetFlow* SAXIHP3RDISSUECAP1EN; // INPUT
		NetFlow* SAXIHP3RREADY; // INPUT
		NetFlow* SAXIHP3WDATA; // INPUT
		NetFlow* SAXIHP3WID; // INPUT
		NetFlow* SAXIHP3WLAST; // INPUT
		NetFlow* SAXIHP3WRISSUECAP1EN; // INPUT
		NetFlow* SAXIHP3WSTRB; // INPUT
		NetFlow* SAXIHP3WVALID; // INPUT
		
	
		X_PS7(
			//Verilog Parameters:
			parameter_string_t LOC, // Default: "UNPLACED"
			//Verilog Ports in definition order:
			NetFlow* DMA0DATYPE, // OUTPUT
			NetFlow* DMA0DAVALID, // OUTPUT
			NetFlow* DMA0DRREADY, // OUTPUT
			NetFlow* DMA0RSTN, // OUTPUT
			NetFlow* DMA1DATYPE, // OUTPUT
			NetFlow* DMA1DAVALID, // OUTPUT
			NetFlow* DMA1DRREADY, // OUTPUT
			NetFlow* DMA1RSTN, // OUTPUT
			NetFlow* DMA2DATYPE, // OUTPUT
			NetFlow* DMA2DAVALID, // OUTPUT
			NetFlow* DMA2DRREADY, // OUTPUT
			NetFlow* DMA2RSTN, // OUTPUT
			NetFlow* DMA3DATYPE, // OUTPUT
			NetFlow* DMA3DAVALID, // OUTPUT
			NetFlow* DMA3DRREADY, // OUTPUT
			NetFlow* DMA3RSTN, // OUTPUT
			NetFlow* EMIOCAN0PHYTX, // OUTPUT
			NetFlow* EMIOCAN1PHYTX, // OUTPUT
			NetFlow* EMIOENET0GMIITXD, // OUTPUT
			NetFlow* EMIOENET0GMIITXEN, // OUTPUT
			NetFlow* EMIOENET0GMIITXER, // OUTPUT
			NetFlow* EMIOENET0MDIOMDC, // OUTPUT
			NetFlow* EMIOENET0MDIOO, // OUTPUT
			NetFlow* EMIOENET0MDIOTN, // OUTPUT
			NetFlow* EMIOENET0PTPDELAYREQRX, // OUTPUT
			NetFlow* EMIOENET0PTPDELAYREQTX, // OUTPUT
			NetFlow* EMIOENET0PTPPDELAYREQRX, // OUTPUT
			NetFlow* EMIOENET0PTPPDELAYREQTX, // OUTPUT
			NetFlow* EMIOENET0PTPPDELAYRESPRX, // OUTPUT
			NetFlow* EMIOENET0PTPPDELAYRESPTX, // OUTPUT
			NetFlow* EMIOENET0PTPSYNCFRAMERX, // OUTPUT
			NetFlow* EMIOENET0PTPSYNCFRAMETX, // OUTPUT
			NetFlow* EMIOENET0SOFRX, // OUTPUT
			NetFlow* EMIOENET0SOFTX, // OUTPUT
			NetFlow* EMIOENET1GMIITXD, // OUTPUT
			NetFlow* EMIOENET1GMIITXEN, // OUTPUT
			NetFlow* EMIOENET1GMIITXER, // OUTPUT
			NetFlow* EMIOENET1MDIOMDC, // OUTPUT
			NetFlow* EMIOENET1MDIOO, // OUTPUT
			NetFlow* EMIOENET1MDIOTN, // OUTPUT
			NetFlow* EMIOENET1PTPDELAYREQRX, // OUTPUT
			NetFlow* EMIOENET1PTPDELAYREQTX, // OUTPUT
			NetFlow* EMIOENET1PTPPDELAYREQRX, // OUTPUT
			NetFlow* EMIOENET1PTPPDELAYREQTX, // OUTPUT
			NetFlow* EMIOENET1PTPPDELAYRESPRX, // OUTPUT
			NetFlow* EMIOENET1PTPPDELAYRESPTX, // OUTPUT
			NetFlow* EMIOENET1PTPSYNCFRAMERX, // OUTPUT
			NetFlow* EMIOENET1PTPSYNCFRAMETX, // OUTPUT
			NetFlow* EMIOENET1SOFRX, // OUTPUT
			NetFlow* EMIOENET1SOFTX, // OUTPUT
			NetFlow* EMIOGPIOO, // OUTPUT
			NetFlow* EMIOGPIOTN, // OUTPUT
			NetFlow* EMIOI2C0SCLO, // OUTPUT
			NetFlow* EMIOI2C0SCLTN, // OUTPUT
			NetFlow* EMIOI2C0SDAO, // OUTPUT
			NetFlow* EMIOI2C0SDATN, // OUTPUT
			NetFlow* EMIOI2C1SCLO, // OUTPUT
			NetFlow* EMIOI2C1SCLTN, // OUTPUT
			NetFlow* EMIOI2C1SDAO, // OUTPUT
			NetFlow* EMIOI2C1SDATN, // OUTPUT
			NetFlow* EMIOPJTAGTDO, // OUTPUT
			NetFlow* EMIOPJTAGTDTN, // OUTPUT
			NetFlow* EMIOSDIO0BUSPOW, // OUTPUT
			NetFlow* EMIOSDIO0BUSVOLT, // OUTPUT
			NetFlow* EMIOSDIO0CLK, // OUTPUT
			NetFlow* EMIOSDIO0CMDO, // OUTPUT
			NetFlow* EMIOSDIO0CMDTN, // OUTPUT
			NetFlow* EMIOSDIO0DATAO, // OUTPUT
			NetFlow* EMIOSDIO0DATATN, // OUTPUT
			NetFlow* EMIOSDIO0LED, // OUTPUT
			NetFlow* EMIOSDIO1BUSPOW, // OUTPUT
			NetFlow* EMIOSDIO1BUSVOLT, // OUTPUT
			NetFlow* EMIOSDIO1CLK, // OUTPUT
			NetFlow* EMIOSDIO1CMDO, // OUTPUT
			NetFlow* EMIOSDIO1CMDTN, // OUTPUT
			NetFlow* EMIOSDIO1DATAO, // OUTPUT
			NetFlow* EMIOSDIO1DATATN, // OUTPUT
			NetFlow* EMIOSDIO1LED, // OUTPUT
			NetFlow* EMIOSPI0MO, // OUTPUT
			NetFlow* EMIOSPI0MOTN, // OUTPUT
			NetFlow* EMIOSPI0SCLKO, // OUTPUT
			NetFlow* EMIOSPI0SCLKTN, // OUTPUT
			NetFlow* EMIOSPI0SO, // OUTPUT
			NetFlow* EMIOSPI0SSNTN, // OUTPUT
			NetFlow* EMIOSPI0SSON, // OUTPUT
			NetFlow* EMIOSPI0STN, // OUTPUT
			NetFlow* EMIOSPI1MO, // OUTPUT
			NetFlow* EMIOSPI1MOTN, // OUTPUT
			NetFlow* EMIOSPI1SCLKO, // OUTPUT
			NetFlow* EMIOSPI1SCLKTN, // OUTPUT
			NetFlow* EMIOSPI1SO, // OUTPUT
			NetFlow* EMIOSPI1SSNTN, // OUTPUT
			NetFlow* EMIOSPI1SSON, // OUTPUT
			NetFlow* EMIOSPI1STN, // OUTPUT
			NetFlow* EMIOTRACECTL, // OUTPUT
			NetFlow* EMIOTRACEDATA, // OUTPUT
			NetFlow* EMIOTTC0WAVEO, // OUTPUT
			NetFlow* EMIOTTC1WAVEO, // OUTPUT
			NetFlow* EMIOUART0DTRN, // OUTPUT
			NetFlow* EMIOUART0RTSN, // OUTPUT
			NetFlow* EMIOUART0TX, // OUTPUT
			NetFlow* EMIOUART1DTRN, // OUTPUT
			NetFlow* EMIOUART1RTSN, // OUTPUT
			NetFlow* EMIOUART1TX, // OUTPUT
			NetFlow* EMIOUSB0PORTINDCTL, // OUTPUT
			NetFlow* EMIOUSB0VBUSPWRSELECT, // OUTPUT
			NetFlow* EMIOUSB1PORTINDCTL, // OUTPUT
			NetFlow* EMIOUSB1VBUSPWRSELECT, // OUTPUT
			NetFlow* EMIOWDTRSTO, // OUTPUT
			NetFlow* EVENTEVENTO, // OUTPUT
			NetFlow* EVENTSTANDBYWFE, // OUTPUT
			NetFlow* EVENTSTANDBYWFI, // OUTPUT
			NetFlow* FCLKCLK, // OUTPUT
			NetFlow* FCLKRESETN, // OUTPUT
			NetFlow* FTMTF2PTRIGACK, // OUTPUT
			NetFlow* FTMTP2FDEBUG, // OUTPUT
			NetFlow* FTMTP2FTRIG, // OUTPUT
			NetFlow* IRQP2F, // OUTPUT
			NetFlow* MAXIGP0ARADDR, // OUTPUT
			NetFlow* MAXIGP0ARBURST, // OUTPUT
			NetFlow* MAXIGP0ARCACHE, // OUTPUT
			NetFlow* MAXIGP0ARESETN, // OUTPUT
			NetFlow* MAXIGP0ARID, // OUTPUT
			NetFlow* MAXIGP0ARLEN, // OUTPUT
			NetFlow* MAXIGP0ARLOCK, // OUTPUT
			NetFlow* MAXIGP0ARPROT, // OUTPUT
			NetFlow* MAXIGP0ARQOS, // OUTPUT
			NetFlow* MAXIGP0ARSIZE, // OUTPUT
			NetFlow* MAXIGP0ARVALID, // OUTPUT
			NetFlow* MAXIGP0AWADDR, // OUTPUT
			NetFlow* MAXIGP0AWBURST, // OUTPUT
			NetFlow* MAXIGP0AWCACHE, // OUTPUT
			NetFlow* MAXIGP0AWID, // OUTPUT
			NetFlow* MAXIGP0AWLEN, // OUTPUT
			NetFlow* MAXIGP0AWLOCK, // OUTPUT
			NetFlow* MAXIGP0AWPROT, // OUTPUT
			NetFlow* MAXIGP0AWQOS, // OUTPUT
			NetFlow* MAXIGP0AWSIZE, // OUTPUT
			NetFlow* MAXIGP0AWVALID, // OUTPUT
			NetFlow* MAXIGP0BREADY, // OUTPUT
			NetFlow* MAXIGP0RREADY, // OUTPUT
			NetFlow* MAXIGP0WDATA, // OUTPUT
			NetFlow* MAXIGP0WID, // OUTPUT
			NetFlow* MAXIGP0WLAST, // OUTPUT
			NetFlow* MAXIGP0WSTRB, // OUTPUT
			NetFlow* MAXIGP0WVALID, // OUTPUT
			NetFlow* MAXIGP1ARADDR, // OUTPUT
			NetFlow* MAXIGP1ARBURST, // OUTPUT
			NetFlow* MAXIGP1ARCACHE, // OUTPUT
			NetFlow* MAXIGP1ARESETN, // OUTPUT
			NetFlow* MAXIGP1ARID, // OUTPUT
			NetFlow* MAXIGP1ARLEN, // OUTPUT
			NetFlow* MAXIGP1ARLOCK, // OUTPUT
			NetFlow* MAXIGP1ARPROT, // OUTPUT
			NetFlow* MAXIGP1ARQOS, // OUTPUT
			NetFlow* MAXIGP1ARSIZE, // OUTPUT
			NetFlow* MAXIGP1ARVALID, // OUTPUT
			NetFlow* MAXIGP1AWADDR, // OUTPUT
			NetFlow* MAXIGP1AWBURST, // OUTPUT
			NetFlow* MAXIGP1AWCACHE, // OUTPUT
			NetFlow* MAXIGP1AWID, // OUTPUT
			NetFlow* MAXIGP1AWLEN, // OUTPUT
			NetFlow* MAXIGP1AWLOCK, // OUTPUT
			NetFlow* MAXIGP1AWPROT, // OUTPUT
			NetFlow* MAXIGP1AWQOS, // OUTPUT
			NetFlow* MAXIGP1AWSIZE, // OUTPUT
			NetFlow* MAXIGP1AWVALID, // OUTPUT
			NetFlow* MAXIGP1BREADY, // OUTPUT
			NetFlow* MAXIGP1RREADY, // OUTPUT
			NetFlow* MAXIGP1WDATA, // OUTPUT
			NetFlow* MAXIGP1WID, // OUTPUT
			NetFlow* MAXIGP1WLAST, // OUTPUT
			NetFlow* MAXIGP1WSTRB, // OUTPUT
			NetFlow* MAXIGP1WVALID, // OUTPUT
			NetFlow* SAXIACPARESETN, // OUTPUT
			NetFlow* SAXIACPARREADY, // OUTPUT
			NetFlow* SAXIACPAWREADY, // OUTPUT
			NetFlow* SAXIACPBID, // OUTPUT
			NetFlow* SAXIACPBRESP, // OUTPUT
			NetFlow* SAXIACPBVALID, // OUTPUT
			NetFlow* SAXIACPRDATA, // OUTPUT
			NetFlow* SAXIACPRID, // OUTPUT
			NetFlow* SAXIACPRLAST, // OUTPUT
			NetFlow* SAXIACPRRESP, // OUTPUT
			NetFlow* SAXIACPRVALID, // OUTPUT
			NetFlow* SAXIACPWREADY, // OUTPUT
			NetFlow* SAXIGP0ARESETN, // OUTPUT
			NetFlow* SAXIGP0ARREADY, // OUTPUT
			NetFlow* SAXIGP0AWREADY, // OUTPUT
			NetFlow* SAXIGP0BID, // OUTPUT
			NetFlow* SAXIGP0BRESP, // OUTPUT
			NetFlow* SAXIGP0BVALID, // OUTPUT
			NetFlow* SAXIGP0RDATA, // OUTPUT
			NetFlow* SAXIGP0RID, // OUTPUT
			NetFlow* SAXIGP0RLAST, // OUTPUT
			NetFlow* SAXIGP0RRESP, // OUTPUT
			NetFlow* SAXIGP0RVALID, // OUTPUT
			NetFlow* SAXIGP0WREADY, // OUTPUT
			NetFlow* SAXIGP1ARESETN, // OUTPUT
			NetFlow* SAXIGP1ARREADY, // OUTPUT
			NetFlow* SAXIGP1AWREADY, // OUTPUT
			NetFlow* SAXIGP1BID, // OUTPUT
			NetFlow* SAXIGP1BRESP, // OUTPUT
			NetFlow* SAXIGP1BVALID, // OUTPUT
			NetFlow* SAXIGP1RDATA, // OUTPUT
			NetFlow* SAXIGP1RID, // OUTPUT
			NetFlow* SAXIGP1RLAST, // OUTPUT
			NetFlow* SAXIGP1RRESP, // OUTPUT
			NetFlow* SAXIGP1RVALID, // OUTPUT
			NetFlow* SAXIGP1WREADY, // OUTPUT
			NetFlow* SAXIHP0ARESETN, // OUTPUT
			NetFlow* SAXIHP0ARREADY, // OUTPUT
			NetFlow* SAXIHP0AWREADY, // OUTPUT
			NetFlow* SAXIHP0BID, // OUTPUT
			NetFlow* SAXIHP0BRESP, // OUTPUT
			NetFlow* SAXIHP0BVALID, // OUTPUT
			NetFlow* SAXIHP0RACOUNT, // OUTPUT
			NetFlow* SAXIHP0RCOUNT, // OUTPUT
			NetFlow* SAXIHP0RDATA, // OUTPUT
			NetFlow* SAXIHP0RID, // OUTPUT
			NetFlow* SAXIHP0RLAST, // OUTPUT
			NetFlow* SAXIHP0RRESP, // OUTPUT
			NetFlow* SAXIHP0RVALID, // OUTPUT
			NetFlow* SAXIHP0WACOUNT, // OUTPUT
			NetFlow* SAXIHP0WCOUNT, // OUTPUT
			NetFlow* SAXIHP0WREADY, // OUTPUT
			NetFlow* SAXIHP1ARESETN, // OUTPUT
			NetFlow* SAXIHP1ARREADY, // OUTPUT
			NetFlow* SAXIHP1AWREADY, // OUTPUT
			NetFlow* SAXIHP1BID, // OUTPUT
			NetFlow* SAXIHP1BRESP, // OUTPUT
			NetFlow* SAXIHP1BVALID, // OUTPUT
			NetFlow* SAXIHP1RACOUNT, // OUTPUT
			NetFlow* SAXIHP1RCOUNT, // OUTPUT
			NetFlow* SAXIHP1RDATA, // OUTPUT
			NetFlow* SAXIHP1RID, // OUTPUT
			NetFlow* SAXIHP1RLAST, // OUTPUT
			NetFlow* SAXIHP1RRESP, // OUTPUT
			NetFlow* SAXIHP1RVALID, // OUTPUT
			NetFlow* SAXIHP1WACOUNT, // OUTPUT
			NetFlow* SAXIHP1WCOUNT, // OUTPUT
			NetFlow* SAXIHP1WREADY, // OUTPUT
			NetFlow* SAXIHP2ARESETN, // OUTPUT
			NetFlow* SAXIHP2ARREADY, // OUTPUT
			NetFlow* SAXIHP2AWREADY, // OUTPUT
			NetFlow* SAXIHP2BID, // OUTPUT
			NetFlow* SAXIHP2BRESP, // OUTPUT
			NetFlow* SAXIHP2BVALID, // OUTPUT
			NetFlow* SAXIHP2RACOUNT, // OUTPUT
			NetFlow* SAXIHP2RCOUNT, // OUTPUT
			NetFlow* SAXIHP2RDATA, // OUTPUT
			NetFlow* SAXIHP2RID, // OUTPUT
			NetFlow* SAXIHP2RLAST, // OUTPUT
			NetFlow* SAXIHP2RRESP, // OUTPUT
			NetFlow* SAXIHP2RVALID, // OUTPUT
			NetFlow* SAXIHP2WACOUNT, // OUTPUT
			NetFlow* SAXIHP2WCOUNT, // OUTPUT
			NetFlow* SAXIHP2WREADY, // OUTPUT
			NetFlow* SAXIHP3ARESETN, // OUTPUT
			NetFlow* SAXIHP3ARREADY, // OUTPUT
			NetFlow* SAXIHP3AWREADY, // OUTPUT
			NetFlow* SAXIHP3BID, // OUTPUT
			NetFlow* SAXIHP3BRESP, // OUTPUT
			NetFlow* SAXIHP3BVALID, // OUTPUT
			NetFlow* SAXIHP3RACOUNT, // OUTPUT
			NetFlow* SAXIHP3RCOUNT, // OUTPUT
			NetFlow* SAXIHP3RDATA, // OUTPUT
			NetFlow* SAXIHP3RID, // OUTPUT
			NetFlow* SAXIHP3RLAST, // OUTPUT
			NetFlow* SAXIHP3RRESP, // OUTPUT
			NetFlow* SAXIHP3RVALID, // OUTPUT
			NetFlow* SAXIHP3WACOUNT, // OUTPUT
			NetFlow* SAXIHP3WCOUNT, // OUTPUT
			NetFlow* SAXIHP3WREADY, // OUTPUT
			NetFlow* DDRA, // INOUT
			NetFlow* DDRBA, // INOUT
			NetFlow* DDRCASB, // INOUT
			NetFlow* DDRCKE, // INOUT
			NetFlow* DDRCKN, // INOUT
			NetFlow* DDRCKP, // INOUT
			NetFlow* DDRCSB, // INOUT
			NetFlow* DDRDM, // INOUT
			NetFlow* DDRDQ, // INOUT
			NetFlow* DDRDQSN, // INOUT
			NetFlow* DDRDQSP, // INOUT
			NetFlow* DDRDRSTB, // INOUT
			NetFlow* DDRODT, // INOUT
			NetFlow* DDRRASB, // INOUT
			NetFlow* DDRVRN, // INOUT
			NetFlow* DDRVRP, // INOUT
			NetFlow* DDRWEB, // INOUT
			NetFlow* MIO, // INOUT
			NetFlow* PSCLK, // INOUT
			NetFlow* PSPORB, // INOUT
			NetFlow* PSSRSTB, // INOUT
			NetFlow* DDRARB, // INPUT
			NetFlow* DMA0ACLK, // INPUT
			NetFlow* DMA0DAREADY, // INPUT
			NetFlow* DMA0DRLAST, // INPUT
			NetFlow* DMA0DRTYPE, // INPUT
			NetFlow* DMA0DRVALID, // INPUT
			NetFlow* DMA1ACLK, // INPUT
			NetFlow* DMA1DAREADY, // INPUT
			NetFlow* DMA1DRLAST, // INPUT
			NetFlow* DMA1DRTYPE, // INPUT
			NetFlow* DMA1DRVALID, // INPUT
			NetFlow* DMA2ACLK, // INPUT
			NetFlow* DMA2DAREADY, // INPUT
			NetFlow* DMA2DRLAST, // INPUT
			NetFlow* DMA2DRTYPE, // INPUT
			NetFlow* DMA2DRVALID, // INPUT
			NetFlow* DMA3ACLK, // INPUT
			NetFlow* DMA3DAREADY, // INPUT
			NetFlow* DMA3DRLAST, // INPUT
			NetFlow* DMA3DRTYPE, // INPUT
			NetFlow* DMA3DRVALID, // INPUT
			NetFlow* EMIOCAN0PHYRX, // INPUT
			NetFlow* EMIOCAN1PHYRX, // INPUT
			NetFlow* EMIOENET0EXTINTIN, // INPUT
			NetFlow* EMIOENET0GMIICOL, // INPUT
			NetFlow* EMIOENET0GMIICRS, // INPUT
			NetFlow* EMIOENET0GMIIRXCLK, // INPUT
			NetFlow* EMIOENET0GMIIRXD, // INPUT
			NetFlow* EMIOENET0GMIIRXDV, // INPUT
			NetFlow* EMIOENET0GMIIRXER, // INPUT
			NetFlow* EMIOENET0GMIITXCLK, // INPUT
			NetFlow* EMIOENET0MDIOI, // INPUT
			NetFlow* EMIOENET1EXTINTIN, // INPUT
			NetFlow* EMIOENET1GMIICOL, // INPUT
			NetFlow* EMIOENET1GMIICRS, // INPUT
			NetFlow* EMIOENET1GMIIRXCLK, // INPUT
			NetFlow* EMIOENET1GMIIRXD, // INPUT
			NetFlow* EMIOENET1GMIIRXDV, // INPUT
			NetFlow* EMIOENET1GMIIRXER, // INPUT
			NetFlow* EMIOENET1GMIITXCLK, // INPUT
			NetFlow* EMIOENET1MDIOI, // INPUT
			NetFlow* EMIOGPIOI, // INPUT
			NetFlow* EMIOI2C0SCLI, // INPUT
			NetFlow* EMIOI2C0SDAI, // INPUT
			NetFlow* EMIOI2C1SCLI, // INPUT
			NetFlow* EMIOI2C1SDAI, // INPUT
			NetFlow* EMIOPJTAGTCK, // INPUT
			NetFlow* EMIOPJTAGTDI, // INPUT
			NetFlow* EMIOPJTAGTMS, // INPUT
			NetFlow* EMIOSDIO0CDN, // INPUT
			NetFlow* EMIOSDIO0CLKFB, // INPUT
			NetFlow* EMIOSDIO0CMDI, // INPUT
			NetFlow* EMIOSDIO0DATAI, // INPUT
			NetFlow* EMIOSDIO0WP, // INPUT
			NetFlow* EMIOSDIO1CDN, // INPUT
			NetFlow* EMIOSDIO1CLKFB, // INPUT
			NetFlow* EMIOSDIO1CMDI, // INPUT
			NetFlow* EMIOSDIO1DATAI, // INPUT
			NetFlow* EMIOSDIO1WP, // INPUT
			NetFlow* EMIOSPI0MI, // INPUT
			NetFlow* EMIOSPI0SCLKI, // INPUT
			NetFlow* EMIOSPI0SI, // INPUT
			NetFlow* EMIOSPI0SSIN, // INPUT
			NetFlow* EMIOSPI1MI, // INPUT
			NetFlow* EMIOSPI1SCLKI, // INPUT
			NetFlow* EMIOSPI1SI, // INPUT
			NetFlow* EMIOSPI1SSIN, // INPUT
			NetFlow* EMIOSRAMINTIN, // INPUT
			NetFlow* EMIOTRACECLK, // INPUT
			NetFlow* EMIOTTC0CLKI, // INPUT
			NetFlow* EMIOTTC1CLKI, // INPUT
			NetFlow* EMIOUART0CTSN, // INPUT
			NetFlow* EMIOUART0DCDN, // INPUT
			NetFlow* EMIOUART0DSRN, // INPUT
			NetFlow* EMIOUART0RIN, // INPUT
			NetFlow* EMIOUART0RX, // INPUT
			NetFlow* EMIOUART1CTSN, // INPUT
			NetFlow* EMIOUART1DCDN, // INPUT
			NetFlow* EMIOUART1DSRN, // INPUT
			NetFlow* EMIOUART1RIN, // INPUT
			NetFlow* EMIOUART1RX, // INPUT
			NetFlow* EMIOUSB0VBUSPWRFAULT, // INPUT
			NetFlow* EMIOUSB1VBUSPWRFAULT, // INPUT
			NetFlow* EMIOWDTCLKI, // INPUT
			NetFlow* EVENTEVENTI, // INPUT
			NetFlow* FCLKCLKTRIGN, // INPUT
			NetFlow* FPGAIDLEN, // INPUT
			NetFlow* FTMDTRACEINATID, // INPUT
			NetFlow* FTMDTRACEINCLOCK, // INPUT
			NetFlow* FTMDTRACEINDATA, // INPUT
			NetFlow* FTMDTRACEINVALID, // INPUT
			NetFlow* FTMTF2PDEBUG, // INPUT
			NetFlow* FTMTF2PTRIG, // INPUT
			NetFlow* FTMTP2FTRIGACK, // INPUT
			NetFlow* IRQF2P, // INPUT
			NetFlow* MAXIGP0ACLK, // INPUT
			NetFlow* MAXIGP0ARREADY, // INPUT
			NetFlow* MAXIGP0AWREADY, // INPUT
			NetFlow* MAXIGP0BID, // INPUT
			NetFlow* MAXIGP0BRESP, // INPUT
			NetFlow* MAXIGP0BVALID, // INPUT
			NetFlow* MAXIGP0RDATA, // INPUT
			NetFlow* MAXIGP0RID, // INPUT
			NetFlow* MAXIGP0RLAST, // INPUT
			NetFlow* MAXIGP0RRESP, // INPUT
			NetFlow* MAXIGP0RVALID, // INPUT
			NetFlow* MAXIGP0WREADY, // INPUT
			NetFlow* MAXIGP1ACLK, // INPUT
			NetFlow* MAXIGP1ARREADY, // INPUT
			NetFlow* MAXIGP1AWREADY, // INPUT
			NetFlow* MAXIGP1BID, // INPUT
			NetFlow* MAXIGP1BRESP, // INPUT
			NetFlow* MAXIGP1BVALID, // INPUT
			NetFlow* MAXIGP1RDATA, // INPUT
			NetFlow* MAXIGP1RID, // INPUT
			NetFlow* MAXIGP1RLAST, // INPUT
			NetFlow* MAXIGP1RRESP, // INPUT
			NetFlow* MAXIGP1RVALID, // INPUT
			NetFlow* MAXIGP1WREADY, // INPUT
			NetFlow* SAXIACPACLK, // INPUT
			NetFlow* SAXIACPARADDR, // INPUT
			NetFlow* SAXIACPARBURST, // INPUT
			NetFlow* SAXIACPARCACHE, // INPUT
			NetFlow* SAXIACPARID, // INPUT
			NetFlow* SAXIACPARLEN, // INPUT
			NetFlow* SAXIACPARLOCK, // INPUT
			NetFlow* SAXIACPARPROT, // INPUT
			NetFlow* SAXIACPARQOS, // INPUT
			NetFlow* SAXIACPARSIZE, // INPUT
			NetFlow* SAXIACPARUSER, // INPUT
			NetFlow* SAXIACPARVALID, // INPUT
			NetFlow* SAXIACPAWADDR, // INPUT
			NetFlow* SAXIACPAWBURST, // INPUT
			NetFlow* SAXIACPAWCACHE, // INPUT
			NetFlow* SAXIACPAWID, // INPUT
			NetFlow* SAXIACPAWLEN, // INPUT
			NetFlow* SAXIACPAWLOCK, // INPUT
			NetFlow* SAXIACPAWPROT, // INPUT
			NetFlow* SAXIACPAWQOS, // INPUT
			NetFlow* SAXIACPAWSIZE, // INPUT
			NetFlow* SAXIACPAWUSER, // INPUT
			NetFlow* SAXIACPAWVALID, // INPUT
			NetFlow* SAXIACPBREADY, // INPUT
			NetFlow* SAXIACPRREADY, // INPUT
			NetFlow* SAXIACPWDATA, // INPUT
			NetFlow* SAXIACPWID, // INPUT
			NetFlow* SAXIACPWLAST, // INPUT
			NetFlow* SAXIACPWSTRB, // INPUT
			NetFlow* SAXIACPWVALID, // INPUT
			NetFlow* SAXIGP0ACLK, // INPUT
			NetFlow* SAXIGP0ARADDR, // INPUT
			NetFlow* SAXIGP0ARBURST, // INPUT
			NetFlow* SAXIGP0ARCACHE, // INPUT
			NetFlow* SAXIGP0ARID, // INPUT
			NetFlow* SAXIGP0ARLEN, // INPUT
			NetFlow* SAXIGP0ARLOCK, // INPUT
			NetFlow* SAXIGP0ARPROT, // INPUT
			NetFlow* SAXIGP0ARQOS, // INPUT
			NetFlow* SAXIGP0ARSIZE, // INPUT
			NetFlow* SAXIGP0ARVALID, // INPUT
			NetFlow* SAXIGP0AWADDR, // INPUT
			NetFlow* SAXIGP0AWBURST, // INPUT
			NetFlow* SAXIGP0AWCACHE, // INPUT
			NetFlow* SAXIGP0AWID, // INPUT
			NetFlow* SAXIGP0AWLEN, // INPUT
			NetFlow* SAXIGP0AWLOCK, // INPUT
			NetFlow* SAXIGP0AWPROT, // INPUT
			NetFlow* SAXIGP0AWQOS, // INPUT
			NetFlow* SAXIGP0AWSIZE, // INPUT
			NetFlow* SAXIGP0AWVALID, // INPUT
			NetFlow* SAXIGP0BREADY, // INPUT
			NetFlow* SAXIGP0RREADY, // INPUT
			NetFlow* SAXIGP0WDATA, // INPUT
			NetFlow* SAXIGP0WID, // INPUT
			NetFlow* SAXIGP0WLAST, // INPUT
			NetFlow* SAXIGP0WSTRB, // INPUT
			NetFlow* SAXIGP0WVALID, // INPUT
			NetFlow* SAXIGP1ACLK, // INPUT
			NetFlow* SAXIGP1ARADDR, // INPUT
			NetFlow* SAXIGP1ARBURST, // INPUT
			NetFlow* SAXIGP1ARCACHE, // INPUT
			NetFlow* SAXIGP1ARID, // INPUT
			NetFlow* SAXIGP1ARLEN, // INPUT
			NetFlow* SAXIGP1ARLOCK, // INPUT
			NetFlow* SAXIGP1ARPROT, // INPUT
			NetFlow* SAXIGP1ARQOS, // INPUT
			NetFlow* SAXIGP1ARSIZE, // INPUT
			NetFlow* SAXIGP1ARVALID, // INPUT
			NetFlow* SAXIGP1AWADDR, // INPUT
			NetFlow* SAXIGP1AWBURST, // INPUT
			NetFlow* SAXIGP1AWCACHE, // INPUT
			NetFlow* SAXIGP1AWID, // INPUT
			NetFlow* SAXIGP1AWLEN, // INPUT
			NetFlow* SAXIGP1AWLOCK, // INPUT
			NetFlow* SAXIGP1AWPROT, // INPUT
			NetFlow* SAXIGP1AWQOS, // INPUT
			NetFlow* SAXIGP1AWSIZE, // INPUT
			NetFlow* SAXIGP1AWVALID, // INPUT
			NetFlow* SAXIGP1BREADY, // INPUT
			NetFlow* SAXIGP1RREADY, // INPUT
			NetFlow* SAXIGP1WDATA, // INPUT
			NetFlow* SAXIGP1WID, // INPUT
			NetFlow* SAXIGP1WLAST, // INPUT
			NetFlow* SAXIGP1WSTRB, // INPUT
			NetFlow* SAXIGP1WVALID, // INPUT
			NetFlow* SAXIHP0ACLK, // INPUT
			NetFlow* SAXIHP0ARADDR, // INPUT
			NetFlow* SAXIHP0ARBURST, // INPUT
			NetFlow* SAXIHP0ARCACHE, // INPUT
			NetFlow* SAXIHP0ARID, // INPUT
			NetFlow* SAXIHP0ARLEN, // INPUT
			NetFlow* SAXIHP0ARLOCK, // INPUT
			NetFlow* SAXIHP0ARPROT, // INPUT
			NetFlow* SAXIHP0ARQOS, // INPUT
			NetFlow* SAXIHP0ARSIZE, // INPUT
			NetFlow* SAXIHP0ARVALID, // INPUT
			NetFlow* SAXIHP0AWADDR, // INPUT
			NetFlow* SAXIHP0AWBURST, // INPUT
			NetFlow* SAXIHP0AWCACHE, // INPUT
			NetFlow* SAXIHP0AWID, // INPUT
			NetFlow* SAXIHP0AWLEN, // INPUT
			NetFlow* SAXIHP0AWLOCK, // INPUT
			NetFlow* SAXIHP0AWPROT, // INPUT
			NetFlow* SAXIHP0AWQOS, // INPUT
			NetFlow* SAXIHP0AWSIZE, // INPUT
			NetFlow* SAXIHP0AWVALID, // INPUT
			NetFlow* SAXIHP0BREADY, // INPUT
			NetFlow* SAXIHP0RDISSUECAP1EN, // INPUT
			NetFlow* SAXIHP0RREADY, // INPUT
			NetFlow* SAXIHP0WDATA, // INPUT
			NetFlow* SAXIHP0WID, // INPUT
			NetFlow* SAXIHP0WLAST, // INPUT
			NetFlow* SAXIHP0WRISSUECAP1EN, // INPUT
			NetFlow* SAXIHP0WSTRB, // INPUT
			NetFlow* SAXIHP0WVALID, // INPUT
			NetFlow* SAXIHP1ACLK, // INPUT
			NetFlow* SAXIHP1ARADDR, // INPUT
			NetFlow* SAXIHP1ARBURST, // INPUT
			NetFlow* SAXIHP1ARCACHE, // INPUT
			NetFlow* SAXIHP1ARID, // INPUT
			NetFlow* SAXIHP1ARLEN, // INPUT
			NetFlow* SAXIHP1ARLOCK, // INPUT
			NetFlow* SAXIHP1ARPROT, // INPUT
			NetFlow* SAXIHP1ARQOS, // INPUT
			NetFlow* SAXIHP1ARSIZE, // INPUT
			NetFlow* SAXIHP1ARVALID, // INPUT
			NetFlow* SAXIHP1AWADDR, // INPUT
			NetFlow* SAXIHP1AWBURST, // INPUT
			NetFlow* SAXIHP1AWCACHE, // INPUT
			NetFlow* SAXIHP1AWID, // INPUT
			NetFlow* SAXIHP1AWLEN, // INPUT
			NetFlow* SAXIHP1AWLOCK, // INPUT
			NetFlow* SAXIHP1AWPROT, // INPUT
			NetFlow* SAXIHP1AWQOS, // INPUT
			NetFlow* SAXIHP1AWSIZE, // INPUT
			NetFlow* SAXIHP1AWVALID, // INPUT
			NetFlow* SAXIHP1BREADY, // INPUT
			NetFlow* SAXIHP1RDISSUECAP1EN, // INPUT
			NetFlow* SAXIHP1RREADY, // INPUT
			NetFlow* SAXIHP1WDATA, // INPUT
			NetFlow* SAXIHP1WID, // INPUT
			NetFlow* SAXIHP1WLAST, // INPUT
			NetFlow* SAXIHP1WRISSUECAP1EN, // INPUT
			NetFlow* SAXIHP1WSTRB, // INPUT
			NetFlow* SAXIHP1WVALID, // INPUT
			NetFlow* SAXIHP2ACLK, // INPUT
			NetFlow* SAXIHP2ARADDR, // INPUT
			NetFlow* SAXIHP2ARBURST, // INPUT
			NetFlow* SAXIHP2ARCACHE, // INPUT
			NetFlow* SAXIHP2ARID, // INPUT
			NetFlow* SAXIHP2ARLEN, // INPUT
			NetFlow* SAXIHP2ARLOCK, // INPUT
			NetFlow* SAXIHP2ARPROT, // INPUT
			NetFlow* SAXIHP2ARQOS, // INPUT
			NetFlow* SAXIHP2ARSIZE, // INPUT
			NetFlow* SAXIHP2ARVALID, // INPUT
			NetFlow* SAXIHP2AWADDR, // INPUT
			NetFlow* SAXIHP2AWBURST, // INPUT
			NetFlow* SAXIHP2AWCACHE, // INPUT
			NetFlow* SAXIHP2AWID, // INPUT
			NetFlow* SAXIHP2AWLEN, // INPUT
			NetFlow* SAXIHP2AWLOCK, // INPUT
			NetFlow* SAXIHP2AWPROT, // INPUT
			NetFlow* SAXIHP2AWQOS, // INPUT
			NetFlow* SAXIHP2AWSIZE, // INPUT
			NetFlow* SAXIHP2AWVALID, // INPUT
			NetFlow* SAXIHP2BREADY, // INPUT
			NetFlow* SAXIHP2RDISSUECAP1EN, // INPUT
			NetFlow* SAXIHP2RREADY, // INPUT
			NetFlow* SAXIHP2WDATA, // INPUT
			NetFlow* SAXIHP2WID, // INPUT
			NetFlow* SAXIHP2WLAST, // INPUT
			NetFlow* SAXIHP2WRISSUECAP1EN, // INPUT
			NetFlow* SAXIHP2WSTRB, // INPUT
			NetFlow* SAXIHP2WVALID, // INPUT
			NetFlow* SAXIHP3ACLK, // INPUT
			NetFlow* SAXIHP3ARADDR, // INPUT
			NetFlow* SAXIHP3ARBURST, // INPUT
			NetFlow* SAXIHP3ARCACHE, // INPUT
			NetFlow* SAXIHP3ARID, // INPUT
			NetFlow* SAXIHP3ARLEN, // INPUT
			NetFlow* SAXIHP3ARLOCK, // INPUT
			NetFlow* SAXIHP3ARPROT, // INPUT
			NetFlow* SAXIHP3ARQOS, // INPUT
			NetFlow* SAXIHP3ARSIZE, // INPUT
			NetFlow* SAXIHP3ARVALID, // INPUT
			NetFlow* SAXIHP3AWADDR, // INPUT
			NetFlow* SAXIHP3AWBURST, // INPUT
			NetFlow* SAXIHP3AWCACHE, // INPUT
			NetFlow* SAXIHP3AWID, // INPUT
			NetFlow* SAXIHP3AWLEN, // INPUT
			NetFlow* SAXIHP3AWLOCK, // INPUT
			NetFlow* SAXIHP3AWPROT, // INPUT
			NetFlow* SAXIHP3AWQOS, // INPUT
			NetFlow* SAXIHP3AWSIZE, // INPUT
			NetFlow* SAXIHP3AWVALID, // INPUT
			NetFlow* SAXIHP3BREADY, // INPUT
			NetFlow* SAXIHP3RDISSUECAP1EN, // INPUT
			NetFlow* SAXIHP3RREADY, // INPUT
			NetFlow* SAXIHP3WDATA, // INPUT
			NetFlow* SAXIHP3WID, // INPUT
			NetFlow* SAXIHP3WLAST, // INPUT
			NetFlow* SAXIHP3WRISSUECAP1EN, // INPUT
			NetFlow* SAXIHP3WSTRB, // INPUT
			NetFlow* SAXIHP3WVALID // INPUT
			){
		
			// Assign parameters and ports: 
			//Verilog Parameters:
			this->LOC = LOC; // Default: "UNPLACED"
			//Verilog Ports in definition order:
			this->DMA0DATYPE = DMA0DATYPE; // OUTPUT
			this->DMA0DAVALID = DMA0DAVALID; // OUTPUT
			this->DMA0DRREADY = DMA0DRREADY; // OUTPUT
			this->DMA0RSTN = DMA0RSTN; // OUTPUT
			this->DMA1DATYPE = DMA1DATYPE; // OUTPUT
			this->DMA1DAVALID = DMA1DAVALID; // OUTPUT
			this->DMA1DRREADY = DMA1DRREADY; // OUTPUT
			this->DMA1RSTN = DMA1RSTN; // OUTPUT
			this->DMA2DATYPE = DMA2DATYPE; // OUTPUT
			this->DMA2DAVALID = DMA2DAVALID; // OUTPUT
			this->DMA2DRREADY = DMA2DRREADY; // OUTPUT
			this->DMA2RSTN = DMA2RSTN; // OUTPUT
			this->DMA3DATYPE = DMA3DATYPE; // OUTPUT
			this->DMA3DAVALID = DMA3DAVALID; // OUTPUT
			this->DMA3DRREADY = DMA3DRREADY; // OUTPUT
			this->DMA3RSTN = DMA3RSTN; // OUTPUT
			this->EMIOCAN0PHYTX = EMIOCAN0PHYTX; // OUTPUT
			this->EMIOCAN1PHYTX = EMIOCAN1PHYTX; // OUTPUT
			this->EMIOENET0GMIITXD = EMIOENET0GMIITXD; // OUTPUT
			this->EMIOENET0GMIITXEN = EMIOENET0GMIITXEN; // OUTPUT
			this->EMIOENET0GMIITXER = EMIOENET0GMIITXER; // OUTPUT
			this->EMIOENET0MDIOMDC = EMIOENET0MDIOMDC; // OUTPUT
			this->EMIOENET0MDIOO = EMIOENET0MDIOO; // OUTPUT
			this->EMIOENET0MDIOTN = EMIOENET0MDIOTN; // OUTPUT
			this->EMIOENET0PTPDELAYREQRX = EMIOENET0PTPDELAYREQRX; // OUTPUT
			this->EMIOENET0PTPDELAYREQTX = EMIOENET0PTPDELAYREQTX; // OUTPUT
			this->EMIOENET0PTPPDELAYREQRX = EMIOENET0PTPPDELAYREQRX; // OUTPUT
			this->EMIOENET0PTPPDELAYREQTX = EMIOENET0PTPPDELAYREQTX; // OUTPUT
			this->EMIOENET0PTPPDELAYRESPRX = EMIOENET0PTPPDELAYRESPRX; // OUTPUT
			this->EMIOENET0PTPPDELAYRESPTX = EMIOENET0PTPPDELAYRESPTX; // OUTPUT
			this->EMIOENET0PTPSYNCFRAMERX = EMIOENET0PTPSYNCFRAMERX; // OUTPUT
			this->EMIOENET0PTPSYNCFRAMETX = EMIOENET0PTPSYNCFRAMETX; // OUTPUT
			this->EMIOENET0SOFRX = EMIOENET0SOFRX; // OUTPUT
			this->EMIOENET0SOFTX = EMIOENET0SOFTX; // OUTPUT
			this->EMIOENET1GMIITXD = EMIOENET1GMIITXD; // OUTPUT
			this->EMIOENET1GMIITXEN = EMIOENET1GMIITXEN; // OUTPUT
			this->EMIOENET1GMIITXER = EMIOENET1GMIITXER; // OUTPUT
			this->EMIOENET1MDIOMDC = EMIOENET1MDIOMDC; // OUTPUT
			this->EMIOENET1MDIOO = EMIOENET1MDIOO; // OUTPUT
			this->EMIOENET1MDIOTN = EMIOENET1MDIOTN; // OUTPUT
			this->EMIOENET1PTPDELAYREQRX = EMIOENET1PTPDELAYREQRX; // OUTPUT
			this->EMIOENET1PTPDELAYREQTX = EMIOENET1PTPDELAYREQTX; // OUTPUT
			this->EMIOENET1PTPPDELAYREQRX = EMIOENET1PTPPDELAYREQRX; // OUTPUT
			this->EMIOENET1PTPPDELAYREQTX = EMIOENET1PTPPDELAYREQTX; // OUTPUT
			this->EMIOENET1PTPPDELAYRESPRX = EMIOENET1PTPPDELAYRESPRX; // OUTPUT
			this->EMIOENET1PTPPDELAYRESPTX = EMIOENET1PTPPDELAYRESPTX; // OUTPUT
			this->EMIOENET1PTPSYNCFRAMERX = EMIOENET1PTPSYNCFRAMERX; // OUTPUT
			this->EMIOENET1PTPSYNCFRAMETX = EMIOENET1PTPSYNCFRAMETX; // OUTPUT
			this->EMIOENET1SOFRX = EMIOENET1SOFRX; // OUTPUT
			this->EMIOENET1SOFTX = EMIOENET1SOFTX; // OUTPUT
			this->EMIOGPIOO = EMIOGPIOO; // OUTPUT
			this->EMIOGPIOTN = EMIOGPIOTN; // OUTPUT
			this->EMIOI2C0SCLO = EMIOI2C0SCLO; // OUTPUT
			this->EMIOI2C0SCLTN = EMIOI2C0SCLTN; // OUTPUT
			this->EMIOI2C0SDAO = EMIOI2C0SDAO; // OUTPUT
			this->EMIOI2C0SDATN = EMIOI2C0SDATN; // OUTPUT
			this->EMIOI2C1SCLO = EMIOI2C1SCLO; // OUTPUT
			this->EMIOI2C1SCLTN = EMIOI2C1SCLTN; // OUTPUT
			this->EMIOI2C1SDAO = EMIOI2C1SDAO; // OUTPUT
			this->EMIOI2C1SDATN = EMIOI2C1SDATN; // OUTPUT
			this->EMIOPJTAGTDO = EMIOPJTAGTDO; // OUTPUT
			this->EMIOPJTAGTDTN = EMIOPJTAGTDTN; // OUTPUT
			this->EMIOSDIO0BUSPOW = EMIOSDIO0BUSPOW; // OUTPUT
			this->EMIOSDIO0BUSVOLT = EMIOSDIO0BUSVOLT; // OUTPUT
			this->EMIOSDIO0CLK = EMIOSDIO0CLK; // OUTPUT
			this->EMIOSDIO0CMDO = EMIOSDIO0CMDO; // OUTPUT
			this->EMIOSDIO0CMDTN = EMIOSDIO0CMDTN; // OUTPUT
			this->EMIOSDIO0DATAO = EMIOSDIO0DATAO; // OUTPUT
			this->EMIOSDIO0DATATN = EMIOSDIO0DATATN; // OUTPUT
			this->EMIOSDIO0LED = EMIOSDIO0LED; // OUTPUT
			this->EMIOSDIO1BUSPOW = EMIOSDIO1BUSPOW; // OUTPUT
			this->EMIOSDIO1BUSVOLT = EMIOSDIO1BUSVOLT; // OUTPUT
			this->EMIOSDIO1CLK = EMIOSDIO1CLK; // OUTPUT
			this->EMIOSDIO1CMDO = EMIOSDIO1CMDO; // OUTPUT
			this->EMIOSDIO1CMDTN = EMIOSDIO1CMDTN; // OUTPUT
			this->EMIOSDIO1DATAO = EMIOSDIO1DATAO; // OUTPUT
			this->EMIOSDIO1DATATN = EMIOSDIO1DATATN; // OUTPUT
			this->EMIOSDIO1LED = EMIOSDIO1LED; // OUTPUT
			this->EMIOSPI0MO = EMIOSPI0MO; // OUTPUT
			this->EMIOSPI0MOTN = EMIOSPI0MOTN; // OUTPUT
			this->EMIOSPI0SCLKO = EMIOSPI0SCLKO; // OUTPUT
			this->EMIOSPI0SCLKTN = EMIOSPI0SCLKTN; // OUTPUT
			this->EMIOSPI0SO = EMIOSPI0SO; // OUTPUT
			this->EMIOSPI0SSNTN = EMIOSPI0SSNTN; // OUTPUT
			this->EMIOSPI0SSON = EMIOSPI0SSON; // OUTPUT
			this->EMIOSPI0STN = EMIOSPI0STN; // OUTPUT
			this->EMIOSPI1MO = EMIOSPI1MO; // OUTPUT
			this->EMIOSPI1MOTN = EMIOSPI1MOTN; // OUTPUT
			this->EMIOSPI1SCLKO = EMIOSPI1SCLKO; // OUTPUT
			this->EMIOSPI1SCLKTN = EMIOSPI1SCLKTN; // OUTPUT
			this->EMIOSPI1SO = EMIOSPI1SO; // OUTPUT
			this->EMIOSPI1SSNTN = EMIOSPI1SSNTN; // OUTPUT
			this->EMIOSPI1SSON = EMIOSPI1SSON; // OUTPUT
			this->EMIOSPI1STN = EMIOSPI1STN; // OUTPUT
			this->EMIOTRACECTL = EMIOTRACECTL; // OUTPUT
			this->EMIOTRACEDATA = EMIOTRACEDATA; // OUTPUT
			this->EMIOTTC0WAVEO = EMIOTTC0WAVEO; // OUTPUT
			this->EMIOTTC1WAVEO = EMIOTTC1WAVEO; // OUTPUT
			this->EMIOUART0DTRN = EMIOUART0DTRN; // OUTPUT
			this->EMIOUART0RTSN = EMIOUART0RTSN; // OUTPUT
			this->EMIOUART0TX = EMIOUART0TX; // OUTPUT
			this->EMIOUART1DTRN = EMIOUART1DTRN; // OUTPUT
			this->EMIOUART1RTSN = EMIOUART1RTSN; // OUTPUT
			this->EMIOUART1TX = EMIOUART1TX; // OUTPUT
			this->EMIOUSB0PORTINDCTL = EMIOUSB0PORTINDCTL; // OUTPUT
			this->EMIOUSB0VBUSPWRSELECT = EMIOUSB0VBUSPWRSELECT; // OUTPUT
			this->EMIOUSB1PORTINDCTL = EMIOUSB1PORTINDCTL; // OUTPUT
			this->EMIOUSB1VBUSPWRSELECT = EMIOUSB1VBUSPWRSELECT; // OUTPUT
			this->EMIOWDTRSTO = EMIOWDTRSTO; // OUTPUT
			this->EVENTEVENTO = EVENTEVENTO; // OUTPUT
			this->EVENTSTANDBYWFE = EVENTSTANDBYWFE; // OUTPUT
			this->EVENTSTANDBYWFI = EVENTSTANDBYWFI; // OUTPUT
			this->FCLKCLK = FCLKCLK; // OUTPUT
			this->FCLKRESETN = FCLKRESETN; // OUTPUT
			this->FTMTF2PTRIGACK = FTMTF2PTRIGACK; // OUTPUT
			this->FTMTP2FDEBUG = FTMTP2FDEBUG; // OUTPUT
			this->FTMTP2FTRIG = FTMTP2FTRIG; // OUTPUT
			this->IRQP2F = IRQP2F; // OUTPUT
			this->MAXIGP0ARADDR = MAXIGP0ARADDR; // OUTPUT
			this->MAXIGP0ARBURST = MAXIGP0ARBURST; // OUTPUT
			this->MAXIGP0ARCACHE = MAXIGP0ARCACHE; // OUTPUT
			this->MAXIGP0ARESETN = MAXIGP0ARESETN; // OUTPUT
			this->MAXIGP0ARID = MAXIGP0ARID; // OUTPUT
			this->MAXIGP0ARLEN = MAXIGP0ARLEN; // OUTPUT
			this->MAXIGP0ARLOCK = MAXIGP0ARLOCK; // OUTPUT
			this->MAXIGP0ARPROT = MAXIGP0ARPROT; // OUTPUT
			this->MAXIGP0ARQOS = MAXIGP0ARQOS; // OUTPUT
			this->MAXIGP0ARSIZE = MAXIGP0ARSIZE; // OUTPUT
			this->MAXIGP0ARVALID = MAXIGP0ARVALID; // OUTPUT
			this->MAXIGP0AWADDR = MAXIGP0AWADDR; // OUTPUT
			this->MAXIGP0AWBURST = MAXIGP0AWBURST; // OUTPUT
			this->MAXIGP0AWCACHE = MAXIGP0AWCACHE; // OUTPUT
			this->MAXIGP0AWID = MAXIGP0AWID; // OUTPUT
			this->MAXIGP0AWLEN = MAXIGP0AWLEN; // OUTPUT
			this->MAXIGP0AWLOCK = MAXIGP0AWLOCK; // OUTPUT
			this->MAXIGP0AWPROT = MAXIGP0AWPROT; // OUTPUT
			this->MAXIGP0AWQOS = MAXIGP0AWQOS; // OUTPUT
			this->MAXIGP0AWSIZE = MAXIGP0AWSIZE; // OUTPUT
			this->MAXIGP0AWVALID = MAXIGP0AWVALID; // OUTPUT
			this->MAXIGP0BREADY = MAXIGP0BREADY; // OUTPUT
			this->MAXIGP0RREADY = MAXIGP0RREADY; // OUTPUT
			this->MAXIGP0WDATA = MAXIGP0WDATA; // OUTPUT
			this->MAXIGP0WID = MAXIGP0WID; // OUTPUT
			this->MAXIGP0WLAST = MAXIGP0WLAST; // OUTPUT
			this->MAXIGP0WSTRB = MAXIGP0WSTRB; // OUTPUT
			this->MAXIGP0WVALID = MAXIGP0WVALID; // OUTPUT
			this->MAXIGP1ARADDR = MAXIGP1ARADDR; // OUTPUT
			this->MAXIGP1ARBURST = MAXIGP1ARBURST; // OUTPUT
			this->MAXIGP1ARCACHE = MAXIGP1ARCACHE; // OUTPUT
			this->MAXIGP1ARESETN = MAXIGP1ARESETN; // OUTPUT
			this->MAXIGP1ARID = MAXIGP1ARID; // OUTPUT
			this->MAXIGP1ARLEN = MAXIGP1ARLEN; // OUTPUT
			this->MAXIGP1ARLOCK = MAXIGP1ARLOCK; // OUTPUT
			this->MAXIGP1ARPROT = MAXIGP1ARPROT; // OUTPUT
			this->MAXIGP1ARQOS = MAXIGP1ARQOS; // OUTPUT
			this->MAXIGP1ARSIZE = MAXIGP1ARSIZE; // OUTPUT
			this->MAXIGP1ARVALID = MAXIGP1ARVALID; // OUTPUT
			this->MAXIGP1AWADDR = MAXIGP1AWADDR; // OUTPUT
			this->MAXIGP1AWBURST = MAXIGP1AWBURST; // OUTPUT
			this->MAXIGP1AWCACHE = MAXIGP1AWCACHE; // OUTPUT
			this->MAXIGP1AWID = MAXIGP1AWID; // OUTPUT
			this->MAXIGP1AWLEN = MAXIGP1AWLEN; // OUTPUT
			this->MAXIGP1AWLOCK = MAXIGP1AWLOCK; // OUTPUT
			this->MAXIGP1AWPROT = MAXIGP1AWPROT; // OUTPUT
			this->MAXIGP1AWQOS = MAXIGP1AWQOS; // OUTPUT
			this->MAXIGP1AWSIZE = MAXIGP1AWSIZE; // OUTPUT
			this->MAXIGP1AWVALID = MAXIGP1AWVALID; // OUTPUT
			this->MAXIGP1BREADY = MAXIGP1BREADY; // OUTPUT
			this->MAXIGP1RREADY = MAXIGP1RREADY; // OUTPUT
			this->MAXIGP1WDATA = MAXIGP1WDATA; // OUTPUT
			this->MAXIGP1WID = MAXIGP1WID; // OUTPUT
			this->MAXIGP1WLAST = MAXIGP1WLAST; // OUTPUT
			this->MAXIGP1WSTRB = MAXIGP1WSTRB; // OUTPUT
			this->MAXIGP1WVALID = MAXIGP1WVALID; // OUTPUT
			this->SAXIACPARESETN = SAXIACPARESETN; // OUTPUT
			this->SAXIACPARREADY = SAXIACPARREADY; // OUTPUT
			this->SAXIACPAWREADY = SAXIACPAWREADY; // OUTPUT
			this->SAXIACPBID = SAXIACPBID; // OUTPUT
			this->SAXIACPBRESP = SAXIACPBRESP; // OUTPUT
			this->SAXIACPBVALID = SAXIACPBVALID; // OUTPUT
			this->SAXIACPRDATA = SAXIACPRDATA; // OUTPUT
			this->SAXIACPRID = SAXIACPRID; // OUTPUT
			this->SAXIACPRLAST = SAXIACPRLAST; // OUTPUT
			this->SAXIACPRRESP = SAXIACPRRESP; // OUTPUT
			this->SAXIACPRVALID = SAXIACPRVALID; // OUTPUT
			this->SAXIACPWREADY = SAXIACPWREADY; // OUTPUT
			this->SAXIGP0ARESETN = SAXIGP0ARESETN; // OUTPUT
			this->SAXIGP0ARREADY = SAXIGP0ARREADY; // OUTPUT
			this->SAXIGP0AWREADY = SAXIGP0AWREADY; // OUTPUT
			this->SAXIGP0BID = SAXIGP0BID; // OUTPUT
			this->SAXIGP0BRESP = SAXIGP0BRESP; // OUTPUT
			this->SAXIGP0BVALID = SAXIGP0BVALID; // OUTPUT
			this->SAXIGP0RDATA = SAXIGP0RDATA; // OUTPUT
			this->SAXIGP0RID = SAXIGP0RID; // OUTPUT
			this->SAXIGP0RLAST = SAXIGP0RLAST; // OUTPUT
			this->SAXIGP0RRESP = SAXIGP0RRESP; // OUTPUT
			this->SAXIGP0RVALID = SAXIGP0RVALID; // OUTPUT
			this->SAXIGP0WREADY = SAXIGP0WREADY; // OUTPUT
			this->SAXIGP1ARESETN = SAXIGP1ARESETN; // OUTPUT
			this->SAXIGP1ARREADY = SAXIGP1ARREADY; // OUTPUT
			this->SAXIGP1AWREADY = SAXIGP1AWREADY; // OUTPUT
			this->SAXIGP1BID = SAXIGP1BID; // OUTPUT
			this->SAXIGP1BRESP = SAXIGP1BRESP; // OUTPUT
			this->SAXIGP1BVALID = SAXIGP1BVALID; // OUTPUT
			this->SAXIGP1RDATA = SAXIGP1RDATA; // OUTPUT
			this->SAXIGP1RID = SAXIGP1RID; // OUTPUT
			this->SAXIGP1RLAST = SAXIGP1RLAST; // OUTPUT
			this->SAXIGP1RRESP = SAXIGP1RRESP; // OUTPUT
			this->SAXIGP1RVALID = SAXIGP1RVALID; // OUTPUT
			this->SAXIGP1WREADY = SAXIGP1WREADY; // OUTPUT
			this->SAXIHP0ARESETN = SAXIHP0ARESETN; // OUTPUT
			this->SAXIHP0ARREADY = SAXIHP0ARREADY; // OUTPUT
			this->SAXIHP0AWREADY = SAXIHP0AWREADY; // OUTPUT
			this->SAXIHP0BID = SAXIHP0BID; // OUTPUT
			this->SAXIHP0BRESP = SAXIHP0BRESP; // OUTPUT
			this->SAXIHP0BVALID = SAXIHP0BVALID; // OUTPUT
			this->SAXIHP0RACOUNT = SAXIHP0RACOUNT; // OUTPUT
			this->SAXIHP0RCOUNT = SAXIHP0RCOUNT; // OUTPUT
			this->SAXIHP0RDATA = SAXIHP0RDATA; // OUTPUT
			this->SAXIHP0RID = SAXIHP0RID; // OUTPUT
			this->SAXIHP0RLAST = SAXIHP0RLAST; // OUTPUT
			this->SAXIHP0RRESP = SAXIHP0RRESP; // OUTPUT
			this->SAXIHP0RVALID = SAXIHP0RVALID; // OUTPUT
			this->SAXIHP0WACOUNT = SAXIHP0WACOUNT; // OUTPUT
			this->SAXIHP0WCOUNT = SAXIHP0WCOUNT; // OUTPUT
			this->SAXIHP0WREADY = SAXIHP0WREADY; // OUTPUT
			this->SAXIHP1ARESETN = SAXIHP1ARESETN; // OUTPUT
			this->SAXIHP1ARREADY = SAXIHP1ARREADY; // OUTPUT
			this->SAXIHP1AWREADY = SAXIHP1AWREADY; // OUTPUT
			this->SAXIHP1BID = SAXIHP1BID; // OUTPUT
			this->SAXIHP1BRESP = SAXIHP1BRESP; // OUTPUT
			this->SAXIHP1BVALID = SAXIHP1BVALID; // OUTPUT
			this->SAXIHP1RACOUNT = SAXIHP1RACOUNT; // OUTPUT
			this->SAXIHP1RCOUNT = SAXIHP1RCOUNT; // OUTPUT
			this->SAXIHP1RDATA = SAXIHP1RDATA; // OUTPUT
			this->SAXIHP1RID = SAXIHP1RID; // OUTPUT
			this->SAXIHP1RLAST = SAXIHP1RLAST; // OUTPUT
			this->SAXIHP1RRESP = SAXIHP1RRESP; // OUTPUT
			this->SAXIHP1RVALID = SAXIHP1RVALID; // OUTPUT
			this->SAXIHP1WACOUNT = SAXIHP1WACOUNT; // OUTPUT
			this->SAXIHP1WCOUNT = SAXIHP1WCOUNT; // OUTPUT
			this->SAXIHP1WREADY = SAXIHP1WREADY; // OUTPUT
			this->SAXIHP2ARESETN = SAXIHP2ARESETN; // OUTPUT
			this->SAXIHP2ARREADY = SAXIHP2ARREADY; // OUTPUT
			this->SAXIHP2AWREADY = SAXIHP2AWREADY; // OUTPUT
			this->SAXIHP2BID = SAXIHP2BID; // OUTPUT
			this->SAXIHP2BRESP = SAXIHP2BRESP; // OUTPUT
			this->SAXIHP2BVALID = SAXIHP2BVALID; // OUTPUT
			this->SAXIHP2RACOUNT = SAXIHP2RACOUNT; // OUTPUT
			this->SAXIHP2RCOUNT = SAXIHP2RCOUNT; // OUTPUT
			this->SAXIHP2RDATA = SAXIHP2RDATA; // OUTPUT
			this->SAXIHP2RID = SAXIHP2RID; // OUTPUT
			this->SAXIHP2RLAST = SAXIHP2RLAST; // OUTPUT
			this->SAXIHP2RRESP = SAXIHP2RRESP; // OUTPUT
			this->SAXIHP2RVALID = SAXIHP2RVALID; // OUTPUT
			this->SAXIHP2WACOUNT = SAXIHP2WACOUNT; // OUTPUT
			this->SAXIHP2WCOUNT = SAXIHP2WCOUNT; // OUTPUT
			this->SAXIHP2WREADY = SAXIHP2WREADY; // OUTPUT
			this->SAXIHP3ARESETN = SAXIHP3ARESETN; // OUTPUT
			this->SAXIHP3ARREADY = SAXIHP3ARREADY; // OUTPUT
			this->SAXIHP3AWREADY = SAXIHP3AWREADY; // OUTPUT
			this->SAXIHP3BID = SAXIHP3BID; // OUTPUT
			this->SAXIHP3BRESP = SAXIHP3BRESP; // OUTPUT
			this->SAXIHP3BVALID = SAXIHP3BVALID; // OUTPUT
			this->SAXIHP3RACOUNT = SAXIHP3RACOUNT; // OUTPUT
			this->SAXIHP3RCOUNT = SAXIHP3RCOUNT; // OUTPUT
			this->SAXIHP3RDATA = SAXIHP3RDATA; // OUTPUT
			this->SAXIHP3RID = SAXIHP3RID; // OUTPUT
			this->SAXIHP3RLAST = SAXIHP3RLAST; // OUTPUT
			this->SAXIHP3RRESP = SAXIHP3RRESP; // OUTPUT
			this->SAXIHP3RVALID = SAXIHP3RVALID; // OUTPUT
			this->SAXIHP3WACOUNT = SAXIHP3WACOUNT; // OUTPUT
			this->SAXIHP3WCOUNT = SAXIHP3WCOUNT; // OUTPUT
			this->SAXIHP3WREADY = SAXIHP3WREADY; // OUTPUT
			this->DDRA = DDRA; // INOUT
			this->DDRBA = DDRBA; // INOUT
			this->DDRCASB = DDRCASB; // INOUT
			this->DDRCKE = DDRCKE; // INOUT
			this->DDRCKN = DDRCKN; // INOUT
			this->DDRCKP = DDRCKP; // INOUT
			this->DDRCSB = DDRCSB; // INOUT
			this->DDRDM = DDRDM; // INOUT
			this->DDRDQ = DDRDQ; // INOUT
			this->DDRDQSN = DDRDQSN; // INOUT
			this->DDRDQSP = DDRDQSP; // INOUT
			this->DDRDRSTB = DDRDRSTB; // INOUT
			this->DDRODT = DDRODT; // INOUT
			this->DDRRASB = DDRRASB; // INOUT
			this->DDRVRN = DDRVRN; // INOUT
			this->DDRVRP = DDRVRP; // INOUT
			this->DDRWEB = DDRWEB; // INOUT
			this->MIO = MIO; // INOUT
			this->PSCLK = PSCLK; // INOUT
			this->PSPORB = PSPORB; // INOUT
			this->PSSRSTB = PSSRSTB; // INOUT
			this->DDRARB = DDRARB; // INPUT
			this->DMA0ACLK = DMA0ACLK; // INPUT
			this->DMA0DAREADY = DMA0DAREADY; // INPUT
			this->DMA0DRLAST = DMA0DRLAST; // INPUT
			this->DMA0DRTYPE = DMA0DRTYPE; // INPUT
			this->DMA0DRVALID = DMA0DRVALID; // INPUT
			this->DMA1ACLK = DMA1ACLK; // INPUT
			this->DMA1DAREADY = DMA1DAREADY; // INPUT
			this->DMA1DRLAST = DMA1DRLAST; // INPUT
			this->DMA1DRTYPE = DMA1DRTYPE; // INPUT
			this->DMA1DRVALID = DMA1DRVALID; // INPUT
			this->DMA2ACLK = DMA2ACLK; // INPUT
			this->DMA2DAREADY = DMA2DAREADY; // INPUT
			this->DMA2DRLAST = DMA2DRLAST; // INPUT
			this->DMA2DRTYPE = DMA2DRTYPE; // INPUT
			this->DMA2DRVALID = DMA2DRVALID; // INPUT
			this->DMA3ACLK = DMA3ACLK; // INPUT
			this->DMA3DAREADY = DMA3DAREADY; // INPUT
			this->DMA3DRLAST = DMA3DRLAST; // INPUT
			this->DMA3DRTYPE = DMA3DRTYPE; // INPUT
			this->DMA3DRVALID = DMA3DRVALID; // INPUT
			this->EMIOCAN0PHYRX = EMIOCAN0PHYRX; // INPUT
			this->EMIOCAN1PHYRX = EMIOCAN1PHYRX; // INPUT
			this->EMIOENET0EXTINTIN = EMIOENET0EXTINTIN; // INPUT
			this->EMIOENET0GMIICOL = EMIOENET0GMIICOL; // INPUT
			this->EMIOENET0GMIICRS = EMIOENET0GMIICRS; // INPUT
			this->EMIOENET0GMIIRXCLK = EMIOENET0GMIIRXCLK; // INPUT
			this->EMIOENET0GMIIRXD = EMIOENET0GMIIRXD; // INPUT
			this->EMIOENET0GMIIRXDV = EMIOENET0GMIIRXDV; // INPUT
			this->EMIOENET0GMIIRXER = EMIOENET0GMIIRXER; // INPUT
			this->EMIOENET0GMIITXCLK = EMIOENET0GMIITXCLK; // INPUT
			this->EMIOENET0MDIOI = EMIOENET0MDIOI; // INPUT
			this->EMIOENET1EXTINTIN = EMIOENET1EXTINTIN; // INPUT
			this->EMIOENET1GMIICOL = EMIOENET1GMIICOL; // INPUT
			this->EMIOENET1GMIICRS = EMIOENET1GMIICRS; // INPUT
			this->EMIOENET1GMIIRXCLK = EMIOENET1GMIIRXCLK; // INPUT
			this->EMIOENET1GMIIRXD = EMIOENET1GMIIRXD; // INPUT
			this->EMIOENET1GMIIRXDV = EMIOENET1GMIIRXDV; // INPUT
			this->EMIOENET1GMIIRXER = EMIOENET1GMIIRXER; // INPUT
			this->EMIOENET1GMIITXCLK = EMIOENET1GMIITXCLK; // INPUT
			this->EMIOENET1MDIOI = EMIOENET1MDIOI; // INPUT
			this->EMIOGPIOI = EMIOGPIOI; // INPUT
			this->EMIOI2C0SCLI = EMIOI2C0SCLI; // INPUT
			this->EMIOI2C0SDAI = EMIOI2C0SDAI; // INPUT
			this->EMIOI2C1SCLI = EMIOI2C1SCLI; // INPUT
			this->EMIOI2C1SDAI = EMIOI2C1SDAI; // INPUT
			this->EMIOPJTAGTCK = EMIOPJTAGTCK; // INPUT
			this->EMIOPJTAGTDI = EMIOPJTAGTDI; // INPUT
			this->EMIOPJTAGTMS = EMIOPJTAGTMS; // INPUT
			this->EMIOSDIO0CDN = EMIOSDIO0CDN; // INPUT
			this->EMIOSDIO0CLKFB = EMIOSDIO0CLKFB; // INPUT
			this->EMIOSDIO0CMDI = EMIOSDIO0CMDI; // INPUT
			this->EMIOSDIO0DATAI = EMIOSDIO0DATAI; // INPUT
			this->EMIOSDIO0WP = EMIOSDIO0WP; // INPUT
			this->EMIOSDIO1CDN = EMIOSDIO1CDN; // INPUT
			this->EMIOSDIO1CLKFB = EMIOSDIO1CLKFB; // INPUT
			this->EMIOSDIO1CMDI = EMIOSDIO1CMDI; // INPUT
			this->EMIOSDIO1DATAI = EMIOSDIO1DATAI; // INPUT
			this->EMIOSDIO1WP = EMIOSDIO1WP; // INPUT
			this->EMIOSPI0MI = EMIOSPI0MI; // INPUT
			this->EMIOSPI0SCLKI = EMIOSPI0SCLKI; // INPUT
			this->EMIOSPI0SI = EMIOSPI0SI; // INPUT
			this->EMIOSPI0SSIN = EMIOSPI0SSIN; // INPUT
			this->EMIOSPI1MI = EMIOSPI1MI; // INPUT
			this->EMIOSPI1SCLKI = EMIOSPI1SCLKI; // INPUT
			this->EMIOSPI1SI = EMIOSPI1SI; // INPUT
			this->EMIOSPI1SSIN = EMIOSPI1SSIN; // INPUT
			this->EMIOSRAMINTIN = EMIOSRAMINTIN; // INPUT
			this->EMIOTRACECLK = EMIOTRACECLK; // INPUT
			this->EMIOTTC0CLKI = EMIOTTC0CLKI; // INPUT
			this->EMIOTTC1CLKI = EMIOTTC1CLKI; // INPUT
			this->EMIOUART0CTSN = EMIOUART0CTSN; // INPUT
			this->EMIOUART0DCDN = EMIOUART0DCDN; // INPUT
			this->EMIOUART0DSRN = EMIOUART0DSRN; // INPUT
			this->EMIOUART0RIN = EMIOUART0RIN; // INPUT
			this->EMIOUART0RX = EMIOUART0RX; // INPUT
			this->EMIOUART1CTSN = EMIOUART1CTSN; // INPUT
			this->EMIOUART1DCDN = EMIOUART1DCDN; // INPUT
			this->EMIOUART1DSRN = EMIOUART1DSRN; // INPUT
			this->EMIOUART1RIN = EMIOUART1RIN; // INPUT
			this->EMIOUART1RX = EMIOUART1RX; // INPUT
			this->EMIOUSB0VBUSPWRFAULT = EMIOUSB0VBUSPWRFAULT; // INPUT
			this->EMIOUSB1VBUSPWRFAULT = EMIOUSB1VBUSPWRFAULT; // INPUT
			this->EMIOWDTCLKI = EMIOWDTCLKI; // INPUT
			this->EVENTEVENTI = EVENTEVENTI; // INPUT
			this->FCLKCLKTRIGN = FCLKCLKTRIGN; // INPUT
			this->FPGAIDLEN = FPGAIDLEN; // INPUT
			this->FTMDTRACEINATID = FTMDTRACEINATID; // INPUT
			this->FTMDTRACEINCLOCK = FTMDTRACEINCLOCK; // INPUT
			this->FTMDTRACEINDATA = FTMDTRACEINDATA; // INPUT
			this->FTMDTRACEINVALID = FTMDTRACEINVALID; // INPUT
			this->FTMTF2PDEBUG = FTMTF2PDEBUG; // INPUT
			this->FTMTF2PTRIG = FTMTF2PTRIG; // INPUT
			this->FTMTP2FTRIGACK = FTMTP2FTRIGACK; // INPUT
			this->IRQF2P = IRQF2P; // INPUT
			this->MAXIGP0ACLK = MAXIGP0ACLK; // INPUT
			this->MAXIGP0ARREADY = MAXIGP0ARREADY; // INPUT
			this->MAXIGP0AWREADY = MAXIGP0AWREADY; // INPUT
			this->MAXIGP0BID = MAXIGP0BID; // INPUT
			this->MAXIGP0BRESP = MAXIGP0BRESP; // INPUT
			this->MAXIGP0BVALID = MAXIGP0BVALID; // INPUT
			this->MAXIGP0RDATA = MAXIGP0RDATA; // INPUT
			this->MAXIGP0RID = MAXIGP0RID; // INPUT
			this->MAXIGP0RLAST = MAXIGP0RLAST; // INPUT
			this->MAXIGP0RRESP = MAXIGP0RRESP; // INPUT
			this->MAXIGP0RVALID = MAXIGP0RVALID; // INPUT
			this->MAXIGP0WREADY = MAXIGP0WREADY; // INPUT
			this->MAXIGP1ACLK = MAXIGP1ACLK; // INPUT
			this->MAXIGP1ARREADY = MAXIGP1ARREADY; // INPUT
			this->MAXIGP1AWREADY = MAXIGP1AWREADY; // INPUT
			this->MAXIGP1BID = MAXIGP1BID; // INPUT
			this->MAXIGP1BRESP = MAXIGP1BRESP; // INPUT
			this->MAXIGP1BVALID = MAXIGP1BVALID; // INPUT
			this->MAXIGP1RDATA = MAXIGP1RDATA; // INPUT
			this->MAXIGP1RID = MAXIGP1RID; // INPUT
			this->MAXIGP1RLAST = MAXIGP1RLAST; // INPUT
			this->MAXIGP1RRESP = MAXIGP1RRESP; // INPUT
			this->MAXIGP1RVALID = MAXIGP1RVALID; // INPUT
			this->MAXIGP1WREADY = MAXIGP1WREADY; // INPUT
			this->SAXIACPACLK = SAXIACPACLK; // INPUT
			this->SAXIACPARADDR = SAXIACPARADDR; // INPUT
			this->SAXIACPARBURST = SAXIACPARBURST; // INPUT
			this->SAXIACPARCACHE = SAXIACPARCACHE; // INPUT
			this->SAXIACPARID = SAXIACPARID; // INPUT
			this->SAXIACPARLEN = SAXIACPARLEN; // INPUT
			this->SAXIACPARLOCK = SAXIACPARLOCK; // INPUT
			this->SAXIACPARPROT = SAXIACPARPROT; // INPUT
			this->SAXIACPARQOS = SAXIACPARQOS; // INPUT
			this->SAXIACPARSIZE = SAXIACPARSIZE; // INPUT
			this->SAXIACPARUSER = SAXIACPARUSER; // INPUT
			this->SAXIACPARVALID = SAXIACPARVALID; // INPUT
			this->SAXIACPAWADDR = SAXIACPAWADDR; // INPUT
			this->SAXIACPAWBURST = SAXIACPAWBURST; // INPUT
			this->SAXIACPAWCACHE = SAXIACPAWCACHE; // INPUT
			this->SAXIACPAWID = SAXIACPAWID; // INPUT
			this->SAXIACPAWLEN = SAXIACPAWLEN; // INPUT
			this->SAXIACPAWLOCK = SAXIACPAWLOCK; // INPUT
			this->SAXIACPAWPROT = SAXIACPAWPROT; // INPUT
			this->SAXIACPAWQOS = SAXIACPAWQOS; // INPUT
			this->SAXIACPAWSIZE = SAXIACPAWSIZE; // INPUT
			this->SAXIACPAWUSER = SAXIACPAWUSER; // INPUT
			this->SAXIACPAWVALID = SAXIACPAWVALID; // INPUT
			this->SAXIACPBREADY = SAXIACPBREADY; // INPUT
			this->SAXIACPRREADY = SAXIACPRREADY; // INPUT
			this->SAXIACPWDATA = SAXIACPWDATA; // INPUT
			this->SAXIACPWID = SAXIACPWID; // INPUT
			this->SAXIACPWLAST = SAXIACPWLAST; // INPUT
			this->SAXIACPWSTRB = SAXIACPWSTRB; // INPUT
			this->SAXIACPWVALID = SAXIACPWVALID; // INPUT
			this->SAXIGP0ACLK = SAXIGP0ACLK; // INPUT
			this->SAXIGP0ARADDR = SAXIGP0ARADDR; // INPUT
			this->SAXIGP0ARBURST = SAXIGP0ARBURST; // INPUT
			this->SAXIGP0ARCACHE = SAXIGP0ARCACHE; // INPUT
			this->SAXIGP0ARID = SAXIGP0ARID; // INPUT
			this->SAXIGP0ARLEN = SAXIGP0ARLEN; // INPUT
			this->SAXIGP0ARLOCK = SAXIGP0ARLOCK; // INPUT
			this->SAXIGP0ARPROT = SAXIGP0ARPROT; // INPUT
			this->SAXIGP0ARQOS = SAXIGP0ARQOS; // INPUT
			this->SAXIGP0ARSIZE = SAXIGP0ARSIZE; // INPUT
			this->SAXIGP0ARVALID = SAXIGP0ARVALID; // INPUT
			this->SAXIGP0AWADDR = SAXIGP0AWADDR; // INPUT
			this->SAXIGP0AWBURST = SAXIGP0AWBURST; // INPUT
			this->SAXIGP0AWCACHE = SAXIGP0AWCACHE; // INPUT
			this->SAXIGP0AWID = SAXIGP0AWID; // INPUT
			this->SAXIGP0AWLEN = SAXIGP0AWLEN; // INPUT
			this->SAXIGP0AWLOCK = SAXIGP0AWLOCK; // INPUT
			this->SAXIGP0AWPROT = SAXIGP0AWPROT; // INPUT
			this->SAXIGP0AWQOS = SAXIGP0AWQOS; // INPUT
			this->SAXIGP0AWSIZE = SAXIGP0AWSIZE; // INPUT
			this->SAXIGP0AWVALID = SAXIGP0AWVALID; // INPUT
			this->SAXIGP0BREADY = SAXIGP0BREADY; // INPUT
			this->SAXIGP0RREADY = SAXIGP0RREADY; // INPUT
			this->SAXIGP0WDATA = SAXIGP0WDATA; // INPUT
			this->SAXIGP0WID = SAXIGP0WID; // INPUT
			this->SAXIGP0WLAST = SAXIGP0WLAST; // INPUT
			this->SAXIGP0WSTRB = SAXIGP0WSTRB; // INPUT
			this->SAXIGP0WVALID = SAXIGP0WVALID; // INPUT
			this->SAXIGP1ACLK = SAXIGP1ACLK; // INPUT
			this->SAXIGP1ARADDR = SAXIGP1ARADDR; // INPUT
			this->SAXIGP1ARBURST = SAXIGP1ARBURST; // INPUT
			this->SAXIGP1ARCACHE = SAXIGP1ARCACHE; // INPUT
			this->SAXIGP1ARID = SAXIGP1ARID; // INPUT
			this->SAXIGP1ARLEN = SAXIGP1ARLEN; // INPUT
			this->SAXIGP1ARLOCK = SAXIGP1ARLOCK; // INPUT
			this->SAXIGP1ARPROT = SAXIGP1ARPROT; // INPUT
			this->SAXIGP1ARQOS = SAXIGP1ARQOS; // INPUT
			this->SAXIGP1ARSIZE = SAXIGP1ARSIZE; // INPUT
			this->SAXIGP1ARVALID = SAXIGP1ARVALID; // INPUT
			this->SAXIGP1AWADDR = SAXIGP1AWADDR; // INPUT
			this->SAXIGP1AWBURST = SAXIGP1AWBURST; // INPUT
			this->SAXIGP1AWCACHE = SAXIGP1AWCACHE; // INPUT
			this->SAXIGP1AWID = SAXIGP1AWID; // INPUT
			this->SAXIGP1AWLEN = SAXIGP1AWLEN; // INPUT
			this->SAXIGP1AWLOCK = SAXIGP1AWLOCK; // INPUT
			this->SAXIGP1AWPROT = SAXIGP1AWPROT; // INPUT
			this->SAXIGP1AWQOS = SAXIGP1AWQOS; // INPUT
			this->SAXIGP1AWSIZE = SAXIGP1AWSIZE; // INPUT
			this->SAXIGP1AWVALID = SAXIGP1AWVALID; // INPUT
			this->SAXIGP1BREADY = SAXIGP1BREADY; // INPUT
			this->SAXIGP1RREADY = SAXIGP1RREADY; // INPUT
			this->SAXIGP1WDATA = SAXIGP1WDATA; // INPUT
			this->SAXIGP1WID = SAXIGP1WID; // INPUT
			this->SAXIGP1WLAST = SAXIGP1WLAST; // INPUT
			this->SAXIGP1WSTRB = SAXIGP1WSTRB; // INPUT
			this->SAXIGP1WVALID = SAXIGP1WVALID; // INPUT
			this->SAXIHP0ACLK = SAXIHP0ACLK; // INPUT
			this->SAXIHP0ARADDR = SAXIHP0ARADDR; // INPUT
			this->SAXIHP0ARBURST = SAXIHP0ARBURST; // INPUT
			this->SAXIHP0ARCACHE = SAXIHP0ARCACHE; // INPUT
			this->SAXIHP0ARID = SAXIHP0ARID; // INPUT
			this->SAXIHP0ARLEN = SAXIHP0ARLEN; // INPUT
			this->SAXIHP0ARLOCK = SAXIHP0ARLOCK; // INPUT
			this->SAXIHP0ARPROT = SAXIHP0ARPROT; // INPUT
			this->SAXIHP0ARQOS = SAXIHP0ARQOS; // INPUT
			this->SAXIHP0ARSIZE = SAXIHP0ARSIZE; // INPUT
			this->SAXIHP0ARVALID = SAXIHP0ARVALID; // INPUT
			this->SAXIHP0AWADDR = SAXIHP0AWADDR; // INPUT
			this->SAXIHP0AWBURST = SAXIHP0AWBURST; // INPUT
			this->SAXIHP0AWCACHE = SAXIHP0AWCACHE; // INPUT
			this->SAXIHP0AWID = SAXIHP0AWID; // INPUT
			this->SAXIHP0AWLEN = SAXIHP0AWLEN; // INPUT
			this->SAXIHP0AWLOCK = SAXIHP0AWLOCK; // INPUT
			this->SAXIHP0AWPROT = SAXIHP0AWPROT; // INPUT
			this->SAXIHP0AWQOS = SAXIHP0AWQOS; // INPUT
			this->SAXIHP0AWSIZE = SAXIHP0AWSIZE; // INPUT
			this->SAXIHP0AWVALID = SAXIHP0AWVALID; // INPUT
			this->SAXIHP0BREADY = SAXIHP0BREADY; // INPUT
			this->SAXIHP0RDISSUECAP1EN = SAXIHP0RDISSUECAP1EN; // INPUT
			this->SAXIHP0RREADY = SAXIHP0RREADY; // INPUT
			this->SAXIHP0WDATA = SAXIHP0WDATA; // INPUT
			this->SAXIHP0WID = SAXIHP0WID; // INPUT
			this->SAXIHP0WLAST = SAXIHP0WLAST; // INPUT
			this->SAXIHP0WRISSUECAP1EN = SAXIHP0WRISSUECAP1EN; // INPUT
			this->SAXIHP0WSTRB = SAXIHP0WSTRB; // INPUT
			this->SAXIHP0WVALID = SAXIHP0WVALID; // INPUT
			this->SAXIHP1ACLK = SAXIHP1ACLK; // INPUT
			this->SAXIHP1ARADDR = SAXIHP1ARADDR; // INPUT
			this->SAXIHP1ARBURST = SAXIHP1ARBURST; // INPUT
			this->SAXIHP1ARCACHE = SAXIHP1ARCACHE; // INPUT
			this->SAXIHP1ARID = SAXIHP1ARID; // INPUT
			this->SAXIHP1ARLEN = SAXIHP1ARLEN; // INPUT
			this->SAXIHP1ARLOCK = SAXIHP1ARLOCK; // INPUT
			this->SAXIHP1ARPROT = SAXIHP1ARPROT; // INPUT
			this->SAXIHP1ARQOS = SAXIHP1ARQOS; // INPUT
			this->SAXIHP1ARSIZE = SAXIHP1ARSIZE; // INPUT
			this->SAXIHP1ARVALID = SAXIHP1ARVALID; // INPUT
			this->SAXIHP1AWADDR = SAXIHP1AWADDR; // INPUT
			this->SAXIHP1AWBURST = SAXIHP1AWBURST; // INPUT
			this->SAXIHP1AWCACHE = SAXIHP1AWCACHE; // INPUT
			this->SAXIHP1AWID = SAXIHP1AWID; // INPUT
			this->SAXIHP1AWLEN = SAXIHP1AWLEN; // INPUT
			this->SAXIHP1AWLOCK = SAXIHP1AWLOCK; // INPUT
			this->SAXIHP1AWPROT = SAXIHP1AWPROT; // INPUT
			this->SAXIHP1AWQOS = SAXIHP1AWQOS; // INPUT
			this->SAXIHP1AWSIZE = SAXIHP1AWSIZE; // INPUT
			this->SAXIHP1AWVALID = SAXIHP1AWVALID; // INPUT
			this->SAXIHP1BREADY = SAXIHP1BREADY; // INPUT
			this->SAXIHP1RDISSUECAP1EN = SAXIHP1RDISSUECAP1EN; // INPUT
			this->SAXIHP1RREADY = SAXIHP1RREADY; // INPUT
			this->SAXIHP1WDATA = SAXIHP1WDATA; // INPUT
			this->SAXIHP1WID = SAXIHP1WID; // INPUT
			this->SAXIHP1WLAST = SAXIHP1WLAST; // INPUT
			this->SAXIHP1WRISSUECAP1EN = SAXIHP1WRISSUECAP1EN; // INPUT
			this->SAXIHP1WSTRB = SAXIHP1WSTRB; // INPUT
			this->SAXIHP1WVALID = SAXIHP1WVALID; // INPUT
			this->SAXIHP2ACLK = SAXIHP2ACLK; // INPUT
			this->SAXIHP2ARADDR = SAXIHP2ARADDR; // INPUT
			this->SAXIHP2ARBURST = SAXIHP2ARBURST; // INPUT
			this->SAXIHP2ARCACHE = SAXIHP2ARCACHE; // INPUT
			this->SAXIHP2ARID = SAXIHP2ARID; // INPUT
			this->SAXIHP2ARLEN = SAXIHP2ARLEN; // INPUT
			this->SAXIHP2ARLOCK = SAXIHP2ARLOCK; // INPUT
			this->SAXIHP2ARPROT = SAXIHP2ARPROT; // INPUT
			this->SAXIHP2ARQOS = SAXIHP2ARQOS; // INPUT
			this->SAXIHP2ARSIZE = SAXIHP2ARSIZE; // INPUT
			this->SAXIHP2ARVALID = SAXIHP2ARVALID; // INPUT
			this->SAXIHP2AWADDR = SAXIHP2AWADDR; // INPUT
			this->SAXIHP2AWBURST = SAXIHP2AWBURST; // INPUT
			this->SAXIHP2AWCACHE = SAXIHP2AWCACHE; // INPUT
			this->SAXIHP2AWID = SAXIHP2AWID; // INPUT
			this->SAXIHP2AWLEN = SAXIHP2AWLEN; // INPUT
			this->SAXIHP2AWLOCK = SAXIHP2AWLOCK; // INPUT
			this->SAXIHP2AWPROT = SAXIHP2AWPROT; // INPUT
			this->SAXIHP2AWQOS = SAXIHP2AWQOS; // INPUT
			this->SAXIHP2AWSIZE = SAXIHP2AWSIZE; // INPUT
			this->SAXIHP2AWVALID = SAXIHP2AWVALID; // INPUT
			this->SAXIHP2BREADY = SAXIHP2BREADY; // INPUT
			this->SAXIHP2RDISSUECAP1EN = SAXIHP2RDISSUECAP1EN; // INPUT
			this->SAXIHP2RREADY = SAXIHP2RREADY; // INPUT
			this->SAXIHP2WDATA = SAXIHP2WDATA; // INPUT
			this->SAXIHP2WID = SAXIHP2WID; // INPUT
			this->SAXIHP2WLAST = SAXIHP2WLAST; // INPUT
			this->SAXIHP2WRISSUECAP1EN = SAXIHP2WRISSUECAP1EN; // INPUT
			this->SAXIHP2WSTRB = SAXIHP2WSTRB; // INPUT
			this->SAXIHP2WVALID = SAXIHP2WVALID; // INPUT
			this->SAXIHP3ACLK = SAXIHP3ACLK; // INPUT
			this->SAXIHP3ARADDR = SAXIHP3ARADDR; // INPUT
			this->SAXIHP3ARBURST = SAXIHP3ARBURST; // INPUT
			this->SAXIHP3ARCACHE = SAXIHP3ARCACHE; // INPUT
			this->SAXIHP3ARID = SAXIHP3ARID; // INPUT
			this->SAXIHP3ARLEN = SAXIHP3ARLEN; // INPUT
			this->SAXIHP3ARLOCK = SAXIHP3ARLOCK; // INPUT
			this->SAXIHP3ARPROT = SAXIHP3ARPROT; // INPUT
			this->SAXIHP3ARQOS = SAXIHP3ARQOS; // INPUT
			this->SAXIHP3ARSIZE = SAXIHP3ARSIZE; // INPUT
			this->SAXIHP3ARVALID = SAXIHP3ARVALID; // INPUT
			this->SAXIHP3AWADDR = SAXIHP3AWADDR; // INPUT
			this->SAXIHP3AWBURST = SAXIHP3AWBURST; // INPUT
			this->SAXIHP3AWCACHE = SAXIHP3AWCACHE; // INPUT
			this->SAXIHP3AWID = SAXIHP3AWID; // INPUT
			this->SAXIHP3AWLEN = SAXIHP3AWLEN; // INPUT
			this->SAXIHP3AWLOCK = SAXIHP3AWLOCK; // INPUT
			this->SAXIHP3AWPROT = SAXIHP3AWPROT; // INPUT
			this->SAXIHP3AWQOS = SAXIHP3AWQOS; // INPUT
			this->SAXIHP3AWSIZE = SAXIHP3AWSIZE; // INPUT
			this->SAXIHP3AWVALID = SAXIHP3AWVALID; // INPUT
			this->SAXIHP3BREADY = SAXIHP3BREADY; // INPUT
			this->SAXIHP3RDISSUECAP1EN = SAXIHP3RDISSUECAP1EN; // INPUT
			this->SAXIHP3RREADY = SAXIHP3RREADY; // INPUT
			this->SAXIHP3WDATA = SAXIHP3WDATA; // INPUT
			this->SAXIHP3WID = SAXIHP3WID; // INPUT
			this->SAXIHP3WLAST = SAXIHP3WLAST; // INPUT
			this->SAXIHP3WRISSUECAP1EN = SAXIHP3WRISSUECAP1EN; // INPUT
			this->SAXIHP3WSTRB = SAXIHP3WSTRB; // INPUT
			this->SAXIHP3WVALID = SAXIHP3WVALID; // INPUT
		
			register_wait_on_event_nets();
		
		}
		
		void register_wait_on_event_nets(){
		// TODO
		}
		void calculate(int time){
		// TODO
		}
	};
	

}
