/******************************************************************************
 * Generated Cpp template for simulation primitives.
 * Author: Benedek Racz
 ******************************************************************************/

#ifndef X_TEMAC_SINGLE_H
#define X_TEMAC_SINGLE_H

#include "NetFlow.h"
#include "sim_types.h"
#include "Primitive.h"

namespace CPrimitives {
	
	class X_TEMAC_SINGLE: public Primitive{

		//Verilog Parameters:
		parameter_string_t LOC;
		parameter_enum_t EMAC_1000BASEX_ENABLE;
		parameter_enum_t EMAC_ADDRFILTER_ENABLE;
		parameter_enum_t EMAC_BYTEPHY;
		parameter_enum_t EMAC_CTRLLENCHECK_DISABLE;
		parameter_int_t EMAC_DCRBASEADDR;
		parameter_enum_t EMAC_GTLOOPBACK;
		parameter_enum_t EMAC_HOST_ENABLE;
		parameter_int_t EMAC_LINKTIMERVAL;
		parameter_enum_t EMAC_LTCHECK_DISABLE;
		parameter_enum_t EMAC_MDIO_ENABLE;
		parameter_enum_t EMAC_MDIO_IGNORE_PHYADZERO;
		parameter_int_t EMAC_PAUSEADDR;
		parameter_enum_t EMAC_PHYINITAUTONEG_ENABLE;
		parameter_enum_t EMAC_PHYISOLATE;
		parameter_enum_t EMAC_PHYLOOPBACKMSB;
		parameter_enum_t EMAC_PHYPOWERDOWN;
		parameter_enum_t EMAC_PHYRESET;
		parameter_enum_t EMAC_RGMII_ENABLE;
		parameter_enum_t EMAC_RX16BITCLIENT_ENABLE;
		parameter_enum_t EMAC_RXFLOWCTRL_ENABLE;
		parameter_enum_t EMAC_RXHALFDUPLEX;
		parameter_enum_t EMAC_RXINBANDFCS_ENABLE;
		parameter_enum_t EMAC_RXJUMBOFRAME_ENABLE;
		parameter_enum_t EMAC_RXRESET;
		parameter_enum_t EMAC_RXVLAN_ENABLE;
		parameter_enum_t EMAC_RX_ENABLE;
		parameter_enum_t EMAC_SGMII_ENABLE;
		parameter_enum_t EMAC_SPEED_LSB;
		parameter_enum_t EMAC_SPEED_MSB;
		parameter_enum_t EMAC_TX16BITCLIENT_ENABLE;
		parameter_enum_t EMAC_TXFLOWCTRL_ENABLE;
		parameter_enum_t EMAC_TXHALFDUPLEX;
		parameter_enum_t EMAC_TXIFGADJUST_ENABLE;
		parameter_enum_t EMAC_TXINBANDFCS_ENABLE;
		parameter_enum_t EMAC_TXJUMBOFRAME_ENABLE;
		parameter_enum_t EMAC_TXRESET;
		parameter_enum_t EMAC_TXVLAN_ENABLE;
		parameter_enum_t EMAC_TX_ENABLE;
		parameter_int_t EMAC_UNICASTADDR;
		parameter_enum_t EMAC_UNIDIRECTION_ENABLE;
		parameter_enum_t EMAC_USECLKEN;
		parameter_string_t SIM_VERSION;
		//Verilog Ports in definition order:
		NetFlow* DCRHOSTDONEIR_A0_B; // net ID: DCRHOSTDONEIR lsb: 0  msb: 0 OUTPUT
		NetFlow* EMACCLIENTANINTERRUPT_A0_B; // net ID: EMACCLIENTANINTERRUPT lsb: 0  msb: 0 OUTPUT
		NetFlow* EMACCLIENTRXBADFRAME_A0_B; // net ID: EMACCLIENTRXBADFRAME lsb: 0  msb: 0 OUTPUT
		NetFlow* EMACCLIENTRXCLIENTCLKOUT_A0_B; // net ID: EMACCLIENTRXCLIENTCLKOUT lsb: 0  msb: 0 OUTPUT
		NetFlow* EMACCLIENTRXD_A0_B; // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
		NetFlow* EMACCLIENTRXD_A1_B; // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
		NetFlow* EMACCLIENTRXD_A2_B; // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
		NetFlow* EMACCLIENTRXD_A3_B; // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
		NetFlow* EMACCLIENTRXD_A4_B; // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
		NetFlow* EMACCLIENTRXD_A5_B; // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
		NetFlow* EMACCLIENTRXD_A6_B; // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
		NetFlow* EMACCLIENTRXD_A7_B; // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
		NetFlow* EMACCLIENTRXD_A8_B; // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
		NetFlow* EMACCLIENTRXD_A9_B; // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
		NetFlow* EMACCLIENTRXD_A10_B; // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
		NetFlow* EMACCLIENTRXD_A11_B; // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
		NetFlow* EMACCLIENTRXD_A12_B; // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
		NetFlow* EMACCLIENTRXD_A13_B; // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
		NetFlow* EMACCLIENTRXD_A14_B; // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
		NetFlow* EMACCLIENTRXD_A15_B; // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
		NetFlow* EMACCLIENTRXDVLD_A0_B; // net ID: EMACCLIENTRXDVLD lsb: 0  msb: 0 OUTPUT
		NetFlow* EMACCLIENTRXDVLDMSW_A0_B; // net ID: EMACCLIENTRXDVLDMSW lsb: 0  msb: 0 OUTPUT
		NetFlow* EMACCLIENTRXFRAMEDROP_A0_B; // net ID: EMACCLIENTRXFRAMEDROP lsb: 0  msb: 0 OUTPUT
		NetFlow* EMACCLIENTRXGOODFRAME_A0_B; // net ID: EMACCLIENTRXGOODFRAME lsb: 0  msb: 0 OUTPUT
		NetFlow* EMACCLIENTRXSTATS_A0_B; // net ID: EMACCLIENTRXSTATS lsb: 0  msb: 6 OUTPUT
		NetFlow* EMACCLIENTRXSTATS_A1_B; // net ID: EMACCLIENTRXSTATS lsb: 0  msb: 6 OUTPUT
		NetFlow* EMACCLIENTRXSTATS_A2_B; // net ID: EMACCLIENTRXSTATS lsb: 0  msb: 6 OUTPUT
		NetFlow* EMACCLIENTRXSTATS_A3_B; // net ID: EMACCLIENTRXSTATS lsb: 0  msb: 6 OUTPUT
		NetFlow* EMACCLIENTRXSTATS_A4_B; // net ID: EMACCLIENTRXSTATS lsb: 0  msb: 6 OUTPUT
		NetFlow* EMACCLIENTRXSTATS_A5_B; // net ID: EMACCLIENTRXSTATS lsb: 0  msb: 6 OUTPUT
		NetFlow* EMACCLIENTRXSTATS_A6_B; // net ID: EMACCLIENTRXSTATS lsb: 0  msb: 6 OUTPUT
		NetFlow* EMACCLIENTRXSTATSBYTEVLD_A0_B; // net ID: EMACCLIENTRXSTATSBYTEVLD lsb: 0  msb: 0 OUTPUT
		NetFlow* EMACCLIENTRXSTATSVLD_A0_B; // net ID: EMACCLIENTRXSTATSVLD lsb: 0  msb: 0 OUTPUT
		NetFlow* EMACCLIENTTXACK_A0_B; // net ID: EMACCLIENTTXACK lsb: 0  msb: 0 OUTPUT
		NetFlow* EMACCLIENTTXCLIENTCLKOUT_A0_B; // net ID: EMACCLIENTTXCLIENTCLKOUT lsb: 0  msb: 0 OUTPUT
		NetFlow* EMACCLIENTTXCOLLISION_A0_B; // net ID: EMACCLIENTTXCOLLISION lsb: 0  msb: 0 OUTPUT
		NetFlow* EMACCLIENTTXRETRANSMIT_A0_B; // net ID: EMACCLIENTTXRETRANSMIT lsb: 0  msb: 0 OUTPUT
		NetFlow* EMACCLIENTTXSTATS_A0_B; // net ID: EMACCLIENTTXSTATS lsb: 0  msb: 0 OUTPUT
		NetFlow* EMACCLIENTTXSTATSBYTEVLD_A0_B; // net ID: EMACCLIENTTXSTATSBYTEVLD lsb: 0  msb: 0 OUTPUT
		NetFlow* EMACCLIENTTXSTATSVLD_A0_B; // net ID: EMACCLIENTTXSTATSVLD lsb: 0  msb: 0 OUTPUT
		NetFlow* EMACDCRACK_A0_B; // net ID: EMACDCRACK lsb: 0  msb: 0 OUTPUT
		NetFlow* EMACPHYENCOMMAALIGN_A0_B; // net ID: EMACPHYENCOMMAALIGN lsb: 0  msb: 0 OUTPUT
		NetFlow* EMACPHYLOOPBACKMSB_A0_B; // net ID: EMACPHYLOOPBACKMSB lsb: 0  msb: 0 OUTPUT
		NetFlow* EMACPHYMCLKOUT_A0_B; // net ID: EMACPHYMCLKOUT lsb: 0  msb: 0 OUTPUT
		NetFlow* EMACPHYMDOUT_A0_B; // net ID: EMACPHYMDOUT lsb: 0  msb: 0 OUTPUT
		NetFlow* EMACPHYMDTRI_A0_B; // net ID: EMACPHYMDTRI lsb: 0  msb: 0 OUTPUT
		NetFlow* EMACPHYMGTRXRESET_A0_B; // net ID: EMACPHYMGTRXRESET lsb: 0  msb: 0 OUTPUT
		NetFlow* EMACPHYMGTTXRESET_A0_B; // net ID: EMACPHYMGTTXRESET lsb: 0  msb: 0 OUTPUT
		NetFlow* EMACPHYPOWERDOWN_A0_B; // net ID: EMACPHYPOWERDOWN lsb: 0  msb: 0 OUTPUT
		NetFlow* EMACPHYSYNCACQSTATUS_A0_B; // net ID: EMACPHYSYNCACQSTATUS lsb: 0  msb: 0 OUTPUT
		NetFlow* EMACPHYTXCHARDISPMODE_A0_B; // net ID: EMACPHYTXCHARDISPMODE lsb: 0  msb: 0 OUTPUT
		NetFlow* EMACPHYTXCHARDISPVAL_A0_B; // net ID: EMACPHYTXCHARDISPVAL lsb: 0  msb: 0 OUTPUT
		NetFlow* EMACPHYTXCHARISK_A0_B; // net ID: EMACPHYTXCHARISK lsb: 0  msb: 0 OUTPUT
		NetFlow* EMACPHYTXCLK_A0_B; // net ID: EMACPHYTXCLK lsb: 0  msb: 0 OUTPUT
		NetFlow* EMACPHYTXD_A0_B; // net ID: EMACPHYTXD lsb: 0  msb: 7 OUTPUT
		NetFlow* EMACPHYTXD_A1_B; // net ID: EMACPHYTXD lsb: 0  msb: 7 OUTPUT
		NetFlow* EMACPHYTXD_A2_B; // net ID: EMACPHYTXD lsb: 0  msb: 7 OUTPUT
		NetFlow* EMACPHYTXD_A3_B; // net ID: EMACPHYTXD lsb: 0  msb: 7 OUTPUT
		NetFlow* EMACPHYTXD_A4_B; // net ID: EMACPHYTXD lsb: 0  msb: 7 OUTPUT
		NetFlow* EMACPHYTXD_A5_B; // net ID: EMACPHYTXD lsb: 0  msb: 7 OUTPUT
		NetFlow* EMACPHYTXD_A6_B; // net ID: EMACPHYTXD lsb: 0  msb: 7 OUTPUT
		NetFlow* EMACPHYTXD_A7_B; // net ID: EMACPHYTXD lsb: 0  msb: 7 OUTPUT
		NetFlow* EMACPHYTXEN_A0_B; // net ID: EMACPHYTXEN lsb: 0  msb: 0 OUTPUT
		NetFlow* EMACPHYTXER_A0_B; // net ID: EMACPHYTXER lsb: 0  msb: 0 OUTPUT
		NetFlow* EMACPHYTXGMIIMIICLKOUT_A0_B; // net ID: EMACPHYTXGMIIMIICLKOUT lsb: 0  msb: 0 OUTPUT
		NetFlow* EMACSPEEDIS10100_A0_B; // net ID: EMACSPEEDIS10100 lsb: 0  msb: 0 OUTPUT
		NetFlow* HOSTMIIMRDY_A0_B; // net ID: HOSTMIIMRDY lsb: 0  msb: 0 OUTPUT
		NetFlow* HOSTRDDATA_A0_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
		NetFlow* HOSTRDDATA_A1_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
		NetFlow* HOSTRDDATA_A2_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
		NetFlow* HOSTRDDATA_A3_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
		NetFlow* HOSTRDDATA_A4_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
		NetFlow* HOSTRDDATA_A5_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
		NetFlow* HOSTRDDATA_A6_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
		NetFlow* HOSTRDDATA_A7_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
		NetFlow* HOSTRDDATA_A8_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
		NetFlow* HOSTRDDATA_A9_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
		NetFlow* HOSTRDDATA_A10_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
		NetFlow* HOSTRDDATA_A11_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
		NetFlow* HOSTRDDATA_A12_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
		NetFlow* HOSTRDDATA_A13_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
		NetFlow* HOSTRDDATA_A14_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
		NetFlow* HOSTRDDATA_A15_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
		NetFlow* HOSTRDDATA_A16_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
		NetFlow* HOSTRDDATA_A17_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
		NetFlow* HOSTRDDATA_A18_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
		NetFlow* HOSTRDDATA_A19_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
		NetFlow* HOSTRDDATA_A20_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
		NetFlow* HOSTRDDATA_A21_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
		NetFlow* HOSTRDDATA_A22_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
		NetFlow* HOSTRDDATA_A23_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
		NetFlow* HOSTRDDATA_A24_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
		NetFlow* HOSTRDDATA_A25_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
		NetFlow* HOSTRDDATA_A26_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
		NetFlow* HOSTRDDATA_A27_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
		NetFlow* HOSTRDDATA_A28_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
		NetFlow* HOSTRDDATA_A29_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
		NetFlow* HOSTRDDATA_A30_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
		NetFlow* HOSTRDDATA_A31_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
		NetFlow* CLIENTEMACDCMLOCKED_A0_B; // net ID: CLIENTEMACDCMLOCKED lsb: 0  msb: 0 INPUT
		NetFlow* CLIENTEMACPAUSEREQ_A0_B; // net ID: CLIENTEMACPAUSEREQ lsb: 0  msb: 0 INPUT
		NetFlow* CLIENTEMACPAUSEVAL_A0_B; // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
		NetFlow* CLIENTEMACPAUSEVAL_A1_B; // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
		NetFlow* CLIENTEMACPAUSEVAL_A2_B; // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
		NetFlow* CLIENTEMACPAUSEVAL_A3_B; // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
		NetFlow* CLIENTEMACPAUSEVAL_A4_B; // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
		NetFlow* CLIENTEMACPAUSEVAL_A5_B; // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
		NetFlow* CLIENTEMACPAUSEVAL_A6_B; // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
		NetFlow* CLIENTEMACPAUSEVAL_A7_B; // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
		NetFlow* CLIENTEMACPAUSEVAL_A8_B; // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
		NetFlow* CLIENTEMACPAUSEVAL_A9_B; // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
		NetFlow* CLIENTEMACPAUSEVAL_A10_B; // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
		NetFlow* CLIENTEMACPAUSEVAL_A11_B; // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
		NetFlow* CLIENTEMACPAUSEVAL_A12_B; // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
		NetFlow* CLIENTEMACPAUSEVAL_A13_B; // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
		NetFlow* CLIENTEMACPAUSEVAL_A14_B; // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
		NetFlow* CLIENTEMACPAUSEVAL_A15_B; // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
		NetFlow* CLIENTEMACRXCLIENTCLKIN_A0_B; // net ID: CLIENTEMACRXCLIENTCLKIN lsb: 0  msb: 0 INPUT
		NetFlow* CLIENTEMACTXCLIENTCLKIN_A0_B; // net ID: CLIENTEMACTXCLIENTCLKIN lsb: 0  msb: 0 INPUT
		NetFlow* CLIENTEMACTXD_A0_B; // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
		NetFlow* CLIENTEMACTXD_A1_B; // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
		NetFlow* CLIENTEMACTXD_A2_B; // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
		NetFlow* CLIENTEMACTXD_A3_B; // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
		NetFlow* CLIENTEMACTXD_A4_B; // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
		NetFlow* CLIENTEMACTXD_A5_B; // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
		NetFlow* CLIENTEMACTXD_A6_B; // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
		NetFlow* CLIENTEMACTXD_A7_B; // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
		NetFlow* CLIENTEMACTXD_A8_B; // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
		NetFlow* CLIENTEMACTXD_A9_B; // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
		NetFlow* CLIENTEMACTXD_A10_B; // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
		NetFlow* CLIENTEMACTXD_A11_B; // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
		NetFlow* CLIENTEMACTXD_A12_B; // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
		NetFlow* CLIENTEMACTXD_A13_B; // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
		NetFlow* CLIENTEMACTXD_A14_B; // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
		NetFlow* CLIENTEMACTXD_A15_B; // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
		NetFlow* CLIENTEMACTXDVLD_A0_B; // net ID: CLIENTEMACTXDVLD lsb: 0  msb: 0 INPUT
		NetFlow* CLIENTEMACTXDVLDMSW_A0_B; // net ID: CLIENTEMACTXDVLDMSW lsb: 0  msb: 0 INPUT
		NetFlow* CLIENTEMACTXFIRSTBYTE_A0_B; // net ID: CLIENTEMACTXFIRSTBYTE lsb: 0  msb: 0 INPUT
		NetFlow* CLIENTEMACTXIFGDELAY_A0_B; // net ID: CLIENTEMACTXIFGDELAY lsb: 0  msb: 7 INPUT
		NetFlow* CLIENTEMACTXIFGDELAY_A1_B; // net ID: CLIENTEMACTXIFGDELAY lsb: 0  msb: 7 INPUT
		NetFlow* CLIENTEMACTXIFGDELAY_A2_B; // net ID: CLIENTEMACTXIFGDELAY lsb: 0  msb: 7 INPUT
		NetFlow* CLIENTEMACTXIFGDELAY_A3_B; // net ID: CLIENTEMACTXIFGDELAY lsb: 0  msb: 7 INPUT
		NetFlow* CLIENTEMACTXIFGDELAY_A4_B; // net ID: CLIENTEMACTXIFGDELAY lsb: 0  msb: 7 INPUT
		NetFlow* CLIENTEMACTXIFGDELAY_A5_B; // net ID: CLIENTEMACTXIFGDELAY lsb: 0  msb: 7 INPUT
		NetFlow* CLIENTEMACTXIFGDELAY_A6_B; // net ID: CLIENTEMACTXIFGDELAY lsb: 0  msb: 7 INPUT
		NetFlow* CLIENTEMACTXIFGDELAY_A7_B; // net ID: CLIENTEMACTXIFGDELAY lsb: 0  msb: 7 INPUT
		NetFlow* CLIENTEMACTXUNDERRUN_A0_B; // net ID: CLIENTEMACTXUNDERRUN lsb: 0  msb: 0 INPUT
		NetFlow* DCREMACCLK_A0_B; // net ID: DCREMACCLK lsb: 0  msb: 0 INPUT
		NetFlow* DCREMACENABLE_A0_B; // net ID: DCREMACENABLE lsb: 0  msb: 0 INPUT
		NetFlow* DCREMACREAD_A0_B; // net ID: DCREMACREAD lsb: 0  msb: 0 INPUT
		NetFlow* DCREMACWRITE_A0_B; // net ID: DCREMACWRITE lsb: 0  msb: 0 INPUT
		NetFlow* HOSTADDR_A0_B; // net ID: HOSTADDR lsb: 0  msb: 9 INPUT
		NetFlow* HOSTADDR_A1_B; // net ID: HOSTADDR lsb: 0  msb: 9 INPUT
		NetFlow* HOSTADDR_A2_B; // net ID: HOSTADDR lsb: 0  msb: 9 INPUT
		NetFlow* HOSTADDR_A3_B; // net ID: HOSTADDR lsb: 0  msb: 9 INPUT
		NetFlow* HOSTADDR_A4_B; // net ID: HOSTADDR lsb: 0  msb: 9 INPUT
		NetFlow* HOSTADDR_A5_B; // net ID: HOSTADDR lsb: 0  msb: 9 INPUT
		NetFlow* HOSTADDR_A6_B; // net ID: HOSTADDR lsb: 0  msb: 9 INPUT
		NetFlow* HOSTADDR_A7_B; // net ID: HOSTADDR lsb: 0  msb: 9 INPUT
		NetFlow* HOSTADDR_A8_B; // net ID: HOSTADDR lsb: 0  msb: 9 INPUT
		NetFlow* HOSTADDR_A9_B; // net ID: HOSTADDR lsb: 0  msb: 9 INPUT
		NetFlow* HOSTCLK_A0_B; // net ID: HOSTCLK lsb: 0  msb: 0 INPUT
		NetFlow* HOSTMIIMSEL_A0_B; // net ID: HOSTMIIMSEL lsb: 0  msb: 0 INPUT
		NetFlow* HOSTOPCODE_A0_B; // net ID: HOSTOPCODE lsb: 0  msb: 1 INPUT
		NetFlow* HOSTOPCODE_A1_B; // net ID: HOSTOPCODE lsb: 0  msb: 1 INPUT
		NetFlow* HOSTREQ_A0_B; // net ID: HOSTREQ lsb: 0  msb: 0 INPUT
		NetFlow* HOSTWRDATA_A0_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
		NetFlow* HOSTWRDATA_A1_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
		NetFlow* HOSTWRDATA_A2_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
		NetFlow* HOSTWRDATA_A3_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
		NetFlow* HOSTWRDATA_A4_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
		NetFlow* HOSTWRDATA_A5_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
		NetFlow* HOSTWRDATA_A6_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
		NetFlow* HOSTWRDATA_A7_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
		NetFlow* HOSTWRDATA_A8_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
		NetFlow* HOSTWRDATA_A9_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
		NetFlow* HOSTWRDATA_A10_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
		NetFlow* HOSTWRDATA_A11_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
		NetFlow* HOSTWRDATA_A12_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
		NetFlow* HOSTWRDATA_A13_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
		NetFlow* HOSTWRDATA_A14_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
		NetFlow* HOSTWRDATA_A15_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
		NetFlow* HOSTWRDATA_A16_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
		NetFlow* HOSTWRDATA_A17_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
		NetFlow* HOSTWRDATA_A18_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
		NetFlow* HOSTWRDATA_A19_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
		NetFlow* HOSTWRDATA_A20_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
		NetFlow* HOSTWRDATA_A21_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
		NetFlow* HOSTWRDATA_A22_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
		NetFlow* HOSTWRDATA_A23_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
		NetFlow* HOSTWRDATA_A24_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
		NetFlow* HOSTWRDATA_A25_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
		NetFlow* HOSTWRDATA_A26_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
		NetFlow* HOSTWRDATA_A27_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
		NetFlow* HOSTWRDATA_A28_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
		NetFlow* HOSTWRDATA_A29_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
		NetFlow* HOSTWRDATA_A30_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
		NetFlow* HOSTWRDATA_A31_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
		NetFlow* PHYEMACCOL_A0_B; // net ID: PHYEMACCOL lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMACCRS_A0_B; // net ID: PHYEMACCRS lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMACGTXCLK_A0_B; // net ID: PHYEMACGTXCLK lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMACMCLKIN_A0_B; // net ID: PHYEMACMCLKIN lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMACMDIN_A0_B; // net ID: PHYEMACMDIN lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMACMIITXCLK_A0_B; // net ID: PHYEMACMIITXCLK lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMACPHYAD_A0_B; // net ID: PHYEMACPHYAD lsb: 0  msb: 4 INPUT
		NetFlow* PHYEMACPHYAD_A1_B; // net ID: PHYEMACPHYAD lsb: 0  msb: 4 INPUT
		NetFlow* PHYEMACPHYAD_A2_B; // net ID: PHYEMACPHYAD lsb: 0  msb: 4 INPUT
		NetFlow* PHYEMACPHYAD_A3_B; // net ID: PHYEMACPHYAD lsb: 0  msb: 4 INPUT
		NetFlow* PHYEMACPHYAD_A4_B; // net ID: PHYEMACPHYAD lsb: 0  msb: 4 INPUT
		NetFlow* PHYEMACRXBUFSTATUS_A0_B; // net ID: PHYEMACRXBUFSTATUS lsb: 0  msb: 1 INPUT
		NetFlow* PHYEMACRXBUFSTATUS_A1_B; // net ID: PHYEMACRXBUFSTATUS lsb: 0  msb: 1 INPUT
		NetFlow* PHYEMACRXCHARISCOMMA_A0_B; // net ID: PHYEMACRXCHARISCOMMA lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMACRXCHARISK_A0_B; // net ID: PHYEMACRXCHARISK lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMACRXCLK_A0_B; // net ID: PHYEMACRXCLK lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMACRXCLKCORCNT_A0_B; // net ID: PHYEMACRXCLKCORCNT lsb: 0  msb: 2 INPUT
		NetFlow* PHYEMACRXCLKCORCNT_A1_B; // net ID: PHYEMACRXCLKCORCNT lsb: 0  msb: 2 INPUT
		NetFlow* PHYEMACRXCLKCORCNT_A2_B; // net ID: PHYEMACRXCLKCORCNT lsb: 0  msb: 2 INPUT
		NetFlow* PHYEMACRXD_A0_B; // net ID: PHYEMACRXD lsb: 0  msb: 7 INPUT
		NetFlow* PHYEMACRXD_A1_B; // net ID: PHYEMACRXD lsb: 0  msb: 7 INPUT
		NetFlow* PHYEMACRXD_A2_B; // net ID: PHYEMACRXD lsb: 0  msb: 7 INPUT
		NetFlow* PHYEMACRXD_A3_B; // net ID: PHYEMACRXD lsb: 0  msb: 7 INPUT
		NetFlow* PHYEMACRXD_A4_B; // net ID: PHYEMACRXD lsb: 0  msb: 7 INPUT
		NetFlow* PHYEMACRXD_A5_B; // net ID: PHYEMACRXD lsb: 0  msb: 7 INPUT
		NetFlow* PHYEMACRXD_A6_B; // net ID: PHYEMACRXD lsb: 0  msb: 7 INPUT
		NetFlow* PHYEMACRXD_A7_B; // net ID: PHYEMACRXD lsb: 0  msb: 7 INPUT
		NetFlow* PHYEMACRXDISPERR_A0_B; // net ID: PHYEMACRXDISPERR lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMACRXDV_A0_B; // net ID: PHYEMACRXDV lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMACRXER_A0_B; // net ID: PHYEMACRXER lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMACRXNOTINTABLE_A0_B; // net ID: PHYEMACRXNOTINTABLE lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMACRXRUNDISP_A0_B; // net ID: PHYEMACRXRUNDISP lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMACSIGNALDET_A0_B; // net ID: PHYEMACSIGNALDET lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMACTXBUFERR_A0_B; // net ID: PHYEMACTXBUFERR lsb: 0  msb: 0 INPUT
		NetFlow* PHYEMACTXGMIIMIICLKIN_A0_B; // net ID: PHYEMACTXGMIIMIICLKIN lsb: 0  msb: 0 INPUT
		NetFlow* RESET_A0_B; // net ID: RESET lsb: 0  msb: 0 INPUT
		
		public: X_TEMAC_SINGLE(
			const char * name,
			//Verilog Parameters:
			parameter_string_t LOC, // Default: "UNPLACED"
			parameter_enum_t EMAC_1000BASEX_ENABLE, // Default: "FALSE"
			parameter_enum_t EMAC_ADDRFILTER_ENABLE, // Default: "FALSE"
			parameter_enum_t EMAC_BYTEPHY, // Default: "FALSE"
			parameter_enum_t EMAC_CTRLLENCHECK_DISABLE, // Default: "FALSE"
			parameter_int_t EMAC_DCRBASEADDR, // Default: 8'h00
			parameter_enum_t EMAC_GTLOOPBACK, // Default: "FALSE"
			parameter_enum_t EMAC_HOST_ENABLE, // Default: "FALSE"
			parameter_int_t EMAC_LINKTIMERVAL, // Default: 9'h000
			parameter_enum_t EMAC_LTCHECK_DISABLE, // Default: "FALSE"
			parameter_enum_t EMAC_MDIO_ENABLE, // Default: "FALSE"
			parameter_enum_t EMAC_MDIO_IGNORE_PHYADZERO, // Default: "FALSE"
			parameter_int_t EMAC_PAUSEADDR, // Default: 48'h000000000000
			parameter_enum_t EMAC_PHYINITAUTONEG_ENABLE, // Default: "FALSE"
			parameter_enum_t EMAC_PHYISOLATE, // Default: "FALSE"
			parameter_enum_t EMAC_PHYLOOPBACKMSB, // Default: "FALSE"
			parameter_enum_t EMAC_PHYPOWERDOWN, // Default: "FALSE"
			parameter_enum_t EMAC_PHYRESET, // Default: "FALSE"
			parameter_enum_t EMAC_RGMII_ENABLE, // Default: "FALSE"
			parameter_enum_t EMAC_RX16BITCLIENT_ENABLE, // Default: "FALSE"
			parameter_enum_t EMAC_RXFLOWCTRL_ENABLE, // Default: "FALSE"
			parameter_enum_t EMAC_RXHALFDUPLEX, // Default: "FALSE"
			parameter_enum_t EMAC_RXINBANDFCS_ENABLE, // Default: "FALSE"
			parameter_enum_t EMAC_RXJUMBOFRAME_ENABLE, // Default: "FALSE"
			parameter_enum_t EMAC_RXRESET, // Default: "FALSE"
			parameter_enum_t EMAC_RXVLAN_ENABLE, // Default: "FALSE"
			parameter_enum_t EMAC_RX_ENABLE, // Default: "TRUE"
			parameter_enum_t EMAC_SGMII_ENABLE, // Default: "FALSE"
			parameter_enum_t EMAC_SPEED_LSB, // Default: "FALSE"
			parameter_enum_t EMAC_SPEED_MSB, // Default: "FALSE"
			parameter_enum_t EMAC_TX16BITCLIENT_ENABLE, // Default: "FALSE"
			parameter_enum_t EMAC_TXFLOWCTRL_ENABLE, // Default: "FALSE"
			parameter_enum_t EMAC_TXHALFDUPLEX, // Default: "FALSE"
			parameter_enum_t EMAC_TXIFGADJUST_ENABLE, // Default: "FALSE"
			parameter_enum_t EMAC_TXINBANDFCS_ENABLE, // Default: "FALSE"
			parameter_enum_t EMAC_TXJUMBOFRAME_ENABLE, // Default: "FALSE"
			parameter_enum_t EMAC_TXRESET, // Default: "FALSE"
			parameter_enum_t EMAC_TXVLAN_ENABLE, // Default: "FALSE"
			parameter_enum_t EMAC_TX_ENABLE, // Default: "TRUE"
			parameter_int_t EMAC_UNICASTADDR, // Default: 48'h000000000000
			parameter_enum_t EMAC_UNIDIRECTION_ENABLE, // Default: "FALSE"
			parameter_enum_t EMAC_USECLKEN, // Default: "FALSE"
			parameter_string_t SIM_VERSION, // Default: "1.0"
			//Verilog Ports in definition order:
			NetFlow* DCRHOSTDONEIR_A0_B, // net ID: DCRHOSTDONEIR lsb: 0  msb: 0 OUTPUT
			NetFlow* EMACCLIENTANINTERRUPT_A0_B, // net ID: EMACCLIENTANINTERRUPT lsb: 0  msb: 0 OUTPUT
			NetFlow* EMACCLIENTRXBADFRAME_A0_B, // net ID: EMACCLIENTRXBADFRAME lsb: 0  msb: 0 OUTPUT
			NetFlow* EMACCLIENTRXCLIENTCLKOUT_A0_B, // net ID: EMACCLIENTRXCLIENTCLKOUT lsb: 0  msb: 0 OUTPUT
			NetFlow* EMACCLIENTRXD_A0_B, // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
			NetFlow* EMACCLIENTRXD_A1_B, // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
			NetFlow* EMACCLIENTRXD_A2_B, // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
			NetFlow* EMACCLIENTRXD_A3_B, // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
			NetFlow* EMACCLIENTRXD_A4_B, // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
			NetFlow* EMACCLIENTRXD_A5_B, // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
			NetFlow* EMACCLIENTRXD_A6_B, // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
			NetFlow* EMACCLIENTRXD_A7_B, // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
			NetFlow* EMACCLIENTRXD_A8_B, // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
			NetFlow* EMACCLIENTRXD_A9_B, // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
			NetFlow* EMACCLIENTRXD_A10_B, // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
			NetFlow* EMACCLIENTRXD_A11_B, // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
			NetFlow* EMACCLIENTRXD_A12_B, // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
			NetFlow* EMACCLIENTRXD_A13_B, // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
			NetFlow* EMACCLIENTRXD_A14_B, // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
			NetFlow* EMACCLIENTRXD_A15_B, // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
			NetFlow* EMACCLIENTRXDVLD_A0_B, // net ID: EMACCLIENTRXDVLD lsb: 0  msb: 0 OUTPUT
			NetFlow* EMACCLIENTRXDVLDMSW_A0_B, // net ID: EMACCLIENTRXDVLDMSW lsb: 0  msb: 0 OUTPUT
			NetFlow* EMACCLIENTRXFRAMEDROP_A0_B, // net ID: EMACCLIENTRXFRAMEDROP lsb: 0  msb: 0 OUTPUT
			NetFlow* EMACCLIENTRXGOODFRAME_A0_B, // net ID: EMACCLIENTRXGOODFRAME lsb: 0  msb: 0 OUTPUT
			NetFlow* EMACCLIENTRXSTATS_A0_B, // net ID: EMACCLIENTRXSTATS lsb: 0  msb: 6 OUTPUT
			NetFlow* EMACCLIENTRXSTATS_A1_B, // net ID: EMACCLIENTRXSTATS lsb: 0  msb: 6 OUTPUT
			NetFlow* EMACCLIENTRXSTATS_A2_B, // net ID: EMACCLIENTRXSTATS lsb: 0  msb: 6 OUTPUT
			NetFlow* EMACCLIENTRXSTATS_A3_B, // net ID: EMACCLIENTRXSTATS lsb: 0  msb: 6 OUTPUT
			NetFlow* EMACCLIENTRXSTATS_A4_B, // net ID: EMACCLIENTRXSTATS lsb: 0  msb: 6 OUTPUT
			NetFlow* EMACCLIENTRXSTATS_A5_B, // net ID: EMACCLIENTRXSTATS lsb: 0  msb: 6 OUTPUT
			NetFlow* EMACCLIENTRXSTATS_A6_B, // net ID: EMACCLIENTRXSTATS lsb: 0  msb: 6 OUTPUT
			NetFlow* EMACCLIENTRXSTATSBYTEVLD_A0_B, // net ID: EMACCLIENTRXSTATSBYTEVLD lsb: 0  msb: 0 OUTPUT
			NetFlow* EMACCLIENTRXSTATSVLD_A0_B, // net ID: EMACCLIENTRXSTATSVLD lsb: 0  msb: 0 OUTPUT
			NetFlow* EMACCLIENTTXACK_A0_B, // net ID: EMACCLIENTTXACK lsb: 0  msb: 0 OUTPUT
			NetFlow* EMACCLIENTTXCLIENTCLKOUT_A0_B, // net ID: EMACCLIENTTXCLIENTCLKOUT lsb: 0  msb: 0 OUTPUT
			NetFlow* EMACCLIENTTXCOLLISION_A0_B, // net ID: EMACCLIENTTXCOLLISION lsb: 0  msb: 0 OUTPUT
			NetFlow* EMACCLIENTTXRETRANSMIT_A0_B, // net ID: EMACCLIENTTXRETRANSMIT lsb: 0  msb: 0 OUTPUT
			NetFlow* EMACCLIENTTXSTATS_A0_B, // net ID: EMACCLIENTTXSTATS lsb: 0  msb: 0 OUTPUT
			NetFlow* EMACCLIENTTXSTATSBYTEVLD_A0_B, // net ID: EMACCLIENTTXSTATSBYTEVLD lsb: 0  msb: 0 OUTPUT
			NetFlow* EMACCLIENTTXSTATSVLD_A0_B, // net ID: EMACCLIENTTXSTATSVLD lsb: 0  msb: 0 OUTPUT
			NetFlow* EMACDCRACK_A0_B, // net ID: EMACDCRACK lsb: 0  msb: 0 OUTPUT
			NetFlow* EMACPHYENCOMMAALIGN_A0_B, // net ID: EMACPHYENCOMMAALIGN lsb: 0  msb: 0 OUTPUT
			NetFlow* EMACPHYLOOPBACKMSB_A0_B, // net ID: EMACPHYLOOPBACKMSB lsb: 0  msb: 0 OUTPUT
			NetFlow* EMACPHYMCLKOUT_A0_B, // net ID: EMACPHYMCLKOUT lsb: 0  msb: 0 OUTPUT
			NetFlow* EMACPHYMDOUT_A0_B, // net ID: EMACPHYMDOUT lsb: 0  msb: 0 OUTPUT
			NetFlow* EMACPHYMDTRI_A0_B, // net ID: EMACPHYMDTRI lsb: 0  msb: 0 OUTPUT
			NetFlow* EMACPHYMGTRXRESET_A0_B, // net ID: EMACPHYMGTRXRESET lsb: 0  msb: 0 OUTPUT
			NetFlow* EMACPHYMGTTXRESET_A0_B, // net ID: EMACPHYMGTTXRESET lsb: 0  msb: 0 OUTPUT
			NetFlow* EMACPHYPOWERDOWN_A0_B, // net ID: EMACPHYPOWERDOWN lsb: 0  msb: 0 OUTPUT
			NetFlow* EMACPHYSYNCACQSTATUS_A0_B, // net ID: EMACPHYSYNCACQSTATUS lsb: 0  msb: 0 OUTPUT
			NetFlow* EMACPHYTXCHARDISPMODE_A0_B, // net ID: EMACPHYTXCHARDISPMODE lsb: 0  msb: 0 OUTPUT
			NetFlow* EMACPHYTXCHARDISPVAL_A0_B, // net ID: EMACPHYTXCHARDISPVAL lsb: 0  msb: 0 OUTPUT
			NetFlow* EMACPHYTXCHARISK_A0_B, // net ID: EMACPHYTXCHARISK lsb: 0  msb: 0 OUTPUT
			NetFlow* EMACPHYTXCLK_A0_B, // net ID: EMACPHYTXCLK lsb: 0  msb: 0 OUTPUT
			NetFlow* EMACPHYTXD_A0_B, // net ID: EMACPHYTXD lsb: 0  msb: 7 OUTPUT
			NetFlow* EMACPHYTXD_A1_B, // net ID: EMACPHYTXD lsb: 0  msb: 7 OUTPUT
			NetFlow* EMACPHYTXD_A2_B, // net ID: EMACPHYTXD lsb: 0  msb: 7 OUTPUT
			NetFlow* EMACPHYTXD_A3_B, // net ID: EMACPHYTXD lsb: 0  msb: 7 OUTPUT
			NetFlow* EMACPHYTXD_A4_B, // net ID: EMACPHYTXD lsb: 0  msb: 7 OUTPUT
			NetFlow* EMACPHYTXD_A5_B, // net ID: EMACPHYTXD lsb: 0  msb: 7 OUTPUT
			NetFlow* EMACPHYTXD_A6_B, // net ID: EMACPHYTXD lsb: 0  msb: 7 OUTPUT
			NetFlow* EMACPHYTXD_A7_B, // net ID: EMACPHYTXD lsb: 0  msb: 7 OUTPUT
			NetFlow* EMACPHYTXEN_A0_B, // net ID: EMACPHYTXEN lsb: 0  msb: 0 OUTPUT
			NetFlow* EMACPHYTXER_A0_B, // net ID: EMACPHYTXER lsb: 0  msb: 0 OUTPUT
			NetFlow* EMACPHYTXGMIIMIICLKOUT_A0_B, // net ID: EMACPHYTXGMIIMIICLKOUT lsb: 0  msb: 0 OUTPUT
			NetFlow* EMACSPEEDIS10100_A0_B, // net ID: EMACSPEEDIS10100 lsb: 0  msb: 0 OUTPUT
			NetFlow* HOSTMIIMRDY_A0_B, // net ID: HOSTMIIMRDY lsb: 0  msb: 0 OUTPUT
			NetFlow* HOSTRDDATA_A0_B, // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			NetFlow* HOSTRDDATA_A1_B, // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			NetFlow* HOSTRDDATA_A2_B, // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			NetFlow* HOSTRDDATA_A3_B, // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			NetFlow* HOSTRDDATA_A4_B, // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			NetFlow* HOSTRDDATA_A5_B, // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			NetFlow* HOSTRDDATA_A6_B, // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			NetFlow* HOSTRDDATA_A7_B, // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			NetFlow* HOSTRDDATA_A8_B, // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			NetFlow* HOSTRDDATA_A9_B, // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			NetFlow* HOSTRDDATA_A10_B, // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			NetFlow* HOSTRDDATA_A11_B, // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			NetFlow* HOSTRDDATA_A12_B, // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			NetFlow* HOSTRDDATA_A13_B, // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			NetFlow* HOSTRDDATA_A14_B, // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			NetFlow* HOSTRDDATA_A15_B, // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			NetFlow* HOSTRDDATA_A16_B, // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			NetFlow* HOSTRDDATA_A17_B, // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			NetFlow* HOSTRDDATA_A18_B, // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			NetFlow* HOSTRDDATA_A19_B, // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			NetFlow* HOSTRDDATA_A20_B, // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			NetFlow* HOSTRDDATA_A21_B, // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			NetFlow* HOSTRDDATA_A22_B, // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			NetFlow* HOSTRDDATA_A23_B, // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			NetFlow* HOSTRDDATA_A24_B, // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			NetFlow* HOSTRDDATA_A25_B, // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			NetFlow* HOSTRDDATA_A26_B, // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			NetFlow* HOSTRDDATA_A27_B, // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			NetFlow* HOSTRDDATA_A28_B, // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			NetFlow* HOSTRDDATA_A29_B, // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			NetFlow* HOSTRDDATA_A30_B, // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			NetFlow* HOSTRDDATA_A31_B, // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			NetFlow* CLIENTEMACDCMLOCKED_A0_B, // net ID: CLIENTEMACDCMLOCKED lsb: 0  msb: 0 INPUT
			NetFlow* CLIENTEMACPAUSEREQ_A0_B, // net ID: CLIENTEMACPAUSEREQ lsb: 0  msb: 0 INPUT
			NetFlow* CLIENTEMACPAUSEVAL_A0_B, // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
			NetFlow* CLIENTEMACPAUSEVAL_A1_B, // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
			NetFlow* CLIENTEMACPAUSEVAL_A2_B, // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
			NetFlow* CLIENTEMACPAUSEVAL_A3_B, // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
			NetFlow* CLIENTEMACPAUSEVAL_A4_B, // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
			NetFlow* CLIENTEMACPAUSEVAL_A5_B, // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
			NetFlow* CLIENTEMACPAUSEVAL_A6_B, // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
			NetFlow* CLIENTEMACPAUSEVAL_A7_B, // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
			NetFlow* CLIENTEMACPAUSEVAL_A8_B, // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
			NetFlow* CLIENTEMACPAUSEVAL_A9_B, // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
			NetFlow* CLIENTEMACPAUSEVAL_A10_B, // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
			NetFlow* CLIENTEMACPAUSEVAL_A11_B, // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
			NetFlow* CLIENTEMACPAUSEVAL_A12_B, // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
			NetFlow* CLIENTEMACPAUSEVAL_A13_B, // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
			NetFlow* CLIENTEMACPAUSEVAL_A14_B, // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
			NetFlow* CLIENTEMACPAUSEVAL_A15_B, // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
			NetFlow* CLIENTEMACRXCLIENTCLKIN_A0_B, // net ID: CLIENTEMACRXCLIENTCLKIN lsb: 0  msb: 0 INPUT
			NetFlow* CLIENTEMACTXCLIENTCLKIN_A0_B, // net ID: CLIENTEMACTXCLIENTCLKIN lsb: 0  msb: 0 INPUT
			NetFlow* CLIENTEMACTXD_A0_B, // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
			NetFlow* CLIENTEMACTXD_A1_B, // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
			NetFlow* CLIENTEMACTXD_A2_B, // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
			NetFlow* CLIENTEMACTXD_A3_B, // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
			NetFlow* CLIENTEMACTXD_A4_B, // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
			NetFlow* CLIENTEMACTXD_A5_B, // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
			NetFlow* CLIENTEMACTXD_A6_B, // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
			NetFlow* CLIENTEMACTXD_A7_B, // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
			NetFlow* CLIENTEMACTXD_A8_B, // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
			NetFlow* CLIENTEMACTXD_A9_B, // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
			NetFlow* CLIENTEMACTXD_A10_B, // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
			NetFlow* CLIENTEMACTXD_A11_B, // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
			NetFlow* CLIENTEMACTXD_A12_B, // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
			NetFlow* CLIENTEMACTXD_A13_B, // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
			NetFlow* CLIENTEMACTXD_A14_B, // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
			NetFlow* CLIENTEMACTXD_A15_B, // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
			NetFlow* CLIENTEMACTXDVLD_A0_B, // net ID: CLIENTEMACTXDVLD lsb: 0  msb: 0 INPUT
			NetFlow* CLIENTEMACTXDVLDMSW_A0_B, // net ID: CLIENTEMACTXDVLDMSW lsb: 0  msb: 0 INPUT
			NetFlow* CLIENTEMACTXFIRSTBYTE_A0_B, // net ID: CLIENTEMACTXFIRSTBYTE lsb: 0  msb: 0 INPUT
			NetFlow* CLIENTEMACTXIFGDELAY_A0_B, // net ID: CLIENTEMACTXIFGDELAY lsb: 0  msb: 7 INPUT
			NetFlow* CLIENTEMACTXIFGDELAY_A1_B, // net ID: CLIENTEMACTXIFGDELAY lsb: 0  msb: 7 INPUT
			NetFlow* CLIENTEMACTXIFGDELAY_A2_B, // net ID: CLIENTEMACTXIFGDELAY lsb: 0  msb: 7 INPUT
			NetFlow* CLIENTEMACTXIFGDELAY_A3_B, // net ID: CLIENTEMACTXIFGDELAY lsb: 0  msb: 7 INPUT
			NetFlow* CLIENTEMACTXIFGDELAY_A4_B, // net ID: CLIENTEMACTXIFGDELAY lsb: 0  msb: 7 INPUT
			NetFlow* CLIENTEMACTXIFGDELAY_A5_B, // net ID: CLIENTEMACTXIFGDELAY lsb: 0  msb: 7 INPUT
			NetFlow* CLIENTEMACTXIFGDELAY_A6_B, // net ID: CLIENTEMACTXIFGDELAY lsb: 0  msb: 7 INPUT
			NetFlow* CLIENTEMACTXIFGDELAY_A7_B, // net ID: CLIENTEMACTXIFGDELAY lsb: 0  msb: 7 INPUT
			NetFlow* CLIENTEMACTXUNDERRUN_A0_B, // net ID: CLIENTEMACTXUNDERRUN lsb: 0  msb: 0 INPUT
			NetFlow* DCREMACCLK_A0_B, // net ID: DCREMACCLK lsb: 0  msb: 0 INPUT
			NetFlow* DCREMACENABLE_A0_B, // net ID: DCREMACENABLE lsb: 0  msb: 0 INPUT
			NetFlow* DCREMACREAD_A0_B, // net ID: DCREMACREAD lsb: 0  msb: 0 INPUT
			NetFlow* DCREMACWRITE_A0_B, // net ID: DCREMACWRITE lsb: 0  msb: 0 INPUT
			NetFlow* HOSTADDR_A0_B, // net ID: HOSTADDR lsb: 0  msb: 9 INPUT
			NetFlow* HOSTADDR_A1_B, // net ID: HOSTADDR lsb: 0  msb: 9 INPUT
			NetFlow* HOSTADDR_A2_B, // net ID: HOSTADDR lsb: 0  msb: 9 INPUT
			NetFlow* HOSTADDR_A3_B, // net ID: HOSTADDR lsb: 0  msb: 9 INPUT
			NetFlow* HOSTADDR_A4_B, // net ID: HOSTADDR lsb: 0  msb: 9 INPUT
			NetFlow* HOSTADDR_A5_B, // net ID: HOSTADDR lsb: 0  msb: 9 INPUT
			NetFlow* HOSTADDR_A6_B, // net ID: HOSTADDR lsb: 0  msb: 9 INPUT
			NetFlow* HOSTADDR_A7_B, // net ID: HOSTADDR lsb: 0  msb: 9 INPUT
			NetFlow* HOSTADDR_A8_B, // net ID: HOSTADDR lsb: 0  msb: 9 INPUT
			NetFlow* HOSTADDR_A9_B, // net ID: HOSTADDR lsb: 0  msb: 9 INPUT
			NetFlow* HOSTCLK_A0_B, // net ID: HOSTCLK lsb: 0  msb: 0 INPUT
			NetFlow* HOSTMIIMSEL_A0_B, // net ID: HOSTMIIMSEL lsb: 0  msb: 0 INPUT
			NetFlow* HOSTOPCODE_A0_B, // net ID: HOSTOPCODE lsb: 0  msb: 1 INPUT
			NetFlow* HOSTOPCODE_A1_B, // net ID: HOSTOPCODE lsb: 0  msb: 1 INPUT
			NetFlow* HOSTREQ_A0_B, // net ID: HOSTREQ lsb: 0  msb: 0 INPUT
			NetFlow* HOSTWRDATA_A0_B, // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			NetFlow* HOSTWRDATA_A1_B, // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			NetFlow* HOSTWRDATA_A2_B, // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			NetFlow* HOSTWRDATA_A3_B, // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			NetFlow* HOSTWRDATA_A4_B, // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			NetFlow* HOSTWRDATA_A5_B, // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			NetFlow* HOSTWRDATA_A6_B, // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			NetFlow* HOSTWRDATA_A7_B, // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			NetFlow* HOSTWRDATA_A8_B, // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			NetFlow* HOSTWRDATA_A9_B, // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			NetFlow* HOSTWRDATA_A10_B, // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			NetFlow* HOSTWRDATA_A11_B, // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			NetFlow* HOSTWRDATA_A12_B, // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			NetFlow* HOSTWRDATA_A13_B, // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			NetFlow* HOSTWRDATA_A14_B, // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			NetFlow* HOSTWRDATA_A15_B, // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			NetFlow* HOSTWRDATA_A16_B, // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			NetFlow* HOSTWRDATA_A17_B, // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			NetFlow* HOSTWRDATA_A18_B, // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			NetFlow* HOSTWRDATA_A19_B, // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			NetFlow* HOSTWRDATA_A20_B, // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			NetFlow* HOSTWRDATA_A21_B, // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			NetFlow* HOSTWRDATA_A22_B, // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			NetFlow* HOSTWRDATA_A23_B, // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			NetFlow* HOSTWRDATA_A24_B, // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			NetFlow* HOSTWRDATA_A25_B, // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			NetFlow* HOSTWRDATA_A26_B, // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			NetFlow* HOSTWRDATA_A27_B, // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			NetFlow* HOSTWRDATA_A28_B, // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			NetFlow* HOSTWRDATA_A29_B, // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			NetFlow* HOSTWRDATA_A30_B, // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			NetFlow* HOSTWRDATA_A31_B, // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			NetFlow* PHYEMACCOL_A0_B, // net ID: PHYEMACCOL lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMACCRS_A0_B, // net ID: PHYEMACCRS lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMACGTXCLK_A0_B, // net ID: PHYEMACGTXCLK lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMACMCLKIN_A0_B, // net ID: PHYEMACMCLKIN lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMACMDIN_A0_B, // net ID: PHYEMACMDIN lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMACMIITXCLK_A0_B, // net ID: PHYEMACMIITXCLK lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMACPHYAD_A0_B, // net ID: PHYEMACPHYAD lsb: 0  msb: 4 INPUT
			NetFlow* PHYEMACPHYAD_A1_B, // net ID: PHYEMACPHYAD lsb: 0  msb: 4 INPUT
			NetFlow* PHYEMACPHYAD_A2_B, // net ID: PHYEMACPHYAD lsb: 0  msb: 4 INPUT
			NetFlow* PHYEMACPHYAD_A3_B, // net ID: PHYEMACPHYAD lsb: 0  msb: 4 INPUT
			NetFlow* PHYEMACPHYAD_A4_B, // net ID: PHYEMACPHYAD lsb: 0  msb: 4 INPUT
			NetFlow* PHYEMACRXBUFSTATUS_A0_B, // net ID: PHYEMACRXBUFSTATUS lsb: 0  msb: 1 INPUT
			NetFlow* PHYEMACRXBUFSTATUS_A1_B, // net ID: PHYEMACRXBUFSTATUS lsb: 0  msb: 1 INPUT
			NetFlow* PHYEMACRXCHARISCOMMA_A0_B, // net ID: PHYEMACRXCHARISCOMMA lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMACRXCHARISK_A0_B, // net ID: PHYEMACRXCHARISK lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMACRXCLK_A0_B, // net ID: PHYEMACRXCLK lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMACRXCLKCORCNT_A0_B, // net ID: PHYEMACRXCLKCORCNT lsb: 0  msb: 2 INPUT
			NetFlow* PHYEMACRXCLKCORCNT_A1_B, // net ID: PHYEMACRXCLKCORCNT lsb: 0  msb: 2 INPUT
			NetFlow* PHYEMACRXCLKCORCNT_A2_B, // net ID: PHYEMACRXCLKCORCNT lsb: 0  msb: 2 INPUT
			NetFlow* PHYEMACRXD_A0_B, // net ID: PHYEMACRXD lsb: 0  msb: 7 INPUT
			NetFlow* PHYEMACRXD_A1_B, // net ID: PHYEMACRXD lsb: 0  msb: 7 INPUT
			NetFlow* PHYEMACRXD_A2_B, // net ID: PHYEMACRXD lsb: 0  msb: 7 INPUT
			NetFlow* PHYEMACRXD_A3_B, // net ID: PHYEMACRXD lsb: 0  msb: 7 INPUT
			NetFlow* PHYEMACRXD_A4_B, // net ID: PHYEMACRXD lsb: 0  msb: 7 INPUT
			NetFlow* PHYEMACRXD_A5_B, // net ID: PHYEMACRXD lsb: 0  msb: 7 INPUT
			NetFlow* PHYEMACRXD_A6_B, // net ID: PHYEMACRXD lsb: 0  msb: 7 INPUT
			NetFlow* PHYEMACRXD_A7_B, // net ID: PHYEMACRXD lsb: 0  msb: 7 INPUT
			NetFlow* PHYEMACRXDISPERR_A0_B, // net ID: PHYEMACRXDISPERR lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMACRXDV_A0_B, // net ID: PHYEMACRXDV lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMACRXER_A0_B, // net ID: PHYEMACRXER lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMACRXNOTINTABLE_A0_B, // net ID: PHYEMACRXNOTINTABLE lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMACRXRUNDISP_A0_B, // net ID: PHYEMACRXRUNDISP lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMACSIGNALDET_A0_B, // net ID: PHYEMACSIGNALDET lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMACTXBUFERR_A0_B, // net ID: PHYEMACTXBUFERR lsb: 0  msb: 0 INPUT
			NetFlow* PHYEMACTXGMIIMIICLKIN_A0_B, // net ID: PHYEMACTXGMIIMIICLKIN lsb: 0  msb: 0 INPUT
			NetFlow* RESET_A0_B // net ID: RESET lsb: 0  msb: 0 INPUT
			):Primitive(name){
			
			// Assign parameters and ports: 
			//Verilog Parameters:
			this->LOC = LOC; // Default: "UNPLACED"
			this->EMAC_1000BASEX_ENABLE = EMAC_1000BASEX_ENABLE; // Default: "FALSE"
			this->EMAC_ADDRFILTER_ENABLE = EMAC_ADDRFILTER_ENABLE; // Default: "FALSE"
			this->EMAC_BYTEPHY = EMAC_BYTEPHY; // Default: "FALSE"
			this->EMAC_CTRLLENCHECK_DISABLE = EMAC_CTRLLENCHECK_DISABLE; // Default: "FALSE"
			this->EMAC_DCRBASEADDR = EMAC_DCRBASEADDR; // Default: 8'h00
			this->EMAC_GTLOOPBACK = EMAC_GTLOOPBACK; // Default: "FALSE"
			this->EMAC_HOST_ENABLE = EMAC_HOST_ENABLE; // Default: "FALSE"
			this->EMAC_LINKTIMERVAL = EMAC_LINKTIMERVAL; // Default: 9'h000
			this->EMAC_LTCHECK_DISABLE = EMAC_LTCHECK_DISABLE; // Default: "FALSE"
			this->EMAC_MDIO_ENABLE = EMAC_MDIO_ENABLE; // Default: "FALSE"
			this->EMAC_MDIO_IGNORE_PHYADZERO = EMAC_MDIO_IGNORE_PHYADZERO; // Default: "FALSE"
			this->EMAC_PAUSEADDR = EMAC_PAUSEADDR; // Default: 48'h000000000000
			this->EMAC_PHYINITAUTONEG_ENABLE = EMAC_PHYINITAUTONEG_ENABLE; // Default: "FALSE"
			this->EMAC_PHYISOLATE = EMAC_PHYISOLATE; // Default: "FALSE"
			this->EMAC_PHYLOOPBACKMSB = EMAC_PHYLOOPBACKMSB; // Default: "FALSE"
			this->EMAC_PHYPOWERDOWN = EMAC_PHYPOWERDOWN; // Default: "FALSE"
			this->EMAC_PHYRESET = EMAC_PHYRESET; // Default: "FALSE"
			this->EMAC_RGMII_ENABLE = EMAC_RGMII_ENABLE; // Default: "FALSE"
			this->EMAC_RX16BITCLIENT_ENABLE = EMAC_RX16BITCLIENT_ENABLE; // Default: "FALSE"
			this->EMAC_RXFLOWCTRL_ENABLE = EMAC_RXFLOWCTRL_ENABLE; // Default: "FALSE"
			this->EMAC_RXHALFDUPLEX = EMAC_RXHALFDUPLEX; // Default: "FALSE"
			this->EMAC_RXINBANDFCS_ENABLE = EMAC_RXINBANDFCS_ENABLE; // Default: "FALSE"
			this->EMAC_RXJUMBOFRAME_ENABLE = EMAC_RXJUMBOFRAME_ENABLE; // Default: "FALSE"
			this->EMAC_RXRESET = EMAC_RXRESET; // Default: "FALSE"
			this->EMAC_RXVLAN_ENABLE = EMAC_RXVLAN_ENABLE; // Default: "FALSE"
			this->EMAC_RX_ENABLE = EMAC_RX_ENABLE; // Default: "TRUE"
			this->EMAC_SGMII_ENABLE = EMAC_SGMII_ENABLE; // Default: "FALSE"
			this->EMAC_SPEED_LSB = EMAC_SPEED_LSB; // Default: "FALSE"
			this->EMAC_SPEED_MSB = EMAC_SPEED_MSB; // Default: "FALSE"
			this->EMAC_TX16BITCLIENT_ENABLE = EMAC_TX16BITCLIENT_ENABLE; // Default: "FALSE"
			this->EMAC_TXFLOWCTRL_ENABLE = EMAC_TXFLOWCTRL_ENABLE; // Default: "FALSE"
			this->EMAC_TXHALFDUPLEX = EMAC_TXHALFDUPLEX; // Default: "FALSE"
			this->EMAC_TXIFGADJUST_ENABLE = EMAC_TXIFGADJUST_ENABLE; // Default: "FALSE"
			this->EMAC_TXINBANDFCS_ENABLE = EMAC_TXINBANDFCS_ENABLE; // Default: "FALSE"
			this->EMAC_TXJUMBOFRAME_ENABLE = EMAC_TXJUMBOFRAME_ENABLE; // Default: "FALSE"
			this->EMAC_TXRESET = EMAC_TXRESET; // Default: "FALSE"
			this->EMAC_TXVLAN_ENABLE = EMAC_TXVLAN_ENABLE; // Default: "FALSE"
			this->EMAC_TX_ENABLE = EMAC_TX_ENABLE; // Default: "TRUE"
			this->EMAC_UNICASTADDR = EMAC_UNICASTADDR; // Default: 48'h000000000000
			this->EMAC_UNIDIRECTION_ENABLE = EMAC_UNIDIRECTION_ENABLE; // Default: "FALSE"
			this->EMAC_USECLKEN = EMAC_USECLKEN; // Default: "FALSE"
			this->SIM_VERSION = SIM_VERSION; // Default: "1.0"
			//Verilog Ports in definition order:
			this->DCRHOSTDONEIR_A0_B = DCRHOSTDONEIR_A0_B; // net ID: DCRHOSTDONEIR lsb: 0  msb: 0 OUTPUT
			this->EMACCLIENTANINTERRUPT_A0_B = EMACCLIENTANINTERRUPT_A0_B; // net ID: EMACCLIENTANINTERRUPT lsb: 0  msb: 0 OUTPUT
			this->EMACCLIENTRXBADFRAME_A0_B = EMACCLIENTRXBADFRAME_A0_B; // net ID: EMACCLIENTRXBADFRAME lsb: 0  msb: 0 OUTPUT
			this->EMACCLIENTRXCLIENTCLKOUT_A0_B = EMACCLIENTRXCLIENTCLKOUT_A0_B; // net ID: EMACCLIENTRXCLIENTCLKOUT lsb: 0  msb: 0 OUTPUT
			this->EMACCLIENTRXD_A0_B = EMACCLIENTRXD_A0_B; // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
			this->EMACCLIENTRXD_A1_B = EMACCLIENTRXD_A1_B; // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
			this->EMACCLIENTRXD_A2_B = EMACCLIENTRXD_A2_B; // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
			this->EMACCLIENTRXD_A3_B = EMACCLIENTRXD_A3_B; // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
			this->EMACCLIENTRXD_A4_B = EMACCLIENTRXD_A4_B; // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
			this->EMACCLIENTRXD_A5_B = EMACCLIENTRXD_A5_B; // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
			this->EMACCLIENTRXD_A6_B = EMACCLIENTRXD_A6_B; // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
			this->EMACCLIENTRXD_A7_B = EMACCLIENTRXD_A7_B; // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
			this->EMACCLIENTRXD_A8_B = EMACCLIENTRXD_A8_B; // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
			this->EMACCLIENTRXD_A9_B = EMACCLIENTRXD_A9_B; // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
			this->EMACCLIENTRXD_A10_B = EMACCLIENTRXD_A10_B; // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
			this->EMACCLIENTRXD_A11_B = EMACCLIENTRXD_A11_B; // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
			this->EMACCLIENTRXD_A12_B = EMACCLIENTRXD_A12_B; // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
			this->EMACCLIENTRXD_A13_B = EMACCLIENTRXD_A13_B; // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
			this->EMACCLIENTRXD_A14_B = EMACCLIENTRXD_A14_B; // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
			this->EMACCLIENTRXD_A15_B = EMACCLIENTRXD_A15_B; // net ID: EMACCLIENTRXD lsb: 0  msb: 15 OUTPUT
			this->EMACCLIENTRXDVLD_A0_B = EMACCLIENTRXDVLD_A0_B; // net ID: EMACCLIENTRXDVLD lsb: 0  msb: 0 OUTPUT
			this->EMACCLIENTRXDVLDMSW_A0_B = EMACCLIENTRXDVLDMSW_A0_B; // net ID: EMACCLIENTRXDVLDMSW lsb: 0  msb: 0 OUTPUT
			this->EMACCLIENTRXFRAMEDROP_A0_B = EMACCLIENTRXFRAMEDROP_A0_B; // net ID: EMACCLIENTRXFRAMEDROP lsb: 0  msb: 0 OUTPUT
			this->EMACCLIENTRXGOODFRAME_A0_B = EMACCLIENTRXGOODFRAME_A0_B; // net ID: EMACCLIENTRXGOODFRAME lsb: 0  msb: 0 OUTPUT
			this->EMACCLIENTRXSTATS_A0_B = EMACCLIENTRXSTATS_A0_B; // net ID: EMACCLIENTRXSTATS lsb: 0  msb: 6 OUTPUT
			this->EMACCLIENTRXSTATS_A1_B = EMACCLIENTRXSTATS_A1_B; // net ID: EMACCLIENTRXSTATS lsb: 0  msb: 6 OUTPUT
			this->EMACCLIENTRXSTATS_A2_B = EMACCLIENTRXSTATS_A2_B; // net ID: EMACCLIENTRXSTATS lsb: 0  msb: 6 OUTPUT
			this->EMACCLIENTRXSTATS_A3_B = EMACCLIENTRXSTATS_A3_B; // net ID: EMACCLIENTRXSTATS lsb: 0  msb: 6 OUTPUT
			this->EMACCLIENTRXSTATS_A4_B = EMACCLIENTRXSTATS_A4_B; // net ID: EMACCLIENTRXSTATS lsb: 0  msb: 6 OUTPUT
			this->EMACCLIENTRXSTATS_A5_B = EMACCLIENTRXSTATS_A5_B; // net ID: EMACCLIENTRXSTATS lsb: 0  msb: 6 OUTPUT
			this->EMACCLIENTRXSTATS_A6_B = EMACCLIENTRXSTATS_A6_B; // net ID: EMACCLIENTRXSTATS lsb: 0  msb: 6 OUTPUT
			this->EMACCLIENTRXSTATSBYTEVLD_A0_B = EMACCLIENTRXSTATSBYTEVLD_A0_B; // net ID: EMACCLIENTRXSTATSBYTEVLD lsb: 0  msb: 0 OUTPUT
			this->EMACCLIENTRXSTATSVLD_A0_B = EMACCLIENTRXSTATSVLD_A0_B; // net ID: EMACCLIENTRXSTATSVLD lsb: 0  msb: 0 OUTPUT
			this->EMACCLIENTTXACK_A0_B = EMACCLIENTTXACK_A0_B; // net ID: EMACCLIENTTXACK lsb: 0  msb: 0 OUTPUT
			this->EMACCLIENTTXCLIENTCLKOUT_A0_B = EMACCLIENTTXCLIENTCLKOUT_A0_B; // net ID: EMACCLIENTTXCLIENTCLKOUT lsb: 0  msb: 0 OUTPUT
			this->EMACCLIENTTXCOLLISION_A0_B = EMACCLIENTTXCOLLISION_A0_B; // net ID: EMACCLIENTTXCOLLISION lsb: 0  msb: 0 OUTPUT
			this->EMACCLIENTTXRETRANSMIT_A0_B = EMACCLIENTTXRETRANSMIT_A0_B; // net ID: EMACCLIENTTXRETRANSMIT lsb: 0  msb: 0 OUTPUT
			this->EMACCLIENTTXSTATS_A0_B = EMACCLIENTTXSTATS_A0_B; // net ID: EMACCLIENTTXSTATS lsb: 0  msb: 0 OUTPUT
			this->EMACCLIENTTXSTATSBYTEVLD_A0_B = EMACCLIENTTXSTATSBYTEVLD_A0_B; // net ID: EMACCLIENTTXSTATSBYTEVLD lsb: 0  msb: 0 OUTPUT
			this->EMACCLIENTTXSTATSVLD_A0_B = EMACCLIENTTXSTATSVLD_A0_B; // net ID: EMACCLIENTTXSTATSVLD lsb: 0  msb: 0 OUTPUT
			this->EMACDCRACK_A0_B = EMACDCRACK_A0_B; // net ID: EMACDCRACK lsb: 0  msb: 0 OUTPUT
			this->EMACPHYENCOMMAALIGN_A0_B = EMACPHYENCOMMAALIGN_A0_B; // net ID: EMACPHYENCOMMAALIGN lsb: 0  msb: 0 OUTPUT
			this->EMACPHYLOOPBACKMSB_A0_B = EMACPHYLOOPBACKMSB_A0_B; // net ID: EMACPHYLOOPBACKMSB lsb: 0  msb: 0 OUTPUT
			this->EMACPHYMCLKOUT_A0_B = EMACPHYMCLKOUT_A0_B; // net ID: EMACPHYMCLKOUT lsb: 0  msb: 0 OUTPUT
			this->EMACPHYMDOUT_A0_B = EMACPHYMDOUT_A0_B; // net ID: EMACPHYMDOUT lsb: 0  msb: 0 OUTPUT
			this->EMACPHYMDTRI_A0_B = EMACPHYMDTRI_A0_B; // net ID: EMACPHYMDTRI lsb: 0  msb: 0 OUTPUT
			this->EMACPHYMGTRXRESET_A0_B = EMACPHYMGTRXRESET_A0_B; // net ID: EMACPHYMGTRXRESET lsb: 0  msb: 0 OUTPUT
			this->EMACPHYMGTTXRESET_A0_B = EMACPHYMGTTXRESET_A0_B; // net ID: EMACPHYMGTTXRESET lsb: 0  msb: 0 OUTPUT
			this->EMACPHYPOWERDOWN_A0_B = EMACPHYPOWERDOWN_A0_B; // net ID: EMACPHYPOWERDOWN lsb: 0  msb: 0 OUTPUT
			this->EMACPHYSYNCACQSTATUS_A0_B = EMACPHYSYNCACQSTATUS_A0_B; // net ID: EMACPHYSYNCACQSTATUS lsb: 0  msb: 0 OUTPUT
			this->EMACPHYTXCHARDISPMODE_A0_B = EMACPHYTXCHARDISPMODE_A0_B; // net ID: EMACPHYTXCHARDISPMODE lsb: 0  msb: 0 OUTPUT
			this->EMACPHYTXCHARDISPVAL_A0_B = EMACPHYTXCHARDISPVAL_A0_B; // net ID: EMACPHYTXCHARDISPVAL lsb: 0  msb: 0 OUTPUT
			this->EMACPHYTXCHARISK_A0_B = EMACPHYTXCHARISK_A0_B; // net ID: EMACPHYTXCHARISK lsb: 0  msb: 0 OUTPUT
			this->EMACPHYTXCLK_A0_B = EMACPHYTXCLK_A0_B; // net ID: EMACPHYTXCLK lsb: 0  msb: 0 OUTPUT
			this->EMACPHYTXD_A0_B = EMACPHYTXD_A0_B; // net ID: EMACPHYTXD lsb: 0  msb: 7 OUTPUT
			this->EMACPHYTXD_A1_B = EMACPHYTXD_A1_B; // net ID: EMACPHYTXD lsb: 0  msb: 7 OUTPUT
			this->EMACPHYTXD_A2_B = EMACPHYTXD_A2_B; // net ID: EMACPHYTXD lsb: 0  msb: 7 OUTPUT
			this->EMACPHYTXD_A3_B = EMACPHYTXD_A3_B; // net ID: EMACPHYTXD lsb: 0  msb: 7 OUTPUT
			this->EMACPHYTXD_A4_B = EMACPHYTXD_A4_B; // net ID: EMACPHYTXD lsb: 0  msb: 7 OUTPUT
			this->EMACPHYTXD_A5_B = EMACPHYTXD_A5_B; // net ID: EMACPHYTXD lsb: 0  msb: 7 OUTPUT
			this->EMACPHYTXD_A6_B = EMACPHYTXD_A6_B; // net ID: EMACPHYTXD lsb: 0  msb: 7 OUTPUT
			this->EMACPHYTXD_A7_B = EMACPHYTXD_A7_B; // net ID: EMACPHYTXD lsb: 0  msb: 7 OUTPUT
			this->EMACPHYTXEN_A0_B = EMACPHYTXEN_A0_B; // net ID: EMACPHYTXEN lsb: 0  msb: 0 OUTPUT
			this->EMACPHYTXER_A0_B = EMACPHYTXER_A0_B; // net ID: EMACPHYTXER lsb: 0  msb: 0 OUTPUT
			this->EMACPHYTXGMIIMIICLKOUT_A0_B = EMACPHYTXGMIIMIICLKOUT_A0_B; // net ID: EMACPHYTXGMIIMIICLKOUT lsb: 0  msb: 0 OUTPUT
			this->EMACSPEEDIS10100_A0_B = EMACSPEEDIS10100_A0_B; // net ID: EMACSPEEDIS10100 lsb: 0  msb: 0 OUTPUT
			this->HOSTMIIMRDY_A0_B = HOSTMIIMRDY_A0_B; // net ID: HOSTMIIMRDY lsb: 0  msb: 0 OUTPUT
			this->HOSTRDDATA_A0_B = HOSTRDDATA_A0_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			this->HOSTRDDATA_A1_B = HOSTRDDATA_A1_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			this->HOSTRDDATA_A2_B = HOSTRDDATA_A2_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			this->HOSTRDDATA_A3_B = HOSTRDDATA_A3_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			this->HOSTRDDATA_A4_B = HOSTRDDATA_A4_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			this->HOSTRDDATA_A5_B = HOSTRDDATA_A5_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			this->HOSTRDDATA_A6_B = HOSTRDDATA_A6_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			this->HOSTRDDATA_A7_B = HOSTRDDATA_A7_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			this->HOSTRDDATA_A8_B = HOSTRDDATA_A8_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			this->HOSTRDDATA_A9_B = HOSTRDDATA_A9_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			this->HOSTRDDATA_A10_B = HOSTRDDATA_A10_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			this->HOSTRDDATA_A11_B = HOSTRDDATA_A11_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			this->HOSTRDDATA_A12_B = HOSTRDDATA_A12_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			this->HOSTRDDATA_A13_B = HOSTRDDATA_A13_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			this->HOSTRDDATA_A14_B = HOSTRDDATA_A14_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			this->HOSTRDDATA_A15_B = HOSTRDDATA_A15_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			this->HOSTRDDATA_A16_B = HOSTRDDATA_A16_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			this->HOSTRDDATA_A17_B = HOSTRDDATA_A17_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			this->HOSTRDDATA_A18_B = HOSTRDDATA_A18_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			this->HOSTRDDATA_A19_B = HOSTRDDATA_A19_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			this->HOSTRDDATA_A20_B = HOSTRDDATA_A20_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			this->HOSTRDDATA_A21_B = HOSTRDDATA_A21_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			this->HOSTRDDATA_A22_B = HOSTRDDATA_A22_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			this->HOSTRDDATA_A23_B = HOSTRDDATA_A23_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			this->HOSTRDDATA_A24_B = HOSTRDDATA_A24_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			this->HOSTRDDATA_A25_B = HOSTRDDATA_A25_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			this->HOSTRDDATA_A26_B = HOSTRDDATA_A26_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			this->HOSTRDDATA_A27_B = HOSTRDDATA_A27_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			this->HOSTRDDATA_A28_B = HOSTRDDATA_A28_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			this->HOSTRDDATA_A29_B = HOSTRDDATA_A29_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			this->HOSTRDDATA_A30_B = HOSTRDDATA_A30_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			this->HOSTRDDATA_A31_B = HOSTRDDATA_A31_B; // net ID: HOSTRDDATA lsb: 0  msb: 31 OUTPUT
			this->CLIENTEMACDCMLOCKED_A0_B = CLIENTEMACDCMLOCKED_A0_B; // net ID: CLIENTEMACDCMLOCKED lsb: 0  msb: 0 INPUT
			this->CLIENTEMACPAUSEREQ_A0_B = CLIENTEMACPAUSEREQ_A0_B; // net ID: CLIENTEMACPAUSEREQ lsb: 0  msb: 0 INPUT
			this->CLIENTEMACPAUSEVAL_A0_B = CLIENTEMACPAUSEVAL_A0_B; // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
			this->CLIENTEMACPAUSEVAL_A1_B = CLIENTEMACPAUSEVAL_A1_B; // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
			this->CLIENTEMACPAUSEVAL_A2_B = CLIENTEMACPAUSEVAL_A2_B; // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
			this->CLIENTEMACPAUSEVAL_A3_B = CLIENTEMACPAUSEVAL_A3_B; // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
			this->CLIENTEMACPAUSEVAL_A4_B = CLIENTEMACPAUSEVAL_A4_B; // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
			this->CLIENTEMACPAUSEVAL_A5_B = CLIENTEMACPAUSEVAL_A5_B; // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
			this->CLIENTEMACPAUSEVAL_A6_B = CLIENTEMACPAUSEVAL_A6_B; // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
			this->CLIENTEMACPAUSEVAL_A7_B = CLIENTEMACPAUSEVAL_A7_B; // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
			this->CLIENTEMACPAUSEVAL_A8_B = CLIENTEMACPAUSEVAL_A8_B; // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
			this->CLIENTEMACPAUSEVAL_A9_B = CLIENTEMACPAUSEVAL_A9_B; // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
			this->CLIENTEMACPAUSEVAL_A10_B = CLIENTEMACPAUSEVAL_A10_B; // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
			this->CLIENTEMACPAUSEVAL_A11_B = CLIENTEMACPAUSEVAL_A11_B; // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
			this->CLIENTEMACPAUSEVAL_A12_B = CLIENTEMACPAUSEVAL_A12_B; // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
			this->CLIENTEMACPAUSEVAL_A13_B = CLIENTEMACPAUSEVAL_A13_B; // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
			this->CLIENTEMACPAUSEVAL_A14_B = CLIENTEMACPAUSEVAL_A14_B; // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
			this->CLIENTEMACPAUSEVAL_A15_B = CLIENTEMACPAUSEVAL_A15_B; // net ID: CLIENTEMACPAUSEVAL lsb: 0  msb: 15 INPUT
			this->CLIENTEMACRXCLIENTCLKIN_A0_B = CLIENTEMACRXCLIENTCLKIN_A0_B; // net ID: CLIENTEMACRXCLIENTCLKIN lsb: 0  msb: 0 INPUT
			this->CLIENTEMACTXCLIENTCLKIN_A0_B = CLIENTEMACTXCLIENTCLKIN_A0_B; // net ID: CLIENTEMACTXCLIENTCLKIN lsb: 0  msb: 0 INPUT
			this->CLIENTEMACTXD_A0_B = CLIENTEMACTXD_A0_B; // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
			this->CLIENTEMACTXD_A1_B = CLIENTEMACTXD_A1_B; // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
			this->CLIENTEMACTXD_A2_B = CLIENTEMACTXD_A2_B; // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
			this->CLIENTEMACTXD_A3_B = CLIENTEMACTXD_A3_B; // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
			this->CLIENTEMACTXD_A4_B = CLIENTEMACTXD_A4_B; // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
			this->CLIENTEMACTXD_A5_B = CLIENTEMACTXD_A5_B; // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
			this->CLIENTEMACTXD_A6_B = CLIENTEMACTXD_A6_B; // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
			this->CLIENTEMACTXD_A7_B = CLIENTEMACTXD_A7_B; // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
			this->CLIENTEMACTXD_A8_B = CLIENTEMACTXD_A8_B; // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
			this->CLIENTEMACTXD_A9_B = CLIENTEMACTXD_A9_B; // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
			this->CLIENTEMACTXD_A10_B = CLIENTEMACTXD_A10_B; // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
			this->CLIENTEMACTXD_A11_B = CLIENTEMACTXD_A11_B; // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
			this->CLIENTEMACTXD_A12_B = CLIENTEMACTXD_A12_B; // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
			this->CLIENTEMACTXD_A13_B = CLIENTEMACTXD_A13_B; // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
			this->CLIENTEMACTXD_A14_B = CLIENTEMACTXD_A14_B; // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
			this->CLIENTEMACTXD_A15_B = CLIENTEMACTXD_A15_B; // net ID: CLIENTEMACTXD lsb: 0  msb: 15 INPUT
			this->CLIENTEMACTXDVLD_A0_B = CLIENTEMACTXDVLD_A0_B; // net ID: CLIENTEMACTXDVLD lsb: 0  msb: 0 INPUT
			this->CLIENTEMACTXDVLDMSW_A0_B = CLIENTEMACTXDVLDMSW_A0_B; // net ID: CLIENTEMACTXDVLDMSW lsb: 0  msb: 0 INPUT
			this->CLIENTEMACTXFIRSTBYTE_A0_B = CLIENTEMACTXFIRSTBYTE_A0_B; // net ID: CLIENTEMACTXFIRSTBYTE lsb: 0  msb: 0 INPUT
			this->CLIENTEMACTXIFGDELAY_A0_B = CLIENTEMACTXIFGDELAY_A0_B; // net ID: CLIENTEMACTXIFGDELAY lsb: 0  msb: 7 INPUT
			this->CLIENTEMACTXIFGDELAY_A1_B = CLIENTEMACTXIFGDELAY_A1_B; // net ID: CLIENTEMACTXIFGDELAY lsb: 0  msb: 7 INPUT
			this->CLIENTEMACTXIFGDELAY_A2_B = CLIENTEMACTXIFGDELAY_A2_B; // net ID: CLIENTEMACTXIFGDELAY lsb: 0  msb: 7 INPUT
			this->CLIENTEMACTXIFGDELAY_A3_B = CLIENTEMACTXIFGDELAY_A3_B; // net ID: CLIENTEMACTXIFGDELAY lsb: 0  msb: 7 INPUT
			this->CLIENTEMACTXIFGDELAY_A4_B = CLIENTEMACTXIFGDELAY_A4_B; // net ID: CLIENTEMACTXIFGDELAY lsb: 0  msb: 7 INPUT
			this->CLIENTEMACTXIFGDELAY_A5_B = CLIENTEMACTXIFGDELAY_A5_B; // net ID: CLIENTEMACTXIFGDELAY lsb: 0  msb: 7 INPUT
			this->CLIENTEMACTXIFGDELAY_A6_B = CLIENTEMACTXIFGDELAY_A6_B; // net ID: CLIENTEMACTXIFGDELAY lsb: 0  msb: 7 INPUT
			this->CLIENTEMACTXIFGDELAY_A7_B = CLIENTEMACTXIFGDELAY_A7_B; // net ID: CLIENTEMACTXIFGDELAY lsb: 0  msb: 7 INPUT
			this->CLIENTEMACTXUNDERRUN_A0_B = CLIENTEMACTXUNDERRUN_A0_B; // net ID: CLIENTEMACTXUNDERRUN lsb: 0  msb: 0 INPUT
			this->DCREMACCLK_A0_B = DCREMACCLK_A0_B; // net ID: DCREMACCLK lsb: 0  msb: 0 INPUT
			this->DCREMACENABLE_A0_B = DCREMACENABLE_A0_B; // net ID: DCREMACENABLE lsb: 0  msb: 0 INPUT
			this->DCREMACREAD_A0_B = DCREMACREAD_A0_B; // net ID: DCREMACREAD lsb: 0  msb: 0 INPUT
			this->DCREMACWRITE_A0_B = DCREMACWRITE_A0_B; // net ID: DCREMACWRITE lsb: 0  msb: 0 INPUT
			this->HOSTADDR_A0_B = HOSTADDR_A0_B; // net ID: HOSTADDR lsb: 0  msb: 9 INPUT
			this->HOSTADDR_A1_B = HOSTADDR_A1_B; // net ID: HOSTADDR lsb: 0  msb: 9 INPUT
			this->HOSTADDR_A2_B = HOSTADDR_A2_B; // net ID: HOSTADDR lsb: 0  msb: 9 INPUT
			this->HOSTADDR_A3_B = HOSTADDR_A3_B; // net ID: HOSTADDR lsb: 0  msb: 9 INPUT
			this->HOSTADDR_A4_B = HOSTADDR_A4_B; // net ID: HOSTADDR lsb: 0  msb: 9 INPUT
			this->HOSTADDR_A5_B = HOSTADDR_A5_B; // net ID: HOSTADDR lsb: 0  msb: 9 INPUT
			this->HOSTADDR_A6_B = HOSTADDR_A6_B; // net ID: HOSTADDR lsb: 0  msb: 9 INPUT
			this->HOSTADDR_A7_B = HOSTADDR_A7_B; // net ID: HOSTADDR lsb: 0  msb: 9 INPUT
			this->HOSTADDR_A8_B = HOSTADDR_A8_B; // net ID: HOSTADDR lsb: 0  msb: 9 INPUT
			this->HOSTADDR_A9_B = HOSTADDR_A9_B; // net ID: HOSTADDR lsb: 0  msb: 9 INPUT
			this->HOSTCLK_A0_B = HOSTCLK_A0_B; // net ID: HOSTCLK lsb: 0  msb: 0 INPUT
			this->HOSTMIIMSEL_A0_B = HOSTMIIMSEL_A0_B; // net ID: HOSTMIIMSEL lsb: 0  msb: 0 INPUT
			this->HOSTOPCODE_A0_B = HOSTOPCODE_A0_B; // net ID: HOSTOPCODE lsb: 0  msb: 1 INPUT
			this->HOSTOPCODE_A1_B = HOSTOPCODE_A1_B; // net ID: HOSTOPCODE lsb: 0  msb: 1 INPUT
			this->HOSTREQ_A0_B = HOSTREQ_A0_B; // net ID: HOSTREQ lsb: 0  msb: 0 INPUT
			this->HOSTWRDATA_A0_B = HOSTWRDATA_A0_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			this->HOSTWRDATA_A1_B = HOSTWRDATA_A1_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			this->HOSTWRDATA_A2_B = HOSTWRDATA_A2_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			this->HOSTWRDATA_A3_B = HOSTWRDATA_A3_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			this->HOSTWRDATA_A4_B = HOSTWRDATA_A4_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			this->HOSTWRDATA_A5_B = HOSTWRDATA_A5_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			this->HOSTWRDATA_A6_B = HOSTWRDATA_A6_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			this->HOSTWRDATA_A7_B = HOSTWRDATA_A7_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			this->HOSTWRDATA_A8_B = HOSTWRDATA_A8_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			this->HOSTWRDATA_A9_B = HOSTWRDATA_A9_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			this->HOSTWRDATA_A10_B = HOSTWRDATA_A10_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			this->HOSTWRDATA_A11_B = HOSTWRDATA_A11_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			this->HOSTWRDATA_A12_B = HOSTWRDATA_A12_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			this->HOSTWRDATA_A13_B = HOSTWRDATA_A13_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			this->HOSTWRDATA_A14_B = HOSTWRDATA_A14_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			this->HOSTWRDATA_A15_B = HOSTWRDATA_A15_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			this->HOSTWRDATA_A16_B = HOSTWRDATA_A16_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			this->HOSTWRDATA_A17_B = HOSTWRDATA_A17_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			this->HOSTWRDATA_A18_B = HOSTWRDATA_A18_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			this->HOSTWRDATA_A19_B = HOSTWRDATA_A19_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			this->HOSTWRDATA_A20_B = HOSTWRDATA_A20_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			this->HOSTWRDATA_A21_B = HOSTWRDATA_A21_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			this->HOSTWRDATA_A22_B = HOSTWRDATA_A22_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			this->HOSTWRDATA_A23_B = HOSTWRDATA_A23_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			this->HOSTWRDATA_A24_B = HOSTWRDATA_A24_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			this->HOSTWRDATA_A25_B = HOSTWRDATA_A25_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			this->HOSTWRDATA_A26_B = HOSTWRDATA_A26_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			this->HOSTWRDATA_A27_B = HOSTWRDATA_A27_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			this->HOSTWRDATA_A28_B = HOSTWRDATA_A28_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			this->HOSTWRDATA_A29_B = HOSTWRDATA_A29_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			this->HOSTWRDATA_A30_B = HOSTWRDATA_A30_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			this->HOSTWRDATA_A31_B = HOSTWRDATA_A31_B; // net ID: HOSTWRDATA lsb: 0  msb: 31 INPUT
			this->PHYEMACCOL_A0_B = PHYEMACCOL_A0_B; // net ID: PHYEMACCOL lsb: 0  msb: 0 INPUT
			this->PHYEMACCRS_A0_B = PHYEMACCRS_A0_B; // net ID: PHYEMACCRS lsb: 0  msb: 0 INPUT
			this->PHYEMACGTXCLK_A0_B = PHYEMACGTXCLK_A0_B; // net ID: PHYEMACGTXCLK lsb: 0  msb: 0 INPUT
			this->PHYEMACMCLKIN_A0_B = PHYEMACMCLKIN_A0_B; // net ID: PHYEMACMCLKIN lsb: 0  msb: 0 INPUT
			this->PHYEMACMDIN_A0_B = PHYEMACMDIN_A0_B; // net ID: PHYEMACMDIN lsb: 0  msb: 0 INPUT
			this->PHYEMACMIITXCLK_A0_B = PHYEMACMIITXCLK_A0_B; // net ID: PHYEMACMIITXCLK lsb: 0  msb: 0 INPUT
			this->PHYEMACPHYAD_A0_B = PHYEMACPHYAD_A0_B; // net ID: PHYEMACPHYAD lsb: 0  msb: 4 INPUT
			this->PHYEMACPHYAD_A1_B = PHYEMACPHYAD_A1_B; // net ID: PHYEMACPHYAD lsb: 0  msb: 4 INPUT
			this->PHYEMACPHYAD_A2_B = PHYEMACPHYAD_A2_B; // net ID: PHYEMACPHYAD lsb: 0  msb: 4 INPUT
			this->PHYEMACPHYAD_A3_B = PHYEMACPHYAD_A3_B; // net ID: PHYEMACPHYAD lsb: 0  msb: 4 INPUT
			this->PHYEMACPHYAD_A4_B = PHYEMACPHYAD_A4_B; // net ID: PHYEMACPHYAD lsb: 0  msb: 4 INPUT
			this->PHYEMACRXBUFSTATUS_A0_B = PHYEMACRXBUFSTATUS_A0_B; // net ID: PHYEMACRXBUFSTATUS lsb: 0  msb: 1 INPUT
			this->PHYEMACRXBUFSTATUS_A1_B = PHYEMACRXBUFSTATUS_A1_B; // net ID: PHYEMACRXBUFSTATUS lsb: 0  msb: 1 INPUT
			this->PHYEMACRXCHARISCOMMA_A0_B = PHYEMACRXCHARISCOMMA_A0_B; // net ID: PHYEMACRXCHARISCOMMA lsb: 0  msb: 0 INPUT
			this->PHYEMACRXCHARISK_A0_B = PHYEMACRXCHARISK_A0_B; // net ID: PHYEMACRXCHARISK lsb: 0  msb: 0 INPUT
			this->PHYEMACRXCLK_A0_B = PHYEMACRXCLK_A0_B; // net ID: PHYEMACRXCLK lsb: 0  msb: 0 INPUT
			this->PHYEMACRXCLKCORCNT_A0_B = PHYEMACRXCLKCORCNT_A0_B; // net ID: PHYEMACRXCLKCORCNT lsb: 0  msb: 2 INPUT
			this->PHYEMACRXCLKCORCNT_A1_B = PHYEMACRXCLKCORCNT_A1_B; // net ID: PHYEMACRXCLKCORCNT lsb: 0  msb: 2 INPUT
			this->PHYEMACRXCLKCORCNT_A2_B = PHYEMACRXCLKCORCNT_A2_B; // net ID: PHYEMACRXCLKCORCNT lsb: 0  msb: 2 INPUT
			this->PHYEMACRXD_A0_B = PHYEMACRXD_A0_B; // net ID: PHYEMACRXD lsb: 0  msb: 7 INPUT
			this->PHYEMACRXD_A1_B = PHYEMACRXD_A1_B; // net ID: PHYEMACRXD lsb: 0  msb: 7 INPUT
			this->PHYEMACRXD_A2_B = PHYEMACRXD_A2_B; // net ID: PHYEMACRXD lsb: 0  msb: 7 INPUT
			this->PHYEMACRXD_A3_B = PHYEMACRXD_A3_B; // net ID: PHYEMACRXD lsb: 0  msb: 7 INPUT
			this->PHYEMACRXD_A4_B = PHYEMACRXD_A4_B; // net ID: PHYEMACRXD lsb: 0  msb: 7 INPUT
			this->PHYEMACRXD_A5_B = PHYEMACRXD_A5_B; // net ID: PHYEMACRXD lsb: 0  msb: 7 INPUT
			this->PHYEMACRXD_A6_B = PHYEMACRXD_A6_B; // net ID: PHYEMACRXD lsb: 0  msb: 7 INPUT
			this->PHYEMACRXD_A7_B = PHYEMACRXD_A7_B; // net ID: PHYEMACRXD lsb: 0  msb: 7 INPUT
			this->PHYEMACRXDISPERR_A0_B = PHYEMACRXDISPERR_A0_B; // net ID: PHYEMACRXDISPERR lsb: 0  msb: 0 INPUT
			this->PHYEMACRXDV_A0_B = PHYEMACRXDV_A0_B; // net ID: PHYEMACRXDV lsb: 0  msb: 0 INPUT
			this->PHYEMACRXER_A0_B = PHYEMACRXER_A0_B; // net ID: PHYEMACRXER lsb: 0  msb: 0 INPUT
			this->PHYEMACRXNOTINTABLE_A0_B = PHYEMACRXNOTINTABLE_A0_B; // net ID: PHYEMACRXNOTINTABLE lsb: 0  msb: 0 INPUT
			this->PHYEMACRXRUNDISP_A0_B = PHYEMACRXRUNDISP_A0_B; // net ID: PHYEMACRXRUNDISP lsb: 0  msb: 0 INPUT
			this->PHYEMACSIGNALDET_A0_B = PHYEMACSIGNALDET_A0_B; // net ID: PHYEMACSIGNALDET lsb: 0  msb: 0 INPUT
			this->PHYEMACTXBUFERR_A0_B = PHYEMACTXBUFERR_A0_B; // net ID: PHYEMACTXBUFERR lsb: 0  msb: 0 INPUT
			this->PHYEMACTXGMIIMIICLKIN_A0_B = PHYEMACTXGMIIMIICLKIN_A0_B; // net ID: PHYEMACTXGMIIMIICLKIN lsb: 0  msb: 0 INPUT
			this->RESET_A0_B = RESET_A0_B; // net ID: RESET lsb: 0  msb: 0 INPUT
			
			register_wait_on_event_nets();
			
		}
		
		void register_wait_on_event_nets(){
		// TODO
		}
		
		void calculate(int time){
		// TODO
		}
		};
		
}
#endif // X_TEMAC_SINGLE_H
