/******************************************************************************
 * Net instancer.
 * This file instantiate all nets in the simulation.
 * This file was generated by a verilog parser.
 ******************************************************************************/

#ifndef NETINSTATIATION_H
#define NETINSTATIATION_H
 
#include <stdio.h>
#include "NetFlow.h"

#define NET_INDEX__BGRAY__INST_SCOUNT_A0_B 0
#define NET_INDEX__BGRAY__INST_SCOUNT_A1_B 1
#define NET_INDEX__BGRAY__INST_SCOUNT_A2_B 2
#define NET_INDEX__BGRAY__INST_SCOUNT_A3_B 3
#define NET_INDEX__BGRAY__INST_SCOUNT_A4_B 4
#define NET_INDEX__BGRAY__INST_SCOUNT_A5_B 5
#define NET_INDEX__BGRAY__INST_SCOUNT_A6_B 6
#define NET_INDEX__BGRAY__INST_SRESULT_A0_B 7
#define NET_INDEX__BGRAY__INST_SRESULT_A1_B 8
#define NET_INDEX__BGRAY__INST_SRESULT_A2_B 9
#define NET_INDEX__BGRAY__INST_SRESULT_A3_B 10
#define NET_INDEX__BGRAY__INST_SRESULT_A4_B 11
#define NET_INDEX__BGRAY__INST_SRESULT_A5_B 12
#define NET_INDEX__BGRAY__INST_SRESULT_A6_B 13



#endif // NETINSTATIATION_H
 

